/** Plan & subscription screen copy. */

const EN = {
  title: "Plan",
  intro: "Your 2kTunes plan decides how many artists you can manage and lets you send releases to stores.",
  currentTitle: "Your subscription",
  planLabel: "Plan",
  noPlan: "No plan yet",
  statusLabel: "Status",
  expiresLabel: "Active until",
  expiredLabel: "Expired on",
  inactiveBody: "Choose a plan below to start distributing your music.",
  expiredBody: "Your plan has expired. Renew or choose another plan to keep distributing.",
  pendingTitle: "Payment awaiting confirmation",
  pendingBody: "2kTunes finance checks your payment reference and activates your plan, usually within one business day.",
  pendingPlan: "Plan",
  pendingMethod: "Paid with",
  pendingReference: "Payment reference",
  pendingAmount: "Amount",
  pendingSubmitted: "Submitted",

  plansTitle: "Plans",
  plansDesc: "Prices are set by 2kTunes and charged per period.",
  plansEmptyTitle: "No plans available right now",
  plansEmptyBody: "Plans are being updated. Please check back soon or contact support.",
  free: "Free",
  perDays: (n: string) => `for ${n} days`,
  maxArtists: (n: string) => `Up to ${n} artists`,
  oneArtist: "1 artist",
  current: "Current plan",
  pendingMarker: "Payment submitted",
  choose: "Choose plan",
  renew: "Renew",
  choosePlan: (name: string) => `Choose the ${name} plan`,
  renewPlan: (name: string) => `Renew the ${name} plan`,

  freeTitle: (name: string) => `Switch to ${name}?`,
  freeBody: "This plan is free and activates immediately.",
  freeConfirm: "Activate plan",
  activated: (name: string) => `${name} plan is active`,

  payTitle: (name: string) => `Pay for ${name}`,
  payDesc: (price: string) => `Send ${price} using one of the options below, then enter your payment reference.`,
  howToPay: "How to pay",
  payNote:
    "Pay using the details shown here, then enter your payment reference. Our finance team confirms payments within one business day.",
  detailLabels: {
    mpesa_lipa_number: "M-Pesa Lipa number",
    bank_account: "Bank account",
    account_name: "Account name",
    bank_name: "Bank name",
    airtel_number: "Airtel Money number",
    mixx_number: "Mixx by Yas number",
  } as Record<string, string>,
  noDetails: "Payment details will be sent to you by our support team.",
  contactSupport: "Contact support",
  method: "Payment method",
  methodPlaceholder: "How did you pay?",
  methods: {
    mpesa_tz: "M-Pesa",
    airtel_tz: "Airtel Money",
    mixx_tz: "Mixx by Yas",
    bank: "Bank transfer",
    card: "Card",
  } as Record<string, string>,
  reference: "Payment reference",
  referenceHint: "The confirmation code from your payment, e.g. the M-Pesa receipt code.",
  referenceRequired: "Enter the payment reference from your receipt.",
  methodRequired: "Choose how you paid.",
  submit: "Submit payment",
  submitted: "Payment submitted — we'll activate your plan once it's confirmed",
};

const SW: typeof EN = {
  title: "Kifurushi",
  intro: "Kifurushi chako cha 2kTunes huamua idadi ya wasanii unaoweza kusimamia na hukuruhusu kutuma matoleo madukani.",
  currentTitle: "Usajili wako",
  planLabel: "Kifurushi",
  noPlan: "Bado huna kifurushi",
  statusLabel: "Hali",
  expiresLabel: "Kinatumika hadi",
  expiredLabel: "Kiliisha tarehe",
  inactiveBody: "Chagua kifurushi hapa chini ili uanze kusambaza muziki wako.",
  expiredBody: "Kifurushi chako kimeisha. Kihuishe au chagua kingine ili kuendelea kusambaza.",
  pendingTitle: "Malipo yanasubiri kuthibitishwa",
  pendingBody: "Idara ya fedha ya 2kTunes hukagua namba yako ya kumbukumbu ya malipo na kuwasha kifurushi chako, kwa kawaida ndani ya siku moja ya kazi.",
  pendingPlan: "Kifurushi",
  pendingMethod: "Umelipa kwa",
  pendingReference: "Kumbukumbu ya malipo",
  pendingAmount: "Kiasi",
  pendingSubmitted: "Ilitumwa",

  plansTitle: "Vifurushi",
  plansDesc: "Bei hupangwa na 2kTunes na hutozwa kwa kila kipindi.",
  plansEmptyTitle: "Hakuna vifurushi kwa sasa",
  plansEmptyBody: "Vifurushi vinasasishwa. Tafadhali angalia tena hivi karibuni au wasiliana na huduma kwa wateja.",
  free: "Bure",
  perDays: (n: string) => `kwa siku ${n}`,
  maxArtists: (n: string) => `Hadi wasanii ${n}`,
  oneArtist: "Msanii 1",
  current: "Kifurushi chako",
  pendingMarker: "Malipo yametumwa",
  choose: "Chagua kifurushi",
  renew: "Huisha",
  choosePlan: (name: string) => `Chagua kifurushi cha ${name}`,
  renewPlan: (name: string) => `Huisha kifurushi cha ${name}`,

  freeTitle: (name: string) => `Hamia ${name}?`,
  freeBody: "Kifurushi hiki ni bure na kinaanza kutumika mara moja.",
  freeConfirm: "Washa kifurushi",
  activated: (name: string) => `Kifurushi cha ${name} kimewashwa`,

  payTitle: (name: string) => `Lipia ${name}`,
  payDesc: (price: string) => `Tuma ${price} kwa mojawapo ya njia zilizo hapa chini, kisha weka kumbukumbu ya malipo yako.`,
  howToPay: "Jinsi ya kulipa",
  payNote:
    "Lipa kwa kutumia taarifa zilizoonyeshwa hapa, kisha weka kumbukumbu ya malipo yako. Idara yetu ya fedha huthibitisha malipo ndani ya siku moja ya kazi.",
  detailLabels: {
    mpesa_lipa_number: "Namba ya Lipa kwa M-Pesa",
    bank_account: "Akaunti ya benki",
    account_name: "Jina la akaunti",
    bank_name: "Jina la benki",
    airtel_number: "Namba ya Airtel Money",
    mixx_number: "Namba ya Mixx by Yas",
  },
  noDetails: "Taarifa za malipo zitatumwa kwako na timu yetu ya huduma kwa wateja.",
  contactSupport: "Wasiliana na huduma kwa wateja",
  method: "Njia ya malipo",
  methodPlaceholder: "Ulilipa kwa njia gani?",
  methods: {
    mpesa_tz: "M-Pesa",
    airtel_tz: "Airtel Money",
    mixx_tz: "Mixx by Yas",
    bank: "Uhamisho wa benki",
    card: "Kadi",
  },
  reference: "Kumbukumbu ya malipo",
  referenceHint: "Namba ya uthibitisho wa malipo yako, mfano namba ya risiti ya M-Pesa.",
  referenceRequired: "Weka kumbukumbu ya malipo kutoka kwenye risiti yako.",
  methodRequired: "Chagua njia uliyotumia kulipa.",
  submit: "Tuma malipo",
  submitted: "Malipo yametumwa — tutawasha kifurushi chako yakishathibitishwa",
};

export const COPY = { EN, SW };
export type PlanCopy = typeof EN;
