import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'EN' | 'FR' | 'PT' | 'ES' | 'SW';

const translations: Record<Language, Record<string, string>> = {
  EN: {
    'nav.services_insights': 'Services & Insights',
    'nav.select_language': 'Select Language',
    'nav.pricing': 'PRICING',
    'nav.why': 'WHY',
    'nav.about': 'ABOUT',
    'nav.faq': 'FAQ',
    'nav.contact': 'CONTACT',
    'nav.signin': 'SIGN IN',
    'nav.getstarted': 'GET STARTED',
    'nav.search_placeholder': 'Search artists, music, news...',
    'nav.search_label': 'SEARCH 2KTUNES...',
    
    'auth.title': 'Start your music career',
    'auth.desc': 'Get your music in stores within 48 hours, 100% royalties, Royalty splits, YouTube Content ID and much more.',
    'auth.google': 'Sign up with Google',
    'auth.apple': 'Sign up with Apple',
    'auth.or': 'OR',
    'auth.email_placeholder': 'E-mail',
    'auth.password_placeholder': 'Password',
    'auth.forgot_password': 'Forgot Password?',
    'auth.email_btn': 'SIGN UP WITH EMAIL',
    'auth.login_btn': 'LOG IN',
    'auth.no_account': "Don't have an account?",
    'auth.signup': 'SIGN UP',
    'auth.login_title': 'Welcome Back',
    'auth.login_desc': 'Log in to manage your releases, view analytics, and withdraw your royalties.',
    'auth.terms': 'By creating an account you agree to the Terms & Conditions and Privacy Policy.',
    'auth.already_member': 'Already a member?',
    'auth.login': 'LOG IN',
    'auth.forgot_password_title': 'Reset your password',
    'auth.forgot_password_desc': 'Enter your email address and we\'ll send you a link to get back into your account.',
    'auth.reset_btn': 'SEND RESET LINK',
    'auth.back_to_login': 'BACK TO LOGIN',
    'auth.feature1': 'Keep 100% of your royalties & rights',
    'auth.feature2': 'Get your music on all major platforms',
    'auth.feature3': 'Invite your team & split your royalties',
    'auth.feature4': 'Chance to get signed by our label',
    
    'onboarding.title': 'Create your account',
    'onboarding.desc': 'Start earning money from your music',
    'onboarding.first_name': 'First Name',
    'onboarding.last_name': 'Last Name',
    'onboarding.payout_notice': 'This name will be used for royalty payouts',
    'onboarding.country': 'Country',
    'onboarding.phone': 'Phone Number',
    'onboarding.news_consent': 'Send occasional updates and news',
    'onboarding.age_consent': 'I’m over 18 years of age',
    'onboarding.testimonial': '“2kTunes is a well-oiled machine that has been supportive of my work, which far surpasses the experiences I\'ve had with other labels and distributors that I have released music over the year”',
    'onboarding.artist_name': 'Artist / Label Name',
    'onboarding.artist_name_placeholder': 'e.g. Hotel Ugly',
    'onboarding.location': 'Base Location',
    'onboarding.location_placeholder': 'e.g. Tanzania',
    'onboarding.genres': 'Primary Genre',
    'onboarding.genre_placeholder': 'Select your genre',
    'onboarding.phone_placeholder': '+255 ...',
    'onboarding.btn': 'SIGN UP',
    'onboarding.back': 'Back',
    'otp.title_email': 'Almost there! Verify your email',
    'otp.title_phone': 'Almost there! Verify your phone',
    'otp.subtitle': 'Help us fight spam and keep 2kTunes strong for real artists! 💪',
    'otp.message': 'Please enter the 6 digit code that we sent to',
    'otp.resend_text': 'Having trouble?',
    'otp.resend_btn': 'Resend code',
    'otp.method_choice': 'How should we verify you?',
    'otp.verify_btn': 'VERIFY',
    
    'payment.title': 'Payment Details',
    'payment.subtitle': 'Last step to get unlimited releases and 100% royalties',
    'payment.method': 'Payment Method',
    'payment.mobile_money': 'Mobile Money',
    'payment.cards': 'Cards',
    'payment.paypal': 'PayPal',
    'payment.google_pay': 'GPay',
    'payment.apple_pay': 'Apple Pay',
    'payment.card_number': 'Card Number',
    'payment.expiry': 'Expiry Date',
    'payment.cvv': 'Security Code',
    'payment.card_name': 'Name on Card',
    'payment.pay_btn': 'PAY AND JOIN 2KTUNES',
    'payment.secure': 'Secure and encrypted',
    'payment.billed_yearly': 'Billed yearly, cancel anytime',
    'payment.provider_mpesa': 'M-Pesa',
    'payment.provider_tigopesa': 'Tigo Pesa',
    'payment.provider_airtel': 'Airtel Money',
    'payment.phone_number': 'Phone Number',
    
    'hero.drop': 'DROP.',
    'hero.grow': 'GROW.',
    'hero.earn': 'EARN.',
    'hero.subtitle': 'Distribution, Marketing, and Royalties for the next generation of global stars.',
    'hero.btn': 'Get Started',
    
    'quick.distribution': 'DISTRIBUTION',
    'quick.marketing': 'MARKETING',
    'quick.royalties': 'ROYALTIES',
    'quick.analytics': 'ANALYTICS',
    'quick.services': 'Artist & Label Services',
    'quick.services_desc': 'Tailored partnerships to accelerate your earnings.',
    
    'dist.title_1': 'Affordable',
    'dist.title_2': 'Self-serve',
    'dist.title_3': 'Distribution',
    'dist.desc': 'Get your music on Spotify, Apple Music, TikTok, and 150+ more stores with just a few clicks. Keep 100% of your rights and royalties.',
    'dist.btn': 'Explore Distribution',
    'dist.feature1_title': 'Fast Uploads',
    'dist.feature1_desc': 'Simple interface to get your music ready for global release in minutes.',
    'dist.feature2_title': 'Smart Links',
    'dist.feature2_desc': 'Pre-save and bio links generated automatically for every release.',
    'dist.feature3_title': 'Direct Payouts',
    'dist.feature3_desc': 'Convert your global streams into local cash. We support Mobile Money, Visa, and PayPal for seamless earnings management.',
    'dist.feature4_title': 'Detailed insights',
    'dist.feature4_desc': 'All the data you need to understand your music and audience is at your fingertips.',
    'dist.feature5_title': 'Tools for every release',
    'dist.feature5_desc': 'Access to mastering, lyrics verification, promo tools and automatic syncing with future store integrations.',
    'dist.payout_methods': 'Supported Payout Methods',
    'payout.mobile_money': 'Mobile Money',
    'payout.mobile_money_desc': 'M-Pesa, MTN, Airtel',
    'payout.visa': 'Visa / Card',
    'payout.visa_desc': 'Global Transfers',
    'payout.paypal': 'PayPal',
    'payout.paypal_desc': 'Digital Payouts',
    
    'news.title': 'From the Newsroom',
    'news.category_product': 'Product News',
    'news.category_artist': 'Artist News',

    'why.title_1': 'Why Choose',
    'why.title_2': '2kTunes',
    'why.feature1_title': 'INSTANT LOCAL WITHDRAWALS',
    'why.feature1_desc': 'The first distribution platform built for Africa. Withdraw your royalties directly to M-Pesa, MTN MoMo, Airtel Money, or your bank account instantly.',
    'why.feature2_title': '100% OWNERSHIP',
    'why.feature2_desc': 'You keep all your rights and 100% of your earnings. No hidden fees or tricky contracts.',
    'why.feature3_title': 'REAL-TIME ANALYTICS',
    'why.feature3_desc': 'Monitor your streams and royalties globally with our transparent, detailed dashboard.',
    'why.feature4_title': 'FAST DISTRIBUTION',
    'why.feature4_desc': "Get your music on Spotify, Apple Music, and TikTok in record time. Don't let your fans wait.",
    
    'pricing.title_1': 'Transparent',
    'pricing.title_2': 'Pricing',
    'pricing.subtitle': 'No hidden costs. Just pure music.',
    'pricing.starter': 'Starter',
    'pricing.pro': 'Pro',
    'pricing.label': 'Label',
    'pricing.mo': '/ mo',
    'pricing.custom': 'Custom',
    'pricing.recommended': 'Recommended',
    'pricing.feature_unlimited': 'Unlimited Uploads',
    'pricing.feature_stores': 'All Stores',
    'pricing.feature_royalties': '100% Royalties',
    'pricing.feature_email': 'Email Support',
    'pricing.feature_everything_starter': 'Everything in Starter',
    'pricing.feature_mastering': 'Mastering Tools',
    'pricing.feature_team': 'Team Access',
    'pricing.feature_priority': 'Priority Support',
    'pricing.feature_unlimited_artists': 'Unlimited Artists',
    'pricing.feature_premium_support': 'Premium Support',
    'pricing.feature_api': 'API Access',
    'pricing.feature_custom_terms': 'Custom Terms',
    'pricing.cta_starter': 'Get Started',
    'pricing.cta_pro': 'Go Pro',
    'pricing.cta_label': 'Contact Us',
    'pricing.tagline_1': 'Global Royalties.',
    'pricing.tagline_2': 'Local Cash.',
    
    'about.title_1': 'Who is',
    'about.title_2': '2kTunes?',
    'about.p1': "2kTunes is the premier music distribution and artist services powerhouse built for the next generation of global stars. We bridged the gap between creative freedom and financial independence.",
    'about.p2': 'Our mission is simple: To provide independent artists with the same tools used by the biggest labels in the world, while ensuring they retain 100% control of their vision and royalties.',
    'about.quote': "We don't just distribute music; we build musical destinies.",

    'contact.title_1': 'Get in',
    'contact.title_2': 'Touch',
    'contact.desc': 'Have questions about distribution, royalties, or our artist services? Our team is here to help you scale your career.',
    'contact.support_label': 'Support Email',
    'contact.support_value': 'support@2ktunes.com',
    'contact.office_label': 'Office Location',
    'contact.office_value': 'Dar es salaam, Tanzania • Nairobi, Kenya • Houston, TX USA',
    'contact.label_name': 'Name',
    'contact.placeholder_name': 'John Doe',
    'contact.label_email': 'Email',
    'contact.placeholder_email': 'john@example.com',
    'contact.label_subject': 'Subject',
    'contact.label_msg': 'Message',
    'contact.placeholder_msg': 'Your message here...',
    'contact.btn': 'Send Message',
    'contact.subject_dist': 'Distribution Inquiry',
    'contact.subject_artist': 'Artist Services',
    'contact.subject_tech': 'Technical Support',
    'contact.subject_other': 'Other',
    
    'faq.title_1': 'Most Asked',
    'faq.title_2': 'Questions',
    'faq.q1': 'How do I upload music?',
    'faq.a1': 'Simply sign up, create a new release on your dashboard, upload your masters and artwork, and pick your stores. Our team handles the rest.',
    'faq.q2': 'How do I get paid?',
    'faq.a2': 'Royalties are tracked in real-time. You can withdraw your earnings instantly to Mobile Money or your local bank account via our secure payment gateway.',
    'faq.q3': 'Do I keep my rights?',
    'faq.a3': 'Yes. You keep 100% ownership of your masters and publishing rights. We are your distribution partner, not your owner.',
    'faq.q4': 'Can I move my music to 2kTunes?',
    'faq.a4': 'Absolutely. Use your existing ISRCs to ensure you keep your play counts and placement when migrating to our platform.',
    
    'cta.title_1': 'Start your music',
    'cta.title_2': 'journey today',
    'cta.subtitle': 'Join thousands of artists who trust 2kTunes to power their independent music career.',
    'cta.btn': 'Join 2kTunes',

    'features.title_1': 'Artist & Label',
    'features.title_2': 'Services That',
    'features.title_3': 'Work For You',
    'features.desc': "For select acts, our team simplifies your career and accelerates your earnings, so you can stay independent. It's the future of music deals.",
    'features.item1': 'Tailored partnerships',
    'features.item2': 'Hands-on release strategy',
    'features.item3': 'End-to-end distribution support',
    'features.item4': 'All-in-one revenue management',
    'features.item5': 'Retain your creative freedom',

    'showcase.title_1': 'Artists',
    'showcase.title_2': 'We Work With',
    'showcase.desc': 'Our Artist & Label Services manage tailored partnerships with 400+ artists and teams, helping them amplify the reach and impact of their music.',
    'showcase.listeners': 'monthly listeners',

    'footer.tagline': 'Global Reach. Local Cash.',
    'footer.preferred': 'Preferred',
    'footer.provider': 'Provider',
    'footer.partners': 'Official Partners',
    'footer.newsletter_title': 'Stay in tune with us!',
    'footer.newsletter_desc': 'Sign up for our newsletter to discover new artists, get insider tips on music distribution, and stay ahead with exclusive updates.',
    'footer.email_placeholder': 'write your e-mail address',
    'footer.subscribe': 'Subscribe',
    'footer.social_title': 'Say Hi!',
    'footer.legal_title': 'Legal',
    'footer.link_work': 'Work with us',
    'footer.link_cookies': 'Manage Cookies',
    'footer.link_sub_tnc': 'Subscription T&C',
    'footer.link_gen_tnc': 'General T&C',
    'footer.link_privacy': 'Privacy Policy',
    'footer.rights': 'All Rights Reserved.',
    'footer.built_by': 'Built by TechOn Software LLC',
    
    'common.visa': 'Visa',
    'common.mobile_money': 'Mobile Money',
    'common.paypal': 'PayPal',
    'common.spotify_artist': 'Spotify for Artists',
    'common.skip': 'Skip for now',
    'dashboard.overview': 'Overview',
    'dashboard.music': 'Music',
    'dashboard.analytics': 'Analytics',
    'dashboard.royalties': 'Royalties',
    'dashboard.settings': 'Settings',
    'dashboard.logout': 'Logout',
    'dashboard.new_release': 'New Release',
    'dashboard.welcome': 'WELCOME BACK,',
    'dashboard.stats_streams': 'Total Streams',
    'dashboard.stats_royalties': 'Royalties',
    'dashboard.stats_releases': 'Active Releases',
    'dashboard.stats_reach': 'Reach',
  },
  FR: {
    'nav.pricing': 'TARIFS',
    'nav.why': 'POURQUOI',
    'nav.about': 'À PROPOS',
    'nav.faq': 'FAQ',
    'nav.contact': 'CONTACT',
    'nav.signin': 'CONNEXION',
    'nav.getstarted': 'COMMENCER',
    'nav.search_placeholder': 'Rechercher des artistes, musique, actualités...',
    
    'hero.drop': 'LANCEZ.',
    'hero.grow': 'GRANDISSEZ.',
    'hero.earn': 'GAGNEZ.',
    
    'quick.distribution': 'DISTRIBUTION',
    'quick.marketing': 'MARKETING',
    'quick.royalties': 'REDEVANCES',
    'quick.analytics': 'ANALYSES',
    'quick.services': 'Services aux Artistes et Labels',
    
    'dist.title_1': 'Abordable',
    'dist.title_2': 'Libre-service',
    'dist.title_3': 'Distribution',
    'dist.btn': 'Explorer la Distribution',
    
    'news.title': 'Salle de Presse',
    'news.category_product': 'Actualités Produits',
    'news.category_artist': 'Actualités Artistes',

    'why.title_1': 'Pourquoi choisir',
    'why.title_2': '2kTunes',
    'why.feature1_title': 'PAIEMENTS LOCAUX',
    'why.feature1_desc': 'Retirez vos gains directement vers Mobile Money ou votre compte de banque local instantanément.',
    'why.feature2_title': '100% PROPRIÉTÉ',
    'why.feature2_desc': 'Vous gardez tous vos droits et 100 % de vos gains. Pas de frais cachés.',
    'why.feature3_title': 'ANALYSES EN TEMPS RÉEL',
    'why.feature3_desc': 'Surveillez vos streams et redevances globalement avec notre tableau de bord transparent.',
    'why.feature4_title': 'DISTRIBUTION RAPIDE',
    'why.feature4_desc': 'Mettez votre musique sur Spotify, Apple Music et TikTok en temps record.',
    
    'pricing.title_1': 'Tarification',
    'pricing.title_2': 'Transparente',
    'pricing.subtitle': 'Pas de coûts cachés. Juste de la musique pure.',
    'pricing.starter': 'Starter',
    'pricing.pro': 'Pro',
    'pricing.label': 'Label',
    'pricing.mo': '/ mois',
    'pricing.custom': 'Sur mesure',
    'pricing.recommended': 'Recommandé',
    'pricing.feature_unlimited': 'Téléchargements Illimités',
    'pricing.feature_stores': 'Tous les Magasins',
    'pricing.feature_royalties': '100% de Redevances',
    'pricing.feature_email': 'Support par Email',
    'pricing.feature_everything_starter': 'Tout ce qui est dans Starter',
    'pricing.feature_mastering': 'Outils de Mastering',
    'pricing.feature_team': 'Accès d\'Équipe',
    'pricing.feature_priority': 'Support Prioritaire',
    'pricing.feature_unlimited_artists': 'Artistes Illimités',
    'pricing.feature_premium_support': 'Support Premium',
    'pricing.feature_api': 'Accès API',
    'pricing.feature_custom_terms': 'Conditions Personnalisées',
    'pricing.cta_starter': 'Commencer',
    'pricing.cta_pro': 'Passer au Pro',
    'pricing.cta_label': 'Contactez-nous',
    
    'about.title_1': 'Qui est',
    'about.title_2': '2kTunes?',
    'about.p1': "2kTunes est la première force de distribution musicale et de services aux artistes conçue pour la prochaine génération de stars mondiales.",
    'about.p2': 'Notre mission est simple : fournir aux artistes indépendants les mêmes outils que les plus grands labels.',
    'about.quote': "Nous ne faisons pas que distribuer de la musique ; nous bâtissons des destinées musicales.",

    'contact.title_1': 'Nous',
    'contact.title_2': 'Contacter',
    'contact.desc': 'Des questions ? Notre équipe est prête à vous aider à faire évoluer votre carrière.',
    'contact.support_label': 'Email de Support',
    'contact.office_label': 'Emplacement du Bureau',
    'contact.label_name': 'Nom',
    'contact.label_email': 'Email',
    'contact.label_subject': 'Sujet',
    'contact.label_msg': 'Message',
    'contact.placeholder_msg': 'Votre message ici...',
    'contact.btn': 'Envoyer',
    
    'faq.title_1': 'Questions',
    'faq.title_2': 'Fréquentes',
    'faq.q1': 'Comment télécharger de la musique ?',
    'faq.a1': 'Inscrivez-vous, créez une sortie, téléchargez vos masters et artwork, et choisissez vos magasins.',
    'faq.q2': 'Comment suis-je payé ?',
    'faq.a2': 'Les redevances sont suivies en temps réel. Retirez instantanément vers Mobile Money ou banque locale.',
    'faq.q3': 'Est-ce que je garde mes droits ?',
    'faq.a3': 'Oui. Vous gardez 100 % de la propriété de vos masters.',
    'faq.q4': 'Puis-je transférer ma musique ?',
    'faq.a4': 'Absolument. Utilisez vos codes ISRC existants pour conserver vos statistiques.',
    
    'cta.title_1': 'Commencez votre',
    'cta.title_2': 'voyage aujourd\'hui',
    'cta.subtitle': 'Rejoignez des milliers d\'artistes qui font confiance à 2kTunes.',
    'cta.btn': 'Rejoindre 2kTunes',

    'features.desc': "Pour certains artistes, notre équipe simplifie votre carrière et accélère vos gains.",
    'features.item1': 'Partenariats sur mesure',
    'features.item2': 'Stratégie de sortie personnalisée',
    'features.item3': 'Support de distribution complet',
    'features.item4': 'Gestion des revenus tout-en-un',
    'features.item5': 'Gardez votre liberté créative',

    'showcase.title_1': 'Artistes',
    'showcase.title_2': 'Avec Qui Nous Travaillons',
    'showcase.desc': 'Nos Services gèrent des partenariats avec plus de 400 artistes et équipes.',
    'showcase.listeners': 'auditeurs mensuels',

    'footer.tagline': 'Portée mondiale. Cash local.',
    'footer.preferred': 'Privilégié',
    'footer.provider': 'Fournisseur',
    'footer.partners': 'Partenaires Officiels',
    'footer.newsletter_title': 'Restez à l\'écoute !',
    'footer.newsletter_desc': 'Inscrivez-vous à notre newsletter pour découvrir de nouveaux artistes.',
    'footer.email_placeholder': 'votre adresse e-mail',
    'footer.subscribe': 'S\'abonner',
    'footer.social_title': 'Dites Bonjour !',
    'footer.legal_title': 'Juridique',
    'footer.link_work': 'Travaillez avec nous',
    'footer.link_cookies': 'Gérer les cookies',
    'footer.link_sub_tnc': 'Conditions d\'abonnement',
    'footer.link_gen_tnc': 'Conditions générales',
    'footer.link_privacy': 'Plan de confidentialité',
    'footer.rights': 'Tous droits réservés.',
  },
  PT: {
    'nav.pricing': 'PREÇOS',
    'nav.why': 'PORQUÊ',
    'nav.about': 'SOBRE',
    'nav.faq': 'FAQ',
    'nav.contact': 'CONTATO',
    'nav.signin': 'ENTRAR',
    'nav.getstarted': 'COMEÇAR',
    'nav.search_placeholder': 'Pesquisar artistas, música, notícias...',
    
    'hero.drop': 'LANCE.',
    'hero.grow': 'CRESÇA.',
    'hero.earn': 'GANHE.',
    
    'quick.distribution': 'DISTRIBUIÇÃO',
    'quick.marketing': 'MARKETING',
    'quick.royalties': 'ROYALTIES',
    'quick.analytics': 'ANÁLISES',
    'quick.services': 'Serviços para Artistas e Selos',
    
    'dist.title_1': 'Acessível',
    'dist.title_2': 'Auto-serviço',
    'dist.title_3': 'Distribuição',
    'dist.btn': 'Explorar Distribuição',
    
    'news.title': 'Sala de Imprensa',
    'news.category_product': 'Notícias de Produtos',
    'news.category_artist': 'Notícias de Artistas',

    'why.title_1': 'Porquê Escolher',
    'why.title_2': '2kTunes',
    'why.feature1_title': 'PAGAMENTOS LOCAIS',
    'why.feature1_desc': 'Levante os seus ganhos diretamente para Mobile Money ou conta bancária local instantaneamente.',
    'why.feature2_title': '100% PROPRIEDADE',
    'why.feature2_desc': 'Mantenha todos os seus direitos e 100% dos seus ganhos. Sem taxas ocultas.',
    'why.feature3_title': 'ANÁLISES EM TEMPO REAL',
    'why.feature3_desc': 'Monitorize os seus streams e royalties globalmente com o nosso painel transparente.',
    'why.feature4_title': 'DISTRIBUIÇÃO RÁPIDA',
    'why.feature4_desc': 'Coloque a sua música no Spotify, Apple Music e TikTok em tempo recorde.',
    
    'pricing.title_1': 'Preços',
    'pricing.title_2': 'Transparentes',
    'pricing.subtitle': 'Sem custos ocultos. Apenas música pura.',
    'pricing.starter': 'Starter',
    'pricing.pro': 'Pro',
    'pricing.label': 'Label',
    'pricing.mo': '/ mês',
    'pricing.custom': 'Personalizado',
    'pricing.recommended': 'Recomendado',
    'pricing.feature_unlimited': 'Uploads Ilimitados',
    'pricing.feature_stores': 'Todas as Lojas',
    'pricing.feature_royalties': '100% de Royalties',
    'pricing.feature_email': 'Suporte por E-mail',
    'pricing.feature_everything_starter': 'Tudo no Starter',
    'pricing.feature_mastering': 'Ferramentas de Mastering',
    'pricing.feature_team': 'Acesso de Equipe',
    'pricing.feature_priority': 'Suporte Prioritário',
    'pricing.feature_unlimited_artists': 'Artistas Ilimitados',
    'pricing.feature_premium_support': 'Suporte Premium',
    'pricing.feature_api': 'Acesso API',
    'pricing.feature_custom_terms': 'Termos Personalizados',
    'pricing.cta_starter': 'Começar',
    'pricing.cta_pro': 'Ser Pro',
    'pricing.cta_label': 'Contacte-nos',
    
    'about.title_1': 'Quem é a',
    'about.title_2': '2kTunes?',
    'about.p1': 'A 2kTunes é a principal força de distribuição de música e serviços para artistas construída para a próxima geração de estrelas globais.',
    'about.p2': 'Nossa missão é simples: fornecer aos artistas independentes as mesmas ferramentas usadas pelas maiores gravadoras.',
    'about.quote': "Não apenas distribuímos música; construímos destinos musicais.",

    'contact.title_1': 'Entre em',
    'contact.title_2': 'Contato',
    'contact.desc': 'Tem dúvidas sobre distribuição ou royalties? Nossa equipe está aqui para ajudar.',
    'contact.support_label': 'E-mail de Suporte',
    'contact.office_label': 'Localização do Escritório',
    'contact.label_name': 'Nome',
    'contact.label_email': 'E-mail',
    'contact.label_subject': 'Assunto',
    'contact.label_msg': 'Mensagem',
    'contact.placeholder_msg': 'Sua mensagem aqui...',
    'contact.btn': 'Enviar Mensagem',
    
    'faq.title_1': 'Perguntas',
    'faq.title_2': 'Frequentes',
    'faq.q1': 'Como faço o upload da música?',
    'faq.a1': 'Basta inscrever-se, criar um lançamento, carregar os seus ficheiros e escolher as lojas.',
    'faq.q2': 'Como sou pago?',
    'faq.a2': 'Os royalties are rastreados em tempo real. Levante instantaneamente para Mobile Money ou banco local.',
    'faq.q3': 'Mantenho os meus direitos?',
    'faq.a3': 'Sim. Você mantém 100% da propriedade dos seus masters.',
    'faq.q4': 'Posso mudar a minha música?',
    'faq.a4': 'Com certeza. Use os seus ISRCs existentes para manter as suas contagens de reprodução.',
    
    'cta.title_1': 'Comece a sua jornada',
    'cta.title_2': 'musical hoje',
    'cta.subtitle': 'Junte-se a milhares de artistas que confiam na 2kTunes.',
    'cta.btn': 'Aderir à 2kTunes',

    'features.desc': "Para artistas selecionados, nossa equipe simplifica sua carreira e acelera seus ganhos.",
    'features.item1': 'Parcerias sob medida',
    'features.item2': 'Estratégia de lançamento manual',
    'features.item3': 'Suporte de distribuição de ponta a ponta',
    'features.item4': 'Gestão de receitas tudo-em-um',
    'features.item5': 'Mantenha sua liberdade criativa',

    'showcase.title_1': 'Artistas',
    'showcase.title_2': 'Com Quem Trabalhamos',
    'showcase.desc': 'Nossa equipe gere parcerias com mais de 400 artistas e equipas.',
    'showcase.listeners': 'ouvintes mensais',

    'footer.tagline': 'Alcance global. Dinheiro local.',
    'footer.preferred': 'Preferencial',
    'footer.provider': 'Fornecedor',
    'footer.partners': 'Parceiros Oficiais',
    'footer.newsletter_title': 'Fique atento!',
    'footer.newsletter_desc': 'Assine nossa newsletter para descobrir novos artistas.',
    'footer.email_placeholder': 'escreva o seu e-mail',
    'footer.subscribe': 'Inscrever',
    'footer.social_title': 'Diga Olá!',
    'footer.legal_title': 'Legal',
    'footer.link_work': 'Trabalhe connosco',
    'footer.link_cookies': 'Gerir Cookies',
    'footer.link_sub_tnc': 'T&C de Assinatura',
    'footer.link_gen_tnc': 'T&C Gerais',
    'footer.link_privacy': 'Política de Privacidade',
    'footer.rights': 'Todos os direitos reservados.',
  },
  ES: {
    'nav.pricing': 'PRECIOS',
    'nav.why': 'POR QUÉ',
    'nav.about': 'SOBRE NOSOTROS',
    'nav.faq': 'FAQ',
    'nav.contact': 'CONTACTO',
    'nav.signin': 'INGRESAR',
    'nav.getstarted': 'EMPEZAR',
    'nav.search_placeholder': 'Buscar artistas, música, noticias...',
    
    'hero.drop': 'LANZA.',
    'hero.grow': 'CRECE.',
    'hero.earn': 'GANA.',
    
    'quick.distribution': 'DISTRIBUCIÓN',
    'quick.marketing': 'MARKETING',
    'quick.royalties': 'REGALÍAS',
    'quick.analytics': 'ANALÍTICA',
    'quick.services': 'Servicios para Artistas y Sellos',
    
    'dist.title_1': 'Asequible',
    'dist.title_2': 'Autoservicio',
    'dist.title_3': 'Distribución',
    'dist.btn': 'Explorar Distribución',
    
    'news.title': 'Sala de Prensa',
    'news.category_product': 'Noticias de Productos',
    'news.category_artist': 'Noticias de Artistas',

    'why.title_1': 'Por qué elegir',
    'why.title_2': '2kTunes',
    'why.feature1_title': 'PAGOS LOCALES',
    'why.feature1_desc': 'Retira tus ganancias directamente a Mobile Money o a tu cuenta bancaria local al instante.',
    'why.feature2_title': '100% PROPIEDAD',
    'why.feature2_desc': 'Mantienes todos tus derechos y el 100% de tus ganancias. Sin cargos ocultos.',
    'why.feature3_title': 'ANALÍTICA EN TIEMPO REAL',
    'why.feature3_desc': 'Monitorea tus reproducciones y regalías globalmente con nuestro tablero transparente.',
    'why.feature4_title': 'DISTRIBUCIÓN RÁPIDA',
    'why.feature4_desc': 'Pon tu música en Spotify, Apple Music y TikTok en tiempo récord.',
    
    'pricing.title_1': 'Precios',
    'pricing.title_2': 'Transparentes',
    'pricing.subtitle': 'Sin costos ocultos. Solo música pura.',
    'pricing.starter': 'Starter',
    'pricing.pro': 'Pro',
    'pricing.label': 'Label',
    'pricing.mo': '/ mes',
    'pricing.custom': 'Personalizado',
    'pricing.recommended': 'Recomendado',
    'pricing.feature_unlimited': 'Subidas Ilimitadas',
    'pricing.feature_stores': 'Todas las Tiendas',
    'pricing.feature_royalties': '100% de Regalías',
    'pricing.feature_email': 'Soporte por Email',
    'pricing.feature_everything_starter': 'Todo en Starter',
    'pricing.feature_mastering': 'Herramientas de Mastering',
    'pricing.feature_team': 'Acceso de Equipo',
    'pricing.feature_priority': 'Soporte Prioritario',
    'pricing.feature_unlimited_artists': 'Artistas Ilimitados',
    'pricing.feature_premium_support': 'Soporte Premium',
    'pricing.feature_api': 'Acceso API',
    'pricing.feature_custom_terms': 'Términos Personalizados',
    'pricing.cta_starter': 'Empezar',
    'pricing.cta_pro': 'Ser Pro',
    'pricing.cta_label': 'Contáctanos',
    
    'about.title_1': '¿Quién es',
    'about.title_2': '2kTunes?',
    'about.p1': '2kTunes es la principal fuerza de distribution de música y servicios para artistas construida para las nuevas estrellas globales.',
    'about.p2': 'Nuestra misión es simple: proveer a artistas independientes las mismas herramientas que los grandes sellos.',
    'about.quote': "No solo distribuimos música; construimos destinos musicales.",

    'contact.title_1': 'Ponte en',
    'contact.title_2': 'Contacto',
    'contact.desc': '¿Tienes preguntas sobre distribución o regalías? Nuestro equipo está listo para ayudarte.',
    'contact.support_label': 'Email de Soporte',
    'contact.office_label': 'Ubicación de la Oficina',
    'contact.label_name': 'Nombre',
    'contact.label_email': 'Email',
    'contact.label_subject': 'Asunto',
    'contact.label_msg': 'Message',
    'contact.placeholder_msg': 'Tu mensaje aquí...',
    'contact.btn': 'Enviar Mezaje',
    
    'faq.title_1': 'Preguntas',
    'faq.title_2': 'Frecuentes',
    'faq.q1': '¿Cómo subo música?',
    'faq.a1': 'Regístrate, crea un lanzamiento, sube tus archivos y elige tus tiendas.',
    'faq.q2': '¿Cómo me pagan?',
    'faq.a2': 'Las regalías se rastrean en tiempo real. Retira al instante a Mobile Money o banco local.',
    'faq.q3': '¿Mantengo mis derechos?',
    'faq.a3': 'Sí. Mantienes el 100% de la propiedad de tus masters.',
    'faq.q4': '¿Puedo cambiar mi música?',
    'faq.a4': 'Absolutamente. Usa tus ISRCs existentes para mantener tus estadísticas de reproducción.',
    
    'cta.title_1': 'Empieza tu viaje',
    'cta.title_2': 'musical hoy',
    'cta.subtitle': 'Únete a miles de artistas que confían en 2kTunes.',
    'cta.btn': 'Unirse a 2kTunes',

    'features.desc': "Para artistas seleccionados, nuestro equipo simplifica tu carrera y acelera tus ganancias.",
    'features.item1': 'Alianzas a medida',
    'features.item2': 'Estrategia de lanzamientos práctica',
    'features.item3': 'Soporte de distribución integral',
    'features.item4': 'Gestión de ingresos todo-en-uno',
    'features.item5': 'Mantén tu libertad creativa',

    'showcase.title_1': 'Artistas',
    'showcase.title_2': 'Con Quienes Trabajamos',
    'showcase.desc': 'Nuestros Servicios gestionan alianzas con más de 400 artistas y equipos.',
    'showcase.listeners': 'oyentes mensuales',

    'footer.tagline': 'Alcance global. Efectivo local.',
    'footer.preferred': 'Preferido',
    'footer.provider': 'Proveedor',
    'footer.partners': 'Socios Oficiales',
    'footer.newsletter_title': '¡Mantente en sintonía!',
    'footer.newsletter_desc': 'Suscríbete a nuestro boletín para descubrir nuevos artistas.',
    'footer.email_placeholder': 'escribe tu email',
    'footer.subscribe': 'Suscribirse',
    'footer.social_title': '¡Di Hola!',
    'footer.legal_title': 'Legal',
    'footer.link_work': 'Trabaja con nosotros',
    'footer.link_cookies': 'Gestionar Cookies',
    'footer.link_sub_tnc': 'T&C de Suscripción',
    'footer.link_gen_tnc': 'T&C Generales',
    'footer.link_privacy': 'Política de Privacidad',
    'footer.rights': 'Todos los derechos reservados.',
  },
  SW: {
    'nav.pricing': 'BEI',
    'nav.why': 'KWANINI',
    'nav.about': 'KUHUSU',
    'nav.faq': 'MASWALI',
    'nav.contact': 'WASILIANA',
    'nav.signin': 'INGIA',
    'nav.getstarted': 'ANZA SASA',
    'nav.search_placeholder': 'Tafuta wasanii, muziki, habari...',
    
    'hero.drop': 'ACHIA.',
    'hero.grow': 'KUA.',
    'hero.earn': 'INGIZA.',
    
    'quick.distribution': 'USAMBAZAJI',
    'quick.marketing': 'MASOKO',
    'quick.royalties': 'MIRABAA',
    'quick.analytics': 'TAKWEEMU',
    'quick.services': 'Huduma za Wasanii na Lebo',
    
    'dist.title_1': 'Bei',
    'dist.title_2': 'Nafuu na',
    'dist.title_3': 'Rahisi',
    'dist.btn': 'Gundua Usambazaji',
    
    'news.title': 'Habari za Hivi Karibuni',
    'news.category_product': 'Habari za Bidhaa',
    'news.category_artist': 'Habari za Wasanii',

    'why.title_1': 'Kwanini Chagua',
    'why.title_2': '2kTunes',
    'why.feature1_title': 'MALIPO YA NDANI',
    'why.feature1_desc': 'Toa kipato chako moja kwa moja kwenda Mobile Money au akaunti yako ya benki ya hapa papo hapo.',
    'why.feature2_title': 'UMILIKI WA 100%',
    'why.feature2_desc': 'Unabaki na haki zako zote na 100% ya mapato yako. Hakuna ada zilizofichwa.',
    'why.feature3_title': 'TAKWEEMU ZA MUDA HALISI',
    'why.feature3_desc': 'Fuatilia miguso na mirabaa yako ulimwenguni kote kupitia dashibodi yetu wazi.',
    'why.feature4_title': 'USAMBAZAJI WA HARAKA',
    'why.feature4_desc': 'Weka muziki wako kwenye Spotify, Apple Music, na TikTok kwa muda mfupi zaidi.',
    
    'pricing.title_1': 'Bei za',
    'pricing.title_2': 'Wazi',
    'pricing.subtitle': 'Hakuna gharama zilizofichwa. Muziki halisi tu.',
    'pricing.starter': 'Starter',
    'pricing.pro': 'Pro',
    'pricing.label': 'Label',
    'pricing.mo': '/ mwezi',
    'pricing.custom': 'Maalum',
    'pricing.recommended': 'Imependekezwa',
    'pricing.feature_unlimited': 'Upakiaji Bila Kikomo',
    'pricing.feature_stores': 'Maduka Yote',
    'pricing.feature_royalties': 'Mirabaa 100%',
    'pricing.feature_email': 'Msaada wa Barua Pepe',
    'pricing.feature_everything_starter': 'Kila Kitu Kwenye Starter',
    'pricing.feature_mastering': 'Zana za Mastering',
    'pricing.feature_team': 'Ufikiaji wa Timu',
    'pricing.feature_priority': 'Msaada wa Kipaumbele',
    'pricing.feature_unlimited_artists': 'Wasanii Bila Kikomo',
    'pricing.feature_premium_support': 'Msaada wa Premium',
    'pricing.feature_api': 'Ufikiaji wa API',
    'pricing.feature_custom_terms': 'Vigezo Maalum',
    'pricing.cta_starter': 'Anza Sasa',
    'pricing.cta_pro': 'Kuwa Pro',
    'pricing.cta_label': 'Wasiliana Nasi',
    
    'about.title_1': 'Nani ni',
    'about.title_2': '2kTunes?',
    'about.p1': "2kTunes ndio kitovu kikuu cha usambazaji wa muziki na huduma za wasanii kilichojengwa kwa ajili ya kizazi kijacho cha mastaa wa kimataifa.",
    'about.p2': 'Dhamira yetu ni rahisi: Kuwapa wasanii huru zana zile zile zinazotumiwa na lebo kubwa zaidi duniani.',
    'about.quote': "Hatuchapishi tu muziki; tunatengeneza hatima za muziki.",

    'contact.title_1': 'Tuwasiliane',
    'contact.title_2': 'Sasa',
    'contact.desc': 'Una maswali kuhusu usambazaji, mirabaa, au huduma zetu? Timu yetu iko hapa kukusaidia kukuza kazi yako.',
    'contact.support_label': 'Barua Pepe ya Msaada',
    'contact.office_label': 'Mahali pa Ofisi',
    'contact.label_name': 'Jina',
    'contact.label_email': 'Barua Pepe',
    'contact.label_subject': 'Mada',
    'contact.label_msg': 'Ujumbe',
    'contact.placeholder_msg': 'Ujumbe wako hapa...',
    'contact.btn': 'Tuma Ujumbe',
    
    'faq.title_1': 'Maswali',
    'faq.title_2': 'Yanayoulizwa',
    'faq.q1': 'How do I upload music?',
    'faq.a1': 'Simply sign up, create a new release on your dashboard, upload your masters and artwork, and pick your stores. Our team handles the rest.',
    'faq.q2': 'How do I get paid?',
    'faq.a2': 'Royalties are tracked in real-time. You can withdraw your earnings instantly to Mobile Money or your local bank account via our secure payment gateway.',
    'faq.q3': 'Do I keep my rights?',
    'faq.a3': 'Yes. You keep 100% ownership of your masters and publishing rights. We are your distribution partner, not your owner.',
    'faq.q4': 'Can I move my music to 2kTunes?',
    'faq.a4': 'Absolutely. Use your existing ISRCs to ensure you keep your play counts and placement when migrating to our platform.',
    
    'cta.title_1': 'Anza safari yako',
    'cta.title_2': 'ya muziki leo',
    'cta.subtitle': 'Jiunge na maelfu ya wasanii wanaoamini 2kTunes kuendeleza kazi zao huru.',
    'cta.btn': 'Jiunge na 2kTunes',

    'features.desc': "Kwa baadhi ya wasanii, timu yetu inarahisisha kazi yako na kuharakisha mapato yako.",
    'features.item1': 'Ushirikiano maalum',
    'features.item2': 'Mkakati wa toleo kwa vitendo',
    'features.item3': 'Msaada wa usambazaji wa mwanzo hadi mwisho',
    'features.item4': 'Usimamizi wa mapato yote kwa pamoja',
    'features.item5': 'Baki na uhuru wako wa ubunifu',

    'showcase.title_1': 'Wasanii',
    'showcase.title_2': 'Tunaofanya nao Kazi',
    'showcase.desc': 'Huduma zetu zinasimamia ushirikiano maalum na wasanii na timu zaidi ya 400.',
    'showcase.listeners': 'wasikilizaji wa mwezi',

    'footer.tagline': 'Ufikiaji wa dunia. Pesa za nyumbani.',
    'footer.preferred': 'Iliyopendekezwa',
    'footer.provider': 'Mtoa Huduma',
    'footer.partners': 'Washirika Rasmi',
    'footer.newsletter_title': 'Habari zaidi !',
    'footer.newsletter_desc': 'Jiunge na jarida letu kugundua wasanii wapya.',
    'footer.email_placeholder': 'andika barua pepe yako',
    'footer.subscribe': 'Jiunge',
    'footer.social_title': 'Tusalimie !',
    'footer.legal_title': 'Sheria',
    'footer.link_work': 'Fanya kazi nasi',
    'footer.link_cookies': 'Dhibiti Cookies',
    'footer.link_sub_tnc': 'Vigezo vya Usajili',
    'footer.link_gen_tnc': 'Vigezo na Masharti',
    'footer.link_privacy': 'Sera ya Faragha',
    'footer.rights': 'Haki zote zimehifadhiwa.',
    'common.visa': 'Visa',
    'common.mobile_money': 'Mobile Money',
    'common.paypal': 'PayPal',
    'common.spotify_artist': 'Spotify for Artists',
    'common.skip': 'Rukia kwa sasa',
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('EN');

  const t = (key: string): string => {
    return translations[language][key] || translations['EN'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
