import type { Release, ReleaseConfig, Store, Track } from "@/lib/api/types";

/** Realistic-shape API rows for tests (never used by the app itself). */
export function makeRelease(over: Partial<Release> = {}): Release {
  return {
    id: 7,
    artist_id: 3,
    release_title: "Bahari",
    version: null,
    artist_name: "Neema",
    additional_artists: [],
    release_type: "Single",
    release_date: "2026-11-20",
    release_time: null,
    release_timezone: null,
    original_release_date: null,
    previously_released: false,
    record_label: null,
    language: "sw",
    primary_genre: "Bongo Flava",
    secondary_genre: null,
    c_line_year: "2026",
    c_line_owner: "Neema",
    p_line_year: "2026",
    p_line_owner: "Neema",
    is_compilation: false,
    upc: null,
    upc_generated: false,
    cover_image: null,
    cover: null,
    platforms: ["spotify"],
    territories: { mode: "worldwide", countries: [] },
    social_options: {},
    agreements: {},
    status: "draft",
    status_label: "Draft",
    stage: 0,
    is_editable: true,
    rejection_reason: null,
    slug: "bahari-abc123",
    smart_link_url: null,
    smart_link_enabled: true,
    presave_enabled: false,
    draft_step: "info",
    submitted_at: null,
    approved_at: null,
    live_at: null,
    created_at: "2026-09-01T10:00:00Z",
    updated_at: "2026-09-02T10:00:00Z",
    tracks_count: 1,
    tracks: [],
    open_issues: [],
    deliveries: [],
    timeline: [],
    ...over,
  };
}

export function makeTrack(over: Partial<Track> = {}): Track {
  return {
    id: 11,
    release_id: 7,
    track_number: 1,
    title: "Bahari",
    version: null,
    primary_artist: "Neema",
    featured_artists: [],
    isrc: null,
    isrc_generated: false,
    language: null,
    lyrics: null,
    instrumental: false,
    explicit: false,
    is_clean_version: false,
    ai_generated: false,
    preview_start_seconds: null,
    publisher: null,
    ownership: "original",
    primary_genre: null,
    audio_url: null,
    audio: null,
    credits: [],
    ...over,
  };
}

export const releaseConfig: ReleaseConfig = {
  artwork: { min_px: 3000, max_px: 6000, max_kb: 20480, mimes: ["jpg", "jpeg", "png"], must_be_square: true },
  audio: { max_mb: 500, formats: ["wav", "flac", "mp3"], lossless_formats: ["wav", "flac"], min_sample_rate: 44100, min_bit_depth: 16, min_duration_seconds: 30 },
  tracks: { Single: { min: 1, max: 3 }, EP: { min: 2, max: 7 }, Album: { min: 5, max: 50 } },
  min_lead_days: 7,
  recommended_lead_days: 21,
  genres: ["Afrobeats", "Bongo Flava", "Amapiano"],
  languages: { sw: "Swahili", en: "English" },
  contributor_roles: ["songwriter", "composer", "lyricist", "producer"],
  isrc_generation: false,
  upc_generation: false,
  required_agreements: ["rights_confirmation", "distribution_terms"],
  upload_chunk_size: 8388608,
  marketplace: { platforms: ["tiktok", "instagram"], categories: ["dance", "music"], campaign_types: ["creator_campaign"], currencies: ["TZS", "USD"], platform_fee_bp: 1500 },
};

export const stores: Store[] = [
  { id: 1, slug: "spotify", name: "Spotify", category: "streaming", status: "available" },
  { id: 2, slug: "boomplay", name: "Boomplay", category: "streaming", status: "available" },
  { id: 3, slug: "mdundo", name: "Mdundo", category: "streaming", status: "coming_soon" },
];

export const emptyMeta = { current_page: 1, last_page: 1, per_page: 20, total: 0 };
