import type { Order } from "@/lib/api/types";

/** A creator request as GET /orders/{id} returns it (artist view by default). */
export function makeOrder(over: Partial<Order> = {}): Order {
  return {
    id: 42,
    reference: "OR261002ABC123",
    kind: "creator_request",
    title: "TikTok dance video · Dada Dance",
    status: "awaiting_payment",
    status_label: "Accepted, awaiting payment",
    role: "buyer",
    price_minor: 10_000_000,
    currency: "TZS",
    platform_fee_minor: null,
    creator_payout_minor: null,
    creator: { id: 4, display_name: "Dada Dance", slug: "dada-dance", avatar_url: null },
    artist: null,
    package: { id: 12, title: "TikTok dance video", platform: "tiktok", turnaround_days: 3 },
    service: null,
    campaign_id: null,
    song: {
      source: "external",
      release_id: null,
      track_id: null,
      title: "Moyo Wangu",
      artist: "Zuri Mwangi",
      url: "https://open.spotify.com/track/abc",
      platform: "spotify",
      listen_url: "https://open.spotify.com/track/abc",
    },
    brief: "Use the chorus at 0:45",
    preferred_post_date: "2026-10-20",
    creator_note: "Posting Friday",
    submission_urls: [],
    submission_notes: null,
    fix_note: null,
    fix_count: 0,
    respond_by: null,
    pay_by: "2026-10-09T09:00:00Z",
    due_at: null,
    payment: { method: null, paid_at: null, manual_reference_submitted: false },
    overdue: false,
    forwarded_at: "2026-10-01T09:00:00Z",
    accepted_at: "2026-10-02T09:00:00Z",
    submitted_at: null,
    completed_at: null,
    created_at: "2026-10-01T08:00:00Z",
    can: { cancel: true, pay: true, accept: false, decline: false, submit: false, dispute: false, message: true },
    timeline: [
      { from: null, to: "requested", label: "Requested", actor: "artist", note: "Request submitted.", at: "2026-10-01T08:00:00Z" },
      { from: "requested", to: "forwarded", label: "Waiting for the creator", actor: "staff", note: null, at: "2026-10-01T09:00:00Z" },
      { from: "forwarded", to: "awaiting_payment", label: "Accepted, awaiting payment", actor: "creator", note: "Posting Friday", at: "2026-10-02T09:00:00Z" },
    ],
    messages: [],
    disputes: [],
    ...over,
  };
}
