/** Screen copy for Promotion: smart links, campaigns and promotion services. */

const EN = {
  title: "Promotion",
  intro:
    "Share your music with smart links, plan campaigns, and hire creators or 2kTunes services. We describe exactly what each service does — results such as streams, followers or playlist placement are never guaranteed.",
  tabsLabel: "Promotion sections",
  tabLinks: "Smart links",
  tabCampaigns: "Campaigns",
  tabServices: "Promotion services",

  /* Smart links */
  linksIntro:
    "Every release gets a smart link: one page listing every store your music is live on, with an optional pre-save before release day.",
  noReleasesTitle: "No releases yet",
  noReleasesBody: "Create a release to get its smart link.",
  newRelease: "New release",
  linkPublic: "Public",
  linkOff: "Smart link is off",
  linkNotYet: "Goes public once the release is submitted",
  linkHidden: "Not public while the release is rejected or taken down",
  linkOffBody: "Visitors can't open this link until you turn it on.",
  linkUrl: (title: string) => `Smart link for ${title}`,
  openLink: "Open",
  openLinkLabel: (title: string) => `Open the smart link for ${title} (opens in a new tab)`,
  copyLink: "Copy link",
  noSlug: "This release has no link address yet.",
  smartLinkLabel: "Smart link",
  presaveLabel: "Pre-save",
  smartLinkToggle: "Smart link on",
  smartLinkToggleHint: "Turn off to hide the public page.",
  presaveToggle: "Pre-save on",
  presaveToggleHint: "Fans can leave their email to be told on release day. Hidden once the release is live.",
  on: "On",
  off: "Off",
  lockedNote:
    "These settings lock once a release is submitted. Contact support if you need them changed.",
  saved: "Smart link settings saved",
  stats: "View link stats",
  statsLabel: (title: string) => `View link stats for ${title}`,
  cover: (title: string) => `Cover art for ${title}`,

  /* Stats dialog */
  statsTitle: (title: string) => `Link stats · ${title}`,
  statsIntro: "Counted from visits to your smart link. No personal data is stored about visitors.",
  range: "Period",
  range7: "Last 7 days",
  range30: "Last 30 days",
  range90: "Last 90 days",
  range12m: "Last 12 months",
  views: "Page views",
  unique: "Unique visitors",
  clicks: "Store clicks",
  presaves: "Pre-saves",
  byStore: "Clicks by store",
  byCountry: "Views by country",
  byDevice: "Views by device",
  byReferrer: "Top referrers",
  direct: "Direct / unknown",
  noStatsTitle: "No visits in this period",
  noStatsBody: "Share your smart link to start seeing visits here.",
  noneYet: "Nothing yet",

  /* Campaigns */
  campaignsIntro: "Group the creator orders and services you buy for a release into one campaign.",
  newCampaign: "New campaign",
  noCampaignsTitle: "No campaigns yet",
  noCampaignsBody: "Create a campaign to plan promotion for a release, then add creators or services to it.",
  colTitle: "Campaign",
  colType: "Type",
  colStatus: "Status",
  colRelease: "Release",
  colOrders: "Orders",
  colBudget: "Budget",
  campaignsCaption: "Your campaigns",
  noBudget: "—",

  /* Campaign form */
  createTitle: "New campaign",
  editTitle: "Edit campaign",
  formIntro: "A campaign is your plan. Nothing is charged until you order a creator package or a service and pay for it.",
  fTitle: "Title",
  fTitleRequired: "Give the campaign a title.",
  fType: "Type",
  fObjective: "Objective",
  fObjectiveNone: "No objective",
  fRelease: "Release",
  fReleaseNone: "No specific release",
  fTrack: "Track",
  fTrackNone: "Whole release",
  fBudget: "Budget",
  fBudgetHint: "For your own planning. Nothing is charged.",
  fBudgetInvalid: "Enter an amount like 150000 or 150000.50.",
  fCurrency: "Currency",
  fCountries: "Target countries",
  fCountriesHint: "Two-letter codes separated by commas, e.g. TZ, KE, UG",
  fCountriesInvalid: "Use two-letter country codes separated by commas, e.g. TZ, KE.",
  fAudience: "Target audience",
  fAudienceHint: "Who should hear this? e.g. Bongo Flava fans aged 18–30 in Dar es Salaam",
  fBrief: "Brief",
  fBriefHint: "Shared with creators you order from, unless you write a separate brief on the order.",
  fPitch: "Playlist pitch",
  fPitchIntro: "Used when pitching the track to playlist curators. Curators decide independently; placement is never guaranteed.",
  fPitchPlatform: "Platform",
  fPitchGenre: "Genre",
  fPitchMood: "Mood",
  fPitchDescription: "Pitch description",
  fPitchSimilar: "Similar artists",
  fStarts: "Starts on",
  fEnds: "Ends on",
  fEndsInvalid: "The end date can't be before the start date.",
  created: "Campaign created",
  saved2: "Campaign saved",

  /* Campaign detail */
  backToCampaigns: "Campaigns",
  details: "Details",
  type: "Type",
  objective: "Objective",
  release: "Release",
  track: "Track",
  budget: "Budget",
  countries: "Target countries",
  audience: "Target audience",
  dates: "Dates",
  datesValue: (a: string, b: string) => `${a} – ${b}`,
  createdAt: "Created",
  brief: "Brief",
  noBrief: "No brief yet.",
  pitch: "Playlist pitch",
  edit: "Edit",
  cancelCampaign: "Cancel campaign",
  cancelTitle: "Cancel this campaign?",
  cancelBody:
    "Unpaid orders in it are cancelled too. Campaigns with paid orders still in progress can't be cancelled until those orders are finished.",
  cancelled: "Campaign cancelled",
  closedNote: "This campaign is closed and can no longer be changed.",
  ordersTitle: "Orders in this campaign",
  noOrders: "No orders yet. Add a creator or a promotion service.",
  findCreators: "Find creators",
  addService: "Add a promotion service",
  serviceBy2k: "2kTunes service",

  /* Services */
  servicesIntro:
    "Services run by the 2kTunes team. Each one describes exactly what we do. Results depend on audiences and third parties and are not guaranteed.",
  noServicesTitle: "No services available",
  noServicesBody: "There are no promotion services on offer right now. Check back later.",
  order: "Order",
  orderLabel: (name: string) => `Order ${name}`,
  disclaimer: "Please note",
  category: "Category",

  /* Add service dialog */
  addServiceTitle: "Add a promotion service",
  chooseService: "Service",
  chooseServicePlaceholder: "Choose a service",
  serviceRequired: "Choose a service.",
  orderBrief: "Brief for this order",
  orderBriefHint: "Leave empty to use the campaign brief.",
  createOrder: "Create order",
  orderCreated: "Order created — pay for it to get started",
};

const SW: typeof EN = {
  title: "Utangazaji",
  intro:
    "Sambaza muziki wako kwa smart link, panga kampeni, na uajiri watengeneza maudhui au huduma za 2kTunes. Tunaeleza wazi kila huduma inachofanya — matokeo kama streams, wafuasi au kuwekwa kwenye playlist hayahakikishwi kamwe.",
  tabsLabel: "Sehemu za utangazaji",
  tabLinks: "Smart link",
  tabCampaigns: "Kampeni",
  tabServices: "Huduma za utangazaji",

  linksIntro:
    "Kila toleo linapata smart link: ukurasa mmoja unaoonyesha kila duka ambalo muziki wako upo, pamoja na pre-save ya hiari kabla ya siku ya kutoka.",
  noReleasesTitle: "Bado huna matoleo",
  noReleasesBody: "Tengeneza toleo ili upate smart link yake.",
  newRelease: "Toleo jipya",
  linkPublic: "Iko hewani",
  linkOff: "Smart link imezimwa",
  linkNotYet: "Itaonekana hadharani baada ya toleo kuwasilishwa",
  linkHidden: "Haionekani hadharani wakati toleo limekataliwa au limeondolewa",
  linkOffBody: "Wageni hawawezi kufungua kiungo hiki hadi uiwashe.",
  linkUrl: (title) => `Smart link ya ${title}`,
  openLink: "Fungua",
  openLinkLabel: (title) => `Fungua smart link ya ${title} (inafunguka kichupo kipya)`,
  copyLink: "Nakili kiungo",
  noSlug: "Toleo hili bado halina anwani ya kiungo.",
  smartLinkLabel: "Smart link",
  presaveLabel: "Pre-save",
  smartLinkToggle: "Smart link imewashwa",
  smartLinkToggleHint: "Zima ili kuficha ukurasa wa umma.",
  presaveToggle: "Pre-save imewashwa",
  presaveToggleHint:
    "Mashabiki wanaweza kuacha barua pepe ili wajulishwe siku ya kutoka. Inafichwa toleo likishakuwa hewani.",
  on: "Imewashwa",
  off: "Imezimwa",
  lockedNote: "Mipangilio hii inafungwa toleo likishawasilishwa. Wasiliana na huduma kwa wateja ukihitaji ibadilishwe.",
  saved: "Mipangilio ya smart link imehifadhiwa",
  stats: "Tazama takwimu za kiungo",
  statsLabel: (title) => `Tazama takwimu za kiungo cha ${title}`,
  cover: (title) => `Picha ya jalada ya ${title}`,

  statsTitle: (title) => `Takwimu za kiungo · ${title}`,
  statsIntro: "Zimehesabiwa kutoka kwa ziara kwenye smart link yako. Hakuna taarifa binafsi za wageni zinazohifadhiwa.",
  range: "Kipindi",
  range7: "Siku 7 zilizopita",
  range30: "Siku 30 zilizopita",
  range90: "Siku 90 zilizopita",
  range12m: "Miezi 12 iliyopita",
  views: "Mara ukurasa ulitazamwa",
  unique: "Wageni tofauti",
  clicks: "Mibofyo kwenda madukani",
  presaves: "Pre-save",
  byStore: "Mibofyo kwa duka",
  byCountry: "Ziara kwa nchi",
  byDevice: "Ziara kwa kifaa",
  byReferrer: "Vyanzo vikuu vya wageni",
  direct: "Moja kwa moja / haijulikani",
  noStatsTitle: "Hakuna ziara katika kipindi hiki",
  noStatsBody: "Sambaza smart link yako ili uanze kuona ziara hapa.",
  noneYet: "Bado hakuna",

  campaignsIntro: "Weka pamoja oda za watengeneza maudhui na huduma unazonunua kwa toleo moja ndani ya kampeni moja.",
  newCampaign: "Kampeni mpya",
  noCampaignsTitle: "Bado huna kampeni",
  noCampaignsBody:
    "Anzisha kampeni kupanga utangazaji wa toleo, kisha ongeza watengeneza maudhui au huduma ndani yake.",
  colTitle: "Kampeni",
  colType: "Aina",
  colStatus: "Hali",
  colRelease: "Toleo",
  colOrders: "Oda",
  colBudget: "Bajeti",
  campaignsCaption: "Kampeni zako",
  noBudget: "—",

  createTitle: "Kampeni mpya",
  editTitle: "Hariri kampeni",
  formIntro:
    "Kampeni ni mpango wako. Hakuna kinachotozwa hadi uagize kifurushi cha mtengeneza maudhui au huduma na ukilipie.",
  fTitle: "Jina",
  fTitleRequired: "Ipe kampeni jina.",
  fType: "Aina",
  fObjective: "Lengo",
  fObjectiveNone: "Hakuna lengo",
  fRelease: "Toleo",
  fReleaseNone: "Hakuna toleo maalum",
  fTrack: "Wimbo",
  fTrackNone: "Toleo zima",
  fBudget: "Bajeti",
  fBudgetHint: "Kwa mipango yako mwenyewe. Hakuna kinachotozwa.",
  fBudgetInvalid: "Weka kiasi kama 150000 au 150000.50.",
  fCurrency: "Sarafu",
  fCountries: "Nchi lengwa",
  fCountriesHint: "Misimbo ya herufi mbili ikitenganishwa kwa koma, mf. TZ, KE, UG",
  fCountriesInvalid: "Tumia misimbo ya nchi ya herufi mbili ikitenganishwa kwa koma, mf. TZ, KE.",
  fAudience: "Hadhira lengwa",
  fAudienceHint: "Nani asikie wimbo huu? mf. wapenzi wa Bongo Flava wenye umri wa miaka 18–30 jijini Dar es Salaam",
  fBrief: "Maelekezo",
  fBriefHint: "Yanashirikishwa na watengeneza maudhui unaowaagiza, isipokuwa ukiandika maelekezo tofauti kwenye oda.",
  fPitch: "Maelezo ya kupendekeza kwa playlist",
  fPitchIntro:
    "Yanatumika kupendekeza wimbo kwa wasimamizi wa playlist. Wasimamizi huamua wenyewe; kuwekwa kwenye playlist hakuhakikishwi kamwe.",
  fPitchPlatform: "Jukwaa",
  fPitchGenre: "Mtindo wa muziki",
  fPitchMood: "Hisia ya wimbo",
  fPitchDescription: "Maelezo ya pendekezo",
  fPitchSimilar: "Wasanii wanaofanana",
  fStarts: "Inaanza",
  fEnds: "Inaisha",
  fEndsInvalid: "Tarehe ya mwisho haiwezi kuwa kabla ya tarehe ya kuanza.",
  created: "Kampeni imeanzishwa",
  saved2: "Kampeni imehifadhiwa",

  backToCampaigns: "Kampeni",
  details: "Maelezo",
  type: "Aina",
  objective: "Lengo",
  release: "Toleo",
  track: "Wimbo",
  budget: "Bajeti",
  countries: "Nchi lengwa",
  audience: "Hadhira lengwa",
  dates: "Tarehe",
  datesValue: (a, b) => `${a} – ${b}`,
  createdAt: "Ilianzishwa",
  brief: "Maelekezo",
  noBrief: "Bado hakuna maelekezo.",
  pitch: "Maelezo ya kupendekeza kwa playlist",
  edit: "Hariri",
  cancelCampaign: "Sitisha kampeni",
  cancelTitle: "Usitishe kampeni hii?",
  cancelBody:
    "Oda ambazo hazijalipiwa ndani yake zitaghairiwa pia. Kampeni yenye oda zilizolipiwa ambazo bado zinaendelea haiwezi kusitishwa hadi oda hizo zikamilike.",
  cancelled: "Kampeni imesitishwa",
  closedNote: "Kampeni hii imefungwa na haiwezi kubadilishwa tena.",
  ordersTitle: "Oda za kampeni hii",
  noOrders: "Bado hakuna oda. Ongeza mtengeneza maudhui au huduma ya utangazaji.",
  findCreators: "Tafuta watengeneza maudhui",
  addService: "Ongeza huduma ya utangazaji",
  serviceBy2k: "Huduma ya 2kTunes",

  servicesIntro:
    "Huduma zinazoendeshwa na timu ya 2kTunes. Kila moja inaeleza wazi tunachofanya. Matokeo yanategemea hadhira na wahusika wengine, na hayahakikishwi.",
  noServicesTitle: "Hakuna huduma zinazopatikana",
  noServicesBody: "Hakuna huduma za utangazaji zinazotolewa kwa sasa. Rudi baadaye.",
  order: "Agiza",
  orderLabel: (name) => `Agiza ${name}`,
  disclaimer: "Tafadhali zingatia",
  category: "Kundi",

  addServiceTitle: "Ongeza huduma ya utangazaji",
  chooseService: "Huduma",
  chooseServicePlaceholder: "Chagua huduma",
  serviceRequired: "Chagua huduma.",
  orderBrief: "Maelekezo ya oda hii",
  orderBriefHint: "Acha wazi ili kutumia maelekezo ya kampeni.",
  createOrder: "Tengeneza oda",
  orderCreated: "Oda imetengenezwa — ilipie ili ianze",
};

export const COPY = { EN, SW };
