/** Wallet screen copy. Shared strings (actions, statuses, errors) come from `t()`. */

const EN = {
  title: "Wallet",
  intro: "Your earnings, withdrawals and payout methods. Every amount comes straight from the 2kTunes ledger.",
  withdraw: "Withdraw",
  nothingToWithdraw: "Nothing is available to withdraw yet.",

  /* Balances */
  balancesTitle: "Balances",
  balancesDesc: "One card per currency you have earned in.",
  balancesEmptyTitle: "No balance yet",
  balancesEmptyBody:
    "Your wallet fills up once store statements for your releases are imported and posted by 2kTunes finance.",
  available: "Available",
  availableHint: "Ready to withdraw now.",
  held: "In withdrawal",
  heldHint: "Reserved for withdrawals that are still being processed.",
  pending: "Pending",
  pendingHint: "Imported from stores but not yet posted to your wallet.",
  lifetime: "Lifetime earnings",
  lifetimeHint: "Everything ever credited to you.",
  withdrawn: "Withdrawn",
  withdrawnHint: "Paid out to you so far.",
  balanceIn: (cur: string) => `${cur} balance`,
  balancesExplainer: "What do these amounts mean?",

  /* Open withdrawals */
  openTitle: "Withdrawals in progress",
  openDesc: "These amounts are held until the payout completes, fails or is cancelled.",

  /* Tabs */
  tabsLabel: "Wallet activity",
  tabWithdrawals: "Withdrawals",
  tabLedger: "Statement",
  tabMethods: "Payout methods",

  /* Withdrawals list */
  withdrawalsCaption: "Withdrawal history",
  withdrawalsEmptyTitle: "No withdrawals yet",
  withdrawalsEmptyBody: "When you withdraw, each request and its progress will show up here.",
  colDate: "Date",
  colReference: "Reference",
  colAmount: "Amount",
  colFee: "Fee",
  colReceive: "You receive",
  colDestination: "Destination",
  colStatus: "Status",
  failure: (reason: string) => `Reason: ${reason}`,
  cancel: "Cancel withdrawal",
  cancelTitle: "Cancel this withdrawal?",
  cancelBody: (amount: string) => `${amount} will go back to your available balance.`,
  cancelConfirm: "Yes, cancel it",
  cancelKeep: "Keep it",
  cancelled: "Withdrawal cancelled",
  sandboxWithdrawal: "Test withdrawal — no money moved.",

  /* Ledger */
  ledgerCaption: "Wallet statement",
  ledgerDesc: "Every credit and debit on your wallet, newest first.",
  ledgerEmptyTitle: "No transactions yet",
  ledgerEmptyBody: "Royalty credits, withdrawals and adjustments will be listed here as they are posted.",
  currencyFilter: "Currency",
  allCurrencies: "All currencies",
  colType: "Type",
  colDescription: "Description",
  colAccount: "Account",
  colBalanceAfter: "Balance after",
  accountAvailable: "Available",
  accountHeld: "Held",
  ledgerTypes: {
    royalty_credit: "Royalty credit",
    creator_earning: "Creator earning",
    service_revenue: "Service revenue",
    legacy_import: "Imported balance",
    legacy_withdrawal_hold: "Earlier withdrawal",
    marketplace_payment: "Marketplace payment",
    marketplace_refund: "Marketplace refund",
    withdrawal_hold: "Withdrawal requested",
    withdrawal_released: "Withdrawal returned",
    withdrawal_settled: "Withdrawal paid out",
    adjustment_credit: "Adjustment (credit)",
    adjustment_debit: "Adjustment (debit)",
  } as Record<string, string>,

  /* Payout methods */
  methodsDesc: "Where your withdrawals are paid. Numbers are stored encrypted and only shown masked.",
  addMethod: "Add payout method",
  methodsEmptyTitle: "No payout method yet",
  methodsEmptyBody: "Add an M-Pesa, Airtel Money, Mixx by Yas or bank account to withdraw your earnings.",
  defaultBadge: "Default",
  removeMethod: (name: string) => `Remove payout method ${name}`,
  removeTitle: "Remove payout method?",
  removeBody: (name: string) => `${name} will no longer be available for withdrawals.`,
  removeConfirm: "Remove",
  removed: "Payout method removed",
  addedAt: (d: string) => `Added ${d}`,

  /* Add payout method */
  addTitle: "Add a payout method",
  addDesc: "Withdrawals will be paid to this account. Double-check the details — money sent to a wrong number can't be recalled.",
  provider: "Provider",
  providerPlaceholder: "Choose a provider",
  providersEmpty: "No payout providers are available right now. Please try again later or contact support.",
  fee: (x: string) => `Fee ${x}`,
  feeTitle: "Fee",
  feeValue: (fixed: string, pct: string) => `${fixed} + ${pct}`,
  limitsTitle: "Limits per withdrawal",
  limitsValue: (min: string, max: string) => `${min} – ${max}`,
  minOnly: (min: string) => `From ${min}`,
  dailyLimit: "Daily limit",
  monthlyLimit: "Monthly limit",
  processingTitle: "Processing",
  processingManual: "Processed by the 2kTunes finance team, usually within 1–2 business days.",
  processingAuto: "Processed automatically.",
  providerCurrency: "Paid in",
  fieldRequired: "This field is required.",
  accountName: "Account holder name",
  accountNameHint: "Exactly as registered with the provider.",
  phoneNumber: "Mobile money number",
  phoneHint: "E.g. 0754 123 456 or +255 754 123 456.",
  accountNumber: "Account number",
  bankName: "Bank name",
  bankBranch: "Branch",
  swift: "SWIFT / BIC code",
  label: "Nickname",
  labelHint: "Helps you tell accounts apart, e.g. “Main M-Pesa”.",
  makeDefault: "Use as my default payout method",
  passwordHint: "We ask for your password before saving where your money goes.",
  save: "Save payout method",
  added: "Payout method added",
  sandboxProvider: "Test provider — withdrawals through it move no real money.",

  /* Withdraw flow */
  wdTitle: "Withdraw funds",
  wdStepForm: "Details",
  wdStepReview: "Review",
  wdStepConfirm: "Confirm",
  wdSteps: "Withdrawal steps",
  wdCurrency: "From balance",
  wdMethod: "Pay to",
  wdMethodPlaceholder: "Choose a payout method",
  wdNoMethods: "Add a payout method before you can withdraw.",
  wdAddMethod: "Add a payout method",
  wdAmount: "Amount",
  wdAvailable: (x: string) => `Available: ${x}`,
  wdUseAll: "Withdraw everything",
  wdAmountInvalid: (cur: string) => `Enter an amount in ${cur}, e.g. 25000 or 25000.50.`,
  wdAmountZero: "Enter an amount greater than zero.",
  wdAmountTooHigh: (x: string) => `You can withdraw up to ${x}.`,
  wdChooseMethod: "Choose where to send the money.",
  wdReview: "Review withdrawal",
  wdQuoting: "Calculating fees…",
  wdYouWithdraw: "Taken from your wallet",
  wdFee: "Fee",
  wdNet: "After fee",
  wdYouReceive: "You receive",
  wdFx: "Exchange rate",
  wdFxValue: (from: string, rate: string, to: string) => `1 ${from} = ${rate} ${to}`,
  wdMin: "Minimum",
  wdMax: "Maximum",
  wdNoMax: "No maximum",
  wdDaily: "Daily limit",
  wdMonthly: "Monthly limit",
  wdBelowMin: (x: string) => `The minimum you can receive with this method is ${x}. Increase the amount.`,
  wdAboveMax: (x: string) => `The maximum per withdrawal with this method is ${x}. Lower the amount.`,
  wdContinue: "Continue",
  wdEdit: "Change details",
  wdConfirmLead: (amount: string, dest: string) => `You're withdrawing ${amount} to ${dest}.`,
  wdConfirmReceive: (amount: string) => `Expected to arrive: ${amount}.`,
  wdPasswordHint: "Your password confirms this withdrawal.",
  wdSubmit: "Withdraw",
  wdSubmitting: "Sending your request…",
  wdDoneTitle: "Withdrawal requested",
  wdDoneBody: (ref: string) => `Reference ${ref}. We'll notify you as it moves through approval and payout.`,
  wdSandbox: "This payout provider is in test mode. No real money will move.",
  wdRetryNote: "Nothing was charged twice — trying again resends the same request.",
  wdErrors: {
    insufficient_funds: "Your available balance is lower than this amount.",
    below_minimum: "This amount is below the minimum for this payout method.",
    above_maximum: "This amount is above the maximum for this payout method.",
    daily_limit: "This would go over today's limit for this payout method. Try a smaller amount or wait until tomorrow.",
    monthly_limit: "This would go over this month's limit for this payout method.",
    too_many_open: "You already have 3 withdrawals in progress. Wait for one to finish first.",
    fx_unavailable: "Withdrawals between these currencies are paused for now (no exchange rate). Try another method or later.",
    provider_unavailable: "This payout provider is temporarily unavailable. Try another method or later.",
    amount_below_fee: "The amount is too small to cover the transfer fee.",
    amount_invalid: "Enter an amount greater than zero.",
    account_suspended: "Withdrawals are disabled for this account. Contact support.",
    method_invalid: "Choose one of your own payout methods.",
  } as Record<string, string>,
};

const SW: typeof EN = {
  title: "Pochi",
  intro: "Mapato yako, utoaji wa pesa na njia zako za malipo. Kila kiasi kinatoka moja kwa moja kwenye leja ya 2kTunes.",
  withdraw: "Toa pesa",
  nothingToWithdraw: "Bado hakuna salio linaloweza kutolewa.",

  balancesTitle: "Salio",
  balancesDesc: "Kadi moja kwa kila sarafu uliyopatia mapato.",
  balancesEmptyTitle: "Bado huna salio",
  balancesEmptyBody:
    "Pochi yako itaanza kujaa baada ya ripoti za maduka kuhusu nyimbo zako kuingizwa na kuthibitishwa na idara ya fedha ya 2kTunes.",
  available: "Inayopatikana",
  availableHint: "Iko tayari kutolewa sasa.",
  held: "Inatolewa",
  heldHint: "Imezuiliwa kwa maombi ya kutoa pesa ambayo bado yanashughulikiwa.",
  pending: "Inasubiri",
  pendingHint: "Imeingizwa kutoka kwenye maduka lakini bado haijawekwa kwenye pochi yako.",
  lifetime: "Mapato yote",
  lifetimeHint: "Kila kitu ulichowahi kuwekewa.",
  withdrawn: "Uliyotoa",
  withdrawnHint: "Pesa ulizolipwa hadi sasa.",
  balanceIn: (cur: string) => `Salio la ${cur}`,
  balancesExplainer: "Kiasi hiki kina maana gani?",

  openTitle: "Maombi ya kutoa pesa yanayoendelea",
  openDesc: "Kiasi hiki kimezuiliwa hadi malipo yakamilike, yashindwe au yaghairiwe.",

  tabsLabel: "Shughuli za pochi",
  tabWithdrawals: "Utoaji wa pesa",
  tabLedger: "Taarifa",
  tabMethods: "Njia za malipo",

  withdrawalsCaption: "Historia ya kutoa pesa",
  withdrawalsEmptyTitle: "Bado hujatoa pesa",
  withdrawalsEmptyBody: "Ukitoa pesa, kila ombi na hatua yake litaonekana hapa.",
  colDate: "Tarehe",
  colReference: "Kumbukumbu",
  colAmount: "Kiasi",
  colFee: "Ada",
  colReceive: "Utapokea",
  colDestination: "Inakokwenda",
  colStatus: "Hali",
  failure: (reason: string) => `Sababu: ${reason}`,
  cancel: "Ghairi ombi",
  cancelTitle: "Ghairi ombi hili la kutoa pesa?",
  cancelBody: (amount: string) => `${amount} zitarudi kwenye salio lako linalopatikana.`,
  cancelConfirm: "Ndiyo, ghairi",
  cancelKeep: "Liache",
  cancelled: "Ombi la kutoa pesa limeghairiwa",
  sandboxWithdrawal: "Utoaji wa majaribio — hakuna pesa iliyohamishwa.",

  ledgerCaption: "Taarifa ya pochi",
  ledgerDesc: "Kila kiingizo na kitoleo kwenye pochi yako, vipya kwanza.",
  ledgerEmptyTitle: "Bado hakuna miamala",
  ledgerEmptyBody: "Mirabaha, utoaji wa pesa na marekebisho yataorodheshwa hapa yanapowekwa.",
  currencyFilter: "Sarafu",
  allCurrencies: "Sarafu zote",
  colType: "Aina",
  colDescription: "Maelezo",
  colAccount: "Akaunti",
  colBalanceAfter: "Salio baada",
  accountAvailable: "Inayopatikana",
  accountHeld: "Iliyozuiliwa",
  ledgerTypes: {
    royalty_credit: "Mirabaha",
    creator_earning: "Mapato ya mbunifu",
    service_revenue: "Mapato ya huduma",
    legacy_import: "Salio lililohamishwa",
    legacy_withdrawal_hold: "Utoaji wa awali",
    marketplace_payment: "Malipo ya soko",
    marketplace_refund: "Marejesho ya soko",
    withdrawal_hold: "Ombi la kutoa pesa",
    withdrawal_released: "Pesa zimerudishwa",
    withdrawal_settled: "Pesa zimelipwa",
    adjustment_credit: "Marekebisho (kuongeza)",
    adjustment_debit: "Marekebisho (kupunguza)",
  },

  methodsDesc: "Mahali pesa zako zinapolipwa. Namba zinahifadhiwa kwa usimbaji fiche na huonyeshwa zikiwa zimefichwa.",
  addMethod: "Ongeza njia ya malipo",
  methodsEmptyTitle: "Bado huna njia ya malipo",
  methodsEmptyBody: "Ongeza M-Pesa, Airtel Money, Mixx by Yas au akaunti ya benki ili kutoa mapato yako.",
  defaultBadge: "Chaguo-msingi",
  removeMethod: (name: string) => `Ondoa njia ya malipo ${name}`,
  removeTitle: "Ondoa njia ya malipo?",
  removeBody: (name: string) => `${name} haitatumika tena kutoa pesa.`,
  removeConfirm: "Ondoa",
  removed: "Njia ya malipo imeondolewa",
  addedAt: (d: string) => `Imeongezwa ${d}`,

  addTitle: "Ongeza njia ya malipo",
  addDesc: "Pesa unazotoa zitalipwa kwenye akaunti hii. Hakiki taarifa vizuri — pesa zilizotumwa kwa namba isiyo sahihi haziwezi kurudishwa.",
  provider: "Mtoa huduma",
  providerPlaceholder: "Chagua mtoa huduma",
  providersEmpty: "Hakuna watoa huduma wa malipo kwa sasa. Jaribu tena baadaye au wasiliana na huduma kwa wateja.",
  fee: (x: string) => `Ada ${x}`,
  feeTitle: "Ada",
  feeValue: (fixed: string, pct: string) => `${fixed} + ${pct}`,
  limitsTitle: "Kikomo kwa kila utoaji",
  limitsValue: (min: string, max: string) => `${min} – ${max}`,
  minOnly: (min: string) => `Kuanzia ${min}`,
  dailyLimit: "Kikomo cha siku",
  monthlyLimit: "Kikomo cha mwezi",
  processingTitle: "Uchakataji",
  processingManual: "Hushughulikiwa na idara ya fedha ya 2kTunes, kwa kawaida ndani ya siku 1–2 za kazi.",
  processingAuto: "Hushughulikiwa moja kwa moja.",
  providerCurrency: "Hulipwa kwa",
  fieldRequired: "Sehemu hii inahitajika.",
  accountName: "Jina la mmiliki wa akaunti",
  accountNameHint: "Kama lilivyosajiliwa kwa mtoa huduma.",
  phoneNumber: "Namba ya pesa kwa simu",
  phoneHint: "Mfano 0754 123 456 au +255 754 123 456.",
  accountNumber: "Namba ya akaunti",
  bankName: "Jina la benki",
  bankBranch: "Tawi",
  swift: "Msimbo wa SWIFT / BIC",
  label: "Jina la utambulisho",
  labelHint: "Hukusaidia kutofautisha akaunti, mfano “M-Pesa kuu”.",
  makeDefault: "Tumia kama njia yangu kuu ya malipo",
  passwordHint: "Tunaomba nenosiri lako kabla ya kuhifadhi mahali pesa zako zinapokwenda.",
  save: "Hifadhi njia ya malipo",
  added: "Njia ya malipo imeongezwa",
  sandboxProvider: "Mtoa huduma wa majaribio — utoaji kupitia huyu hauhamishi pesa halisi.",

  wdTitle: "Toa pesa",
  wdStepForm: "Taarifa",
  wdStepReview: "Hakiki",
  wdStepConfirm: "Thibitisha",
  wdSteps: "Hatua za kutoa pesa",
  wdCurrency: "Kutoka salio la",
  wdMethod: "Lipa kwenda",
  wdMethodPlaceholder: "Chagua njia ya malipo",
  wdNoMethods: "Ongeza njia ya malipo kabla ya kutoa pesa.",
  wdAddMethod: "Ongeza njia ya malipo",
  wdAmount: "Kiasi",
  wdAvailable: (x: string) => `Inayopatikana: ${x}`,
  wdUseAll: "Toa salio lote",
  wdAmountInvalid: (cur: string) => `Weka kiasi kwa ${cur}, mfano 25000 au 25000.50.`,
  wdAmountZero: "Weka kiasi kikubwa kuliko sifuri.",
  wdAmountTooHigh: (x: string) => `Unaweza kutoa hadi ${x}.`,
  wdChooseMethod: "Chagua mahali pa kutuma pesa.",
  wdReview: "Hakiki utoaji",
  wdQuoting: "Tunakokotoa ada…",
  wdYouWithdraw: "Inatolewa kwenye pochi yako",
  wdFee: "Ada",
  wdNet: "Baada ya ada",
  wdYouReceive: "Utapokea",
  wdFx: "Kiwango cha kubadilisha fedha",
  wdFxValue: (from: string, rate: string, to: string) => `1 ${from} = ${rate} ${to}`,
  wdMin: "Kiwango cha chini",
  wdMax: "Kiwango cha juu",
  wdNoMax: "Hakuna kikomo cha juu",
  wdDaily: "Kikomo cha siku",
  wdMonthly: "Kikomo cha mwezi",
  wdBelowMin: (x: string) => `Kiwango cha chini unachoweza kupokea kwa njia hii ni ${x}. Ongeza kiasi.`,
  wdAboveMax: (x: string) => `Kiwango cha juu kwa kila utoaji kwa njia hii ni ${x}. Punguza kiasi.`,
  wdContinue: "Endelea",
  wdEdit: "Badilisha taarifa",
  wdConfirmLead: (amount: string, dest: string) => `Unatoa ${amount} kwenda ${dest}.`,
  wdConfirmReceive: (amount: string) => `Kinachotarajiwa kufika: ${amount}.`,
  wdPasswordHint: "Nenosiri lako linathibitisha utoaji huu.",
  wdSubmit: "Toa pesa",
  wdSubmitting: "Tunatuma ombi lako…",
  wdDoneTitle: "Ombi la kutoa pesa limepokelewa",
  wdDoneBody: (ref: string) => `Kumbukumbu ${ref}. Tutakujulisha kadri linavyoidhinishwa na kulipwa.`,
  wdSandbox: "Mtoa huduma huyu yuko katika hali ya majaribio. Hakuna pesa halisi itakayohamishwa.",
  wdRetryNote: "Hakuna kilichotozwa mara mbili — ukijaribu tena, ombi lilelile linatumwa upya.",
  wdErrors: {
    insufficient_funds: "Salio lako linalopatikana ni dogo kuliko kiasi hiki.",
    below_minimum: "Kiasi hiki kiko chini ya kiwango cha chini cha njia hii ya malipo.",
    above_maximum: "Kiasi hiki kinazidi kiwango cha juu cha njia hii ya malipo.",
    daily_limit: "Hii itazidi kikomo cha leo kwa njia hii ya malipo. Jaribu kiasi kidogo au subiri hadi kesho.",
    monthly_limit: "Hii itazidi kikomo cha mwezi huu kwa njia hii ya malipo.",
    too_many_open: "Tayari una maombi 3 ya kutoa pesa yanayoendelea. Subiri moja likamilike kwanza.",
    fx_unavailable: "Utoaji kati ya sarafu hizi umesitishwa kwa sasa (hakuna kiwango cha kubadilisha). Jaribu njia nyingine au baadaye.",
    provider_unavailable: "Mtoa huduma huyu hapatikani kwa muda. Jaribu njia nyingine au baadaye.",
    amount_below_fee: "Kiasi ni kidogo mno kulipia ada ya kutuma.",
    amount_invalid: "Weka kiasi kikubwa kuliko sifuri.",
    account_suspended: "Utoaji wa pesa umezimwa kwa akaunti hii. Wasiliana na huduma kwa wateja.",
    method_invalid: "Chagua mojawapo ya njia zako za malipo.",
  },
};

export const COPY = { EN, SW };
export type WalletCopy = typeof EN;
