/** Wallet screen copy. Shared strings (actions, statuses, errors) come from `t()`. */

const EN = {
  title: "Wallet",
  intro: "Your earnings, withdrawals and payout methods. Every amount comes straight from the 2kTunes ledger.",
  withdraw: "Withdraw",
  nothingToWithdraw: "Nothing is available to withdraw yet.",

  /* Balances */
  balancesTitle: "Balances",
  balancesDesc: "One card per currency you have earned in.",
  balancesEmptyTitle: "No balance yet",
  balancesEmptyBody:
    "Your wallet fills up once store statements for your releases are imported and posted by 2kTunes finance.",
  available: "Available",
  availableHint: "Ready to withdraw now.",
  held: "In withdrawal",
  heldHint: "Reserved for withdrawals that are still being processed.",
  pending: "Pending",
  pendingHint: "Imported from stores but not yet posted to your wallet.",
  lifetime: "Lifetime earnings",
  lifetimeHint: "Everything ever credited to you.",
  withdrawn: "Withdrawn",
  withdrawnHint: "Paid out to you so far.",
  balanceIn: (cur: string) => `${cur} balance`,
  balancesExplainer: "What do these amounts mean?",

  /* Open withdrawals */
  openTitle: "Withdrawals in progress",
  openDesc: "These amounts are held until the payout completes, fails or is cancelled.",

  /* Tabs */
  tabsLabel: "Wallet activity",
  tabWithdrawals: "Withdrawals",
  tabLedger: "Statement",
  tabMethods: "Payout methods",

  /* Withdrawals list */
  withdrawalsCaption: "Withdrawal history",
  withdrawalsEmptyTitle: "No withdrawals yet",
  withdrawalsEmptyBody: "When you withdraw, each request and its progress will show up here.",
  colDate: "Date",
  colReference: "Reference",
  colAmount: "Amount",
  colFee: "Fee",
  colReceive: "You receive",
  colDestination: "Destination",
  colStatus: "Status",
  failure: (reason: string) => `Reason: ${reason}`,
  cancel: "Cancel withdrawal",
  cancelTitle: "Cancel this withdrawal?",
  cancelBody: (amount: string) => `${amount} will go back to your available balance.`,
  cancelConfirm: "Yes, cancel it",
  cancelKeep: "Keep it",
  cancelled: "Withdrawal cancelled",
  sandboxWithdrawal: "Test withdrawal — no money moved.",

  /* Ledger */
  ledgerCaption: "Wallet statement",
  ledgerDesc: "Every credit and debit on your wallet, newest first.",
  ledgerEmptyTitle: "No transactions yet",
  ledgerEmptyBody: "Royalty credits, withdrawals and adjustments will be listed here as they are posted.",
  currencyFilter: "Currency",
  allCurrencies: "All currencies",
  colType: "Type",
  colDescription: "Description",
  colAccount: "Account",
  colBalanceAfter: "Balance after",
  accountAvailable: "Available",
  accountHeld: "Held",
  ledgerTypes: {
    royalty_credit: "Royalty credit",
    creator_earning: "Creator earning",
    service_revenue: "Service revenue",
    marketplace_payment: "Marketplace payment",
    marketplace_refund: "Marketplace refund",
    withdrawal_hold: "Withdrawal requested",
    withdrawal_released: "Withdrawal returned",
    withdrawal_settled: "Withdrawal paid out",
    adjustment_credit: "Adjustment (credit)",
    adjustment_debit: "Adjustment (debit)",
  } as Record<string, string>,

  /* Payout methods */
  methodsDesc: "Where your withdrawals are paid. Numbers are stored encrypted and only shown masked.",
  addMethod: "Add payout method",
  methodsEmptyTitle: "No payout method yet",
  methodsEmptyBody: "Add mobile money, a bank account (local or international) or PayPal, Payoneer or Wise to withdraw your earnings.",
  defaultBadge: "Default",
  removeMethod: (name: string) => `Remove payout method ${name}`,
  removeTitle: "Remove payout method?",
  removeBody: (name: string) => `${name} will no longer be available for withdrawals.`,
  removeConfirm: "Remove",
  removed: "Payout method removed",
  addedAt: (d: string) => `Added ${d}`,

  /* Add payout method */
  addTitle: "Add a payout method",
  addDesc: "Withdrawals will be paid to this account. Double-check the details — money sent to a wrong number can't be recalled.",
  provider: "Provider",
  providerPlaceholder: "Choose a provider",
  providersEmpty: "No payout providers are available right now. Please try again later or contact support.",
  fee: (x: string) => `Fee ${x}`,
  feeTitle: "Fee",
  feeValue: (fixed: string, pct: string) => `${fixed} + ${pct}`,
  limitsTitle: "Limits per withdrawal",
  limitsValue: (min: string, max: string) => `${min} – ${max}`,
  minOnly: (min: string) => `From ${min}`,
  dailyLimit: "Daily limit",
  monthlyLimit: "Monthly limit",
  processingTitle: "Processing",
  processingManual: "Processed by the 2kTunes finance team, usually within 1–2 business days.",
  processingAuto: "Processed automatically.",
  providerCurrency: "Paid in",
  fieldRequired: "This field is required.",
  accountName: "Account holder name",
  accountNameHint: "Exactly as registered with the provider.",
  phoneNumber: "Mobile money number",
  phoneHint: "E.g. 0754 123 456 or +255 754 123 456.",
  accountNumber: "Account number",
  bankName: "Bank name",
  bankBranch: "Branch",
  swift: "SWIFT / BIC code",
  label: "Nickname",
  labelHint: "Helps you tell accounts apart, e.g. “Main M-Pesa”.",
  makeDefault: "Use as my default payout method",
  passwordHint: "We ask for your password before saving where your money goes.",
  save: "Save payout method",
  added: "Payout method added",
  sandboxProvider: "Test provider — withdrawals through it move no real money.",

  /* Add payout method — method types, steps and dynamic fields */
  addSteps: "Payout method steps",
  stepType: "Method",
  stepProvider: "Provider",
  stepDetails: "Details",
  chooseType: "How do you want to be paid?",
  chooseProvider: "Choose a provider",
  back: "Back",
  next: "Continue",
  types: {
    mobile_money: "Mobile money",
    bank: "Local bank (Tanzania)",
    bank_international: "International bank (SWIFT)",
    wallet: "PayPal / Payoneer / Wise",
  } as Record<string, string>,
  typeDescs: {
    mobile_money: "M-Pesa, Airtel Money or Mixx by Yas, straight to your phone.",
    bank: "A bank account in Tanzania, e.g. NMB, CRDB or NBC.",
    bank_international: "A bank account abroad, paid by SWIFT transfer in USD.",
    wallet: "Your PayPal, Payoneer or Wise account, paid in USD.",
  } as Record<string, string>,
  typeOther: "Other method",
  paidInList: (currencies: string) => `Paid in ${currencies}`,
  feeFrom: (fee: string) => `Fee from ${fee}`,
  noFee: "No fee",
  processingManualShort: "Processed by 2kTunes finance, usually 1–2 business days",
  processingAutoShort: "Processed automatically",
  noCards: "Card payouts aren’t available — we pay to mobile money, bank accounts and PayPal, Payoneer or Wise.",
  financeNote: "Withdrawals are processed by the 2kTunes finance team.",
  intlUsdNote: "International methods are paid in USD at the exchange rate shown before you confirm a withdrawal.",
  selectPlaceholder: "Choose…",
  bankOther: "Other bank",
  emailInvalid: "Enter a valid email address, e.g. name@example.com.",
  tooLong: (max: number) => `Use at most ${max} characters.`,
  fieldLabels: {
    account_name: "Account holder name",
    account_number: "Account number",
    phone_number: "Mobile money number",
    msisdn: "Mobile money number",
    bank_name: "Bank name",
    bank_name_other: "Other bank’s name",
    bank_branch: "Branch",
    bank_country: "Bank country",
    swift_code: "SWIFT / BIC code",
    routing_number: "Routing / sort code",
    bank_address: "Bank address",
    account_holder_address: "Account holder address",
    account_email: "Account email",
    email: "Email",
    iban: "IBAN",
  } as Record<string, string>,
  /** Overrides by method type (e.g. mobile money "account_number" is a phone). */
  fieldLabelsByType: {
    mobile_money: { account_number: "Mobile money number" },
    bank_international: { account_number: "IBAN or account number" },
    wallet: { account_email: "Account email" },
  } as Record<string, Record<string, string>>,
  fieldHints: {
    account_name: "Exactly as registered with the bank or provider.",
    swift_code: "8 or 11 characters, e.g. CORUTZTZ.",
    bank_name_other: "The full name of your bank.",
    routing_number: "Only if your bank uses one (ABA, sort code, IFSC…).",
    account_holder_address: "Your address as the bank has it.",
    account_email: "The email address of your PayPal, Payoneer or Wise account.",
  } as Record<string, string>,
  intlAccountHint: "Use your IBAN if your bank has one; otherwise your account number.",

  /* Withdraw flow */
  wdTitle: "Withdraw funds",
  wdStepForm: "Details",
  wdStepReview: "Review",
  wdStepConfirm: "Confirm",
  wdSteps: "Withdrawal steps",
  wdCurrency: "From balance",
  wdMethod: "Pay to",
  wdMethodPlaceholder: "Choose a payout method",
  wdNoMethods: "Add a payout method before you can withdraw.",
  wdAddMethod: "Add a payout method",
  wdAmount: "Amount",
  wdAvailable: (x: string) => `Available: ${x}`,
  wdUseAll: "Withdraw everything",
  wdAmountInvalid: (cur: string) => `Enter an amount in ${cur}, e.g. 25000 or 25000.50.`,
  wdAmountZero: "Enter an amount greater than zero.",
  wdAmountTooHigh: (x: string) => `You can withdraw up to ${x}.`,
  wdChooseMethod: "Choose where to send the money.",
  wdReview: "Review withdrawal",
  wdQuoting: "Calculating fees…",
  wdYouWithdraw: "Taken from your wallet",
  wdFee: "Fee",
  wdNet: "After fee",
  wdYouReceive: "You receive",
  wdFx: "Exchange rate",
  wdFxValue: (from: string, rate: string, to: string) => `1 ${from} = ${rate} ${to}`,
  wdMin: "Minimum",
  wdMax: "Maximum",
  wdNoMax: "No maximum",
  wdDaily: "Daily limit",
  wdMonthly: "Monthly limit",
  wdBelowMin: (x: string) => `The minimum you can receive with this method is ${x}. Increase the amount.`,
  wdAboveMax: (x: string) => `The maximum per withdrawal with this method is ${x}. Lower the amount.`,
  wdContinue: "Continue",
  wdEdit: "Change details",
  wdConfirmLead: (amount: string, dest: string) => `You're withdrawing ${amount} to ${dest}.`,
  wdConfirmReceive: (amount: string) => `Expected to arrive: ${amount}.`,
  wdPasswordHint: "Your password confirms this withdrawal.",
  wdSubmit: "Withdraw",
  wdSubmitting: "Sending your request…",
  wdDoneTitle: "Withdrawal requested",
  wdDoneBody: (ref: string) => `Reference ${ref}. We'll notify you as it moves through approval and payout.`,
  wdSandbox: "This payout provider is in test mode. No real money will move.",
  wdRetryNote: "Nothing was charged twice — trying again resends the same request.",
  wdErrors: {
    insufficient_funds: "Your available balance is lower than this amount.",
    below_minimum: "This amount is below the minimum for this payout method.",
    above_maximum: "This amount is above the maximum for this payout method.",
    daily_limit: "This would go over today's limit for this payout method. Try a smaller amount or wait until tomorrow.",
    monthly_limit: "This would go over this month's limit for this payout method.",
    too_many_open: "You already have 3 withdrawals in progress. Wait for one to finish first.",
    fx_unavailable: "Withdrawals between these currencies are paused for now (no exchange rate). Try another method or later.",
    provider_unavailable: "This payout provider is temporarily unavailable. Try another method or later.",
    amount_below_fee: "The amount is too small to cover the transfer fee.",
    amount_invalid: "Enter an amount greater than zero.",
    account_suspended: "Withdrawals are disabled for this account. Contact support.",
    method_invalid: "Choose one of your own payout methods.",
  } as Record<string, string>,
};

const SW: typeof EN = {
  title: "Pochi",
  intro: "Mapato yako, utoaji wa pesa na njia zako za malipo. Kila kiasi kinatoka moja kwa moja kwenye leja ya 2kTunes.",
  withdraw: "Toa pesa",
  nothingToWithdraw: "Bado hakuna salio linaloweza kutolewa.",

  balancesTitle: "Salio",
  balancesDesc: "Kadi moja kwa kila sarafu uliyopatia mapato.",
  balancesEmptyTitle: "Bado huna salio",
  balancesEmptyBody:
    "Pochi yako itaanza kujaa baada ya ripoti za maduka kuhusu nyimbo zako kuingizwa na kuthibitishwa na idara ya fedha ya 2kTunes.",
  available: "Inayopatikana",
  availableHint: "Iko tayari kutolewa sasa.",
  held: "Inatolewa",
  heldHint: "Imezuiliwa kwa maombi ya kutoa pesa ambayo bado yanashughulikiwa.",
  pending: "Inasubiri",
  pendingHint: "Imeingizwa kutoka kwenye maduka lakini bado haijawekwa kwenye pochi yako.",
  lifetime: "Mapato yote",
  lifetimeHint: "Kila kitu ulichowahi kuwekewa.",
  withdrawn: "Uliyotoa",
  withdrawnHint: "Pesa ulizolipwa hadi sasa.",
  balanceIn: (cur: string) => `Salio la ${cur}`,
  balancesExplainer: "Kiasi hiki kina maana gani?",

  openTitle: "Maombi ya kutoa pesa yanayoendelea",
  openDesc: "Kiasi hiki kimezuiliwa hadi malipo yakamilike, yashindwe au yaghairiwe.",

  tabsLabel: "Shughuli za pochi",
  tabWithdrawals: "Utoaji wa pesa",
  tabLedger: "Taarifa",
  tabMethods: "Njia za malipo",

  withdrawalsCaption: "Historia ya kutoa pesa",
  withdrawalsEmptyTitle: "Bado hujatoa pesa",
  withdrawalsEmptyBody: "Ukitoa pesa, kila ombi na hatua yake litaonekana hapa.",
  colDate: "Tarehe",
  colReference: "Kumbukumbu",
  colAmount: "Kiasi",
  colFee: "Ada",
  colReceive: "Utapokea",
  colDestination: "Inakokwenda",
  colStatus: "Hali",
  failure: (reason: string) => `Sababu: ${reason}`,
  cancel: "Ghairi ombi",
  cancelTitle: "Ghairi ombi hili la kutoa pesa?",
  cancelBody: (amount: string) => `${amount} zitarudi kwenye salio lako linalopatikana.`,
  cancelConfirm: "Ndiyo, ghairi",
  cancelKeep: "Liache",
  cancelled: "Ombi la kutoa pesa limeghairiwa",
  sandboxWithdrawal: "Utoaji wa majaribio — hakuna pesa iliyohamishwa.",

  ledgerCaption: "Taarifa ya pochi",
  ledgerDesc: "Kila kiingizo na kitoleo kwenye pochi yako, vipya kwanza.",
  ledgerEmptyTitle: "Bado hakuna miamala",
  ledgerEmptyBody: "Mirabaha, utoaji wa pesa na marekebisho yataorodheshwa hapa yanapowekwa.",
  currencyFilter: "Sarafu",
  allCurrencies: "Sarafu zote",
  colType: "Aina",
  colDescription: "Maelezo",
  colAccount: "Akaunti",
  colBalanceAfter: "Salio baada",
  accountAvailable: "Inayopatikana",
  accountHeld: "Iliyozuiliwa",
  ledgerTypes: {
    royalty_credit: "Mirabaha",
    creator_earning: "Mapato ya mbunifu",
    service_revenue: "Mapato ya huduma",
    marketplace_payment: "Malipo ya soko",
    marketplace_refund: "Marejesho ya soko",
    withdrawal_hold: "Ombi la kutoa pesa",
    withdrawal_released: "Pesa zimerudishwa",
    withdrawal_settled: "Pesa zimelipwa",
    adjustment_credit: "Marekebisho (kuongeza)",
    adjustment_debit: "Marekebisho (kupunguza)",
  },

  methodsDesc: "Mahali pesa zako zinapolipwa. Namba zinahifadhiwa kwa usimbaji fiche na huonyeshwa zikiwa zimefichwa.",
  addMethod: "Ongeza njia ya malipo",
  methodsEmptyTitle: "Bado huna njia ya malipo",
  methodsEmptyBody: "Ongeza pesa kwa simu, akaunti ya benki (ya ndani au ya kimataifa) au PayPal, Payoneer au Wise ili kutoa mapato yako.",
  defaultBadge: "Chaguo-msingi",
  removeMethod: (name: string) => `Ondoa njia ya malipo ${name}`,
  removeTitle: "Ondoa njia ya malipo?",
  removeBody: (name: string) => `${name} haitatumika tena kutoa pesa.`,
  removeConfirm: "Ondoa",
  removed: "Njia ya malipo imeondolewa",
  addedAt: (d: string) => `Imeongezwa ${d}`,

  addTitle: "Ongeza njia ya malipo",
  addDesc: "Pesa unazotoa zitalipwa kwenye akaunti hii. Hakiki taarifa vizuri — pesa zilizotumwa kwa namba isiyo sahihi haziwezi kurudishwa.",
  provider: "Mtoa huduma",
  providerPlaceholder: "Chagua mtoa huduma",
  providersEmpty: "Hakuna watoa huduma wa malipo kwa sasa. Jaribu tena baadaye au wasiliana na huduma kwa wateja.",
  fee: (x: string) => `Ada ${x}`,
  feeTitle: "Ada",
  feeValue: (fixed: string, pct: string) => `${fixed} + ${pct}`,
  limitsTitle: "Kikomo kwa kila utoaji",
  limitsValue: (min: string, max: string) => `${min} – ${max}`,
  minOnly: (min: string) => `Kuanzia ${min}`,
  dailyLimit: "Kikomo cha siku",
  monthlyLimit: "Kikomo cha mwezi",
  processingTitle: "Uchakataji",
  processingManual: "Hushughulikiwa na idara ya fedha ya 2kTunes, kwa kawaida ndani ya siku 1–2 za kazi.",
  processingAuto: "Hushughulikiwa moja kwa moja.",
  providerCurrency: "Hulipwa kwa",
  fieldRequired: "Sehemu hii inahitajika.",
  accountName: "Jina la mmiliki wa akaunti",
  accountNameHint: "Kama lilivyosajiliwa kwa mtoa huduma.",
  phoneNumber: "Namba ya pesa kwa simu",
  phoneHint: "Mfano 0754 123 456 au +255 754 123 456.",
  accountNumber: "Namba ya akaunti",
  bankName: "Jina la benki",
  bankBranch: "Tawi",
  swift: "Msimbo wa SWIFT / BIC",
  label: "Jina la utambulisho",
  labelHint: "Hukusaidia kutofautisha akaunti, mfano “M-Pesa kuu”.",
  makeDefault: "Tumia kama njia yangu kuu ya malipo",
  passwordHint: "Tunaomba nenosiri lako kabla ya kuhifadhi mahali pesa zako zinapokwenda.",
  save: "Hifadhi njia ya malipo",
  added: "Njia ya malipo imeongezwa",
  sandboxProvider: "Mtoa huduma wa majaribio — utoaji kupitia huyu hauhamishi pesa halisi.",

  addSteps: "Hatua za njia ya malipo",
  stepType: "Njia",
  stepProvider: "Mtoa huduma",
  stepDetails: "Taarifa",
  chooseType: "Ungependa kulipwa vipi?",
  chooseProvider: "Chagua mtoa huduma",
  back: "Rudi",
  next: "Endelea",
  types: {
    mobile_money: "Pesa kwa simu",
    bank: "Benki ya ndani (Tanzania)",
    bank_international: "Benki ya kimataifa (SWIFT)",
    wallet: "PayPal / Payoneer / Wise",
  },
  typeDescs: {
    mobile_money: "M-Pesa, Airtel Money au Mixx by Yas, moja kwa moja kwenye simu yako.",
    bank: "Akaunti ya benki nchini Tanzania, mfano NMB, CRDB au NBC.",
    bank_international: "Akaunti ya benki nje ya nchi, hulipwa kwa uhamisho wa SWIFT kwa USD.",
    wallet: "Akaunti yako ya PayPal, Payoneer au Wise, hulipwa kwa USD.",
  },
  typeOther: "Njia nyingine",
  paidInList: (currencies: string) => `Hulipwa kwa ${currencies}`,
  feeFrom: (fee: string) => `Ada kuanzia ${fee}`,
  noFee: "Hakuna ada",
  processingManualShort: "Hushughulikiwa na idara ya fedha ya 2kTunes, kwa kawaida siku 1–2 za kazi",
  processingAutoShort: "Hushughulikiwa moja kwa moja",
  noCards: "Hatulipi kwenye kadi — tunalipa kwa pesa kwa simu, akaunti za benki na PayPal, Payoneer au Wise.",
  financeNote: "Maombi ya kutoa pesa hushughulikiwa na idara ya fedha ya 2kTunes.",
  intlUsdNote: "Njia za kimataifa hulipwa kwa USD kwa kiwango cha kubadilisha fedha kinachoonyeshwa kabla hujathibitisha utoaji.",
  selectPlaceholder: "Chagua…",
  bankOther: "Benki nyingine",
  emailInvalid: "Weka barua pepe sahihi, mfano jina@mfano.com.",
  tooLong: (max: number) => `Tumia herufi zisizozidi ${max}.`,
  fieldLabels: {
    account_name: "Jina la mmiliki wa akaunti",
    account_number: "Namba ya akaunti",
    phone_number: "Namba ya pesa kwa simu",
    msisdn: "Namba ya pesa kwa simu",
    bank_name: "Jina la benki",
    bank_name_other: "Jina la benki nyingine",
    bank_branch: "Tawi",
    bank_country: "Nchi ya benki",
    swift_code: "Msimbo wa SWIFT / BIC",
    routing_number: "Namba ya routing / sort code",
    bank_address: "Anwani ya benki",
    account_holder_address: "Anwani ya mmiliki wa akaunti",
    account_email: "Barua pepe ya akaunti",
    email: "Barua pepe",
    iban: "IBAN",
  },
  fieldLabelsByType: {
    mobile_money: { account_number: "Namba ya pesa kwa simu" },
    bank_international: { account_number: "IBAN au namba ya akaunti" },
    wallet: { account_email: "Barua pepe ya akaunti" },
  },
  fieldHints: {
    account_name: "Kama lilivyosajiliwa kwenye benki au kwa mtoa huduma.",
    swift_code: "Herufi 8 au 11, mfano CORUTZTZ.",
    bank_name_other: "Jina kamili la benki yako.",
    routing_number: "Ikiwa tu benki yako inatumia (ABA, sort code, IFSC…).",
    account_holder_address: "Anwani yako kama ilivyo kwenye benki.",
    account_email: "Barua pepe ya akaunti yako ya PayPal, Payoneer au Wise.",
  },
  intlAccountHint: "Tumia IBAN kama benki yako inayo; vinginevyo namba ya akaunti.",

  wdTitle: "Toa pesa",
  wdStepForm: "Taarifa",
  wdStepReview: "Hakiki",
  wdStepConfirm: "Thibitisha",
  wdSteps: "Hatua za kutoa pesa",
  wdCurrency: "Kutoka salio la",
  wdMethod: "Lipa kwenda",
  wdMethodPlaceholder: "Chagua njia ya malipo",
  wdNoMethods: "Ongeza njia ya malipo kabla ya kutoa pesa.",
  wdAddMethod: "Ongeza njia ya malipo",
  wdAmount: "Kiasi",
  wdAvailable: (x: string) => `Inayopatikana: ${x}`,
  wdUseAll: "Toa salio lote",
  wdAmountInvalid: (cur: string) => `Weka kiasi kwa ${cur}, mfano 25000 au 25000.50.`,
  wdAmountZero: "Weka kiasi kikubwa kuliko sifuri.",
  wdAmountTooHigh: (x: string) => `Unaweza kutoa hadi ${x}.`,
  wdChooseMethod: "Chagua mahali pa kutuma pesa.",
  wdReview: "Hakiki utoaji",
  wdQuoting: "Tunakokotoa ada…",
  wdYouWithdraw: "Inatolewa kwenye pochi yako",
  wdFee: "Ada",
  wdNet: "Baada ya ada",
  wdYouReceive: "Utapokea",
  wdFx: "Kiwango cha kubadilisha fedha",
  wdFxValue: (from: string, rate: string, to: string) => `1 ${from} = ${rate} ${to}`,
  wdMin: "Kiwango cha chini",
  wdMax: "Kiwango cha juu",
  wdNoMax: "Hakuna kikomo cha juu",
  wdDaily: "Kikomo cha siku",
  wdMonthly: "Kikomo cha mwezi",
  wdBelowMin: (x: string) => `Kiwango cha chini unachoweza kupokea kwa njia hii ni ${x}. Ongeza kiasi.`,
  wdAboveMax: (x: string) => `Kiwango cha juu kwa kila utoaji kwa njia hii ni ${x}. Punguza kiasi.`,
  wdContinue: "Endelea",
  wdEdit: "Badilisha taarifa",
  wdConfirmLead: (amount: string, dest: string) => `Unatoa ${amount} kwenda ${dest}.`,
  wdConfirmReceive: (amount: string) => `Kinachotarajiwa kufika: ${amount}.`,
  wdPasswordHint: "Nenosiri lako linathibitisha utoaji huu.",
  wdSubmit: "Toa pesa",
  wdSubmitting: "Tunatuma ombi lako…",
  wdDoneTitle: "Ombi la kutoa pesa limepokelewa",
  wdDoneBody: (ref: string) => `Kumbukumbu ${ref}. Tutakujulisha kadri linavyoidhinishwa na kulipwa.`,
  wdSandbox: "Mtoa huduma huyu yuko katika hali ya majaribio. Hakuna pesa halisi itakayohamishwa.",
  wdRetryNote: "Hakuna kilichotozwa mara mbili — ukijaribu tena, ombi lilelile linatumwa upya.",
  wdErrors: {
    insufficient_funds: "Salio lako linalopatikana ni dogo kuliko kiasi hiki.",
    below_minimum: "Kiasi hiki kiko chini ya kiwango cha chini cha njia hii ya malipo.",
    above_maximum: "Kiasi hiki kinazidi kiwango cha juu cha njia hii ya malipo.",
    daily_limit: "Hii itazidi kikomo cha leo kwa njia hii ya malipo. Jaribu kiasi kidogo au subiri hadi kesho.",
    monthly_limit: "Hii itazidi kikomo cha mwezi huu kwa njia hii ya malipo.",
    too_many_open: "Tayari una maombi 3 ya kutoa pesa yanayoendelea. Subiri moja likamilike kwanza.",
    fx_unavailable: "Utoaji kati ya sarafu hizi umesitishwa kwa sasa (hakuna kiwango cha kubadilisha). Jaribu njia nyingine au baadaye.",
    provider_unavailable: "Mtoa huduma huyu hapatikani kwa muda. Jaribu njia nyingine au baadaye.",
    amount_below_fee: "Kiasi ni kidogo mno kulipia ada ya kutuma.",
    amount_invalid: "Weka kiasi kikubwa kuliko sifuri.",
    account_suspended: "Utoaji wa pesa umezimwa kwa akaunti hii. Wasiliana na huduma kwa wateja.",
    method_invalid: "Chagua mojawapo ya njia zako za malipo.",
  },
};

const FR: typeof EN = {
  title: "Portefeuille",
  intro: "Vos revenus, vos retraits et vos moyens de paiement. Chaque montant provient directement du registre comptable de 2kTunes.",
  withdraw: "Retirer",
  nothingToWithdraw: "Aucun montant n’est encore disponible au retrait.",

  balancesTitle: "Soldes",
  balancesDesc: "Une carte par devise dans laquelle vous avez perçu des revenus.",
  balancesEmptyTitle: "Pas encore de solde",
  balancesEmptyBody:
    "Votre portefeuille sera alimenté dès que les relevés des plateformes pour vos sorties auront été importés et validés par l’équipe financière de 2kTunes.",
  available: "Disponible",
  availableHint: "Prêt à être retiré dès maintenant.",
  held: "En cours de retrait",
  heldHint: "Réservé pour des retraits encore en cours de traitement.",
  pending: "En attente",
  pendingHint: "Importé depuis les plateformes, mais pas encore crédité sur votre portefeuille.",
  lifetime: "Revenus cumulés",
  lifetimeHint: "Tout ce qui vous a été crédité depuis le début.",
  withdrawn: "Retiré",
  withdrawnHint: "Montant qui vous a été versé jusqu’à présent.",
  balanceIn: (cur: string) => `Solde en ${cur}`,
  balancesExplainer: "Que signifient ces montants ?",

  openTitle: "Retraits en cours",
  openDesc: "Ces montants sont bloqués jusqu’à ce que le versement aboutisse, échoue ou soit annulé.",

  tabsLabel: "Activité du portefeuille",
  tabWithdrawals: "Retraits",
  tabLedger: "Relevé",
  tabMethods: "Moyens de paiement",

  withdrawalsCaption: "Historique des retraits",
  withdrawalsEmptyTitle: "Aucun retrait pour l’instant",
  withdrawalsEmptyBody: "Lorsque vous effectuerez un retrait, chaque demande et son avancement s’afficheront ici.",
  colDate: "Date",
  colReference: "Référence",
  colAmount: "Montant",
  colFee: "Frais",
  colReceive: "Vous recevez",
  colDestination: "Destination",
  colStatus: "Statut",
  failure: (reason: string) => `Motif : ${reason}`,
  cancel: "Annuler le retrait",
  cancelTitle: "Annuler ce retrait ?",
  cancelBody: (amount: string) => `${amount} sera reversé sur votre solde disponible.`,
  cancelConfirm: "Oui, annuler",
  cancelKeep: "Le conserver",
  cancelled: "Retrait annulé",
  sandboxWithdrawal: "Retrait de test — aucun argent n’a été transféré.",

  ledgerCaption: "Relevé du portefeuille",
  ledgerDesc: "Tous les crédits et débits de votre portefeuille, du plus récent au plus ancien.",
  ledgerEmptyTitle: "Aucune transaction pour l’instant",
  ledgerEmptyBody: "Les crédits de royalties, les retraits et les ajustements apparaîtront ici dès leur enregistrement.",
  currencyFilter: "Devise",
  allCurrencies: "Toutes les devises",
  colType: "Type",
  colDescription: "Description",
  colAccount: "Compte",
  colBalanceAfter: "Solde après",
  accountAvailable: "Disponible",
  accountHeld: "Bloqué",
  ledgerTypes: {
    royalty_credit: "Crédit de royalties",
    creator_earning: "Revenu de créateur",
    service_revenue: "Revenu de service",
    marketplace_payment: "Paiement marketplace",
    marketplace_refund: "Remboursement marketplace",
    withdrawal_hold: "Retrait demandé",
    withdrawal_released: "Retrait restitué",
    withdrawal_settled: "Retrait versé",
    adjustment_credit: "Ajustement (crédit)",
    adjustment_debit: "Ajustement (débit)",
  },

  methodsDesc: "Là où vos retraits sont versés. Les numéros sont chiffrés et ne sont affichés que masqués.",
  addMethod: "Ajouter un moyen de paiement",
  methodsEmptyTitle: "Aucun moyen de paiement",
  methodsEmptyBody: "Ajoutez un compte Mobile money, un compte bancaire (local ou international) ou PayPal, Payoneer ou Wise pour retirer vos revenus.",
  defaultBadge: "Par défaut",
  removeMethod: (name: string) => `Supprimer le moyen de paiement ${name}`,
  removeTitle: "Supprimer ce moyen de paiement ?",
  removeBody: (name: string) => `${name} ne sera plus disponible pour les retraits.`,
  removeConfirm: "Supprimer",
  removed: "Moyen de paiement supprimé",
  addedAt: (d: string) => `Ajouté le ${d}`,

  addTitle: "Ajouter un moyen de paiement",
  addDesc: "Vos retraits seront versés sur ce compte. Vérifiez bien les informations — l’argent envoyé à un mauvais numéro ne peut pas être récupéré.",
  provider: "Prestataire",
  providerPlaceholder: "Choisissez un prestataire",
  providersEmpty: "Aucun prestataire de paiement n’est disponible pour le moment. Réessayez plus tard ou contactez le support.",
  fee: (x: string) => `Frais ${x}`,
  feeTitle: "Frais",
  feeValue: (fixed: string, pct: string) => `${fixed} + ${pct}`,
  limitsTitle: "Limites par retrait",
  limitsValue: (min: string, max: string) => `${min} – ${max}`,
  minOnly: (min: string) => `À partir de ${min}`,
  dailyLimit: "Plafond journalier",
  monthlyLimit: "Plafond mensuel",
  processingTitle: "Traitement",
  processingManual: "Traité par l’équipe financière de 2kTunes, généralement sous 1 à 2 jours ouvrés.",
  processingAuto: "Traité automatiquement.",
  providerCurrency: "Versé en",
  fieldRequired: "Ce champ est obligatoire.",
  accountName: "Nom du titulaire du compte",
  accountNameHint: "Exactement tel qu’enregistré auprès du prestataire.",
  phoneNumber: "Numéro Mobile money",
  phoneHint: "Ex. 0754 123 456 ou +255 754 123 456.",
  accountNumber: "Numéro de compte",
  bankName: "Nom de la banque",
  bankBranch: "Agence",
  swift: "Code SWIFT / BIC",
  label: "Surnom",
  labelHint: "Pour distinguer vos comptes, ex. « M-Pesa principal ».",
  makeDefault: "Utiliser comme moyen de paiement par défaut",
  passwordHint: "Nous vous demandons votre mot de passe avant d’enregistrer la destination de votre argent.",
  save: "Enregistrer",
  added: "Moyen de paiement ajouté",
  sandboxProvider: "Prestataire de test — les retraits effectués par ce biais ne transfèrent pas d’argent réel.",

  addSteps: "Étapes du moyen de paiement",
  stepType: "Méthode",
  stepProvider: "Prestataire",
  stepDetails: "Détails",
  chooseType: "Comment souhaitez-vous être payé ?",
  chooseProvider: "Choisissez un prestataire",
  back: "Retour",
  next: "Continuer",
  types: {
    mobile_money: "Mobile money",
    bank: "Banque locale (Tanzanie)",
    bank_international: "Banque internationale (SWIFT)",
    wallet: "PayPal / Payoneer / Wise",
  },
  typeDescs: {
    mobile_money: "M-Pesa, Airtel Money ou Mixx by Yas, directement sur votre téléphone.",
    bank: "Un compte bancaire en Tanzanie, ex. NMB, CRDB ou NBC.",
    bank_international: "Un compte bancaire à l’étranger, payé par virement SWIFT en USD.",
    wallet: "Votre compte PayPal, Payoneer ou Wise, payé en USD.",
  },
  typeOther: "Autre méthode",
  paidInList: (currencies: string) => `Versé en ${currencies}`,
  feeFrom: (fee: string) => `Frais à partir de ${fee}`,
  noFee: "Sans frais",
  processingManualShort: "Traité par l’équipe financière de 2kTunes, généralement 1 à 2 jours ouvrés",
  processingAutoShort: "Traité automatiquement",
  noCards: "Les versements sur carte ne sont pas disponibles — nous payons sur Mobile money, comptes bancaires et PayPal, Payoneer ou Wise.",
  financeNote: "Les retraits sont traités par l’équipe financière de 2kTunes.",
  intlUsdNote: "Les méthodes internationales sont payées en USD, au taux de change affiché avant la confirmation du retrait.",
  selectPlaceholder: "Choisir…",
  bankOther: "Autre banque",
  emailInvalid: "Saisissez une adresse e-mail valide, ex. nom@exemple.com.",
  tooLong: (max: number) => `Utilisez au maximum ${max} ${max > 1 ? "caractères" : "caractère"}.`,
  fieldLabels: {
    account_name: "Nom du titulaire du compte",
    account_number: "Numéro de compte",
    phone_number: "Numéro Mobile money",
    msisdn: "Numéro Mobile money",
    bank_name: "Nom de la banque",
    bank_name_other: "Nom de l’autre banque",
    bank_branch: "Agence",
    bank_country: "Pays de la banque",
    swift_code: "Code SWIFT / BIC",
    routing_number: "Code de routage / sort code",
    bank_address: "Adresse de la banque",
    account_holder_address: "Adresse du titulaire du compte",
    account_email: "E-mail du compte",
    email: "E-mail",
    iban: "IBAN",
  },
  fieldLabelsByType: {
    mobile_money: { account_number: "Numéro Mobile money" },
    bank_international: { account_number: "IBAN ou numéro de compte" },
    wallet: { account_email: "E-mail du compte" },
  },
  fieldHints: {
    account_name: "Exactement tel qu’enregistré auprès de la banque ou du prestataire.",
    swift_code: "8 ou 11 caractères, ex. CORUTZTZ.",
    bank_name_other: "Le nom complet de votre banque.",
    routing_number: "Uniquement si votre banque en utilise un (ABA, sort code, IFSC…).",
    account_holder_address: "Votre adresse telle qu’elle figure auprès de la banque.",
    account_email: "L’adresse e-mail de votre compte PayPal, Payoneer ou Wise.",
  },
  intlAccountHint: "Utilisez votre IBAN si votre banque en a un ; sinon, votre numéro de compte.",

  wdTitle: "Retirer des fonds",
  wdStepForm: "Détails",
  wdStepReview: "Vérification",
  wdStepConfirm: "Confirmation",
  wdSteps: "Étapes du retrait",
  wdCurrency: "Depuis le solde",
  wdMethod: "Verser sur",
  wdMethodPlaceholder: "Choisissez un moyen de paiement",
  wdNoMethods: "Ajoutez un moyen de paiement avant de pouvoir effectuer un retrait.",
  wdAddMethod: "Ajouter un moyen de paiement",
  wdAmount: "Montant",
  wdAvailable: (x: string) => `Disponible : ${x}`,
  wdUseAll: "Tout retirer",
  wdAmountInvalid: (cur: string) => `Saisissez un montant en ${cur}, ex. 25000 ou 25000.50.`,
  wdAmountZero: "Saisissez un montant supérieur à zéro.",
  wdAmountTooHigh: (x: string) => `Vous pouvez retirer jusqu’à ${x}.`,
  wdChooseMethod: "Choisissez où envoyer l’argent.",
  wdReview: "Vérifier le retrait",
  wdQuoting: "Calcul des frais…",
  wdYouWithdraw: "Débité de votre portefeuille",
  wdFee: "Frais",
  wdNet: "Après frais",
  wdYouReceive: "Vous recevez",
  wdFx: "Taux de change",
  wdFxValue: (from: string, rate: string, to: string) => `1 ${from} = ${rate} ${to}`,
  wdMin: "Minimum",
  wdMax: "Maximum",
  wdNoMax: "Pas de maximum",
  wdDaily: "Plafond journalier",
  wdMonthly: "Plafond mensuel",
  wdBelowMin: (x: string) => `Le montant minimum que vous pouvez recevoir avec cette méthode est de ${x}. Augmentez le montant.`,
  wdAboveMax: (x: string) => `Le maximum par retrait avec cette méthode est de ${x}. Réduisez le montant.`,
  wdContinue: "Continuer",
  wdEdit: "Modifier",
  wdConfirmLead: (amount: string, dest: string) => `Vous retirez ${amount} vers ${dest}.`,
  wdConfirmReceive: (amount: string) => `Montant attendu à l’arrivée : ${amount}.`,
  wdPasswordHint: "Votre mot de passe confirme ce retrait.",
  wdSubmit: "Retirer",
  wdSubmitting: "Envoi de votre demande…",
  wdDoneTitle: "Retrait demandé",
  wdDoneBody: (ref: string) => `Référence ${ref}. Nous vous informerons à chaque étape, de l’approbation jusqu’au versement.`,
  wdSandbox: "Ce prestataire de paiement est en mode test. Aucun argent réel ne sera transféré.",
  wdRetryNote: "Rien n’a été débité deux fois — réessayer renvoie la même demande.",
  wdErrors: {
    insufficient_funds: "Votre solde disponible est inférieur à ce montant.",
    below_minimum: "Ce montant est inférieur au minimum de ce moyen de paiement.",
    above_maximum: "Ce montant dépasse le maximum de ce moyen de paiement.",
    daily_limit: "Ce retrait dépasserait le plafond du jour pour ce moyen de paiement. Essayez un montant plus faible ou attendez demain.",
    monthly_limit: "Ce retrait dépasserait le plafond du mois pour ce moyen de paiement.",
    too_many_open: "Vous avez déjà 3 retraits en cours. Attendez que l’un d’eux soit terminé.",
    fx_unavailable: "Les retraits entre ces devises sont suspendus pour le moment (aucun taux de change). Essayez une autre méthode ou réessayez plus tard.",
    provider_unavailable: "Ce prestataire de paiement est temporairement indisponible. Essayez une autre méthode ou réessayez plus tard.",
    amount_below_fee: "Le montant est trop faible pour couvrir les frais de transfert.",
    amount_invalid: "Saisissez un montant supérieur à zéro.",
    account_suspended: "Les retraits sont désactivés pour ce compte. Contactez le support.",
    method_invalid: "Choisissez l’un de vos propres moyens de paiement.",
  },
};

export const COPY = { EN, SW, FR };
export type WalletCopy = typeof EN;
