import type { IssueCode } from "./wizard/validation";

type P = Record<string, string | number>;

const EN = {
  /* Catalog list */
  listTitle: "Catalog",
  listDescription: "Every release you have started, submitted or distributed.",
  newRelease: "New release",
  filterLabel: "Filter by status",
  filterAll: "All",
  filterDrafts: "Drafts",
  filterInReview: "In review",
  filterDistributing: "Distributing",
  filterLive: "Live",
  filterInactive: "Inactive",
  searchLabel: "Search releases",
  searchPlaceholder: "Title, artist or UPC",
  typeLabel: "Type",
  typeAny: "All types",
  sortLabel: "Sort",
  sortNewest: "Newest first",
  sortOldest: "Oldest first",
  sortReleaseDate: "Release date",
  sortTitle: "Title A–Z",
  colRelease: "Release",
  colType: "Type",
  colTracks: "Tracks",
  colDate: "Release date",
  colStatus: "Status",
  tracksCount: (n: number) => (n === 1 ? "1 track" : `${n} tracks`),
  emptyAllTitle: "No releases yet",
  emptyAllBody: "Start your first release — you can save it as a draft and finish it any time.",
  emptyFilteredTitle: "Nothing matches",
  emptyFilteredBody: "Try another status or search term.",
  coverAlt: (title: string) => `Cover art for ${title}`,
  noCover: "No artwork yet",

  /* Detail */
  backToCatalog: "Catalog",
  by: (artist: string) => `by ${artist}`,
  tabsLabel: "Release sections",
  tabOverview: "Overview",
  tabTracks: "Tracks",
  tabStores: "Stores & delivery",
  tabSmartLink: "Smart link",
  tabSplits: "Splits",
  tabHistory: "History",
  tabIssues: "Issues",
  edit: "Edit release",
  continueEditing: "Continue editing",
  submit: "Submit for review",
  submitting: "Submitting…",
  withdraw: "Withdraw submission",
  withdrawTitle: "Withdraw this submission?",
  withdrawBody: "The release goes back to draft so you can change it. You'll need to submit it again.",
  withdrawn: "Submission withdrawn — the release is a draft again.",
  takedown: "Request takedown",
  takedownTitle: "Request a takedown",
  takedownBody: "We'll ask every store to remove this release. This can take several days and can't be undone from here.",
  takedownReason: "Why do you want it taken down?",
  takedownHint: "At least 5 characters. Our team reads this.",
  takedownRequested: "Takedown requested.",
  deleteDraft: "Delete draft",
  deleteTitle: "Delete this draft?",
  deleteBody: "The draft, its tracks and uploaded files are removed permanently.",
  deleted: "Draft deleted.",
  submitted: "Submitted for review. We'll notify you when it's reviewed.",
  subscriptionRequired: "You need an active plan to submit releases.",
  choosePlan: "Choose a plan",
  notReadyTitle: "This release isn't ready to submit yet",
  fixInWizard: "Fix in the editor",
  lockedNote: "Releases can only be edited while they are drafts or when changes are requested.",
  stageLabel: "Progress",
  stages: ["Draft", "Submitted", "In review", "Approved", "Delivered", "Live"],
  rejectionTitle: "Rejected",
  changesTitle: "Changes requested",
  changesBody: "Our review team asked for these changes. Edit the release, then submit it again.",
  details: "Details",
  fType: "Type",
  fArtist: "Primary artist",
  fAdditional: "Other artists",
  fVersion: "Version",
  fGenre: "Genre",
  fLanguage: "Language",
  fReleaseDate: "Release date",
  fOriginalDate: "Original release date",
  fLabel: "Record label",
  fCLine: "© line",
  fPLine: "℗ line",
  fUpc: "UPC / EAN",
  upcPending: "Assigned at approval",
  fSubmitted: "Submitted",
  fApproved: "Approved",
  fLive: "Live since",
  fTerritories: "Territories",
  worldwide: "Worldwide",
  onlyIn: (c: string) => `Only in ${c}`,
  exceptIn: (c: string) => `Everywhere except ${c}`,
  none: "—",

  /* Tracks tab */
  noTracks: "No tracks yet.",
  trackExplicit: "Explicit",
  trackInstrumental: "Instrumental",
  trackNoAudio: "No audio uploaded",
  isrcPending: "ISRC assigned at approval",
  audioPreview: (title: string) => `Preview of ${title}`,
  credits: "Credits",

  /* Stores tab */
  selectedStores: "Selected stores",
  noStores: "No stores selected yet.",
  deliveriesTitle: "Delivery status",
  deliveriesEmpty: "Deliveries start after the release is approved.",
  openInStore: (store: string) => `Open on ${store}`,
  deliveredAt: (d: string) => `Delivered ${d}`,
  liveAt: (d: string) => `Live ${d}`,

  /* Smart link tab */
  smartLinkTitle: "Your release page",
  smartLinkBody: "One link for fans that lists every store your release is on, with pre-save before release day when enabled.",
  smartLinkPublic: "Public",
  smartLinkNotYet: "Not public yet",
  smartLinkNotYetBody: "The page goes public once the release is submitted.",
  smartLinkDisabled: "Turned off",
  presaveOn: "Pre-save / notify-me is on",
  presaveOff: "Pre-save / notify-me is off",
  openPage: "Open page",
  statsInPromotion: "See clicks and visits in Promotion",
  noSlug: "This release doesn't have a link address yet.",

  /* Splits tab */
  splitsBody: "Split sheets decide how royalties from this release are shared. Everyone invited must accept before a sheet becomes active.",
  splitsEmpty: "No split sheet yet — 100% of royalties go to you.",
  manageSplits: "Create or manage splits",
  version: (n: number) => `Version ${n}`,
  wholeRelease: "Whole release",
  effectiveFrom: (d: string) => `Effective from ${d}`,

  /* History tab */
  historyEmpty: "No history yet.",
  byYou: "You",
  byTeam: "2kTunes team",
  bySystem: "System",

  /* Issues tab */
  issuesEmpty: "No open issues from review.",
  issueTrack: (n: string) => `Track: ${n}`,
  issueField: (f: string) => `Field: ${f}`,

  /* Wizard */
  wizardNewTitle: "New release",
  wizardEditTitle: "Edit release",
  wizardDescription: "Your work is saved as a draft as you go.",
  stepsLabel: "Release steps",
  stepInfo: "Release info",
  stepArtwork: "Artwork",
  stepTracks: "Tracks",
  stepCredits: "Credits",
  stepStores: "Stores",
  stepReview: "Review & submit",
  saveStateSaving: "Saving draft…",
  saveStateSaved: "All changes saved",
  saveStateError: "Couldn't save — ",
  saveRetry: "Retry",
  saveAndContinue: "Save & continue",
  createDraft: "Create draft & continue",
  back: "Back",
  next: "Next",
  notEditableTitle: "This release can't be edited",
  notEditableBody: "Only drafts and releases with requested changes can be edited.",
  viewRelease: "View release",
  stepHasErrors: (n: number) => (n === 1 ? "1 thing to fix" : `${n} things to fix`),

  /* Info step */
  releaseType: "Release type",
  typeSingle: "Single",
  typeSingleDesc: "1–3 tracks",
  typeEP: "EP",
  typeEPDesc: "2–7 tracks",
  typeAlbum: "Album",
  typeAlbumDesc: "5 or more tracks",
  typeRange: (min: number, max: number) => `${min}–${max} tracks`,
  releaseTitle: "Release title",
  releaseTitleHint: "Exactly as it should appear in stores — no “feat.” here.",
  version_: "Version",
  versionHint: "E.g. Remix, Acoustic, Live. Leave empty for the original.",
  primaryArtist: "Primary artist",
  chooseArtist: "Choose an artist profile",
  typedArtist: "Artist name",
  noArtistProfiles: "You don't have an artist profile yet.",
  createArtistProfile: "Create an artist profile",
  primaryGenre: "Primary genre",
  secondaryGenre: "Secondary genre",
  chooseGenre: "Choose a genre",
  language: "Language of title and lyrics",
  chooseLanguage: "Choose a language",
  releaseDate: "Release date",
  releaseDateHint: (min: number, rec: number) =>
    `At least ${min} days from today. ${rec}+ days gives time for pitching and pre-saves.`,
  previouslyReleased: "This was released before",
  previouslyReleasedHint: "Tick if it's already out elsewhere (e.g. a re-release).",
  originalReleaseDate: "Original release date",
  recordLabel: "Record label",
  recordLabelHint: "Leave empty to release independently under your artist name.",
  rightsTitle: "Copyright",
  rightsBody: "© is the owner of the artwork and release; ℗ is the owner of the sound recording. Usually both are you or your label.",
  cLineYear: "© year",
  cLineOwner: "© owner",
  pLineYear: "℗ year",
  pLineOwner: "℗ owner",
  upc: "UPC / EAN",
  upcHintGenerate: "Leave empty and we'll assign one.",
  upcHintManual: "Leave empty and our team assigns one at approval.",
  additionalArtists: "Other artists on this release",
  additionalArtistsHint: "Featured artists or additional primary artists.",
  addArtist: "Add artist",
  artistName: "Name",
  artistRole: "Role",
  role_primary_artist: "Primary artist",
  role_featured_artist: "Featured artist",
  role_remixer: "Remixer",
  removeArtist: (name: string) => `Remove ${name || "artist"}`,

  /* Artwork step */
  artworkTitle: "Cover artwork",
  artworkRules: (min: number, max: number, mb: number) =>
    `Square JPG or PNG, at least ${min} × ${min} px and at most ${max} × ${max} px, up to ${mb} MB. No blur, logos of stores, URLs or contact details.`,
  artworkChoose: "Choose image",
  artworkReplace: "Replace image",
  artworkCurrent: "Current artwork",
  artworkNone: "No artwork uploaded yet.",
  artworkChecking: "Checking image…",
  artworkUploading: "Uploading artwork",
  artworkSaved: "Artwork saved.",
  artworkReadError: "We couldn't read that image. Try exporting it again as JPG or PNG.",
  artworkSize: (w: number, h: number) => `${w} × ${h} px`,

  /* Tracks step */
  tracksTitle: "Tracks",
  tracksRules: (type: string, min: number, max: number) => `A ${type} has ${min}–${max} tracks.`,
  audioRules: (formats: string, mb: number, rate: number, depth: number) =>
    `${formats}, up to ${mb} MB. Lossless WAV/FLAC at ${rate / 1000} kHz / ${depth}-bit or better is recommended.`,
  addTrack: "Add track",
  newTrackTitle: "New track title",
  addTrackHint: "Add the title first, then upload its audio.",
  trackNumber: (n: number) => `Track ${n}`,
  trackTitle: "Track title",
  trackVersion: "Version",
  trackPrimaryArtist: "Primary artist",
  trackFeatured: "Featured artists",
  trackFeaturedHint: "Separate names with commas.",
  trackLanguage: "Lyrics language",
  sameAsRelease: "Same as release",
  trackIsrc: "ISRC",
  trackIsrcHint: "Leave empty and one is assigned.",
  trackOwnership: "Ownership",
  own_original: "Original song",
  own_cover: "Cover of another song",
  own_remix: "Remix",
  own_public_domain: "Public domain",
  trackPublisher: "Publisher",
  trackPublisherHint: "Required for covers (the original song's publisher).",
  trackExplicitLabel: "Explicit lyrics",
  trackCleanLabel: "Clean version of an explicit track",
  trackInstrumentalLabel: "Instrumental (no vocals)",
  trackAiLabel: "Made with AI-generated vocals or instrumentation",
  trackLyrics: "Lyrics",
  moveUp: (t: string) => `Move ${t} up`,
  moveDown: (t: string) => `Move ${t} down`,
  deleteTrack: (t: string) => `Delete ${t}`,
  deleteTrackTitle: "Delete this track?",
  deleteTrackBody: "The track and its uploaded audio are removed from the draft.",
  trackSaved: "Saved",
  audioTitle: "Audio",
  audioChoose: "Upload audio",
  audioReplace: "Replace audio",
  audioResumeHint: "Choose the same file again to resume where it stopped.",
  audioHashing: "Checking file",
  audioUploading: "Uploading",
  audioFinalizing: "Verifying on the server",
  audioAttaching: "Attaching to the track",
  audioDone: "Audio uploaded",
  audioFailed: "Upload stopped",
  audioCancel: "Cancel upload",
  audioCancelled: "Upload cancelled.",
  audioRetry: "Retry upload",
  audioProgress: (label: string, pct: number) => `${label}: ${pct}%`,
  audioFacts: (fmt: string, rate: string, depth: string, dur: string) => `${fmt} · ${rate} · ${depth} · ${dur}`,
  audioWarning: "Note",

  /* Credits step */
  creditsTitle: "Credits & contributors",
  creditsBody: "Stores need the real names of the people who wrote the song. Every track needs at least one songwriter, composer or lyricist (unless it's public domain).",
  addCredit: "Add contributor",
  creditRole: "Role",
  creditName: "Full legal name",
  creditDetail: "Detail",
  creditDetailHint: "Optional, e.g. instrument.",
  removeCredit: (name: string) => `Remove ${name || "contributor"}`,
  copyCredits: "Copy these credits to all other tracks",
  creditsCopied: (n: number) => `Copied to ${n} track(s).`,
  noCredits: "No contributors yet.",
  creditRoles: {
    primary_artist: "Primary artist",
    featured_artist: "Featured artist",
    producer: "Producer",
    co_producer: "Co-producer",
    composer: "Composer",
    songwriter: "Songwriter",
    lyricist: "Lyricist",
    arranger: "Arranger",
    mixing_engineer: "Mixing engineer",
    mastering_engineer: "Mastering engineer",
    recording_engineer: "Recording engineer",
    performer: "Performer",
    vocalist: "Vocalist",
    publisher: "Publisher",
    remixer: "Remixer",
  } as Record<string, string>,
  noTracksForCredits: "Add tracks first, then their credits.",

  /* Stores step */
  storesTitle: "Stores",
  storesBody: "Choose where your release goes. Only stores marked available can be selected today.",
  selectAll: "Select all available",
  clearAll: "Clear",
  comingSoon: "Coming soon",
  storeCategories: {
    streaming: "Streaming",
    social: "Social & video",
    discovery: "Discovery",
    rights: "Rights management",
  } as Record<string, string>,
  territoriesTitle: "Territories",
  terrWorldwide: "Worldwide",
  terrWorldwideDesc: "Available in every country the stores serve.",
  terrInclude: "Only selected countries",
  terrIncludeDesc: "Release only where you list.",
  terrExclude: "All except selected countries",
  terrExcludeDesc: "Block specific countries.",
  countries: "Country codes",
  countriesHint: "Two-letter codes separated by commas, e.g. TZ, KE, UG.",

  /* Review step */
  reviewTitle: "Review",
  reviewBody: "We check your release against store requirements before you submit.",
  checking: "Checking your release…",
  readyTitle: "Ready to submit",
  readyBody: "Everything required is in place.",
  notReady: "Fix these before submitting",
  warnings: "Worth a look",
  goToStep: "Go to step",
  agreementsTitle: "Agreements",
  agree_rights_confirmation: "I own or control all rights to distribute this music and artwork.",
  agree_distribution_terms: "I accept the 2kTunes distribution terms.",
  agree_no_ai_misrepresentation: "I haven't misrepresented AI-generated content or impersonated another artist.",
  termsLink: "Read the distribution agreement",
  smartLinkSettings: "Release page",
  smartLinkToggle: "Create a public release page (smart link)",
  smartLinkToggleHint: "Goes live after you submit; it lists stores as they go live.",
  presaveToggle: "Let fans sign up to be notified on release day",
  presaveToggleHint: "Shown on the release page until the release is live.",
  submitRelease: "Submit for review",
  submitHint: "After submitting, the release is locked while our team reviews it.",
  summaryTracks: (n: number) => (n === 1 ? "1 track" : `${n} tracks`),
  summaryStores: (n: number) => (n === 1 ? "1 store" : `${n} stores`),

  /* Validation messages */
  issue: {
    required: () => "This is required.",
    too_long: (p: P) => `Keep it under ${p.max} characters.`,
    date_too_soon: (p: P) => `Choose a date at least ${p.days} days from today (${p.date} or later).`,
    date_in_future: () => "The original release date must be in the past.",
    year_invalid: (p: P) => `Enter a 4-digit year between 1900 and ${p.max}.`,
    upc_invalid: () => "That UPC/EAN isn't valid. Check the digits or leave it empty.",
    isrc_invalid: (p: P) => `Track ${p.n}: the ISRC isn't valid (format CC-XXX-YY-NNNNN).`,
    isrc_duplicate: (p: P) => `Track ${p.n}: this ISRC is already used on another track.`,
    tracks_too_few: (p: P) => `A ${p.type || "release"} needs at least ${p.min} track(s).`,
    tracks_too_many: (p: P) => `A ${p.type} can have at most ${p.max} tracks.`,
    track_title_missing: (p: P) => `Track ${p.n}: add a title.`,
    track_audio_missing: (p: P) => `Track ${p.n}: upload the audio.`,
    explicit_and_clean: (p: P) => `Track ${p.n}: a track can't be both explicit and a clean version.`,
    writer_missing: (p: P) => `Track ${p.n}: add at least one songwriter, composer or lyricist.`,
    credit_name_missing: (p: P) => `Track ${p.n}: every contributor needs a name.`,
    stores_none: () => "Choose at least one store.",
    stores_unavailable: (p: P) => `These stores aren't available yet: ${p.stores}.`,
    countries_missing: () => "List the countries, or choose worldwide.",
    country_invalid: (p: P) => `These aren't two-letter country codes: ${p.codes}.`,
    agreement_missing: () => "Please confirm to continue.",
    file_type: (p: P) => (p.formats ? `Use one of: ${p.formats}.` : "Use a JPG or PNG image."),
    file_too_large: (p: P) => `The file is larger than ${p.mb} MB.`,
    not_square: (p: P) => `Artwork must be square. Yours is ${p.w} × ${p.h} px.`,
    too_small: (p: P) => `Artwork must be at least ${p.min} × ${p.min} px. Yours is ${p.w} × ${p.h} px.`,
    too_big: (p: P) => `Artwork must be at most ${p.max} × ${p.max} px. Yours is ${p.w} × ${p.h} px.`,
  } satisfies Record<IssueCode, (p: P) => string>,
};

const SW: typeof EN = {
  listTitle: "Katalogi",
  listDescription: "Kila toleo ulilolianzisha, kuwasilisha au kusambaza.",
  newRelease: "Toleo jipya",
  filterLabel: "Chuja kwa hali",
  filterAll: "Zote",
  filterDrafts: "Rasimu",
  filterInReview: "Zinakaguliwa",
  filterDistributing: "Zinasambazwa",
  filterLive: "Hewani",
  filterInactive: "Hazitumiki",
  searchLabel: "Tafuta matoleo",
  searchPlaceholder: "Jina, msanii au UPC",
  typeLabel: "Aina",
  typeAny: "Aina zote",
  sortLabel: "Panga",
  sortNewest: "Mapya kwanza",
  sortOldest: "Ya zamani kwanza",
  sortReleaseDate: "Tarehe ya kutoka",
  sortTitle: "Jina A–Z",
  colRelease: "Toleo",
  colType: "Aina",
  colTracks: "Nyimbo",
  colDate: "Tarehe ya kutoka",
  colStatus: "Hali",
  tracksCount: (n) => (n === 1 ? "Wimbo 1" : `Nyimbo ${n}`),
  emptyAllTitle: "Bado huna matoleo",
  emptyAllBody: "Anza toleo lako la kwanza — unaweza kulihifadhi kama rasimu na kulikamilisha wakati wowote.",
  emptyFilteredTitle: "Hakuna kinacholingana",
  emptyFilteredBody: "Jaribu hali nyingine au neno lingine la utafutaji.",
  coverAlt: (title) => `Picha ya jalada ya ${title}`,
  noCover: "Bado hakuna picha ya jalada",

  backToCatalog: "Katalogi",
  by: (artist) => `na ${artist}`,
  tabsLabel: "Sehemu za toleo",
  tabOverview: "Muhtasari",
  tabTracks: "Nyimbo",
  tabStores: "Maduka na usambazaji",
  tabSmartLink: "Kiungo janja",
  tabSplits: "Mgawanyo",
  tabHistory: "Historia",
  tabIssues: "Marekebisho",
  edit: "Hariri toleo",
  continueEditing: "Endelea kuhariri",
  submit: "Wasilisha kwa ukaguzi",
  submitting: "Inawasilisha…",
  withdraw: "Ondoa uwasilishaji",
  withdrawTitle: "Uondoe uwasilishaji huu?",
  withdrawBody: "Toleo litarudi kuwa rasimu ili uweze kulibadilisha. Utahitaji kuliwasilisha tena.",
  withdrawn: "Uwasilishaji umeondolewa — toleo ni rasimu tena.",
  takedown: "Omba kuondolewa",
  takedownTitle: "Omba toleo liondolewe",
  takedownBody: "Tutaomba kila duka liondoe toleo hili. Inaweza kuchukua siku kadhaa na haiwezi kutenduliwa hapa.",
  takedownReason: "Kwa nini unataka liondolewe?",
  takedownHint: "Angalau herufi 5. Timu yetu itasoma hili.",
  takedownRequested: "Ombi la kuondolewa limetumwa.",
  deleteDraft: "Futa rasimu",
  deleteTitle: "Ufute rasimu hii?",
  deleteBody: "Rasimu, nyimbo zake na faili zilizopakiwa zitaondolewa kabisa.",
  deleted: "Rasimu imefutwa.",
  submitted: "Limewasilishwa kwa ukaguzi. Tutakujulisha likishakaguliwa.",
  subscriptionRequired: "Unahitaji mpango hai ili kuwasilisha matoleo.",
  choosePlan: "Chagua mpango",
  notReadyTitle: "Toleo hili bado halijawa tayari kuwasilishwa",
  fixInWizard: "Rekebisha kwenye kihariri",
  lockedNote: "Matoleo yanaweza kuhaririwa tu yakiwa rasimu au marekebisho yakiombwa.",
  stageLabel: "Maendeleo",
  stages: ["Rasimu", "Limewasilishwa", "Linakaguliwa", "Limeidhinishwa", "Limesambazwa", "Hewani"],
  rejectionTitle: "Limekataliwa",
  changesTitle: "Marekebisho yanahitajika",
  changesBody: "Timu yetu ya ukaguzi imeomba mabadiliko haya. Hariri toleo kisha uliwasilishe tena.",
  details: "Maelezo",
  fType: "Aina",
  fArtist: "Msanii mkuu",
  fAdditional: "Wasanii wengine",
  fVersion: "Toleo la wimbo",
  fGenre: "Mtindo",
  fLanguage: "Lugha",
  fReleaseDate: "Tarehe ya kutoka",
  fOriginalDate: "Tarehe ya awali ya kutoka",
  fLabel: "Lebo ya muziki",
  fCLine: "Mstari wa ©",
  fPLine: "Mstari wa ℗",
  fUpc: "UPC / EAN",
  upcPending: "Litatolewa wakati wa kuidhinishwa",
  fSubmitted: "Liliwasilishwa",
  fApproved: "Liliidhinishwa",
  fLive: "Hewani tangu",
  fTerritories: "Maeneo",
  worldwide: "Dunia nzima",
  onlyIn: (c) => `Tu katika ${c}`,
  exceptIn: (c) => `Kila mahali isipokuwa ${c}`,
  none: "—",

  noTracks: "Bado hakuna nyimbo.",
  trackExplicit: "Maneno makali",
  trackInstrumental: "Ala tu",
  trackNoAudio: "Hakuna sauti iliyopakiwa",
  isrcPending: "ISRC itatolewa wakati wa kuidhinishwa",
  audioPreview: (title) => `Sikiliza ${title}`,
  credits: "Wachangiaji",

  selectedStores: "Maduka yaliyochaguliwa",
  noStores: "Bado hujachagua maduka.",
  deliveriesTitle: "Hali ya usambazaji",
  deliveriesEmpty: "Usambazaji huanza baada ya toleo kuidhinishwa.",
  openInStore: (store) => `Fungua kwenye ${store}`,
  deliveredAt: (d) => `Limesambazwa ${d}`,
  liveAt: (d) => `Hewani ${d}`,

  smartLinkTitle: "Ukurasa wa toleo lako",
  smartLinkBody: "Kiungo kimoja kwa mashabiki kinachoonyesha kila duka toleo lako lilipo, pamoja na kujisajili mapema kabla ya siku ya kutoka kikiwashwa.",
  smartLinkPublic: "Wazi kwa umma",
  smartLinkNotYet: "Bado si wazi",
  smartLinkNotYetBody: "Ukurasa utakuwa wazi baada ya toleo kuwasilishwa.",
  smartLinkDisabled: "Umezimwa",
  presaveOn: "Kujisajili kupata taarifa kumewashwa",
  presaveOff: "Kujisajili kupata taarifa kumezimwa",
  openPage: "Fungua ukurasa",
  statsInPromotion: "Angalia mibofyo na matembeleo kwenye Utangazaji",
  noSlug: "Toleo hili bado halina anwani ya kiungo.",

  splitsBody: "Karatasi za mgawanyo huamua jinsi mirabaha ya toleo hili inavyogawanywa. Kila aliyealikwa lazima akubali kabla karatasi haijaanza kutumika.",
  splitsEmpty: "Bado hakuna karatasi ya mgawanyo — asilimia 100 ya mirabaha ni yako.",
  manageSplits: "Unda au simamia mgawanyo",
  version: (n) => `Toleo la ${n}`,
  wholeRelease: "Toleo zima",
  effectiveFrom: (d) => `Inatumika kuanzia ${d}`,

  historyEmpty: "Bado hakuna historia.",
  byYou: "Wewe",
  byTeam: "Timu ya 2kTunes",
  bySystem: "Mfumo",

  issuesEmpty: "Hakuna marekebisho yaliyoombwa na ukaguzi.",
  issueTrack: (n) => `Wimbo: ${n}`,
  issueField: (f) => `Sehemu: ${f}`,

  wizardNewTitle: "Toleo jipya",
  wizardEditTitle: "Hariri toleo",
  wizardDescription: "Kazi yako inahifadhiwa kama rasimu unapoendelea.",
  stepsLabel: "Hatua za toleo",
  stepInfo: "Taarifa za toleo",
  stepArtwork: "Picha ya jalada",
  stepTracks: "Nyimbo",
  stepCredits: "Wachangiaji",
  stepStores: "Maduka",
  stepReview: "Kagua na uwasilishe",
  saveStateSaving: "Inahifadhi rasimu…",
  saveStateSaved: "Mabadiliko yote yamehifadhiwa",
  saveStateError: "Imeshindwa kuhifadhi — ",
  saveRetry: "Jaribu tena",
  saveAndContinue: "Hifadhi na uendelee",
  createDraft: "Unda rasimu na uendelee",
  back: "Rudi",
  next: "Endelea",
  notEditableTitle: "Toleo hili haliwezi kuhaririwa",
  notEditableBody: "Ni rasimu na matoleo yaliyoombwa marekebisho tu yanayoweza kuhaririwa.",
  viewRelease: "Angalia toleo",
  stepHasErrors: (n) => (n === 1 ? "Jambo 1 la kurekebisha" : `Mambo ${n} ya kurekebisha`),

  releaseType: "Aina ya toleo",
  typeSingle: "Single",
  typeSingleDesc: "Nyimbo 1–3",
  typeEP: "EP",
  typeEPDesc: "Nyimbo 2–7",
  typeAlbum: "Albamu",
  typeAlbumDesc: "Nyimbo 5 au zaidi",
  typeRange: (min, max) => `Nyimbo ${min}–${max}`,
  releaseTitle: "Jina la toleo",
  releaseTitleHint: "Kama linavyotakiwa kuonekana madukani — usiweke “feat.” hapa.",
  version_: "Toleo la wimbo",
  versionHint: "Mfano: Remix, Acoustic, Live. Acha wazi kwa toleo la asili.",
  primaryArtist: "Msanii mkuu",
  chooseArtist: "Chagua wasifu wa msanii",
  typedArtist: "Jina la msanii",
  noArtistProfiles: "Bado huna wasifu wa msanii.",
  createArtistProfile: "Unda wasifu wa msanii",
  primaryGenre: "Mtindo mkuu",
  secondaryGenre: "Mtindo wa pili",
  chooseGenre: "Chagua mtindo",
  language: "Lugha ya jina na maneno",
  chooseLanguage: "Chagua lugha",
  releaseDate: "Tarehe ya kutoka",
  releaseDateHint: (min, rec) =>
    `Angalau siku ${min} kuanzia leo. Siku ${rec} au zaidi zinatoa muda wa kupendekeza kwenye orodha za nyimbo na kujisajili mapema.`,
  previouslyReleased: "Hili liliwahi kutolewa",
  previouslyReleasedHint: "Weka alama kama tayari liko nje mahali pengine (mf. linatolewa upya).",
  originalReleaseDate: "Tarehe ya awali ya kutoka",
  recordLabel: "Lebo ya muziki",
  recordLabelHint: "Acha wazi kutoa kwa kujitegemea kwa jina lako la msanii.",
  rightsTitle: "Hakimiliki",
  rightsBody: "© ni mmiliki wa picha na toleo; ℗ ni mmiliki wa rekodi ya sauti. Mara nyingi wote ni wewe au lebo yako.",
  cLineYear: "Mwaka wa ©",
  cLineOwner: "Mmiliki wa ©",
  pLineYear: "Mwaka wa ℗",
  pLineOwner: "Mmiliki wa ℗",
  upc: "UPC / EAN",
  upcHintGenerate: "Acha wazi na tutakupa moja.",
  upcHintManual: "Acha wazi na timu yetu itatoa moja wakati wa kuidhinisha.",
  additionalArtists: "Wasanii wengine kwenye toleo hili",
  additionalArtistsHint: "Wasanii walioshirikishwa au wasanii wakuu wa ziada.",
  addArtist: "Ongeza msanii",
  artistName: "Jina",
  artistRole: "Nafasi",
  role_primary_artist: "Msanii mkuu",
  role_featured_artist: "Msanii aliyeshirikishwa",
  role_remixer: "Mpangaji wa remix",
  removeArtist: (name) => `Ondoa ${name || "msanii"}`,

  artworkTitle: "Picha ya jalada",
  artworkRules: (min, max, mb) =>
    `JPG au PNG ya mraba, angalau ${min} × ${min} px na isiyozidi ${max} × ${max} px, hadi MB ${mb}. Isiwe na ukungu, nembo za maduka, viungo au mawasiliano.`,
  artworkChoose: "Chagua picha",
  artworkReplace: "Badilisha picha",
  artworkCurrent: "Picha ya sasa",
  artworkNone: "Bado hakuna picha iliyopakiwa.",
  artworkChecking: "Inakagua picha…",
  artworkUploading: "Inapakia picha",
  artworkSaved: "Picha imehifadhiwa.",
  artworkReadError: "Hatukuweza kusoma picha hiyo. Jaribu kuihifadhi upya kama JPG au PNG.",
  artworkSize: (w, h) => `${w} × ${h} px`,

  tracksTitle: "Nyimbo",
  tracksRules: (type, min, max) => `${type} huwa na nyimbo ${min}–${max}.`,
  audioRules: (formats, mb, rate, depth) =>
    `${formats}, hadi MB ${mb}. Inapendekezwa WAV/FLAC isiyopunguzwa ubora ya ${rate / 1000} kHz / ${depth}-bit au zaidi.`,
  addTrack: "Ongeza wimbo",
  newTrackTitle: "Jina la wimbo mpya",
  addTrackHint: "Weka jina kwanza, kisha pakia sauti yake.",
  trackNumber: (n) => `Wimbo ${n}`,
  trackTitle: "Jina la wimbo",
  trackVersion: "Toleo la wimbo",
  trackPrimaryArtist: "Msanii mkuu",
  trackFeatured: "Wasanii walioshirikishwa",
  trackFeaturedHint: "Tenganisha majina kwa koma.",
  trackLanguage: "Lugha ya maneno",
  sameAsRelease: "Sawa na toleo",
  trackIsrc: "ISRC",
  trackIsrcHint: "Acha wazi na itatolewa.",
  trackOwnership: "Umiliki",
  own_original: "Wimbo asilia",
  own_cover: "Wimbo wa mtu mwingine (cover)",
  own_remix: "Remix",
  own_public_domain: "Mali ya umma",
  trackPublisher: "Mchapishaji",
  trackPublisherHint: "Inahitajika kwa cover (mchapishaji wa wimbo asilia).",
  trackExplicitLabel: "Maneno makali",
  trackCleanLabel: "Toleo safi la wimbo wenye maneno makali",
  trackInstrumentalLabel: "Ala tu (bila sauti ya kuimba)",
  trackAiLabel: "Umetengenezwa kwa sauti au ala zilizozalishwa na AI",
  trackLyrics: "Maneno ya wimbo",
  moveUp: (t) => `Pandisha ${t} juu`,
  moveDown: (t) => `Shusha ${t} chini`,
  deleteTrack: (t) => `Futa ${t}`,
  deleteTrackTitle: "Ufute wimbo huu?",
  deleteTrackBody: "Wimbo na sauti yake iliyopakiwa vitaondolewa kwenye rasimu.",
  trackSaved: "Imehifadhiwa",
  audioTitle: "Sauti",
  audioChoose: "Pakia sauti",
  audioReplace: "Badilisha sauti",
  audioResumeHint: "Chagua faili ile ile tena ili kuendelea pale ilipoishia.",
  audioHashing: "Inakagua faili",
  audioUploading: "Inapakia",
  audioFinalizing: "Inathibitisha kwenye seva",
  audioAttaching: "Inaunganisha na wimbo",
  audioDone: "Sauti imepakiwa",
  audioFailed: "Upakiaji umesimama",
  audioCancel: "Ghairi upakiaji",
  audioCancelled: "Upakiaji umeghairiwa.",
  audioRetry: "Jaribu kupakia tena",
  audioProgress: (label, pct) => `${label}: ${pct}%`,
  audioFacts: (fmt, rate, depth, dur) => `${fmt} · ${rate} · ${depth} · ${dur}`,
  audioWarning: "Zingatia",

  creditsTitle: "Wachangiaji",
  creditsBody: "Maduka yanahitaji majina halisi ya walioandika wimbo. Kila wimbo unahitaji angalau mtunzi wa wimbo, mtunzi wa muziki au mwandishi wa maneno mmoja (isipokuwa kama ni mali ya umma).",
  addCredit: "Ongeza mchangiaji",
  creditRole: "Nafasi",
  creditName: "Jina kamili rasmi",
  creditDetail: "Maelezo",
  creditDetailHint: "Si lazima, mf. ala ya muziki.",
  removeCredit: (name) => `Ondoa ${name || "mchangiaji"}`,
  copyCredits: "Nakili wachangiaji hawa kwenye nyimbo nyingine zote",
  creditsCopied: (n) => `Imenakiliwa kwenye nyimbo ${n}.`,
  noCredits: "Bado hakuna wachangiaji.",
  creditRoles: {
    primary_artist: "Msanii mkuu",
    featured_artist: "Msanii aliyeshirikishwa",
    producer: "Mtayarishaji",
    co_producer: "Mtayarishaji mwenza",
    composer: "Mtunzi wa muziki",
    songwriter: "Mtunzi wa wimbo",
    lyricist: "Mwandishi wa maneno",
    arranger: "Mpangaji wa muziki",
    mixing_engineer: "Mhandisi wa mchanganyiko",
    mastering_engineer: "Mhandisi wa mastering",
    recording_engineer: "Mhandisi wa kurekodi",
    performer: "Mwanamuziki",
    vocalist: "Mwimbaji",
    publisher: "Mchapishaji",
    remixer: "Mpangaji wa remix",
  },
  noTracksForCredits: "Ongeza nyimbo kwanza, kisha wachangiaji wake.",

  storesTitle: "Maduka",
  storesBody: "Chagua toleo lako liende wapi. Ni maduka yaliyo tayari tu yanayoweza kuchaguliwa leo.",
  selectAll: "Chagua yote yaliyo tayari",
  clearAll: "Futa",
  comingSoon: "Yanakuja hivi karibuni",
  storeCategories: {
    streaming: "Usikilizaji mtandaoni",
    social: "Mitandao ya kijamii na video",
    discovery: "Ugunduzi",
    rights: "Usimamizi wa haki",
  },
  territoriesTitle: "Maeneo",
  terrWorldwide: "Dunia nzima",
  terrWorldwideDesc: "Linapatikana katika kila nchi maduka yanapohudumia.",
  terrInclude: "Nchi zilizochaguliwa tu",
  terrIncludeDesc: "Toa tu mahali unapoorodhesha.",
  terrExclude: "Zote isipokuwa nchi zilizochaguliwa",
  terrExcludeDesc: "Zuia nchi fulani.",
  countries: "Misimbo ya nchi",
  countriesHint: "Misimbo ya herufi mbili ikitenganishwa kwa koma, mf. TZ, KE, UG.",

  reviewTitle: "Kagua",
  reviewBody: "Tunakagua toleo lako dhidi ya masharti ya maduka kabla hujaliwasilisha.",
  checking: "Inakagua toleo lako…",
  readyTitle: "Tayari kuwasilishwa",
  readyBody: "Kila kinachohitajika kipo.",
  notReady: "Rekebisha haya kabla ya kuwasilisha",
  warnings: "Inafaa kuangalia",
  goToStep: "Nenda kwenye hatua",
  agreementsTitle: "Makubaliano",
  agree_rights_confirmation: "Ninamiliki au kudhibiti haki zote za kusambaza muziki huu na picha yake.",
  agree_distribution_terms: "Ninakubali masharti ya usambazaji ya 2kTunes.",
  agree_no_ai_misrepresentation: "Sijapotosha kuhusu maudhui ya AI wala kujifanya msanii mwingine.",
  termsLink: "Soma makubaliano ya usambazaji",
  smartLinkSettings: "Ukurasa wa toleo",
  smartLinkToggle: "Unda ukurasa wa toleo wa umma (kiungo janja)",
  smartLinkToggleHint: "Unakuwa hewani baada ya kuwasilisha; unaonyesha maduka kadri yanavyokuwa hewani.",
  presaveToggle: "Waruhusu mashabiki kujisajili kupata taarifa siku ya kutoka",
  presaveToggleHint: "Inaonyeshwa kwenye ukurasa wa toleo hadi toleo liwe hewani.",
  submitRelease: "Wasilisha kwa ukaguzi",
  submitHint: "Baada ya kuwasilisha, toleo hufungwa wakati timu yetu inalikagua.",
  summaryTracks: (n) => (n === 1 ? "Wimbo 1" : `Nyimbo ${n}`),
  summaryStores: (n) => (n === 1 ? "Duka 1" : `Maduka ${n}`),

  issue: {
    required: () => "Hii inahitajika.",
    too_long: (p) => `Isizidi herufi ${p.max}.`,
    date_too_soon: (p) => `Chagua tarehe angalau siku ${p.days} kuanzia leo (${p.date} au baadaye).`,
    date_in_future: () => "Tarehe ya awali ya kutoka lazima iwe iliyopita.",
    year_invalid: (p) => `Weka mwaka wa tarakimu 4 kati ya 1900 na ${p.max}.`,
    upc_invalid: () => "UPC/EAN hiyo si sahihi. Angalia tarakimu au iache wazi.",
    isrc_invalid: (p) => `Wimbo ${p.n}: ISRC si sahihi (muundo CC-XXX-YY-NNNNN).`,
    isrc_duplicate: (p) => `Wimbo ${p.n}: ISRC hii tayari imetumika kwenye wimbo mwingine.`,
    tracks_too_few: (p) => `${p.type || "Toleo"} linahitaji angalau nyimbo ${p.min}.`,
    tracks_too_many: (p) => `${p.type} haliwezi kuzidi nyimbo ${p.max}.`,
    track_title_missing: (p) => `Wimbo ${p.n}: weka jina.`,
    track_audio_missing: (p) => `Wimbo ${p.n}: pakia sauti.`,
    explicit_and_clean: (p) => `Wimbo ${p.n}: wimbo hauwezi kuwa na maneno makali na pia kuwa toleo safi.`,
    writer_missing: (p) => `Wimbo ${p.n}: ongeza angalau mtunzi wa wimbo, mtunzi wa muziki au mwandishi wa maneno mmoja.`,
    credit_name_missing: (p) => `Wimbo ${p.n}: kila mchangiaji anahitaji jina.`,
    stores_none: () => "Chagua angalau duka moja.",
    stores_unavailable: (p) => `Maduka haya bado hayapatikani: ${p.stores}.`,
    countries_missing: () => "Orodhesha nchi, au chagua dunia nzima.",
    country_invalid: (p) => `Hii si misimbo ya nchi ya herufi mbili: ${p.codes}.`,
    agreement_missing: () => "Tafadhali thibitisha ili kuendelea.",
    file_type: (p) => (p.formats ? `Tumia mojawapo ya: ${p.formats}.` : "Tumia picha ya JPG au PNG."),
    file_too_large: (p) => `Faili ni kubwa kuliko MB ${p.mb}.`,
    not_square: (p) => `Picha lazima iwe ya mraba. Yako ni ${p.w} × ${p.h} px.`,
    too_small: (p) => `Picha lazima iwe angalau ${p.min} × ${p.min} px. Yako ni ${p.w} × ${p.h} px.`,
    too_big: (p) => `Picha isizidi ${p.max} × ${p.max} px. Yako ni ${p.w} × ${p.h} px.`,
  },
};

export const COPY = { EN, SW };
export type MusicCopy = typeof EN;
