/** Royalties screen copy. */

const EN = {
  title: "Royalties",
  intro: "What your music earned, broken down by month, store, country, release, track or statement. Only statements posted by 2kTunes finance are counted.",
  filtersLabel: "Report filters",
  groupBy: "Break down by",
  by: {
    month: "Month",
    store: "Store",
    territory: "Country",
    release: "Release",
    track: "Track",
    usage: "Usage type",
    statement: "Statement",
  },
  from: "From",
  to: "To",
  currency: "Currency",
  allCurrencies: "All currencies",
  rangeInvalid: "The start date must be on or before the end date.",
  showing: (from: string, to: string) => `Showing ${from} – ${to}`,
  breakdownTitle: "Breakdown",
  breakdownCaption: (by: string) => `Royalties by ${by.toLowerCase()}`,
  colAmount: "Earnings",
  colUnits: "Units",
  colLines: "Report lines",
  totalFor: (cur: string) => `Total (${cur})`,
  emptyTitle: "No royalties in this period",
  emptyBody:
    "Royalties appear here after store statements are imported and posted by 2kTunes finance. Stores usually report 1–3 months after the plays happen.",
  unknown: "Unknown",
  usage: {
    stream: "Streams",
    streams: "Streams",
    download: "Downloads",
    video: "Video",
    ugc: "User videos (UGC)",
    other: "Other",
  } as Record<string, string>,
  statementsTitle: "Statements",
  statementsDesc: "Store statements that credited your wallet.",
  statementsCaption: "Posted statements",
  colSource: "Source",
  colPeriod: "Period",
  colPosted: "Posted",
  period: (from: string, to: string) => `${from} – ${to}`,
  statementsEmptyTitle: "No statements yet",
  statementsEmptyBody:
    "Once 2kTunes finance imports and posts a store statement that includes your music, it will be listed here and credited to your wallet.",
};

const SW: typeof EN = {
  title: "Mirabaha",
  intro: "Kile muziki wako ulichopata, kwa mwezi, duka, nchi, albamu, wimbo au ripoti. Ripoti zilizothibitishwa na idara ya fedha ya 2kTunes pekee ndizo huhesabiwa.",
  filtersLabel: "Vichujio vya ripoti",
  groupBy: "Gawanya kwa",
  by: {
    month: "Mwezi",
    store: "Duka",
    territory: "Nchi",
    release: "Toleo",
    track: "Wimbo",
    usage: "Aina ya matumizi",
    statement: "Ripoti",
  },
  from: "Kuanzia",
  to: "Hadi",
  currency: "Sarafu",
  allCurrencies: "Sarafu zote",
  rangeInvalid: "Tarehe ya kuanzia lazima iwe kabla au sawa na tarehe ya mwisho.",
  showing: (from: string, to: string) => `Inaonyesha ${from} – ${to}`,
  breakdownTitle: "Mgawanyo",
  breakdownCaption: (by: string) => `Mirabaha kwa ${by.toLowerCase()}`,
  colAmount: "Mapato",
  colUnits: "Idadi",
  colLines: "Mistari ya ripoti",
  totalFor: (cur: string) => `Jumla (${cur})`,
  emptyTitle: "Hakuna mirabaha katika kipindi hiki",
  emptyBody:
    "Mirabaha huonekana hapa baada ya ripoti za maduka kuingizwa na kuthibitishwa na idara ya fedha ya 2kTunes. Kwa kawaida maduka huripoti miezi 1–3 baada ya nyimbo kusikilizwa.",
  unknown: "Haijulikani",
  usage: {
    stream: "Usikilizaji",
    streams: "Usikilizaji",
    download: "Upakuaji",
    video: "Video",
    ugc: "Video za watumiaji (UGC)",
    other: "Mengineyo",
  },
  statementsTitle: "Ripoti",
  statementsDesc: "Ripoti za maduka zilizoweka pesa kwenye pochi yako.",
  statementsCaption: "Ripoti zilizothibitishwa",
  colSource: "Chanzo",
  colPeriod: "Kipindi",
  colPosted: "Imethibitishwa",
  period: (from: string, to: string) => `${from} – ${to}`,
  statementsEmptyTitle: "Bado hakuna ripoti",
  statementsEmptyBody:
    "Idara ya fedha ya 2kTunes ikishaingiza na kuthibitisha ripoti ya duka yenye muziki wako, itaorodheshwa hapa na pesa kuwekwa kwenye pochi yako.",
};

const FR: typeof EN = {
  title: "Royalties",
  intro: "Ce que votre musique a rapporté, par mois, plateforme, pays, sortie, titre ou relevé. Seuls les relevés publiés par le service financier de 2kTunes sont comptabilisés.",
  filtersLabel: "Filtres du rapport",
  groupBy: "Répartir par",
  by: {
    month: "Mois",
    store: "Plateforme",
    territory: "Pays",
    release: "Sortie",
    track: "Titre",
    usage: "Type d'utilisation",
    statement: "Relevé",
  },
  from: "Du",
  to: "Au",
  currency: "Devise",
  allCurrencies: "Toutes les devises",
  rangeInvalid: "La date de début doit être antérieure ou égale à la date de fin.",
  showing: (from: string, to: string) => `Du ${from} au ${to}`,
  breakdownTitle: "Répartition",
  breakdownCaption: (by: string) => `Royalties par ${by.toLowerCase()}`,
  colAmount: "Revenus",
  colUnits: "Unités",
  colLines: "Lignes du rapport",
  totalFor: (cur: string) => `Total (${cur})`,
  emptyTitle: "Pas de royalties sur cette période",
  emptyBody:
    "Les royalties apparaissent ici une fois les relevés des plateformes importés et publiés par le service financier de 2kTunes. Les plateformes déclarent généralement 1 à 3 mois après les écoutes.",
  unknown: "Inconnu",
  usage: {
    stream: "Écoutes",
    streams: "Écoutes",
    download: "Téléchargements",
    video: "Vidéo",
    ugc: "Vidéos d'utilisateurs (UGC)",
    other: "Autre",
  },
  statementsTitle: "Relevés",
  statementsDesc: "Relevés des plateformes qui ont crédité votre portefeuille.",
  statementsCaption: "Relevés publiés",
  colSource: "Source",
  colPeriod: "Période",
  colPosted: "Publié le",
  period: (from: string, to: string) => `${from} – ${to}`,
  statementsEmptyTitle: "Aucun relevé pour l'instant",
  statementsEmptyBody:
    "Dès que le service financier de 2kTunes aura importé et publié un relevé de plateforme incluant votre musique, il apparaîtra ici et sera crédité sur votre portefeuille.",
};

export const COPY = { EN, SW, FR };
export type RoyaltiesCopy = typeof EN;
