/** Screen copy for the creator workspace (/dashboard/creator). */

const EN = {
  title: "Creator workspace",
  intro: "Your creator profile, social accounts, packages and incoming orders from artists.",

  /* Start */
  startTitle: "Start your creator profile",
  startIntro:
    "Artists on 2kTunes hire creators to feature their music in content. Set up your profile, add your social accounts and at least one priced package, then submit it for review. Only approved profiles are shown to artists.",
  startCta: "Create profile",
  started: "Profile created",
  startedBody: "Next, add your social accounts and a package, then submit for review.",

  /* Status */
  statusDraft: "Your profile is a draft. Artists can't see it yet. Submit it for review when it's ready.",
  statusPending: "Your profile is being reviewed. We usually review profiles within 2 business days.",
  statusApproved: "Your profile is live. Artists can find you and send you orders.",
  statusRejected: "Your profile wasn't approved yet. Make the changes below and submit again.",
  statusSuspended: "Your profile is suspended and hidden from artists.",
  reviewNote: "Note from 2kTunes",
  submit: "Submit for review",
  submitted: "Submitted for review",
  submitNeeds: "To submit you need a bio, your country, at least one social account and at least one active package.",
  viewPublic: "View your public profile",

  /* Tabs */
  tabsLabel: "Creator workspace sections",
  tabProfile: "Profile",
  tabSocial: "Social accounts",
  tabPackages: "Packages",
  tabPortfolio: "Portfolio",
  tabOrders: "Incoming orders",

  /* Profile form */
  displayName: "Display name",
  displayNameRequired: "Enter the name artists will see.",
  bio: "Bio",
  bioHint: "What kind of content do you make, and who watches it?",
  country: "Country",
  countryHint: "Where you live and create. Type to search.",
  countryInvalid: "Choose a country from the list.",
  city: "City",
  languages: "Languages",
  languagesHint: "Tap every language you create content in (up to 10).",
  languagesInvalid: "Choose no more than 10 languages.",
  categories: "Content categories",
  categoriesHint: (max: number) => `Choose up to ${max}.`,
  categoriesMax: (max: number) => `Choose no more than ${max} categories.`,
  turnaround: "Usual turnaround (days)",
  turnaroundInvalid: "Enter a number of days from 1 to 60.",
  available: "I'm taking new orders",
  availableHint: "Turn off to stop receiving new orders without hiding your profile.",
  reviewWarning: "Changing your display name or bio sends an approved profile back to review.",
  saved: "Profile saved",

  /* Avatar */
  avatar: "Profile photo",
  avatarHint: "JPG, PNG or WebP, up to 4 MB.",
  avatarChoose: "Upload photo",
  avatarType: "Use a JPG, PNG or WebP image.",
  avatarSize: "The image must be 4 MB or smaller.",
  avatarSaved: "Photo updated",

  /* Social */
  socialIntro: (self: string, admin: string, platform: string) =>
    `Add the accounts where you post. The numbers you enter are shown to artists labelled "${self}" until 2kTunes checks them; checked accounts show "${admin}" or "${platform}".`,
  socialReset:
    "If you change the handle, followers, average views or engagement of a verified account, it goes back to self-reported until we check it again.",
  socialEmpty: "No social accounts yet.",
  addAccount: "Add account",
  removeAccount: (n: number) => `Remove account ${n}`,
  accountN: (n: number) => `Account ${n}`,
  platform: "Platform",
  choosePlatform: "Choose a platform",
  platformRequired: "Choose a platform.",
  platformDuplicate: "You can add each platform once.",
  handle: "Handle",
  handleRequired: "Enter your handle.",
  url: "Profile link",
  urlInvalid: "Enter the full link, starting with https://",
  followers: "Followers",
  avgViews: "Average views",
  engagement: "Engagement rate (%)",
  engagementInvalid: "Enter a percentage between 0 and 100, e.g. 4.5",
  wholeNumber: "Enter a whole number.",
  audience: "Audience countries",
  audienceHint: "Country code and percent, e.g. TZ 60, KE 20",
  audienceInvalid: "Use a country code and a whole percent, e.g. TZ 60, KE 20.",
  saveAccounts: "Save social accounts",
  accountsSaved: "Social accounts saved",
  maxAccounts: (n: number) => `You can add up to ${n} accounts.`,

  /* Packages */
  packagesIntro:
    "Fixed-price offers artists can order. Describe exactly what you deliver, and never promise views, streams or followers.",
  noPackages: "No packages yet. Add at least one to submit your profile.",
  addPackage: "Add package",
  editPackage: "Edit package",
  deletePackage: "Delete package",
  deleteTitle: "Delete this package?",
  deleteBody: "If artists have already ordered it, it's deactivated instead of deleted so their orders stay intact.",
  deleted: "Package removed",
  pkgTitle: "Title",
  pkgTitleRequired: "Give the package a title.",
  pkgPlatform: "Platform",
  pkgPrice: "Price",
  pkgPriceInvalid: "Enter a price greater than zero, e.g. 50000.",
  pkgCurrency: "Currency",
  pkgTurnaround: "Delivery time (days)",
  pkgDeliverable: "Deliverable",
  pkgDeliverableHint: "e.g. 1 TikTok video, 15 to 30 seconds, using the song as the sound",
  pkgDescription: "Description",
  pkgActive: "Active (artists can order it)",
  pkgSaved: "Package saved",
  inactive: "Inactive",
  days: (n: number) => (n === 1 ? "1 day" : `${n} days`),
  edit: (title: string) => `Edit ${title}`,
  remove: (title: string) => `Delete ${title}`,

  /* Portfolio */
  portfolioIntro: (max: number) => `Show up to ${max} examples of your best work. Links must start with https://`,
  portfolioEmpty: "No examples yet.",
  portfolioFull: (max: number) => `You've added the maximum of ${max} examples. Remove one to add another.`,
  addExample: "Add example",
  exUrl: "Link",
  exUrlInvalid: "Enter a full https:// link.",
  exTitle: "Title",
  exViews: "Views",
  exAdded: "Example added",
  exRemoved: "Example removed",
  removeExample: (title: string) => `Remove ${title}`,
  openExample: (title: string) => `${title} (opens in a new tab)`,
  example: "Example",

  /* Orders */
  ordersIntro: "Paid orders from artists. Open an order to accept it, message the artist or deliver your work.",
  noOrders: "No orders yet. Once your profile is approved, paid orders from artists appear here.",
  ordersCaption: "Incoming orders",
  colOrder: "Order",
  colRelease: "Release",
  colStatus: "Status",
  colPayout: "Your payout",
  colDue: "Due",
  allOrders: "View all orders",
};

const SW: typeof EN = {
  title: "Eneo la mtengeneza maudhui",
  intro: "Wasifu wako wa mtengeneza maudhui, akaunti za mitandao, vifurushi na oda zinazoingia kutoka kwa wasanii.",

  startTitle: "Anzisha wasifu wako wa mtengeneza maudhui",
  startIntro:
    "Wasanii kwenye 2kTunes huajiri watengeneza maudhui kutumia muziki wao kwenye maudhui. Andaa wasifu wako, ongeza akaunti zako za mitandao na angalau kifurushi kimoja chenye bei, kisha uwasilishe kwa ukaguzi. Wasifu ulioidhinishwa pekee ndio unaoonyeshwa kwa wasanii.",
  startCta: "Tengeneza wasifu",
  started: "Wasifu umetengenezwa",
  startedBody: "Sasa ongeza akaunti zako za mitandao na kifurushi, kisha uwasilishe kwa ukaguzi.",

  statusDraft: "Wasifu wako ni rasimu. Wasanii hawawezi kuuona bado. Uwasilishe kwa ukaguzi ukiwa tayari.",
  statusPending: "Wasifu wako unakaguliwa. Kwa kawaida tunakagua wasifu ndani ya siku 2 za kazi.",
  statusApproved: "Wasifu wako uko hewani. Wasanii wanaweza kukupata na kukutumia oda.",
  statusRejected: "Wasifu wako bado haujaidhinishwa. Fanya mabadiliko hapa chini kisha uwasilishe tena.",
  statusSuspended: "Wasifu wako umesimamishwa na umefichwa kwa wasanii.",
  reviewNote: "Ujumbe kutoka 2kTunes",
  submit: "Wasilisha kwa ukaguzi",
  submitted: "Umewasilishwa kwa ukaguzi",
  submitNeeds:
    "Ili kuwasilisha unahitaji maelezo yako, nchi yako, angalau akaunti moja ya mtandao na angalau kifurushi kimoja kinachopatikana.",
  viewPublic: "Tazama wasifu wako wa umma",

  tabsLabel: "Sehemu za eneo la mtengeneza maudhui",
  tabProfile: "Wasifu",
  tabSocial: "Akaunti za mitandao",
  tabPackages: "Vifurushi",
  tabPortfolio: "Kazi za mfano",
  tabOrders: "Oda zinazoingia",

  displayName: "Jina la kuonyeshwa",
  displayNameRequired: "Weka jina ambalo wasanii wataona.",
  bio: "Maelezo kukuhusu",
  bioHint: "Unatengeneza maudhui ya aina gani, na nani huyatazama?",
  country: "Nchi",
  countryHint: "Unapoishi na kutengeneza maudhui. Andika kutafuta.",
  countryInvalid: "Chagua nchi kutoka kwenye orodha.",
  city: "Mji",
  languages: "Lugha",
  languagesHint: "Gusa kila lugha unayotumia kutengeneza maudhui (hadi 10).",
  languagesInvalid: "Chagua lugha zisizozidi 10.",
  categories: "Makundi ya maudhui",
  categoriesHint: (max) => `Chagua hadi ${max}.`,
  categoriesMax: (max) => `Usichague zaidi ya makundi ${max}.`,
  turnaround: "Muda wa kawaida wa kukamilisha (siku)",
  turnaroundInvalid: "Weka idadi ya siku kuanzia 1 hadi 60.",
  available: "Ninapokea oda mpya",
  availableHint: "Zima ili usipokee oda mpya bila kuficha wasifu wako.",
  reviewWarning: "Kubadilisha jina la kuonyeshwa au maelezo kunarudisha wasifu ulioidhinishwa kwenye ukaguzi.",
  saved: "Wasifu umehifadhiwa",

  avatar: "Picha ya wasifu",
  avatarHint: "JPG, PNG au WebP, hadi MB 4.",
  avatarChoose: "Pakia picha",
  avatarType: "Tumia picha ya JPG, PNG au WebP.",
  avatarSize: "Picha isizidi MB 4.",
  avatarSaved: "Picha imesasishwa",

  socialIntro: (self, admin, platform) =>
    `Ongeza akaunti unazochapisha. Takwimu unazoweka zinaonyeshwa kwa wasanii zikiwa na alama "${self}" hadi 2kTunes izikague; akaunti zilizokaguliwa zinaonyesha "${admin}" au "${platform}".`,
  socialReset:
    "Ukibadilisha jina la akaunti, wafuasi, wastani wa watazamaji au kiwango cha mwingiliano cha akaunti iliyothibitishwa, inarudi kuwa imeripotiwa na mhusika hadi tuikague tena.",
  socialEmpty: "Bado hakuna akaunti za mitandao.",
  addAccount: "Ongeza akaunti",
  removeAccount: (n) => `Ondoa akaunti ${n}`,
  accountN: (n) => `Akaunti ${n}`,
  platform: "Jukwaa",
  choosePlatform: "Chagua jukwaa",
  platformRequired: "Chagua jukwaa.",
  platformDuplicate: "Unaweza kuongeza kila jukwaa mara moja tu.",
  handle: "Jina la akaunti",
  handleRequired: "Weka jina la akaunti yako.",
  url: "Kiungo cha wasifu",
  urlInvalid: "Weka kiungo kamili, kinachoanza na https://",
  followers: "Wafuasi",
  avgViews: "Wastani wa watazamaji",
  engagement: "Kiwango cha mwingiliano (%)",
  engagementInvalid: "Weka asilimia kati ya 0 na 100, mf. 4.5",
  wholeNumber: "Weka namba kamili.",
  audience: "Nchi za hadhira",
  audienceHint: "Msimbo wa nchi na asilimia, mf. TZ 60, KE 20",
  audienceInvalid: "Tumia msimbo wa nchi na asilimia kamili, mf. TZ 60, KE 20.",
  saveAccounts: "Hifadhi akaunti za mitandao",
  accountsSaved: "Akaunti za mitandao zimehifadhiwa",
  maxAccounts: (n) => `Unaweza kuongeza hadi akaunti ${n}.`,

  packagesIntro:
    "Ofa za bei maalum ambazo wasanii wanaweza kuagiza. Eleza wazi utakachowasilisha, na usiahidi kamwe watazamaji, streams au wafuasi.",
  noPackages: "Bado hakuna vifurushi. Ongeza angalau kimoja ili uwasilishe wasifu wako.",
  addPackage: "Ongeza kifurushi",
  editPackage: "Hariri kifurushi",
  deletePackage: "Futa kifurushi",
  deleteTitle: "Ufute kifurushi hiki?",
  deleteBody:
    "Kama wasanii wameshakiagiza, kitazimwa badala ya kufutwa ili oda zao zibaki salama.",
  deleted: "Kifurushi kimeondolewa",
  pkgTitle: "Jina",
  pkgTitleRequired: "Kipe kifurushi jina.",
  pkgPlatform: "Jukwaa",
  pkgPrice: "Bei",
  pkgPriceInvalid: "Weka bei iliyo zaidi ya sifuri, mf. 50000.",
  pkgCurrency: "Sarafu",
  pkgTurnaround: "Muda wa kuwasilisha (siku)",
  pkgDeliverable: "Utakachowasilisha",
  pkgDeliverableHint: "mf. Video 1 ya TikTok, sekunde 15 hadi 30, ikitumia wimbo kama sauti",
  pkgDescription: "Maelezo",
  pkgActive: "Kinapatikana (wasanii wanaweza kukiagiza)",
  pkgSaved: "Kifurushi kimehifadhiwa",
  inactive: "Hakipatikani",
  days: (n) => (n === 1 ? "Siku 1" : `Siku ${n}`),
  edit: (title) => `Hariri ${title}`,
  remove: (title) => `Futa ${title}`,

  portfolioIntro: (max) => `Onyesha hadi mifano ${max} ya kazi zako bora. Viungo vianze na https://`,
  portfolioEmpty: "Bado hakuna mifano.",
  portfolioFull: (max) => `Umefikia kikomo cha mifano ${max}. Ondoa mmoja ili uongeze mwingine.`,
  addExample: "Ongeza mfano",
  exUrl: "Kiungo",
  exUrlInvalid: "Weka kiungo kamili cha https://",
  exTitle: "Jina",
  exViews: "Watazamaji",
  exAdded: "Mfano umeongezwa",
  exRemoved: "Mfano umeondolewa",
  removeExample: (title) => `Ondoa ${title}`,
  openExample: (title) => `${title} (inafunguka kichupo kipya)`,
  example: "Mfano",

  ordersIntro:
    "Oda zilizolipiwa kutoka kwa wasanii. Fungua oda ili uikubali, umtumie msanii ujumbe au uwasilishe kazi yako.",
  noOrders: "Bado hakuna oda. Wasifu wako ukishaidhinishwa, oda zilizolipiwa kutoka kwa wasanii zitaonekana hapa.",
  ordersCaption: "Oda zinazoingia",
  colOrder: "Oda",
  colRelease: "Toleo",
  colStatus: "Hali",
  colPayout: "Malipo yako",
  colDue: "Mwisho",
  allOrders: "Tazama oda zote",
};

const FR: typeof EN = {
  title: "Espace créateur",
  intro: "Votre profil de créateur, vos réseaux sociaux, vos offres et les commandes reçues des artistes.",

  /* Start */
  startTitle: "Créez votre profil de créateur",
  startIntro:
    "Sur 2kTunes, les artistes font appel à des créateurs de contenu pour mettre leur musique en avant. Configurez votre profil, ajoutez vos réseaux sociaux et au moins une offre tarifée, puis soumettez-le pour validation. Seuls les profils approuvés sont visibles par les artistes.",
  startCta: "Créer mon profil",
  started: "Profil créé",
  startedBody: "Ajoutez maintenant vos réseaux sociaux et une offre, puis soumettez votre profil pour validation.",

  /* Status */
  statusDraft:
    "Votre profil est un brouillon, encore invisible pour les artistes. Soumettez-le pour validation quand il est prêt.",
  statusPending: "Votre profil est en cours de validation. Nous examinons généralement les profils sous 2 jours ouvrés.",
  statusApproved: "Votre profil est en ligne. Les artistes peuvent vous trouver et vous passer commande.",
  statusRejected: "Votre profil n'a pas encore été approuvé. Apportez les modifications ci-dessous et soumettez-le à nouveau.",
  statusSuspended: "Votre profil est suspendu et masqué aux artistes.",
  reviewNote: "Note de 2kTunes",
  submit: "Soumettre",
  submitted: "Soumis pour validation",
  submitNeeds:
    "Pour soumettre votre profil, il faut une bio, votre pays, au moins un compte social et au moins une offre active.",
  viewPublic: "Voir votre profil public",

  /* Tabs */
  tabsLabel: "Sections de l'espace créateur",
  tabProfile: "Profil",
  tabSocial: "Réseaux",
  tabPackages: "Offres",
  tabPortfolio: "Portfolio",
  tabOrders: "Commandes reçues",

  /* Profile form */
  displayName: "Nom affiché",
  displayNameRequired: "Saisissez le nom que verront les artistes.",
  bio: "Bio",
  bioHint: "Quel type de contenu créez-vous, et qui le regarde ?",
  country: "Pays",
  countryHint: "Là où vous vivez et créez. Tapez pour rechercher.",
  countryInvalid: "Choisissez un pays dans la liste.",
  city: "Ville",
  languages: "Langues",
  languagesHint: "Touchez chaque langue dans laquelle vous créez (10 maximum).",
  languagesInvalid: "Choisissez 10 langues au maximum.",
  categories: "Catégories de contenu",
  categoriesHint: (max: number) => `Jusqu'à ${max} au choix.`,
  categoriesMax: (max: number) =>
    max <= 1 ? `Choisissez au maximum ${max} catégorie.` : `Choisissez au maximum ${max} catégories.`,
  turnaround: "Délai habituel (jours)",
  turnaroundInvalid: "Saisissez un nombre de jours entre 1 et 60.",
  available: "J'accepte de nouvelles commandes",
  availableHint: "Désactivez pour ne plus recevoir de commandes sans masquer votre profil.",
  reviewWarning: "Modifier le nom affiché ou la bio d'un profil approuvé le renvoie en validation.",
  saved: "Profil enregistré",

  /* Avatar */
  avatar: "Photo de profil",
  avatarHint: "JPG, PNG ou WebP, 4 Mo max.",
  avatarChoose: "Importer une photo",
  avatarType: "Utilisez une image JPG, PNG ou WebP.",
  avatarSize: "L'image ne doit pas dépasser 4 Mo.",
  avatarSaved: "Photo mise à jour",

  /* Social */
  socialIntro: (self: string, admin: string, platform: string) =>
    `Ajoutez les comptes sur lesquels vous publiez. Les chiffres saisis sont affichés aux artistes avec la mention « ${self} » jusqu'à leur vérification par 2kTunes ; les comptes vérifiés affichent « ${admin} » ou « ${platform} ».`,
  socialReset:
    "Si vous modifiez l'identifiant, les abonnés, les vues moyennes ou l'engagement d'un compte vérifié, il repasse en « déclaré » jusqu'à une nouvelle vérification.",
  socialEmpty: "Aucun compte social pour l'instant.",
  addAccount: "Ajouter un compte",
  removeAccount: (n: number) => `Supprimer le compte ${n}`,
  accountN: (n: number) => `Compte ${n}`,
  platform: "Plateforme",
  choosePlatform: "Choisir une plateforme",
  platformRequired: "Choisissez une plateforme.",
  platformDuplicate: "Chaque plateforme ne peut être ajoutée qu'une fois.",
  handle: "Identifiant",
  handleRequired: "Saisissez votre identifiant.",
  url: "Lien du profil",
  urlInvalid: "Saisissez le lien complet, commençant par https://",
  followers: "Abonnés",
  avgViews: "Vues moyennes",
  engagement: "Taux d'engagement (%)",
  engagementInvalid: "Saisissez un pourcentage entre 0 et 100, ex. 4.5",
  wholeNumber: "Saisissez un nombre entier.",
  audience: "Pays de l'audience",
  audienceHint: "Code pays et pourcentage, ex. CI 60, SN 20",
  audienceInvalid: "Saisissez un code pays et un pourcentage entier, ex. CI 60, SN 20.",
  saveAccounts: "Enregistrer les comptes",
  accountsSaved: "Comptes sociaux enregistrés",
  maxAccounts: (n: number) => `Vous pouvez ajouter jusqu'à ${n} comptes.`,

  /* Packages */
  packagesIntro:
    "Des offres à prix fixe que les artistes peuvent commander. Décrivez précisément ce que vous livrez, et ne promettez jamais de vues, de streams ni d'abonnés.",
  noPackages: "Aucune offre pour l'instant. Ajoutez-en au moins une pour soumettre votre profil.",
  addPackage: "Ajouter une offre",
  editPackage: "Modifier l'offre",
  deletePackage: "Supprimer l'offre",
  deleteTitle: "Supprimer cette offre ?",
  deleteBody:
    "Si des artistes l'ont déjà commandée, elle est désactivée plutôt que supprimée afin de préserver leurs commandes.",
  deleted: "Offre supprimée",
  pkgTitle: "Titre",
  pkgTitleRequired: "Donnez un titre à l'offre.",
  pkgPlatform: "Plateforme",
  pkgPrice: "Prix",
  pkgPriceInvalid: "Saisissez un prix supérieur à zéro, ex. 50000.",
  pkgCurrency: "Devise",
  pkgTurnaround: "Délai de livraison (jours)",
  pkgDeliverable: "Livrable",
  pkgDeliverableHint: "ex. 1 vidéo TikTok de 15 à 30 secondes, avec le morceau en son",
  pkgDescription: "Description",
  pkgActive: "Active (les artistes peuvent la commander)",
  pkgSaved: "Offre enregistrée",
  inactive: "Inactive",
  days: (n: number) => (n <= 1 ? `${n} jour` : `${n} jours`),
  edit: (title: string) => `Modifier ${title}`,
  remove: (title: string) => `Supprimer ${title}`,

  /* Portfolio */
  portfolioIntro: (max: number) =>
    `Présentez jusqu'à ${max} exemples de vos meilleurs contenus. Les liens doivent commencer par https://`,
  portfolioEmpty: "Aucun exemple pour l'instant.",
  portfolioFull: (max: number) =>
    `Vous avez atteint le maximum de ${max} exemples. Supprimez-en un pour en ajouter un autre.`,
  addExample: "Ajouter un exemple",
  exUrl: "Lien",
  exUrlInvalid: "Saisissez un lien https:// complet.",
  exTitle: "Titre",
  exViews: "Vues",
  exAdded: "Exemple ajouté",
  exRemoved: "Exemple supprimé",
  removeExample: (title: string) => `Supprimer ${title}`,
  openExample: (title: string) => `${title} (nouvel onglet)`,
  example: "Exemple",

  /* Orders */
  ordersIntro:
    "Commandes payées par les artistes. Ouvrez une commande pour l'accepter, écrire à l'artiste ou livrer votre travail.",
  noOrders: "Aucune commande pour l'instant. Une fois votre profil approuvé, les commandes payées des artistes apparaîtront ici.",
  ordersCaption: "Commandes reçues",
  colOrder: "Commande",
  colRelease: "Sortie",
  colStatus: "Statut",
  colPayout: "Votre gain",
  colDue: "Échéance",
  allOrders: "Voir toutes les commandes",
};

export const COPY = { EN, SW, FR };
