/**
 * Creator workspace copy for the request flow: incoming requests, work in
 * progress, earnings, the portfolio manager and the required profile photo.
 * No dashes in user-facing text.
 */
const EN = {
  tabRequests: "Requests",
  tabActive: "In progress",
  tabEarnings: "Earnings",

  /* Photo step */
  photoStepTitle: "Step 1: add your profile photo",
  photoStepBody: "Artists see your photo first. Use a clear photo of your face. We crop it to a square, so keep your face in the centre.",
  photoRequired: "Add a profile photo before you submit for review.",
  photoPreview: "Profile photo preview",
  photoChoose: "Choose a photo",
  photoChange: "Change photo",
  photoHint: "JPG, PNG or WebP, up to 4 MB. Square works best.",
  photoMissing: "Photo required",

  /* Incoming requests */
  incomingIntro: "2kTunes reviews every request before sending it to you. Listen to the song, then accept or decline within 3 days.",
  incomingEmpty: "No new requests. Requests appear here after 2kTunes reviews them.",
  from: (name: string) => `From ${name}`,
  listen: "Listen",
  openSong: "Open the song",
  loadingAudio: "Loading the song…",
  noAudio: "No audio to preview. Open the request for details.",
  openRequest: "Open request",
  youEarn: "You earn",
  postBy: (d: string) => `Preferred post date: ${d}`,

  /* In progress */
  activeIntro: "Paid orders are held by 2kTunes. Post the content, then submit the link. You are paid after 2kTunes verifies it.",
  activeEmpty: "Nothing in progress right now.",
  waitingPay: "Accepted. Waiting for the artist to pay.",
  waitingVerify: "Submitted. 2kTunes is verifying your post.",
  inDispute: "In dispute. 2kTunes is reviewing it.",
  fixNote: "Fix requested",
  due: (d: string) => `Due ${d}`,

  /* Earnings */
  earningsIntro: "Your share of each order, after the platform fee.",
  pending: "Pending",
  pendingHint: "Held by 2kTunes for paid orders. Not withdrawable yet: it moves to your wallet when 2kTunes verifies your post.",
  pendingOrders: (n: number) => (n === 1 ? "1 order" : `${n} orders`),
  available: "Available",
  availableHint: "In your wallet. You can withdraw it.",
  lifetime: "Earned so far",
  notWithdrawable: "Not withdrawable",
  feeNote: (pct: string) => `2kTunes keeps a ${pct} platform fee on each order. Amounts shown are your share.`,
  noEarnings: "No earnings yet. Accept a request to get started.",
  toWallet: "Go to wallet",

  /* Portfolio manager */
  portfolioIntro: (max: number) =>
    `Show your best work, up to ${max} items. Upload a short video or add a link. 2kTunes may feature videos on the home page.`,
  addTitle: "Add to your portfolio",
  modeLabel: "What are you adding?",
  modeUpload: "Upload a video",
  modeUploadHint: "MP4 or WebM, up to 50 MB",
  modeLink: "Add a link",
  modeLinkHint: "TikTok, Instagram or YouTube",
  video: "Video file",
  videoChoose: "Choose a video",
  videoChange: "Change video",
  videoHint: "Short vertical videos (9:16) look best.",
  videoRequired: "Choose a video file.",
  videoType: "Use an MP4 or WebM video.",
  videoSize: "The video must be 50 MB or smaller.",
  link: "Link",
  linkHint: "The full link to the post.",
  linkInvalid: "Enter the full link, starting with https://",
  detected: (p: string) => `Detected: ${p}`,
  thumbnail: "Thumbnail",
  thumbnailHint: "JPG, PNG or WebP, up to 4 MB.",
  thumbnailType: "Use a JPG, PNG or WebP image.",
  thumbnailSize: "The image must be 4 MB or smaller.",
  thumbnailChoose: "Choose an image",
  caption: "Caption",
  views: "Views",
  viewsHint: "Self-reported. Shown with that label.",
  wholeNumber: "Enter a whole number.",
  uploading: (pct: number) => `Uploading ${pct}%`,
  add: "Add to portfolio",
  added: "Added to your portfolio",
  removed: "Removed",
  remove: (t: string) => `Remove ${t}`,
  removeTitle: "Remove this item?",
  full: (max: number) => `You have ${max} items, the maximum. Remove one to add another.`,
  empty: "Nothing here yet. Your first video is the best way to win requests.",
  selfReported: (n: string) => `${n} views, self-reported`,
  featured: "On the home page",
  item: "Portfolio item",
  uploadedVideo: "Uploaded video",
};

export type WorkCopy = typeof EN;

const SW: WorkCopy = {
  tabRequests: "Maombi",
  tabActive: "Yanayoendelea",
  tabEarnings: "Mapato",

  photoStepTitle: "Hatua ya 1: weka picha yako ya wasifu",
  photoStepBody: "Wasanii wanaona picha yako kwanza. Tumia picha safi ya uso wako. Tunaikata iwe mraba, kwa hiyo weka uso katikati.",
  photoRequired: "Weka picha ya wasifu kabla ya kutuma kwa ukaguzi.",
  photoPreview: "Muonekano wa picha ya wasifu",
  photoChoose: "Chagua picha",
  photoChange: "Badilisha picha",
  photoHint: "JPG, PNG au WebP, hadi MB 4. Picha ya mraba ni bora.",
  photoMissing: "Picha inahitajika",

  incomingIntro: "2kTunes inakagua kila ombi kabla ya kukutumia. Sikiliza wimbo, kisha kubali au kataa ndani ya siku 3.",
  incomingEmpty: "Hakuna maombi mapya. Maombi yanaonekana hapa baada ya 2kTunes kuyakagua.",
  from: (name) => `Kutoka kwa ${name}`,
  listen: "Sikiliza",
  openSong: "Fungua wimbo",
  loadingAudio: "Inapakia wimbo…",
  noAudio: "Hakuna sauti ya kusikiliza. Fungua ombi kwa maelezo.",
  openRequest: "Fungua ombi",
  youEarn: "Utapata",
  postBy: (d) => `Tarehe inayopendekezwa: ${d}`,

  activeIntro: "Oda zilizolipwa zinashikiliwa na 2kTunes. Chapisha maudhui, kisha wasilisha kiungo. Unalipwa baada ya 2kTunes kuthibitisha.",
  activeEmpty: "Hakuna kinachoendelea kwa sasa.",
  waitingPay: "Umekubali. Inasubiri msanii alipe.",
  waitingVerify: "Umewasilisha. 2kTunes inathibitisha chapisho lako.",
  inDispute: "Lina mgogoro. 2kTunes inalikagua.",
  fixNote: "Marekebisho yameombwa",
  due: (d) => `Mwisho ${d}`,

  earningsIntro: "Sehemu yako ya kila oda, baada ya ada ya jukwaa.",
  pending: "Yanasubiri",
  pendingHint: "Yanashikiliwa na 2kTunes kwa oda zilizolipwa. Bado hayatoleki: yanaingia kwenye pochi yako 2kTunes ikithibitisha chapisho.",
  pendingOrders: (n) => (n === 1 ? "Oda 1" : `Oda ${n}`),
  available: "Yanayopatikana",
  availableHint: "Yako kwenye pochi yako. Unaweza kuyatoa.",
  lifetime: "Uliyopata hadi sasa",
  notWithdrawable: "Hayatoleki bado",
  feeNote: (pct) => `2kTunes inachukua ada ya jukwaa ya ${pct} kwa kila oda. Kiasi kinachoonyeshwa ni sehemu yako.`,
  noEarnings: "Bado hakuna mapato. Kubali ombi ili uanze.",
  toWallet: "Nenda kwenye pochi",

  portfolioIntro: (max) =>
    `Onyesha kazi zako bora, hadi vitu ${max}. Pakia video fupi au weka kiungo. 2kTunes inaweza kuonyesha video kwenye ukurasa wa mwanzo.`,
  addTitle: "Ongeza kwenye kazi zako",
  modeLabel: "Unaongeza nini?",
  modeUpload: "Pakia video",
  modeUploadHint: "MP4 au WebM, hadi MB 50",
  modeLink: "Weka kiungo",
  modeLinkHint: "TikTok, Instagram au YouTube",
  video: "Faili la video",
  videoChoose: "Chagua video",
  videoChange: "Badilisha video",
  videoHint: "Video fupi za wima (9:16) zinapendeza zaidi.",
  videoRequired: "Chagua faili la video.",
  videoType: "Tumia video ya MP4 au WebM.",
  videoSize: "Video isizidi MB 50.",
  link: "Kiungo",
  linkHint: "Kiungo kamili cha chapisho.",
  linkInvalid: "Weka kiungo kamili kinachoanza na https://",
  detected: (p) => `Imetambuliwa: ${p}`,
  thumbnail: "Picha ndogo",
  thumbnailHint: "JPG, PNG au WebP, hadi MB 4.",
  thumbnailType: "Tumia picha ya JPG, PNG au WebP.",
  thumbnailSize: "Picha isizidi MB 4.",
  thumbnailChoose: "Chagua picha",
  caption: "Maelezo",
  views: "Watazamaji",
  viewsHint: "Kwa kauli yako. Huonyeshwa hivyo.",
  wholeNumber: "Weka namba kamili.",
  uploading: (pct) => `Inapakia ${pct}%`,
  add: "Ongeza",
  added: "Imeongezwa kwenye kazi zako",
  removed: "Imeondolewa",
  remove: (t) => `Ondoa ${t}`,
  removeTitle: "Uondoe kitu hiki?",
  full: (max) => `Una vitu ${max}, kiwango cha juu. Ondoa kimoja ili kuongeza kingine.`,
  empty: "Bado hakuna kitu. Video yako ya kwanza ndiyo njia bora ya kupata maombi.",
  selfReported: (n) => `Watazamaji ${n}, kwa kauli yako`,
  featured: "Kwenye ukurasa wa mwanzo",
  item: "Kazi",
  uploadedVideo: "Video iliyopakiwa",
};

const FR: WorkCopy = {
  tabRequests: "Demandes",
  tabActive: "En cours",
  tabEarnings: "Revenus",

  photoStepTitle: "Étape 1 : ajoutez votre photo de profil",
  photoStepBody: "Les artistes voient votre photo en premier. Utilisez une photo nette de votre visage. Nous la recadrons en carré : gardez le visage au centre.",
  photoRequired: "Ajoutez une photo de profil avant d’envoyer pour vérification.",
  photoPreview: "Aperçu de la photo de profil",
  photoChoose: "Choisir une photo",
  photoChange: "Changer la photo",
  photoHint: "JPG, PNG ou WebP, jusqu’à 4 Mo. Le format carré est idéal.",
  photoMissing: "Photo requise",

  incomingIntro: "2kTunes vérifie chaque demande avant de vous l’envoyer. Écoutez le titre, puis acceptez ou refusez sous 3 jours.",
  incomingEmpty: "Aucune nouvelle demande. Elles apparaissent ici après vérification par 2kTunes.",
  from: (name) => `De ${name}`,
  listen: "Écouter",
  openSong: "Ouvrir le titre",
  loadingAudio: "Chargement du titre…",
  noAudio: "Pas d’extrait audio. Ouvrez la demande pour les détails.",
  openRequest: "Ouvrir la demande",
  youEarn: "Vous gagnez",
  postBy: (d) => `Date de publication souhaitée : ${d}`,

  activeIntro: "Les commandes payées sont conservées par 2kTunes. Publiez, puis envoyez le lien. Vous êtes payé après vérification par 2kTunes.",
  activeEmpty: "Rien en cours pour le moment.",
  waitingPay: "Acceptée. En attente du paiement de l’artiste.",
  waitingVerify: "Envoyée. 2kTunes vérifie votre publication.",
  inDispute: "En litige. 2kTunes l’examine.",
  fixNote: "Correction demandée",
  due: (d) => `Échéance ${d}`,

  earningsIntro: "Votre part de chaque commande, après les frais de plateforme.",
  pending: "En attente",
  pendingHint: "Conservé par 2kTunes pour les commandes payées. Pas encore retirable : arrive sur votre portefeuille quand 2kTunes vérifie votre publication.",
  pendingOrders: (n) => (n === 1 ? "1 commande" : `${n} commandes`),
  available: "Disponible",
  availableHint: "Sur votre portefeuille. Vous pouvez le retirer.",
  lifetime: "Gagné jusqu’ici",
  notWithdrawable: "Non retirable",
  feeNote: (pct) => `2kTunes prélève ${pct} de frais de plateforme par commande. Les montants affichés sont votre part.`,
  noEarnings: "Pas encore de revenus. Acceptez une demande pour commencer.",
  toWallet: "Aller au portefeuille",

  portfolioIntro: (max) =>
    `Montrez votre meilleur travail, jusqu’à ${max} éléments. Envoyez une courte vidéo ou ajoutez un lien. 2kTunes peut mettre des vidéos en avant sur l’accueil.`,
  addTitle: "Ajouter au portfolio",
  modeLabel: "Que voulez-vous ajouter ?",
  modeUpload: "Envoyer une vidéo",
  modeUploadHint: "MP4 ou WebM, jusqu’à 50 Mo",
  modeLink: "Ajouter un lien",
  modeLinkHint: "TikTok, Instagram ou YouTube",
  video: "Fichier vidéo",
  videoChoose: "Choisir une vidéo",
  videoChange: "Changer la vidéo",
  videoHint: "Les vidéos verticales courtes (9:16) rendent le mieux.",
  videoRequired: "Choisissez un fichier vidéo.",
  videoType: "Utilisez une vidéo MP4 ou WebM.",
  videoSize: "La vidéo doit faire 50 Mo au maximum.",
  link: "Lien",
  linkHint: "Le lien complet de la publication.",
  linkInvalid: "Saisissez le lien complet, commençant par https://",
  detected: (p) => `Détecté : ${p}`,
  thumbnail: "Miniature",
  thumbnailHint: "JPG, PNG ou WebP, jusqu’à 4 Mo.",
  thumbnailType: "Utilisez une image JPG, PNG ou WebP.",
  thumbnailSize: "L’image doit faire 4 Mo au maximum.",
  thumbnailChoose: "Choisir une image",
  caption: "Légende",
  views: "Vues",
  viewsHint: "Déclarées par vous. Affichées avec cette mention.",
  wholeNumber: "Saisissez un nombre entier.",
  uploading: (pct) => `Envoi ${pct} %`,
  add: "Ajouter",
  added: "Ajouté au portfolio",
  removed: "Retiré",
  remove: (t) => `Retirer ${t}`,
  removeTitle: "Retirer cet élément ?",
  full: (max) => `Vous avez ${max} éléments, le maximum. Retirez-en un pour en ajouter.`,
  empty: "Rien pour l’instant. Votre première vidéo est le meilleur moyen d’obtenir des demandes.",
  selfReported: (n) => `${n} vues, déclarées`,
  featured: "Sur l’accueil",
  item: "Élément du portfolio",
  uploadedVideo: "Vidéo envoyée",
};

export const WORK_COPY = { EN, SW, FR };
