/** Copy for /dashboard/support and /dashboard/help. */

const EN = {
  title: "Support",
  description: "Ask our team about releases, royalties, withdrawals or your account. We reply by email and here.",
  newTicket: "New ticket",
  helpLink: "Browse help articles",
  ticketsCaption: "Your support tickets",
  colReference: "Reference",
  colSubject: "Subject",
  colCategory: "Topic",
  colStatus: "Status",
  colActivity: "Last activity",
  emptyTitle: "No tickets yet",
  emptyBody: "If something isn't working, open a ticket and our team will help.",

  formTitle: "New support ticket",
  formDescription: "Tell us what happened and what you expected. The more detail, the faster we can help.",
  category: "Topic",
  categoryPlaceholder: "Choose a topic",
  categoryRequired: "Choose a topic.",
  subject: "Subject",
  subjectRequired: "Enter a subject.",
  body: "Message",
  bodyHint: "At least 10 characters.",
  bodyShort: "Write at least 10 characters.",
  release: "Related release",
  releaseNone: "None",
  attachment: "Attachment",
  attachmentHint: "JPG, PNG, PDF, TXT or CSV, up to 10 MB.",
  attachmentType: "Attach a JPG, PNG, PDF, TXT or CSV file.",
  attachmentSize: "That file is larger than 10 MB.",
  removeAttachment: "Remove attachment",
  submit: "Send ticket",
  created: "Ticket sent",
  createdBody: (ref: string) => `Reference ${ref}. We'll reply here and by email.`,
  cancel: "Cancel",

  back: "Support",
  ticketRef: (ref: string) => `Ticket ${ref}`,
  opened: (date: string) => `Opened ${date}`,
  threadLabel: "Conversation",
  you: "You",
  staff: "2kTunes support",
  attached: "Attachment",
  replyTitle: "Reply",
  replyLabel: "Your reply",
  replyRequired: "Write a reply.",
  sendReply: "Send reply",
  replySent: "Reply sent",
  closeTicket: "Close ticket",
  closeTitle: "Close this ticket?",
  closeBody: "Close it if your question is answered. You won't be able to reply afterwards, but you can always open a new ticket.",
  closed: "Ticket closed",
  closedNote: "This ticket is closed, so replies are turned off. If you still need help, open a new ticket.",
  openNew: "Open a new ticket",
  notFound: "This ticket doesn't exist or isn't yours.",
  noMessages: "No messages yet.",

  categories: {
    release: "Releases",
    royalties: "Royalties",
    payouts: "Withdrawals & payouts",
    account: "Account",
    marketplace: "Marketplace",
    technical: "Technical problem",
    other: "Something else",
  } as Record<string, string>,

  helpTitle: "Help articles",
  helpDescription: "Guides for releasing music, getting paid and managing your account.",
  search: "Search help articles",
  searchPlaceholder: "e.g. artwork, M-Pesa, ISRC",
  filterLabel: "Filter by topic",
  all: "All",
  helpEmptyTitle: "No articles found",
  helpEmptyBody: "Try different words, or ask our team directly.",
  helpEmptyNone: "There are no help articles in this language yet.",
  resultCount: (n: number) => (n === 1 ? "1 article" : `${n} articles`),
  stillNeedHelp: "Still need help?",
  stillNeedHelpBody: "Our team answers every ticket, usually within one business day.",
  openTicket: "Open a ticket",
  backToHelp: "Help articles",
  updated: (date: string) => `Updated ${date}`,
  helpCategories: {
    "getting-started": "Getting started",
    releases: "Releases",
    royalties: "Royalties",
    payouts: "Payouts",
    account: "Account",
    promotion: "Promotion",
  } as Record<string, string>,
};

const SW: typeof EN = {
  title: "Msaada",
  description: "Uliza timu yetu kuhusu kazi, mirabaha, utoaji wa fedha au akaunti yako. Tunajibu kwa barua pepe na hapa.",
  newTicket: "Tiketi mpya",
  helpLink: "Soma makala za msaada",
  ticketsCaption: "Tiketi zako za msaada",
  colReference: "Namba ya kumbukumbu",
  colSubject: "Kichwa",
  colCategory: "Mada",
  colStatus: "Hali",
  colActivity: "Shughuli ya mwisho",
  emptyTitle: "Bado huna tiketi",
  emptyBody: "Kama kuna kitu hakifanyi kazi, fungua tiketi na timu yetu itakusaidia.",

  formTitle: "Tiketi mpya ya msaada",
  formDescription: "Tueleze kilichotokea na ulichotarajia. Maelezo zaidi yanatusaidia kukusaidia haraka.",
  category: "Mada",
  categoryPlaceholder: "Chagua mada",
  categoryRequired: "Chagua mada.",
  subject: "Kichwa",
  subjectRequired: "Weka kichwa.",
  body: "Ujumbe",
  bodyHint: "Angalau herufi 10.",
  bodyShort: "Andika angalau herufi 10.",
  release: "Kazi inayohusika",
  releaseNone: "Hakuna",
  attachment: "Kiambatisho",
  attachmentHint: "JPG, PNG, PDF, TXT au CSV, hadi MB 10.",
  attachmentType: "Ambatisha faili ya JPG, PNG, PDF, TXT au CSV.",
  attachmentSize: "Faili hiyo ni kubwa kuliko MB 10.",
  removeAttachment: "Ondoa kiambatisho",
  submit: "Tuma tiketi",
  created: "Tiketi imetumwa",
  createdBody: (ref) => `Namba ya kumbukumbu ${ref}. Tutajibu hapa na kwa barua pepe.`,
  cancel: "Ghairi",

  back: "Msaada",
  ticketRef: (ref) => `Tiketi ${ref}`,
  opened: (date) => `Ilifunguliwa ${date}`,
  threadLabel: "Mazungumzo",
  you: "Wewe",
  staff: "Msaada wa 2kTunes",
  attached: "Kiambatisho",
  replyTitle: "Jibu",
  replyLabel: "Jibu lako",
  replyRequired: "Andika jibu.",
  sendReply: "Tuma jibu",
  replySent: "Jibu limetumwa",
  closeTicket: "Funga tiketi",
  closeTitle: "Ufunge tiketi hii?",
  closeBody: "Ifunge kama swali lako limejibiwa. Hutaweza kujibu tena, lakini unaweza kufungua tiketi mpya wakati wowote.",
  closed: "Tiketi imefungwa",
  closedNote: "Tiketi hii imefungwa, kwa hivyo huwezi kujibu tena. Kama bado unahitaji msaada, fungua tiketi mpya.",
  openNew: "Fungua tiketi mpya",
  notFound: "Tiketi hii haipo au si yako.",
  noMessages: "Bado hakuna ujumbe.",

  categories: {
    release: "Kazi za muziki",
    royalties: "Mirabaha",
    payouts: "Utoaji wa fedha na malipo",
    account: "Akaunti",
    marketplace: "Soko",
    technical: "Tatizo la kiufundi",
    other: "Jambo jingine",
  },

  helpTitle: "Makala za msaada",
  helpDescription: "Miongozo ya kutoa muziki, kulipwa na kusimamia akaunti yako.",
  search: "Tafuta makala za msaada",
  searchPlaceholder: "mfano: jalada, M-Pesa, ISRC",
  filterLabel: "Chuja kwa mada",
  all: "Zote",
  helpEmptyTitle: "Hakuna makala zilizopatikana",
  helpEmptyBody: "Jaribu maneno mengine, au uliza timu yetu moja kwa moja.",
  helpEmptyNone: "Bado hakuna makala za msaada kwa lugha hii.",
  resultCount: (n) => (n === 1 ? "Makala 1" : `Makala ${n}`),
  stillNeedHelp: "Bado unahitaji msaada?",
  stillNeedHelpBody: "Timu yetu hujibu kila tiketi, kwa kawaida ndani ya siku moja ya kazi.",
  openTicket: "Fungua tiketi",
  backToHelp: "Makala za msaada",
  updated: (date) => `Imesasishwa ${date}`,
  helpCategories: {
    "getting-started": "Kuanza",
    releases: "Kazi za muziki",
    royalties: "Mirabaha",
    payouts: "Malipo",
    account: "Akaunti",
    promotion: "Utangazaji",
  },
};

export const COPY = { EN, SW };

export const TICKET_CATEGORIES = [
  "release",
  "royalties",
  "payouts",
  "account",
  "marketplace",
  "technical",
  "other",
] as const;

export const ATTACHMENT_ACCEPT = ".jpg,.jpeg,.png,.pdf,.txt,.csv";
export const ATTACHMENT_MAX = 10 * 1024 * 1024;

/** Returns "type" | "size" | null for a support attachment. */
export function attachmentProblem(file: File): "type" | "size" | null {
  if (!/\.(jpe?g|png|pdf|txt|csv)$/i.test(file.name)) return "type";
  if (file.size > ATTACHMENT_MAX) return "size";
  return null;
}
