/** Copy for /dashboard/artists. */

const EN = {
  title: "Artists",
  description: "The artist profiles your releases are published under.",
  add: "Add artist",
  usage: (used: number, max: number) => `${used} of ${max} artist ${max === 1 ? "profile" : "profiles"} used`,
  usageLabel: "Artist profiles used",
  atLimit: "You've reached your plan's artist limit.",
  upgrade: "See plans",
  noPlanNote: "Without an active plan you can have one artist profile.",
  emptyTitle: "No artists yet",
  emptyBody: "Create an artist profile to start releasing music.",
  releases: (n: number) => (n === 1 ? "1 release" : `${n} releases`),
  edit: "Edit",
  changePhoto: "Change photo",
  uploadPhoto: "Upload photo",
  uploading: "Uploading…",
  photoUpdated: "Photo updated",
  photoFor: (name: string) => `Photo for ${name}`,
  photoRules: "JPG, PNG or WebP, at least 300 × 300 px, up to 6 MB.",
  photoType: "Choose a JPG, PNG or WebP image.",
  photoSize: "That image is larger than 6 MB.",
  photoDims: "The image must be at least 300 × 300 pixels.",
  photoUnreadable: "We couldn't read that image. Try a different file.",
  listLabel: "Your artists",

  createTitle: "Add artist",
  editTitle: (name: string) => `Edit ${name}`,
  formDescription: "Use the artist name exactly as it should appear on stores.",
  name: "Artist name",
  nameRequired: "Enter the artist name.",
  bio: "Bio",
  bioHint: "A short introduction for fans and editors.",
  country: "Country",
  genre: "Primary genre",
  genrePlaceholder: "Choose a genre",
  linksLegend: "Profile links",
  linksHint: "Full links starting with https://. Stores use these to match your existing profiles.",
  urlInvalid: "Enter a full link starting with https://",
  save: "Save artist",
  create: "Create artist",
  created: "Artist created",
  saved: "Artist updated",
  cancel: "Cancel",
  limitReached: "You've reached the number of artist profiles your plan allows.",
  limitLink: "Compare plans",
  exists: "You already have an artist with this name.",
  links: {
    spotify_link: "Spotify",
    apple_music_link: "Apple Music",
    youtube_music_link: "YouTube Music",
    instagram_link: "Instagram",
    facebook_link: "Facebook",
    tiktok_link: "TikTok",
    boomplay_link: "Boomplay",
    audiomack_link: "Audiomack",
  },
};

const SW: typeof EN = {
  title: "Wasanii",
  description: "Wasifu wa wasanii ambao kazi zako zinachapishwa chini yake.",
  add: "Ongeza msanii",
  usage: (used, max) => `Wasifu ${used} kati ya ${max} umetumika`,
  usageLabel: "Wasifu wa wasanii uliotumika",
  atLimit: "Umefikia kikomo cha wasanii kwa kifurushi chako.",
  upgrade: "Angalia vifurushi",
  noPlanNote: "Bila kifurushi kinachotumika unaweza kuwa na wasifu mmoja wa msanii.",
  emptyTitle: "Bado huna wasanii",
  emptyBody: "Tengeneza wasifu wa msanii ili uanze kutoa muziki.",
  releases: (n) => (n === 1 ? "Kazi 1" : `Kazi ${n}`),
  edit: "Hariri",
  changePhoto: "Badilisha picha",
  uploadPhoto: "Pakia picha",
  uploading: "Inapakia…",
  photoUpdated: "Picha imesasishwa",
  photoFor: (name) => `Picha ya ${name}`,
  photoRules: "JPG, PNG au WebP, angalau pikseli 300 × 300, hadi MB 6.",
  photoType: "Chagua picha ya JPG, PNG au WebP.",
  photoSize: "Picha hiyo ni kubwa kuliko MB 6.",
  photoDims: "Picha lazima iwe angalau pikseli 300 × 300.",
  photoUnreadable: "Hatukuweza kusoma picha hiyo. Jaribu faili nyingine.",
  listLabel: "Wasanii wako",

  createTitle: "Ongeza msanii",
  editTitle: (name) => `Hariri ${name}`,
  formDescription: "Tumia jina la msanii kama linavyotakiwa kuonekana kwenye maduka ya muziki.",
  name: "Jina la msanii",
  nameRequired: "Weka jina la msanii.",
  bio: "Wasifu mfupi",
  bioHint: "Utambulisho mfupi kwa mashabiki na wahariri.",
  country: "Nchi",
  genre: "Aina kuu ya muziki",
  genrePlaceholder: "Chagua aina ya muziki",
  linksLegend: "Viungo vya wasifu",
  linksHint: "Viungo kamili vinavyoanza na https://. Maduka huvitumia kulinganisha na wasifu wako uliopo.",
  urlInvalid: "Weka kiungo kamili kinachoanza na https://",
  save: "Hifadhi msanii",
  create: "Tengeneza msanii",
  created: "Msanii ametengenezwa",
  saved: "Msanii amesasishwa",
  cancel: "Ghairi",
  limitReached: "Umefikia idadi ya wasifu wa wasanii inayoruhusiwa na kifurushi chako.",
  limitLink: "Linganisha vifurushi",
  exists: "Tayari una msanii mwenye jina hili.",
  links: {
    spotify_link: "Spotify",
    apple_music_link: "Apple Music",
    youtube_music_link: "YouTube Music",
    instagram_link: "Instagram",
    facebook_link: "Facebook",
    tiktok_link: "TikTok",
    boomplay_link: "Boomplay",
    audiomack_link: "Audiomack",
  },
};

export const COPY = { EN, SW };
