const EN = {
  greeting: (name: string) => (name ? `Welcome back, ${name}` : "Welcome back"),
  description: "Your releases, earnings and what needs your attention.",
  newRelease: "New release",
  finishSetupTitle: "Finish setting up your account",
  finishSetupBody: "Tell us whether you're an artist, label or creator and add your first artist profile.",
  finishSetup: "Continue setup",
  nextActions: "Next actions",
  noActions: "You're all caught up.",
  actions: {
    verify_email: "Confirm your email address to secure your account.",
    changes_requested: (title: string) => (title ? `“${title}” needs changes before it can go out.` : "A release needs changes before it can go out."),
    drafts: (n: number) => (n === 1 ? "You have 1 unfinished draft." : `You have ${n} unfinished drafts.`),
    plan: "Choose a plan to submit releases for distribution.",
    plan_pending: "Your plan payment is being confirmed by our team.",
    payout_method: "Add M-Pesa, Airtel Money, Mixx or a bank account to withdraw your earnings.",
    split_invites: (n: number) =>
      n === 1 ? "You have 1 royalty split invitation to review." : `You have ${n} royalty split invitations to review.`,
  },
  balances: "Balances",
  toWallet: "Open wallet",
  available: "Available",
  held: (x: string) => `${x} in withdrawal`,
  pending: (x: string) => `${x} pending`,
  noBalanceTitle: "No earnings yet",
  noBalanceBody: "Royalties appear here after stores report your streams and 2kTunes posts the statement.",
  releases: "Releases",
  toCatalog: "Open catalog",
  groups: {
    drafts: "Drafts",
    in_review: "In review",
    distributing: "Distributing",
    live: "Live",
    inactive: "Inactive",
  },
  noReleasesTitle: "No releases yet",
  noReleasesBody: "Start your first release — it's saved as a draft while you work.",
  recent: "Recent releases",
  updated: (when: string) => `Updated ${when}`,
  analytics: "Performance",
  toAnalytics: "Open analytics",
  streams: "Streams (12 months)",
  videoUses: "Video uses (12 months)",
  topStore: "Top store",
  topTerritory: "Top country",
  topRelease: "Top release",
  noAnalyticsTitle: "No performance data yet",
  noAnalyticsBody: "Numbers appear once stores send statements and they are posted. We never estimate.",
  activity: "Activity",
  unread: "Unread notifications",
  activeOrders: "Active creator orders",
  openTickets: "Open support tickets",
};

const SW: typeof EN = {
  greeting: (name) => (name ? `Karibu tena, ${name}` : "Karibu tena"),
  description: "Matoleo yako, mapato yako na mambo yanayohitaji umakini wako.",
  newRelease: "Toleo jipya",
  finishSetupTitle: "Maliza kuandaa akaunti yako",
  finishSetupBody: "Tuambie kama wewe ni msanii, lebo au mtengeneza maudhui, kisha ongeza wasifu wako wa kwanza wa msanii.",
  finishSetup: "Endelea kuandaa",
  nextActions: "Hatua zinazofuata",
  noActions: "Umemaliza kila kitu kwa sasa.",
  actions: {
    verify_email: "Thibitisha barua pepe yako ili kulinda akaunti yako.",
    changes_requested: (title) => (title ? `“${title}” linahitaji marekebisho kabla ya kutoka.` : "Toleo moja linahitaji marekebisho kabla ya kutoka."),
    drafts: (n) => (n === 1 ? "Una rasimu 1 ambayo haijakamilika." : `Una rasimu ${n} ambazo hazijakamilika.`),
    plan: "Chagua mpango ili kuwasilisha matoleo kwa usambazaji.",
    plan_pending: "Malipo ya mpango wako yanathibitishwa na timu yetu.",
    payout_method: "Ongeza M-Pesa, Airtel Money, Mixx au akaunti ya benki ili kutoa mapato yako.",
    split_invites: (n) => (n === 1 ? "Una mwaliko 1 wa mgawanyo wa mirabaha wa kukagua." : `Una mialiko ${n} ya mgawanyo wa mirabaha ya kukagua.`),
  },
  balances: "Salio",
  toWallet: "Fungua pochi",
  available: "Linapatikana",
  held: (x) => `${x} kwenye utoaji`,
  pending: (x) => `${x} yanasubiri`,
  noBalanceTitle: "Bado hakuna mapato",
  noBalanceBody: "Mirabaha itaonekana hapa baada ya maduka kuripoti usikilizaji wako na 2kTunes kuchapisha taarifa ya malipo.",
  releases: "Matoleo",
  toCatalog: "Fungua katalogi",
  groups: {
    drafts: "Rasimu",
    in_review: "Yanakaguliwa",
    distributing: "Yanasambazwa",
    live: "Hewani",
    inactive: "Hayatumiki",
  },
  noReleasesTitle: "Bado huna matoleo",
  noReleasesBody: "Anza toleo lako la kwanza — linahifadhiwa kama rasimu unapoendelea.",
  recent: "Matoleo ya karibuni",
  updated: (when) => `Limesasishwa ${when}`,
  analytics: "Utendaji",
  toAnalytics: "Fungua takwimu",
  streams: "Usikilizaji (miezi 12)",
  videoUses: "Matumizi kwenye video (miezi 12)",
  topStore: "Duka linaloongoza",
  topTerritory: "Nchi inayoongoza",
  topRelease: "Toleo linaloongoza",
  noAnalyticsTitle: "Bado hakuna takwimu za utendaji",
  noAnalyticsBody: "Takwimu zitaonekana maduka yakishatuma taarifa na zikachapishwa. Hatukadirii kamwe.",
  activity: "Shughuli",
  unread: "Taarifa ambazo hazijasomwa",
  activeOrders: "Oda za watengeneza maudhui zinazoendelea",
  openTickets: "Tiketi za msaada zilizo wazi",
};

export const COPY = { EN, SW };
