/** Copy for /onboarding. Read with `useCopy(COPY)`. */

const EN = {
  docTitle: "Set up your account",
  stepsLabel: "Onboarding progress",
  stepAccount: "Your account",
  stepArtist: "Artist profile",
  stepCreator: "Creator profile",
  stepOf: (n: number, total: number) => `Step ${n} of ${total}`,

  accountTitle: "Tell us about you",
  accountSub: "This sets up payouts, currency and language. You can change any of it later in Settings.",
  typeLegend: "I'm using 2kTunes as",
  firstName: "First name",
  lastName: "Last name",
  businessName: "Label or company name",
  businessHint: "The name that appears on your statements.",
  country: "Country",
  countryHint: "Where you live or where your business is registered.",
  phone: "Phone number",
  phoneHint: "Include the country code, e.g. +255 712 345 678.",
  currency: "Preferred currency",
  currencyHint: "Used to show your earnings. Payouts still happen in local currency.",
  language: "Language",
  langEn: "English",
  langSw: "Kiswahili",
  firstNameRequired: "Enter your first name.",
  businessRequired: "Enter your label or company name.",
  countryRequired: "Choose your country.",

  artistTitle: "Your artist profile",
  artistSub: "Releases are published under an artist profile. Create the first one now.",
  artistSubLabel: "Add the first artist you manage. You can add more later from the Artists page.",
  artistExisting: "You already have these artist profiles:",
  artistExistingLabel: "You can add more artists at any time from the Artists page in your dashboard.",
  artistName: "Artist name",
  artistNameHint: "Exactly as it should appear on stores.",
  artistNameRequired: "Enter the artist name.",
  genre: "Primary genre",
  genrePlaceholder: "Choose a genre",
  artistCountry: "Artist's country",
  createArtist: "Create artist profile",
  artistCreated: "Artist profile created",
  releasesCount: (n: number) => (n === 1 ? "1 release" : `${n} releases`),
  configError: "We couldn't load the genre list. You can still continue.",

  creatorTitle: "Creator profile",
  creatorSubCreator:
    "Recommended: artists find and pay creators through the marketplace. Set up the basics now and add packages later.",
  creatorSubOther:
    "Optional: if you also make content for other artists, set up a creator profile to get paid for it.",
  displayName: "Display name",
  displayNameHint: "How artists will see you in the marketplace.",
  displayNameRequired: "Enter a display name.",
  categories: "Content categories",
  categoriesHint: (max: number) => `Choose up to ${max}.`,
  languages: "Languages you create in",
  languagesHint: (max: number) => `Choose up to ${max}.`,
  saveCreator: "Save and finish",
  skip: "Skip for now",
  skipHint: "You can set up a creator profile later from the Creator workspace.",
  creatorSaved: "Creator profile saved",
  noOptions: "Options couldn't be loaded. You can skip this step and finish it later.",

  back: "Back",
  continue: "Continue",
  finish: "Finish",
  finishing: "Finishing…",
  welcome: "Welcome to 2kTunes",
  welcomeBody: "Your account is ready.",
  signedInAs: (email: string) => `Signed in as ${email}`,
  signOut: "Sign out",
};

const SW: typeof EN = {
  docTitle: "Weka akaunti yako",
  stepsLabel: "Maendeleo ya usajili",
  stepAccount: "Akaunti yako",
  stepArtist: "Wasifu wa msanii",
  stepCreator: "Wasifu wa mtayarishaji maudhui",
  stepOf: (n, total) => `Hatua ${n} kati ya ${total}`,

  accountTitle: "Tueleze kuhusu wewe",
  accountSub: "Hii inaweka malipo, sarafu na lugha. Unaweza kubadilisha chochote baadaye kwenye Mipangilio.",
  typeLegend: "Ninatumia 2kTunes kama",
  firstName: "Jina la kwanza",
  lastName: "Jina la mwisho",
  businessName: "Jina la lebo au kampuni",
  businessHint: "Jina litakaloonekana kwenye taarifa zako za mapato.",
  country: "Nchi",
  countryHint: "Unapoishi au mahali kampuni yako iliposajiliwa.",
  phone: "Namba ya simu",
  phoneHint: "Weka msimbo wa nchi, mfano +255 712 345 678.",
  currency: "Sarafu unayopendelea",
  currencyHint: "Inatumika kuonyesha mapato yako. Malipo bado yanafanyika kwa sarafu ya ndani.",
  language: "Lugha",
  langEn: "English",
  langSw: "Kiswahili",
  firstNameRequired: "Weka jina lako la kwanza.",
  businessRequired: "Weka jina la lebo au kampuni yako.",
  countryRequired: "Chagua nchi yako.",

  artistTitle: "Wasifu wako wa msanii",
  artistSub: "Kazi zinachapishwa chini ya wasifu wa msanii. Tengeneza wa kwanza sasa.",
  artistSubLabel: "Ongeza msanii wa kwanza unayemsimamia. Unaweza kuongeza wengine baadaye kwenye ukurasa wa Wasanii.",
  artistExisting: "Tayari una wasifu hizi za wasanii:",
  artistExistingLabel: "Unaweza kuongeza wasanii wengine wakati wowote kwenye ukurasa wa Wasanii ndani ya dashibodi.",
  artistName: "Jina la msanii",
  artistNameHint: "Kama linavyotakiwa kuonekana kwenye maduka ya muziki.",
  artistNameRequired: "Weka jina la msanii.",
  genre: "Aina kuu ya muziki",
  genrePlaceholder: "Chagua aina ya muziki",
  artistCountry: "Nchi ya msanii",
  createArtist: "Tengeneza wasifu wa msanii",
  artistCreated: "Wasifu wa msanii umetengenezwa",
  releasesCount: (n) => (n === 1 ? "Kazi 1" : `Kazi ${n}`),
  configError: "Hatukuweza kupakia orodha ya aina za muziki. Bado unaweza kuendelea.",

  creatorTitle: "Wasifu wa mtayarishaji maudhui",
  creatorSubCreator:
    "Inapendekezwa: wasanii huwapata na kuwalipa watayarishaji maudhui kupitia soko. Weka mambo ya msingi sasa na uongeze vifurushi baadaye.",
  creatorSubOther:
    "Si lazima: kama pia unatengeneza maudhui kwa ajili ya wasanii wengine, weka wasifu wa mtayarishaji ili ulipwe kwa kazi hiyo.",
  displayName: "Jina la kuonyesha",
  displayNameHint: "Jinsi wasanii watakavyokuona sokoni.",
  displayNameRequired: "Weka jina la kuonyesha.",
  categories: "Aina za maudhui",
  categoriesHint: (max) => `Chagua hadi ${max}.`,
  languages: "Lugha unazotumia kutengeneza maudhui",
  languagesHint: (max) => `Chagua hadi ${max}.`,
  saveCreator: "Hifadhi na umalize",
  skip: "Ruka kwa sasa",
  skipHint: "Unaweza kuweka wasifu wa mtayarishaji baadaye kupitia Eneo la Mtayarishaji.",
  creatorSaved: "Wasifu wa mtayarishaji umehifadhiwa",
  noOptions: "Chaguo hazikuweza kupakiwa. Unaweza kuruka hatua hii na kuimaliza baadaye.",

  back: "Rudi",
  continue: "Endelea",
  finish: "Maliza",
  finishing: "Inamaliza…",
  welcome: "Karibu 2kTunes",
  welcomeBody: "Akaunti yako iko tayari.",
  signedInAs: (email) => `Umeingia kama ${email}`,
  signOut: "Toka",
};

export const COPY = { EN, SW };

/** Marketplace content categories (config/marketplace.php). */
const CATEGORY_EN: Record<string, string> = {
  dance: "Dance",
  comedy: "Comedy",
  lifestyle: "Lifestyle",
  fashion: "Fashion",
  beauty: "Beauty",
  music: "Music",
  lip_sync: "Lip sync",
  storytelling: "Storytelling",
  fitness: "Fitness",
  food: "Food",
  travel: "Travel",
  tech: "Tech",
  education: "Education",
  sports: "Sports",
  gaming: "Gaming",
  family: "Family",
  faith: "Faith",
};
const CATEGORY_SW: typeof CATEGORY_EN = {
  dance: "Kucheza",
  comedy: "Vichekesho",
  lifestyle: "Mtindo wa maisha",
  fashion: "Mitindo ya mavazi",
  beauty: "Urembo",
  music: "Muziki",
  lip_sync: "Kuigiza wimbo (lip sync)",
  storytelling: "Kusimulia hadithi",
  fitness: "Mazoezi",
  food: "Chakula",
  travel: "Safari",
  tech: "Teknolojia",
  education: "Elimu",
  sports: "Michezo",
  gaming: "Michezo ya video",
  family: "Familia",
  faith: "Imani",
};
export const CATEGORY_COPY = { EN: CATEGORY_EN, SW: CATEGORY_SW };

/** Copy for <CountrySelect>. */
export const COUNTRY_COPY = {
  EN: { choose: "Choose a country", africa: "Africa", others: "Rest of the world" },
  SW: { choose: "Chagua nchi", africa: "Afrika", others: "Nchi nyingine duniani" },
};
