import type { Localized } from "@/lib/LanguageContext";
import type { PageCopy } from "../MarketingPage";

export const DISTRIBUTION: Localized<PageCopy> = {
  EN: {
    meta: {
      title: "Distribution",
      description: "Release your music to global streaming services, short-video apps and African platforms from one upload.",
    },
    hero: {
      eyebrow: "Distribution",
      title: "One upload. Every place people listen.",
      lede: "Send singles, EPs and albums to global streaming services, short-video apps and African platforms. We handle formats, metadata and delivery — you choose the stores and the date.",
      secondary: { label: "See pricing", to: "/pricing" },
      visual: "release",
    },
    sections: [
      {
        type: "stores",
        tone: "raised",
        eyebrow: "Destinations",
        title: "Global reach, with African platforms built in.",
        lede: "Pick destinations per release. Some stores have their own content rules and territory limits; we tell you before you submit, not after.",
      },
      {
        type: "steps",
        tone: "light",
        eyebrow: "Release flow",
        title: "A guided release, start to finish.",
        lede: "Save a draft at any point and come back to it. Nothing goes to a store until you submit and our review is complete.",
        steps: [
          { title: "Add your music", body: "Upload WAV or FLAC audio and square artwork of at least 3000 × 3000 px." },
          { title: "Tell the stores who made it", body: "Artists, featured artists, songwriters, producers, genre, language and explicit flag." },
          { title: "Choose stores & date", body: "Select destinations and a release date — earlier dates leave room for pitching." },
          { title: "We review", body: "We check audio, artwork and metadata against store rules and flag anything that would be rejected." },
          { title: "Delivered & live", body: "Your release goes out to each store, and you can track its status per destination." },
        ],
      },
      {
        type: "features",
        tone: "dark",
        eyebrow: "What's included",
        title: "Everything a release needs to land properly.",
        items: [
          { icon: "badge", title: "ISRC & UPC codes", body: "Free codes for every track and release if you don't already have your own." },
          { icon: "calendar", title: "Scheduled release dates", body: "Pick the day your music goes live, worldwide or by territory where stores allow it." },
          { icon: "file", title: "Metadata review", body: "Human review of titles, credits and artwork catches problems before a store does." },
          { icon: "layers", title: "Singles, EPs and albums", body: "Release any format, including multi-artist and compilation releases." },
          { icon: "video", title: "Short-video ready", body: "Make your sound available for creators to use in short-video content where platforms support it." },
          { icon: "shield", title: "Takedowns and edits", body: "Request metadata changes or take a release down from your dashboard at any time." },
        ],
      },
      {
        type: "notice",
        tone: "raised",
        title: "What we can promise — and what we can't",
        body: "We promise accurate delivery, clear status and honest reporting. We can't promise streams, playlist placements or editorial features, and each store makes its own decisions about what it accepts and features.",
      },
      {
        type: "faq",
        tone: "dark",
        eyebrow: "Distribution FAQ",
        title: "Before you release",
        items: [
          { q: "How early should I submit?", a: "At least two to three weeks before your release date. If you want to pitch to store editors, submit four or more weeks ahead." },
          { q: "What audio format do you need?", a: "Lossless WAV or FLAC, 16-bit/44.1 kHz or higher. MP3 files are not accepted by most stores." },
          { q: "Can I release a cover song?", a: "Yes, as long as you have the right mechanical licence for the territories you release in. We'll ask you to confirm this during upload." },
          { q: "I already released this song elsewhere. Can I move it?", a: "Yes. Use the same ISRC codes and original release date so your play counts and history carry over." },
        ],
        link: { label: "More answers in the Help Center", to: "/help" },
      },
    ],
    cta: { title: "Ready when your music is.", lede: "Create your account now and upload your first release whenever you're ready." },
  },
  SW: {
    meta: {
      title: "Usambazaji",
      description: "Toa muziki wako kwenye huduma za kimataifa, programu za video fupi na majukwaa ya Afrika kwa upakiaji mmoja.",
    },
    hero: {
      eyebrow: "Usambazaji",
      title: "Upakiaji mmoja. Kila mahali watu wanaposikiliza.",
      lede: "Tuma nyimbo, EP na albamu kwenye huduma za kimataifa, programu za video fupi na majukwaa ya Afrika. Tunashughulikia mifumo, taarifa na uwasilishaji — wewe unachagua maduka na tarehe.",
      secondary: { label: "Angalia bei", to: "/pricing" },
      visual: "release",
    },
    sections: [
      {
        type: "stores",
        tone: "raised",
        eyebrow: "Maeneo",
        title: "Kufika kimataifa, pamoja na majukwaa ya Afrika.",
        lede: "Chagua maeneo kwa kila toleo. Baadhi ya maduka yana masharti yao ya maudhui na mipaka ya nchi; tunakujulisha kabla ya kuwasilisha, si baadaye.",
      },
      {
        type: "steps",
        tone: "light",
        eyebrow: "Hatua za kutoa",
        title: "Toleo linaloongozwa, mwanzo hadi mwisho.",
        lede: "Hifadhi rasimu wakati wowote na urudi baadaye. Hakuna kinachokwenda dukani hadi uwasilishe na ukaguzi wetu ukamilike.",
        steps: [
          { title: "Weka muziki wako", body: "Pakia sauti ya WAV au FLAC na picha ya mraba ya angalau pikseli 3000 × 3000." },
          { title: "Eleza waliohusika", body: "Wasanii, walioshirikishwa, watunzi, watayarishaji, aina ya muziki, lugha na kama una maneno makali." },
          { title: "Chagua maduka na tarehe", body: "Chagua maeneo na tarehe ya kutoa — tarehe za mbali zinatoa nafasi ya kuwasilisha kwa wahariri." },
          { title: "Tunakagua", body: "Tunakagua sauti, picha na taarifa kulingana na masharti ya maduka na kukuonyesha kitakachokataliwa." },
          { title: "Imesambazwa na iko hewani", body: "Toleo lako linakwenda kila duka, na unafuatilia hali yake kwa kila eneo." },
        ],
      },
      {
        type: "features",
        tone: "dark",
        eyebrow: "Kilichomo",
        title: "Kila kitu toleo linachohitaji ili lifike vizuri.",
        items: [
          { icon: "badge", title: "Namba za ISRC na UPC", body: "Namba za bure kwa kila wimbo na toleo kama huna zako tayari." },
          { icon: "calendar", title: "Tarehe za kutoa zilizopangwa", body: "Chagua siku muziki wako unaanza kusikika, duniani kote au kwa nchi pale maduka yanaporuhusu." },
          { icon: "file", title: "Ukaguzi wa taarifa", body: "Ukaguzi wa watu halisi wa majina, wahusika na picha unagundua matatizo kabla ya duka." },
          { icon: "layers", title: "Nyimbo, EP na albamu", body: "Toa aina yoyote, zikiwemo za wasanii wengi na mkusanyiko." },
          { icon: "video", title: "Tayari kwa video fupi", body: "Ruhusu watengeneza maudhui kutumia sauti yako kwenye video fupi pale majukwaa yanaporuhusu." },
          { icon: "shield", title: "Kuondoa na kubadilisha", body: "Omba mabadiliko ya taarifa au ondoa toleo kutoka dashibodi wakati wowote." },
        ],
      },
      {
        type: "notice",
        tone: "raised",
        title: "Tunachoweza kuahidi — na tusichoweza",
        body: "Tunaahidi uwasilishaji sahihi, hali inayoonekana na ripoti za kweli. Hatuwezi kuahidi usikilizaji, kuwekwa kwenye orodha au kuchaguliwa na wahariri, na kila duka hufanya maamuzi yake kuhusu kinachokubaliwa.",
      },
      {
        type: "faq",
        tone: "dark",
        eyebrow: "Maswali ya usambazaji",
        title: "Kabla hujatoa",
        items: [
          { q: "Niwasilishe mapema kiasi gani?", a: "Angalau wiki mbili hadi tatu kabla ya tarehe ya kutoa. Kama unataka kuwasilisha kwa wahariri wa maduka, wasilisha wiki nne au zaidi kabla." },
          { q: "Mnahitaji sauti ya aina gani?", a: "WAV au FLAC isiyopunguzwa ubora, 16-bit/44.1 kHz au zaidi. Maduka mengi hayakubali MP3." },
          { q: "Naweza kutoa wimbo wa kurudia (cover)?", a: "Ndiyo, ikiwa una leseni sahihi ya haki za utunzi kwa nchi unazotoa. Tutakuomba uthibitishe wakati wa kupakia." },
          { q: "Nilishatoa wimbo huu mahali pengine. Naweza kuuhamisha?", a: "Ndiyo. Tumia namba zilezile za ISRC na tarehe ya awali ya kutoa ili idadi ya usikilizaji na historia viendelee." },
        ],
        link: { label: "Majibu zaidi kwenye Kituo cha Msaada", to: "/help" },
      },
    ],
    cta: { title: "Tuko tayari muziki wako ukiwa tayari.", lede: "Fungua akaunti sasa na upakie toleo lako la kwanza utakapokuwa tayari." },
  },
  FR: {
    meta: {
      title: "Distribution",
      description: "Diffusez votre musique sur les services de streaming mondiaux, les applis de vidéo courte et les plateformes africaines en une seule mise en ligne.",
    },
    hero: {
      eyebrow: "Distribution",
      title: "Une mise en ligne. Partout où l’on écoute.",
      lede: "Envoyez singles, EP et albums vers les services de streaming mondiaux, les applis de vidéo courte et les plateformes africaines. Nous gérons formats, métadonnées et livraison — vous choisissez les plateformes et la date.",
      secondary: { label: "Voir les tarifs", to: "/pricing" },
      visual: "release",
    },
    sections: [
      {
        type: "stores",
        tone: "raised",
        eyebrow: "Destinations",
        title: "Une portée mondiale, plateformes africaines incluses.",
        lede: "Choisissez les destinations pour chaque sortie. Certaines plateformes ont leurs propres règles de contenu et limites territoriales ; nous vous prévenons avant l’envoi, pas après.",
      },
      {
        type: "steps",
        tone: "light",
        eyebrow: "Étapes de sortie",
        title: "Une sortie guidée, du début à la fin.",
        lede: "Enregistrez un brouillon à tout moment et revenez-y plus tard. Rien n’est envoyé aux plateformes tant que vous n’avez pas soumis et que notre vérification n’est pas terminée.",
        steps: [
          { title: "Ajoutez votre musique", body: "Importez un audio WAV ou FLAC et une pochette carrée d’au moins 3000 × 3000 px." },
          { title: "Indiquez qui l’a créée", body: "Artistes, artistes invités, auteurs-compositeurs, producteurs, genre, langue et mention explicite." },
          { title: "Plateformes et date", body: "Sélectionnez les destinations et une date de sortie — une date plus lointaine laisse le temps de pitcher." },
          { title: "Nous vérifions", body: "Nous contrôlons l’audio, la pochette et les métadonnées selon les règles des plateformes et signalons tout ce qui serait rejeté." },
          { title: "Livrée et en ligne", body: "Votre sortie part vers chaque plateforme, et vous suivez son statut par destination." },
        ],
      },
      {
        type: "features",
        tone: "dark",
        eyebrow: "Ce qui est inclus",
        title: "Tout ce qu’il faut pour une sortie réussie.",
        items: [
          { icon: "badge", title: "Codes ISRC et UPC", body: "Des codes gratuits pour chaque titre et chaque sortie si vous n’avez pas déjà les vôtres." },
          { icon: "calendar", title: "Dates de sortie programmées", body: "Choisissez le jour de mise en ligne, dans le monde entier ou par territoire lorsque les plateformes le permettent." },
          { icon: "file", title: "Vérification des métadonnées", body: "Une relecture humaine des titres, crédits et pochettes repère les problèmes avant les plateformes." },
          { icon: "layers", title: "Singles, EP et albums", body: "Sortez tout format, y compris les sorties multi-artistes et les compilations." },
          { icon: "video", title: "Prêt pour la vidéo courte", body: "Rendez votre son disponible pour les créateurs de contenu en vidéo courte, sur les plateformes qui le permettent." },
          { icon: "shield", title: "Retraits et modifications", body: "Demandez des modifications de métadonnées ou retirez une sortie depuis votre tableau de bord, à tout moment." },
        ],
      },
      {
        type: "notice",
        tone: "raised",
        title: "Ce que nous pouvons promettre — et ce que nous ne pouvons pas",
        body: "Nous promettons une livraison exacte, un statut clair et des rapports honnêtes. Nous ne pouvons pas promettre de streams, de placements en playlist ni de mises en avant éditoriales : chaque plateforme décide elle-même de ce qu’elle accepte et met en avant.",
      },
      {
        type: "faq",
        tone: "dark",
        eyebrow: "FAQ distribution",
        title: "Avant votre sortie",
        items: [
          { q: "Combien de temps à l’avance dois-je soumettre ?", a: "Au moins deux à trois semaines avant votre date de sortie. Si vous souhaitez pitcher auprès des éditeurs des plateformes, soumettez au moins quatre semaines à l’avance." },
          { q: "Quel format audio vous faut-il ?", a: "WAV ou FLAC sans perte, 16 bits/44,1 kHz ou plus. La plupart des plateformes n’acceptent pas les fichiers MP3." },
          { q: "Puis-je sortir une reprise ?", a: "Oui, à condition de disposer de la licence mécanique adaptée aux territoires de sortie. Nous vous demanderons de le confirmer lors de la mise en ligne." },
          { q: "J’ai déjà sorti ce titre ailleurs. Puis-je le transférer ?", a: "Oui. Utilisez les mêmes codes ISRC et la date de sortie d’origine pour conserver vos compteurs d’écoutes et votre historique." },
        ],
        link: { label: "Plus de réponses dans le Centre d’aide", to: "/help" },
      },
    ],
    cta: { title: "Prêts quand votre musique l’est.", lede: "Créez votre compte maintenant et mettez en ligne votre première sortie quand vous serez prêt." },
  },
};
