import type { Localized } from "@/lib/LanguageContext";

/**
 * Legal drafts. ALL OF THESE ARE DRAFTS pending review by counsel; the page
 * renders a prominent "Draft — to be reviewed by counsel" banner. Original
 * text written for 2kTunes — not adapted from any other company's terms.
 */

export type LegalDocId = "terms" | "privacy" | "distribution-agreement" | "acceptable-use";
type LegalSection = { id: string; heading: string; body: string[] };
type LegalDoc = { title: string; summary: string; sections: LegalSection[] };

export const LEGAL_UPDATED = "2026-10-02";

export const LEGAL: Record<LegalDocId, Localized<LegalDoc>> = {
  terms: {
    EN: {
      title: "Terms of Service",
      summary: "The rules for using the 2kTunes website, dashboard and services.",
      sections: [
        { id: "about", heading: "1. About these terms", body: ["These Terms of Service form an agreement between you and 2kTunes (“2kTunes”, “we”, “us”) for your use of our website, dashboard and related services (the “Services”). By creating an account or using the Services, you agree to these terms.", "If you distribute music through 2kTunes, the Distribution Agreement also applies. Our Privacy Policy explains how we handle personal data, and our Acceptable Use Policy sets out what is not allowed."] },
        { id: "eligibility", heading: "2. Who can use 2kTunes", body: ["You must be at least 18 years old, or the age of majority where you live, to open an account. If you act for a label, company or group, you confirm you are authorised to bind them to these terms.", "You must give accurate information when you register and keep it up to date."] },
        { id: "account", heading: "3. Your account", body: ["You are responsible for keeping your login details secure and for all activity under your account. Tell us immediately at the contact address below if you believe your account has been accessed without permission.", "We may suspend or close accounts that breach these terms, the Acceptable Use Policy or applicable law, or that put other users, stores or 2kTunes at risk."] },
        { id: "plans", heading: "4. Plans, fees and payment", body: ["Some Services require a paid plan. Prices, billing periods and what each plan includes are shown before you pay. Promotion services and campaigns are priced separately and shown before you commit.", "Unless the law says otherwise, fees already paid are not refundable for a billing period that has started. We will give reasonable notice before changing the price of a plan you are subscribed to."] },
        { id: "royalties", heading: "5. Royalties and withdrawals", body: ["Royalties are credited to your wallet after we receive and process reports and payments from stores and partners. Amounts shown before that are estimates.", "Withdrawals are subject to the minimum amount, available payout methods, fees and exchange rates shown in your dashboard at the time you request them. We may delay or withhold payments connected to suspected fraud, artificial streaming, rights disputes or legal requirements, and will tell you why where the law allows."] },
        { id: "content", heading: "6. Your content", body: ["You keep all rights in the music, artwork and other material you upload. You grant us the licences described in the Distribution Agreement so we can provide the Services.", "You must only upload content you own or are authorised to distribute."] },
        { id: "no-guarantee", heading: "7. No guaranteed results", body: ["Stores, editors, curators, creators and audiences make their own decisions. We do not guarantee any number of streams, placements, features, followers or earnings."] },
        { id: "liability", heading: "8. Liability", body: ["We provide the Services with reasonable skill and care. To the extent permitted by law, we are not liable for indirect or consequential losses, or for the acts of stores, payment providers or other third parties. Nothing in these terms limits liability that cannot be limited by law."] },
        { id: "changes", heading: "9. Changes and termination", body: ["We may update these terms. If a change is material, we will notify you before it takes effect. You may close your account at any time; some obligations, such as payment of earned royalties, continue after closure."] },
        { id: "marketplace", heading: "10. Creator marketplace", body: ["Artists can request a creator's package for a song. 2kTunes reviews every request before it reaches the creator. The creator then has 3 days to accept or decline. The artist pays only after the creator accepts, within 7 days of acceptance; otherwise the request expires and nothing is charged.", "Payments are held by 2kTunes in an internal holding account until the work is verified. This is internal accounting, not a regulated escrow or trust service. After the creator submits the post, 2kTunes checks it, and only once 2kTunes verifies the post is the payment released to the creator, minus a 15% platform fee.", "There is no automatic approval and no fixed number of revisions. 2kTunes may ask the creator to fix a post before verifying it.", "A post is due within the package turnaround after payment. If it is not delivered within the turnaround plus 2 days, the order is flagged as late and 2kTunes may refund the artist to their 2kTunes wallet. Either party may open a dispute while the payment is held; 2kTunes reviews it and may release the payment, refund the artist or split the amount.", "Artists and creators do not contact each other directly. All messages go through 2kTunes and are visible to 2kTunes staff, and contact details (phone numbers, emails, links and handles) are removed automatically. We do not share creators' contact details or social handles with artists.", "Creator metrics are self-reported unless marked as verified. View counts shown on showcase videos are reported by the creator and are not checked by 2kTunes. Creators promise the content described in their package, not results."] },
        { id: "offers", heading: "11. Offers and promo codes", body: ["From time to time we run offers, such as a discount, a fixed price or a free period, and some need a promo code. Offers and codes never stack: when more than one could apply, you pay the lowest price, and a price never goes below zero.", "An offer for a “first subscription” is only for accounts that have never had a confirmed paid plan. A free offer gives you the plan for its free period (or the plan's normal duration if no period is stated); when it ends, the plan expires and you renew at the normal price. Offers may have an end date and limits on the total number of uses or on uses per account."] },
        { id: "referrals", heading: "12. Referral program", body: ["You can invite other artists with your referral link. A referral counts only for a brand-new account that signs up with your link, confirms its email address and, unless the program states otherwise, starts its first paid subscription.", "You can't refer yourself or another account you control. Rewards are capped each month and are added after a hold period. A reward is either credit to your 2kTunes wallet, which you can withdraw like other earnings, or free days added to your plan, as shown in your dashboard.", "A friend you invite gets the referred price on their first subscription only. We may reject referrals we believe are fraudulent or abusive, and we may change or end the program at any time; rewards already credited are not affected.", "Privacy: the invite page shows only your first name to the people you invite, and you see only your friends' initials and the status of each referral."] },
        { id: "law", heading: "13. Governing law and contact", body: ["These terms are governed by the laws of the United Republic of Tanzania. Questions about these terms can be sent to support@2ktunes.com."] },
      ],
    },
    SW: {
      title: "Masharti ya Huduma",
      summary: "Kanuni za kutumia tovuti, dashibodi na huduma za 2kTunes.",
      sections: [
        { id: "about", heading: "1. Kuhusu masharti haya", body: ["Masharti haya ya Huduma ni makubaliano kati yako na 2kTunes (“2kTunes”, “sisi”) kuhusu matumizi ya tovuti, dashibodi na huduma zinazohusiana (“Huduma”). Kwa kufungua akaunti au kutumia Huduma, unakubali masharti haya.", "Kama unasambaza muziki kupitia 2kTunes, Mkataba wa Usambazaji pia unatumika. Sera yetu ya Faragha inaeleza jinsi tunavyoshughulikia taarifa binafsi, na Sera ya Matumizi Yanayokubalika inaeleza yasiyoruhusiwa."] },
        { id: "eligibility", heading: "2. Nani anaweza kutumia 2kTunes", body: ["Lazima uwe na umri wa angalau miaka 18, au umri wa utu uzima kisheria unapoishi, kufungua akaunti. Kama unafanya kazi kwa niaba ya lebo, kampuni au kikundi, unathibitisha kuwa una mamlaka ya kuwafunga kwa masharti haya.", "Lazima utoe taarifa sahihi unapojisajili na uzisasishe."] },
        { id: "account", heading: "3. Akaunti yako", body: ["Una wajibu wa kulinda taarifa zako za kuingia na shughuli zote kwenye akaunti yako. Tujulishe mara moja kupitia anwani iliyo hapa chini ukiamini akaunti yako imeingiliwa bila ruhusa.", "Tunaweza kusimamisha au kufunga akaunti zinazokiuka masharti haya, Sera ya Matumizi Yanayokubalika au sheria, au zinazoweka watumiaji wengine, maduka au 2kTunes hatarini."] },
        { id: "plans", heading: "4. Vifurushi, ada na malipo", body: ["Baadhi ya Huduma zinahitaji kifurushi cha kulipia. Bei, vipindi vya malipo na kilichomo kwenye kila kifurushi vinaonyeshwa kabla ya kulipa. Huduma za utangazaji na kampeni zina bei tofauti na zinaonyeshwa kabla ya kukubali.", "Isipokuwa sheria inasema vinginevyo, ada iliyolipwa hairudishwi kwa kipindi cha malipo kilichoanza. Tutatoa taarifa ya kutosha kabla ya kubadilisha bei ya kifurushi ulichojiunga nacho."] },
        { id: "royalties", heading: "5. Mirabaha na utoaji wa pesa", body: ["Mirabaha inaingizwa kwenye pochi yako baada ya kupokea na kushughulikia ripoti na malipo kutoka maduka na washirika. Kiasi kinachoonyeshwa kabla ya hapo ni makadirio.", "Utoaji wa pesa unategemea kiwango cha chini, njia za malipo zinazopatikana, ada na viwango vya ubadilishaji vinavyoonyeshwa kwenye dashibodi wakati wa kuomba. Tunaweza kuchelewesha au kuzuia malipo yanayohusiana na udanganyifu unaoshukiwa, usikilizaji wa kughushi, migogoro ya haki au matakwa ya kisheria, na tutakueleza sababu pale sheria inaporuhusu."] },
        { id: "content", heading: "6. Maudhui yako", body: ["Unabaki na haki zote za muziki, picha na vitu vingine unavyopakia. Unatupa leseni zilizoelezwa kwenye Mkataba wa Usambazaji ili tuweze kutoa Huduma.", "Lazima upakie tu maudhui unayomiliki au una ruhusa ya kuyasambaza."] },
        { id: "no-guarantee", heading: "7. Hakuna matokeo yaliyohakikishwa", body: ["Maduka, wahariri, wachaguzi, watengeneza maudhui na hadhira hufanya maamuzi yao wenyewe. Hatuhakikishi idadi yoyote ya usikilizaji, nafasi, kuchaguliwa, wafuasi au mapato."] },
        { id: "liability", heading: "8. Dhima", body: ["Tunatoa Huduma kwa ujuzi na uangalifu unaostahili. Kwa kiwango kinachoruhusiwa na sheria, hatuwajibiki kwa hasara zisizo za moja kwa moja, au kwa matendo ya maduka, watoa huduma za malipo au wahusika wengine. Hakuna kitu katika masharti haya kinachopunguza dhima isiyoweza kupunguzwa kisheria."] },
        { id: "changes", heading: "9. Mabadiliko na kusitisha", body: ["Tunaweza kusasisha masharti haya. Kama badiliko ni kubwa, tutakujulisha kabla halijaanza kutumika. Unaweza kufunga akaunti wakati wowote; baadhi ya wajibu, kama kulipa mirabaha iliyopatikana, unaendelea baada ya kufunga."] },
        { id: "marketplace", heading: "10. Soko la watengeneza maudhui", body: ["Msanii anaweza kuomba kifurushi cha mtengeneza maudhui kwa ajili ya wimbo. 2kTunes inakagua kila ombi kabla halijamfikia mtengeneza maudhui. Kisha mtengeneza maudhui ana siku 3 kukubali au kukataa. Msanii analipa tu baada ya mtengeneza maudhui kukubali, ndani ya siku 7 tangu kukubaliwa; vinginevyo ombi linaisha na hakuna kinachotozwa.", "Malipo yanashikiliwa na 2kTunes kwenye akaunti ya ndani hadi kazi ithibitishwe. Huu ni uhasibu wa ndani, si huduma ya escrow au amana inayodhibitiwa. Mtengeneza maudhui akiwasilisha chapisho, 2kTunes inalikagua, na ni baada tu ya 2kTunes kuthibitisha chapisho ndipo malipo yanatolewa kwa mtengeneza maudhui, ukiondoa ada ya jukwaa ya 15%.", "Hakuna uidhinishaji wa moja kwa moja na hakuna idadi maalum ya marekebisho. 2kTunes inaweza kumwomba mtengeneza maudhui arekebishe chapisho kabla ya kulithibitisha.", "Chapisho linatakiwa ndani ya muda wa kifurushi baada ya malipo. Lisipowasilishwa ndani ya muda huo pamoja na siku 2, oda inawekewa alama ya kuchelewa na 2kTunes inaweza kumrudishia msanii pesa kwenye pochi yake ya 2kTunes. Upande wowote unaweza kufungua mgogoro wakati malipo yanashikiliwa; 2kTunes inaukagua na inaweza kutoa malipo, kumrudishia msanii pesa au kugawa kiasi.", "Wasanii na watengeneza maudhui hawawasiliani moja kwa moja. Ujumbe wote hupitia 2kTunes na unaonekana na wafanyakazi wa 2kTunes, na taarifa za mawasiliano (namba za simu, barua pepe, viungo na majina ya akaunti) huondolewa moja kwa moja. Hatushirikishi wasanii taarifa za mawasiliano wala majina ya akaunti za mitandao ya watengeneza maudhui.", "Takwimu za watengeneza maudhui ni kwa kauli yao isipokuwa zimewekwa alama ya kuthibitishwa. Idadi ya watazamaji kwenye video za maonyesho inatolewa na mtengeneza maudhui na haikaguliwi na 2kTunes. Watengeneza maudhui wanaahidi maudhui yaliyoelezwa kwenye kifurushi, si matokeo."] },
        { id: "offers", heading: "11. Ofa na misimbo ya ofa", body: ["Mara kwa mara tunaendesha ofa, kama punguzo, bei maalum au kipindi cha bure, na baadhi zinahitaji msimbo wa ofa. Ofa na misimbo haziunganishwi: zaidi ya moja zikifaa, unalipa bei ya chini zaidi, na bei haishuki chini ya sifuri.", "Ofa ya “usajili wa kwanza” ni kwa akaunti ambazo hazijawahi kuwa na kifurushi cha kulipia kilichothibitishwa. Ofa ya bure inakupa kifurushi kwa kipindi chake cha bure (au muda wa kawaida wa kifurushi kama kipindi hakijatajwa); kikiisha, kifurushi kinaisha na unakilipia upya kwa bei ya kawaida. Ofa zinaweza kuwa na tarehe ya mwisho na kikomo cha idadi ya matumizi kwa jumla au kwa kila akaunti."] },
        { id: "referrals", heading: "12. Mpango wa mialiko", body: ["Unaweza kuwaalika wasanii wengine kwa kiungo chako cha mwaliko. Mwaliko unahesabika tu kwa akaunti mpya kabisa inayojisajili kwa kiungo chako, kuthibitisha barua pepe yake na, isipokuwa mpango useme vinginevyo, kuanza usajili wake wa kwanza wa kulipia.", "Huwezi kujialika mwenyewe wala akaunti nyingine unayoidhibiti. Zawadi zina kikomo kila mwezi na zinaongezwa baada ya kipindi cha kusubiri. Zawadi ni salio kwenye pochi yako ya 2kTunes, unaloweza kutoa kama mapato mengine, au siku za bure kwenye kifurushi chako, kama inavyoonyeshwa kwenye dashibodi yako.", "Rafiki unayemwalika anapata bei ya mwaliko kwenye usajili wake wa kwanza tu. Tunaweza kukataa mialiko tunayoamini ni ya udanganyifu au matumizi mabaya, na tunaweza kubadilisha au kusitisha mpango wakati wowote; zawadi zilizokwisha ingizwa haziathiriki.", "Faragha: ukurasa wa mwaliko unaonyesha jina lako la kwanza tu kwa unaowaalika, na wewe unaona herufi za kwanza za marafiki zako na hali ya kila mwaliko tu."] },
        { id: "law", heading: "13. Sheria inayotumika na mawasiliano", body: ["Masharti haya yanaongozwa na sheria za Jamhuri ya Muungano wa Tanzania. Maswali kuhusu masharti haya yatumwe kwa support@2ktunes.com."] },
      ],
    },
    FR: {
      title: "Conditions d’utilisation",
      summary: "Les règles d’utilisation du site web, du tableau de bord et des services 2kTunes.",
      sections: [
        { id: "about", heading: "1. À propos des présentes conditions", body: ["Les présentes Conditions d’utilisation constituent un accord entre vous et 2kTunes (« 2kTunes », « nous ») concernant votre utilisation de notre site web, de notre tableau de bord et des services associés (les « Services »). En créant un compte ou en utilisant les Services, vous acceptez les présentes conditions.", "Si vous distribuez de la musique via 2kTunes, le Contrat de distribution s’applique également. Notre Politique de confidentialité explique comment nous traitons les données personnelles, et notre Politique d’utilisation acceptable précise ce qui est interdit."] },
        { id: "eligibility", heading: "2. Qui peut utiliser 2kTunes", body: ["Vous devez avoir au moins 18 ans, ou l’âge de la majorité dans votre pays de résidence, pour ouvrir un compte. Si vous agissez pour le compte d’un label, d’une société ou d’un groupe, vous confirmez être habilité à l’engager au titre des présentes conditions.", "Vous devez fournir des informations exactes lors de votre inscription et les tenir à jour."] },
        { id: "account", heading: "3. Votre compte", body: ["Vous êtes responsable de la sécurité de vos identifiants de connexion et de toute activité effectuée depuis votre compte. Informez-nous immédiatement à l’adresse de contact ci-dessous si vous pensez que votre compte a fait l’objet d’un accès non autorisé.", "Nous pouvons suspendre ou fermer les comptes qui enfreignent les présentes conditions, la Politique d’utilisation acceptable ou la loi applicable, ou qui mettent en danger d’autres utilisateurs, les plateformes ou 2kTunes."] },
        { id: "plans", heading: "4. Offres, frais et paiement", body: ["Certains Services nécessitent une offre payante. Les prix, les périodes de facturation et le contenu de chaque offre sont affichés avant le paiement. Les services de promotion et les campagnes sont tarifés séparément et affichés avant tout engagement.", "Sauf disposition légale contraire, les frais déjà payés ne sont pas remboursables pour une période de facturation commencée. Nous vous donnerons un préavis raisonnable avant de modifier le prix d’une offre à laquelle vous êtes abonné."] },
        { id: "royalties", heading: "5. Royalties et retraits", body: ["Les royalties sont créditées sur votre portefeuille après réception et traitement des rapports et paiements des plateformes et partenaires. Les montants affichés avant cette étape sont des estimations.", "Les retraits sont soumis au montant minimum, aux moyens de paiement disponibles, aux frais et aux taux de change affichés dans votre tableau de bord au moment de la demande. Nous pouvons retarder ou retenir des paiements liés à une fraude présumée, à des écoutes artificielles, à des litiges sur les droits ou à des obligations légales, et vous en indiquerons la raison lorsque la loi le permet."] },
        { id: "content", heading: "6. Votre contenu", body: ["Vous conservez tous les droits sur la musique, les pochettes et les autres éléments que vous mettez en ligne. Vous nous accordez les licences décrites dans le Contrat de distribution afin que nous puissions fournir les Services.", "Vous ne devez mettre en ligne que des contenus dont vous êtes propriétaire ou que vous êtes autorisé à distribuer."] },
        { id: "no-guarantee", heading: "7. Aucun résultat garanti", body: ["Les plateformes, éditeurs, curateurs, créateurs et publics prennent leurs propres décisions. Nous ne garantissons aucun nombre d’écoutes, de placements, de mises en avant, d’abonnés ou de revenus."] },
        { id: "liability", heading: "8. Responsabilité", body: ["Nous fournissons les Services avec une compétence et un soin raisonnables. Dans la mesure permise par la loi, nous ne sommes pas responsables des pertes indirectes ou consécutives, ni des actes des plateformes, des prestataires de paiement ou d’autres tiers. Rien dans les présentes conditions ne limite une responsabilité qui ne peut être limitée en vertu de la loi."] },
        { id: "changes", heading: "9. Modifications et résiliation", body: ["Nous pouvons mettre à jour les présentes conditions. En cas de modification substantielle, nous vous en informerons avant son entrée en vigueur. Vous pouvez fermer votre compte à tout moment ; certaines obligations, comme le paiement des royalties acquises, perdurent après la fermeture."] },
        { id: "marketplace", heading: "10. Marketplace des créateurs", body: ["Un artiste peut demander l’offre d’un créateur pour un titre. 2kTunes vérifie chaque demande avant qu’elle n’atteigne le créateur. Le créateur a ensuite 3 jours pour accepter ou refuser. L’artiste paie seulement après l’acceptation du créateur, dans les 7 jours qui suivent ; à défaut, la demande expire et rien n’est débité.", "Les paiements sont conservés par 2kTunes sur un compte interne jusqu’à la vérification du travail. Il s’agit d’une comptabilité interne, et non d’un service de séquestre ou de fiducie réglementé. Une fois la publication envoyée par le créateur, 2kTunes la vérifie, et ce n’est qu’après cette vérification que le paiement est versé au créateur, moins des frais de plateforme de 15 %.", "Il n’y a ni validation automatique ni nombre fixe de révisions. 2kTunes peut demander au créateur de corriger une publication avant de la valider.", "La publication est due dans le délai de l’offre après le paiement. Si elle n’est pas livrée dans ce délai augmenté de 2 jours, la commande est signalée en retard et 2kTunes peut rembourser l’artiste sur son portefeuille 2kTunes. Chaque partie peut ouvrir un litige tant que le paiement est conservé ; 2kTunes l’examine et peut verser le paiement, rembourser l’artiste ou partager le montant.", "Les artistes et les créateurs ne se contactent pas directement. Tous les messages passent par 2kTunes et sont visibles par l’équipe 2kTunes, et les coordonnées (numéros, e-mails, liens et pseudos) sont retirées automatiquement. Nous ne communiquons pas aux artistes les coordonnées ni les pseudos des créateurs.", "Les statistiques des créateurs sont déclaratives, sauf mention vérifiée. Les nombres de vues affichés sur les vidéos de la vitrine sont déclarés par le créateur et ne sont pas vérifiés par 2kTunes. Les créateurs s’engagent sur le contenu décrit dans leur offre, pas sur des résultats."] },
        { id: "offers", heading: "11. Offres et codes promo", body: ["Nous proposons parfois des offres, comme une réduction, un prix fixe ou une période gratuite, et certaines nécessitent un code promo. Les offres et les codes ne se cumulent jamais : si plusieurs peuvent s’appliquer, vous payez le prix le plus bas, et un prix ne descend jamais sous zéro.", "Une offre « première souscription » est réservée aux comptes qui n’ont jamais eu d’offre payante confirmée. Une offre gratuite vous donne l’offre pendant sa période gratuite (ou sa durée normale si aucune période n’est indiquée) ; à son terme, l’offre expire et vous la renouvelez au prix normal. Les offres peuvent avoir une date de fin et des limites sur le nombre total d’utilisations ou par compte."] },
        { id: "referrals", heading: "12. Programme de parrainage", body: ["Vous pouvez inviter d’autres artistes avec votre lien de parrainage. Un parrainage ne compte que pour un tout nouveau compte qui s’inscrit avec votre lien, confirme son adresse e-mail et, sauf indication contraire du programme, souscrit sa première offre payante.", "Vous ne pouvez pas vous parrainer vous-même ni parrainer un autre compte que vous contrôlez. Les récompenses sont plafonnées chaque mois et ajoutées après une période d’attente. Une récompense est soit un crédit sur votre portefeuille 2kTunes, retirable comme vos autres revenus, soit des jours gratuits ajoutés à votre offre, comme indiqué dans votre tableau de bord.", "L’ami que vous invitez bénéficie du prix parrainé sur sa première souscription uniquement. Nous pouvons refuser les parrainages que nous estimons frauduleux ou abusifs, et nous pouvons modifier ou arrêter le programme à tout moment ; les récompenses déjà créditées ne sont pas concernées.", "Vie privée : la page d’invitation n’affiche que votre prénom aux personnes que vous invitez, et vous ne voyez que les initiales de vos amis et le statut de chaque parrainage."] },
        { id: "law", heading: "13. Droit applicable et contact", body: ["Les présentes conditions sont régies par les lois de la République-Unie de Tanzanie. Toute question à leur sujet peut être adressée à support@2ktunes.com."] },
      ],
    },
  },
  privacy: {
    EN: {
      title: "Privacy Policy",
      summary: "What personal data we collect, why, and the choices you have.",
      sections: [
        { id: "who", heading: "1. Who we are", body: ["2kTunes is responsible for the personal data described in this policy. We handle personal data in line with the Personal Data Protection Act, 2022 of Tanzania and other laws that apply to you."] },
        { id: "collect", heading: "2. What we collect", body: ["Account data: name, email, password (stored only as a secure hash), account type and profile details you add.", "Release data: music, artwork, credits and metadata, including names of collaborators you add.", "Payout data: mobile money numbers, bank details and tax information you provide for withdrawals.", "Usage data: log and device information, and approximate location derived from IP address, used to secure and improve the Services."] },
        { id: "use", heading: "3. How we use it", body: ["To provide the Services: delivering releases, calculating and paying royalties, running campaigns you request and supporting you.", "To keep the platform safe: preventing fraud, artificial streaming and unauthorised access.", "To meet legal obligations such as tax and anti-money-laundering requirements.", "To send service messages. Marketing messages are optional and you can opt out at any time."] },
        { id: "share", heading: "4. Who we share it with", body: ["Stores and distribution partners receive release metadata, including artist and contributor names, so your music can be delivered.", "Payment providers receive the details needed to process your withdrawals.", "Service providers (hosting, email, analytics) process data on our instructions.", "Authorities, where the law requires. We do not sell your personal data."] },
        { id: "transfers", heading: "5. International transfers", body: ["Some partners and providers are located outside Tanzania. Where data is transferred, we use appropriate safeguards required by law."] },
        { id: "retention", heading: "6. How long we keep it", body: ["We keep account data while your account is open. Financial records are kept for as long as tax and accounting law requires, even after you close your account."] },
        { id: "rights", heading: "7. Your rights", body: ["You can ask to access, correct or delete your personal data, object to certain uses, or withdraw consent where we rely on it. Contact support@2ktunes.com. You may also complain to the Personal Data Protection Commission of Tanzania."] },
        { id: "security", heading: "8. Security", body: ["We use technical and organisational measures to protect your data, including encryption in transit and hashed passwords. No system is perfectly secure; tell us promptly if you suspect a problem."] },
        { id: "smart-links", heading: "9. Smart links and pre-save", body: ["When someone opens an artist's smart link, we record the visit without storing their IP address or setting cookies: only a salted visitor code that changes every day, the country and the type of device. Artists see these totals, never individual visitors.", "If you leave your email on a pre-save page, we use it only to tell you when that release is out, and you can unsubscribe at any time."] },
        { id: "referrals", heading: "10. Referrals and offers", body: ["If you join through a referral link, the person who invited you sees only your initials and whether you joined, qualified or earned them a reward. The invite page shows only the first name of the person who invited you.", "We keep referral and offer records to apply prices, pay rewards and prevent abuse."] },
      ],
    },
    SW: {
      title: "Sera ya Faragha",
      summary: "Taarifa binafsi tunazokusanya, kwa nini, na chaguo ulizonazo.",
      sections: [
        { id: "who", heading: "1. Sisi ni nani", body: ["2kTunes inawajibika kwa taarifa binafsi zilizoelezwa kwenye sera hii. Tunashughulikia taarifa binafsi kwa mujibu wa Sheria ya Ulinzi wa Taarifa Binafsi ya Tanzania, 2022 na sheria nyingine zinazokuhusu."] },
        { id: "collect", heading: "2. Tunachokusanya", body: ["Taarifa za akaunti: jina, barua pepe, nenosiri (linahifadhiwa kama hash salama tu), aina ya akaunti na taarifa za wasifu unazoongeza.", "Taarifa za matoleo: muziki, picha, wahusika na taarifa za wimbo, yakiwemo majina ya washirika unaowaongeza.", "Taarifa za malipo: namba za pesa ya simu, taarifa za benki na kodi unazotoa kwa ajili ya kutoa pesa.", "Taarifa za matumizi: kumbukumbu na taarifa za kifaa, na eneo la takriban kutokana na anwani ya IP, kwa ajili ya usalama na kuboresha Huduma."] },
        { id: "use", heading: "3. Tunavyozitumia", body: ["Kutoa Huduma: kusambaza matoleo, kukokotoa na kulipa mirabaha, kuendesha kampeni unazoomba na kukusaidia.", "Kulinda jukwaa: kuzuia udanganyifu, usikilizaji wa kughushi na kuingia bila ruhusa.", "Kutimiza wajibu wa kisheria kama kodi na kuzuia utakatishaji fedha.", "Kutuma ujumbe wa huduma. Ujumbe wa matangazo ni wa hiari na unaweza kujiondoa wakati wowote."] },
        { id: "share", heading: "4. Tunashirikisha na nani", body: ["Maduka na washirika wa usambazaji hupokea taarifa za toleo, yakiwemo majina ya wasanii na wachangiaji, ili muziki wako usambazwe.", "Watoa huduma za malipo hupokea taarifa zinazohitajika kushughulikia utoaji wa pesa.", "Watoa huduma (hifadhi, barua pepe, takwimu) hushughulikia taarifa kwa maelekezo yetu.", "Mamlaka, pale sheria inapotaka. Hatuuzi taarifa zako binafsi."] },
        { id: "transfers", heading: "5. Uhamisho nje ya nchi", body: ["Baadhi ya washirika na watoa huduma wako nje ya Tanzania. Taarifa zinapohamishwa, tunatumia kinga zinazotakiwa na sheria."] },
        { id: "retention", heading: "6. Tunazihifadhi kwa muda gani", body: ["Tunahifadhi taarifa za akaunti wakati akaunti yako iko wazi. Kumbukumbu za fedha zinahifadhiwa kwa muda unaotakiwa na sheria za kodi na uhasibu, hata baada ya kufunga akaunti."] },
        { id: "rights", heading: "7. Haki zako", body: ["Unaweza kuomba kuona, kusahihisha au kufuta taarifa zako binafsi, kupinga matumizi fulani, au kuondoa ridhaa pale tunapoitegemea. Wasiliana na support@2ktunes.com. Unaweza pia kuwasilisha malalamiko kwa Tume ya Ulinzi wa Taarifa Binafsi ya Tanzania."] },
        { id: "security", heading: "8. Usalama", body: ["Tunatumia hatua za kiufundi na za kiutawala kulinda taarifa zako, ikiwemo usimbaji fiche wakati wa kusafirisha na manenosiri yaliyohashiwa. Hakuna mfumo ulio salama kikamilifu; tujulishe haraka ukishuku tatizo."] },
        { id: "smart-links", heading: "9. Viungo mahiri na pre-save", body: ["Mtu anapofungua kiungo mahiri cha msanii, tunarekodi ziara bila kuhifadhi anwani yake ya IP wala kuweka vidakuzi (cookies): ni msimbo wa mgeni unaobadilika kila siku, nchi na aina ya kifaa tu. Wasanii wanaona jumla hizi tu, si wageni mmoja mmoja.", "Ukiacha barua pepe yako kwenye ukurasa wa pre-save, tunaitumia tu kukujulisha toleo hilo likitoka, na unaweza kujiondoa wakati wowote."] },
        { id: "referrals", heading: "10. Mialiko na ofa", body: ["Ukijiunga kupitia kiungo cha mwaliko, aliyekualika anaona herufi zako za kwanza tu na kama umejiunga, umefuzu au umemletea zawadi. Ukurasa wa mwaliko unaonyesha jina la kwanza tu la aliyekualika.", "Tunahifadhi kumbukumbu za mialiko na ofa ili kutumia bei, kulipa zawadi na kuzuia matumizi mabaya."] },
      ],
    },
    FR: {
      title: "Politique de confidentialité",
      summary: "Les données personnelles que nous collectons, pourquoi, et les choix dont vous disposez.",
      sections: [
        { id: "who", heading: "1. Qui sommes-nous", body: ["2kTunes est responsable des données personnelles décrites dans la présente politique. Nous traitons les données personnelles conformément à la loi tanzanienne de 2022 sur la protection des données personnelles (Personal Data Protection Act, 2022) et aux autres lois qui vous sont applicables."] },
        { id: "collect", heading: "2. Ce que nous collectons", body: ["Données de compte : nom, e-mail, mot de passe (conservé uniquement sous forme de hachage sécurisé), type de compte et informations de profil que vous ajoutez.", "Données de sortie : musique, pochettes, crédits et métadonnées, y compris les noms des collaborateurs que vous ajoutez.", "Données de paiement : numéros mobile money, coordonnées bancaires et informations fiscales que vous fournissez pour les retraits.", "Données d’utilisation : journaux et informations sur l’appareil, ainsi que la localisation approximative déduite de l’adresse IP, utilisés pour sécuriser et améliorer les Services."] },
        { id: "use", heading: "3. Comment nous les utilisons", body: ["Pour fournir les Services : livrer les sorties, calculer et verser les royalties, mener les campagnes que vous demandez et vous assister.", "Pour assurer la sécurité de la plateforme : prévenir la fraude, les écoutes artificielles et les accès non autorisés.", "Pour respecter nos obligations légales, notamment en matière fiscale et de lutte contre le blanchiment d’argent.", "Pour vous envoyer des messages de service. Les messages marketing sont facultatifs et vous pouvez vous désabonner à tout moment."] },
        { id: "share", heading: "4. Avec qui nous les partageons", body: ["Les plateformes et partenaires de distribution reçoivent les métadonnées des sorties, y compris les noms des artistes et contributeurs, afin que votre musique puisse être livrée.", "Les prestataires de paiement reçoivent les informations nécessaires au traitement de vos retraits.", "Les prestataires de services (hébergement, e-mail, statistiques) traitent les données selon nos instructions.", "Les autorités, lorsque la loi l’exige. Nous ne vendons pas vos données personnelles."] },
        { id: "transfers", heading: "5. Transferts internationaux", body: ["Certains partenaires et prestataires sont situés hors de Tanzanie. En cas de transfert de données, nous appliquons les garanties appropriées exigées par la loi."] },
        { id: "retention", heading: "6. Durée de conservation", body: ["Nous conservons les données de compte tant que votre compte est ouvert. Les documents financiers sont conservés aussi longtemps que l’exige la législation fiscale et comptable, y compris après la fermeture de votre compte."] },
        { id: "rights", heading: "7. Vos droits", body: ["Vous pouvez demander à accéder à vos données personnelles, à les rectifier ou à les supprimer, vous opposer à certaines utilisations, ou retirer votre consentement lorsque nous nous fondons sur celui-ci. Contactez support@2ktunes.com. Vous pouvez également déposer une plainte auprès de la Personal Data Protection Commission de Tanzanie."] },
        { id: "security", heading: "8. Sécurité", body: ["Nous mettons en œuvre des mesures techniques et organisationnelles pour protéger vos données, notamment le chiffrement en transit et le hachage des mots de passe. Aucun système n’est parfaitement sûr ; prévenez-nous rapidement si vous soupçonnez un problème."] },
        { id: "smart-links", heading: "9. Smart links et pré-enregistrement", body: ["Lorsqu’une personne ouvre le smart link d’un artiste, nous enregistrons la visite sans conserver son adresse IP ni déposer de cookies : uniquement un code visiteur salé qui change chaque jour, le pays et le type d’appareil. Les artistes voient ces totaux, jamais les visiteurs individuels.", "Si vous laissez votre e-mail sur une page de pré-enregistrement (pre-save), nous l’utilisons uniquement pour vous prévenir de la sortie concernée, et vous pouvez vous désabonner à tout moment."] },
        { id: "referrals", heading: "10. Parrainage et offres", body: ["Si vous vous inscrivez via un lien de parrainage, la personne qui vous a invité ne voit que vos initiales et si vous vous êtes inscrit, qualifié ou si vous lui avez fait gagner une récompense. La page d’invitation n’affiche que le prénom de la personne qui vous a invité.", "Nous conservons les données de parrainage et d’offres pour appliquer les prix, verser les récompenses et prévenir les abus."] },
      ],
    },
  },
  "distribution-agreement": {
    EN: {
      title: "Distribution Agreement",
      summary: "The licence you give 2kTunes to deliver your music, and what each side is responsible for.",
      sections: [
        { id: "scope", heading: "1. Scope", body: ["This agreement applies whenever you submit a release to 2kTunes for distribution. It supplements the Terms of Service."] },
        { id: "licence", heading: "2. Licence you grant", body: ["You grant 2kTunes a non-exclusive, worldwide licence, for the territories and stores you select, to reproduce, deliver, distribute, make available and promote your releases through stores and distribution partners, and to collect income from them on your behalf.", "You keep ownership of your masters and compositions. 2kTunes acquires no ownership rights in your music."] },
        { id: "warranties", heading: "3. Your promises", body: ["You confirm that you own or control all rights needed for each release (including master, composition, samples, artwork and performer consents) and that distributing it will not infringe anyone's rights.", "You confirm that the metadata you provide is accurate."] },
        { id: "our-duties", heading: "4. What we do", body: ["We review releases for store compliance, deliver them to selected destinations through our distribution partners, report earnings to you, and pay your share as described in your plan and dashboard.", "Stores decide independently whether to accept, feature or remove content."] },
        { id: "revenue", heading: "5. Earnings and splits", body: ["Your share of income, and any commission or fee, is shown in your plan and dashboard. Where you set royalty splits, you instruct us to pay each collaborator their share, and you confirm the split reflects your agreements with them."] },
        { id: "takedowns", heading: "6. Takedowns", body: ["You can request a takedown at any time. We may remove releases that breach this agreement, receive a valid rights claim, or show signs of artificial streaming. Stores' own removal timelines apply."] },
        { id: "claims", heading: "7. Rights claims", body: ["If a third party claims rights in your release, we may pause distribution and hold related earnings until the claim is resolved. You agree to cooperate and to cover losses caused by a breach of your promises."] },
        { id: "term", heading: "8. Term and ending", body: ["This agreement continues for each release until it is taken down from all stores. Earned royalties remain payable after termination, subject to any hold under section 7."] },
      ],
    },
    SW: {
      title: "Mkataba wa Usambazaji",
      summary: "Leseni unayoipa 2kTunes kusambaza muziki wako, na wajibu wa kila upande.",
      sections: [
        { id: "scope", heading: "1. Wigo", body: ["Mkataba huu unatumika kila unapowasilisha toleo kwa 2kTunes kwa ajili ya usambazaji. Unaongeza juu ya Masharti ya Huduma."] },
        { id: "licence", heading: "2. Leseni unayotoa", body: ["Unaipa 2kTunes leseni isiyo ya upekee, ya dunia nzima, kwa nchi na maduka unayochagua, kunakili, kuwasilisha, kusambaza, kupatikana na kutangaza matoleo yako kupitia maduka na washirika wa usambazaji, na kukusanya mapato kutoka kwao kwa niaba yako.", "Unabaki na umiliki wa master na utunzi wako. 2kTunes haipati haki yoyote ya umiliki wa muziki wako."] },
        { id: "warranties", heading: "3. Ahadi zako", body: ["Unathibitisha kuwa unamiliki au kudhibiti haki zote zinazohitajika kwa kila toleo (ikiwemo master, utunzi, sampuli, picha na ridhaa za waimbaji) na kwamba kulisambaza hakutakiuka haki za mtu yeyote.", "Unathibitisha kuwa taarifa unazotoa ni sahihi."] },
        { id: "our-duties", heading: "4. Tunachofanya", body: ["Tunakagua matoleo kulingana na masharti ya maduka, tunayasambaza kwenye maeneo yaliyochaguliwa kupitia washirika wetu, tunakuripotia mapato, na tunalipa sehemu yako kama ilivyoelezwa kwenye kifurushi na dashibodi.", "Maduka huamua yenyewe kama yatakubali, kuchagua au kuondoa maudhui."] },
        { id: "revenue", heading: "5. Mapato na mgawanyo", body: ["Sehemu yako ya mapato, na kamisheni au ada yoyote, inaonyeshwa kwenye kifurushi na dashibodi. Unapoweka mgawanyo wa mirabaha, unatuelekeza kumlipa kila mshirika sehemu yake, na unathibitisha kuwa mgawanyo unaendana na makubaliano yenu."] },
        { id: "takedowns", heading: "6. Kuondoa matoleo", body: ["Unaweza kuomba toleo liondolewe wakati wowote. Tunaweza kuondoa matoleo yanayokiuka mkataba huu, yanayopata dai halali la haki, au yanayoonyesha dalili za usikilizaji wa kughushi. Ratiba za maduka za kuondoa zinatumika."] },
        { id: "claims", heading: "7. Madai ya haki", body: ["Mtu mwingine akidai haki kwenye toleo lako, tunaweza kusimamisha usambazaji na kushikilia mapato yanayohusika hadi dai litatuliwe. Unakubali kushirikiana na kufidia hasara zinazotokana na kuvunja ahadi zako."] },
        { id: "term", heading: "8. Muda na kumalizika", body: ["Mkataba huu unaendelea kwa kila toleo hadi liondolewe kwenye maduka yote. Mirabaha iliyopatikana inaendelea kulipwa baada ya kumalizika, kwa kuzingatia ushikiliaji wowote chini ya kifungu cha 7."] },
      ],
    },
    FR: {
      title: "Contrat de distribution",
      summary: "La licence que vous accordez à 2kTunes pour livrer votre musique, et les responsabilités de chaque partie.",
      sections: [
        { id: "scope", heading: "1. Champ d’application", body: ["Le présent contrat s’applique chaque fois que vous soumettez une sortie à 2kTunes pour distribution. Il complète les Conditions d’utilisation."] },
        { id: "licence", heading: "2. Licence que vous accordez", body: ["Vous accordez à 2kTunes une licence non exclusive et mondiale, pour les territoires et plateformes que vous sélectionnez, afin de reproduire, livrer, distribuer, mettre à disposition et promouvoir vos sorties via les plateformes et partenaires de distribution, et d’en percevoir les revenus en votre nom.", "Vous conservez la propriété de vos masters et de vos compositions. 2kTunes n’acquiert aucun droit de propriété sur votre musique."] },
        { id: "warranties", heading: "3. Vos engagements", body: ["Vous confirmez détenir ou contrôler tous les droits nécessaires pour chaque sortie (y compris le master, la composition, les samples, la pochette et les autorisations des interprètes) et que sa distribution ne portera atteinte aux droits de personne.", "Vous confirmez que les métadonnées que vous fournissez sont exactes."] },
        { id: "our-duties", heading: "4. Ce que nous faisons", body: ["Nous vérifions la conformité des sorties aux règles des plateformes, les livrons aux destinations choisies via nos partenaires de distribution, vous rendons compte des revenus et vous versons votre part comme indiqué dans votre offre et votre tableau de bord.", "Les plateformes décident en toute indépendance d’accepter, de mettre en avant ou de retirer un contenu."] },
        { id: "revenue", heading: "5. Revenus et partages", body: ["Votre part des revenus, ainsi que toute commission ou tout frais, est indiquée dans votre offre et votre tableau de bord. Lorsque vous définissez des partages de revenus, vous nous donnez instruction de verser à chaque collaborateur sa part, et vous confirmez que ce partage reflète vos accords avec eux."] },
        { id: "takedowns", heading: "6. Retraits de sorties", body: ["Vous pouvez demander le retrait d’une sortie à tout moment. Nous pouvons retirer les sorties qui enfreignent le présent contrat, font l’objet d’une réclamation de droits valable ou présentent des signes d’écoutes artificielles. Les délais de retrait propres à chaque plateforme s’appliquent."] },
        { id: "claims", heading: "7. Réclamations de droits", body: ["Si un tiers revendique des droits sur votre sortie, nous pouvons suspendre la distribution et retenir les revenus concernés jusqu’à la résolution de la réclamation. Vous acceptez de coopérer et de couvrir les pertes causées par un manquement à vos engagements."] },
        { id: "term", heading: "8. Durée et fin du contrat", body: ["Le présent contrat reste en vigueur pour chaque sortie jusqu’à son retrait de toutes les plateformes. Les royalties acquises restent dues après la résiliation, sous réserve de toute retenue prévue à l’article 7."] },
      ],
    },
  },
  "acceptable-use": {
    EN: {
      title: "Acceptable Use Policy",
      summary: "What you may not do with 2kTunes, so the platform stays trusted by stores, artists and fans.",
      sections: [
        { id: "streams", heading: "1. No artificial streaming", body: ["Do not use or buy bots, stream farms, paid playlist placements that guarantee plays, or any other means of inflating streams, followers or engagement. Releases involved may be removed and related earnings withheld."] },
        { id: "rights", heading: "2. Only content you have rights to", body: ["Do not upload music, samples, beats or artwork you don't own or have permission to use. Do not impersonate other artists or use misleading artist names or titles."] },
        { id: "content", heading: "3. Prohibited content", body: ["Do not distribute content that is illegal, promotes violence or hatred, sexually exploits minors, or violates store content policies. Explicit content must be marked as explicit."] },
        { id: "campaigns", heading: "4. Honest campaigns", body: ["Creators must disclose paid promotion using platform tools and follow advertising rules. Artists must not ask creators to hide that a post is paid. Campaign briefs may not require deceptive or harmful content."] },
        { id: "spam", heading: "5. No spam or low-quality mass uploads", body: ["Do not upload duplicate releases, keyword-stuffed titles, or large volumes of low-effort audio intended to game store algorithms."] },
        { id: "security", heading: "6. Platform security", body: ["Do not attempt to access other accounts, probe or disrupt our systems, or scrape data without permission."] },
        { id: "enforcement", heading: "7. Enforcement", body: ["We may warn, restrict features, remove releases, withhold affected earnings or close accounts that breach this policy, depending on severity. Report concerns to support@2ktunes.com."] },
      ],
    },
    SW: {
      title: "Sera ya Matumizi Yanayokubalika",
      summary: "Usichoruhusiwa kufanya na 2kTunes, ili jukwaa liendelee kuaminiwa na maduka, wasanii na mashabiki.",
      sections: [
        { id: "streams", heading: "1. Hakuna usikilizaji wa kughushi", body: ["Usitumie wala kununua roboti, mashamba ya usikilizaji, nafasi za kulipia kwenye orodha zinazohakikisha usikilizaji, au njia nyingine yoyote ya kuongeza usikilizaji, wafuasi au mwitikio kwa udanganyifu. Matoleo yanayohusika yanaweza kuondolewa na mapato yake kuzuiliwa."] },
        { id: "rights", heading: "2. Maudhui unayoyamiliki tu", body: ["Usipakie muziki, sampuli, midundo au picha usiyomiliki au huna ruhusa kuitumia. Usijifanye msanii mwingine wala kutumia majina ya wasanii au nyimbo yanayopotosha."] },
        { id: "content", heading: "3. Maudhui yaliyokatazwa", body: ["Usisambaze maudhui yaliyo kinyume cha sheria, yanayochochea vurugu au chuki, yanayowanyanyasa watoto kingono, au yanayokiuka sera za maduka. Maudhui yenye maneno makali lazima yawekewe alama hiyo."] },
        { id: "campaigns", heading: "4. Kampeni za uaminifu", body: ["Watengeneza maudhui lazima waonyeshe matangazo ya kulipia kwa kutumia zana za jukwaa na kufuata sheria za matangazo. Wasanii hawaruhusiwi kuwaomba watengeneza maudhui kuficha kuwa chapisho limelipiwa. Maelekezo ya kampeni hayawezi kudai maudhui ya udanganyifu au yenye madhara."] },
        { id: "spam", heading: "5. Hakuna upakiaji wa taka", body: ["Usipakie matoleo yanayojirudia, majina yaliyojazwa maneno ya kutafutia, au sauti nyingi za ubora wa chini zinazolenga kudanganya mifumo ya maduka."] },
        { id: "security", heading: "6. Usalama wa jukwaa", body: ["Usijaribu kuingia kwenye akaunti za wengine, kuchunguza au kuvuruga mifumo yetu, au kuchota taarifa bila ruhusa."] },
        { id: "enforcement", heading: "7. Utekelezaji", body: ["Tunaweza kuonya, kuzuia huduma fulani, kuondoa matoleo, kuzuia mapato yanayohusika au kufunga akaunti zinazokiuka sera hii, kulingana na uzito wa kosa. Ripoti wasiwasi kwa support@2ktunes.com."] },
      ],
    },
    FR: {
      title: "Politique d’utilisation acceptable",
      summary: "Ce que vous ne pouvez pas faire avec 2kTunes, pour que la plateforme conserve la confiance des plateformes de streaming, des artistes et des fans.",
      sections: [
        { id: "streams", heading: "1. Pas d’écoutes artificielles", body: ["N’utilisez pas et n’achetez pas de bots, de fermes d’écoutes, de placements payants en playlist garantissant des écoutes, ni aucun autre moyen de gonfler les écoutes, les abonnés ou l’engagement. Les sorties concernées peuvent être retirées et les revenus associés retenus."] },
        { id: "rights", heading: "2. Uniquement des contenus dont vous détenez les droits", body: ["Ne mettez pas en ligne de musique, de samples, de beats ou de pochettes dont vous n’êtes pas propriétaire ou que vous n’êtes pas autorisé à utiliser. N’usurpez pas l’identité d’autres artistes et n’utilisez pas de noms d’artistes ou de titres trompeurs."] },
        { id: "content", heading: "3. Contenus interdits", body: ["Ne distribuez pas de contenus illégaux, incitant à la violence ou à la haine, exploitant sexuellement des mineurs, ou contraires aux règles de contenu des plateformes. Les contenus explicites doivent être signalés comme tels."] },
        { id: "campaigns", heading: "4. Des campagnes honnêtes", body: ["Les créateurs doivent signaler toute promotion rémunérée à l’aide des outils des plateformes et respecter les règles en matière de publicité. Les artistes ne doivent pas demander aux créateurs de dissimuler qu’une publication est rémunérée. Les briefs de campagne ne peuvent exiger de contenu trompeur ou préjudiciable."] },
        { id: "spam", heading: "5. Pas de spam ni d’envois massifs de faible qualité", body: ["Ne mettez pas en ligne de sorties en double, de titres bourrés de mots-clés ou de grands volumes d’audio bâclé destinés à manipuler les algorithmes des plateformes."] },
        { id: "security", heading: "6. Sécurité de la plateforme", body: ["Ne tentez pas d’accéder à d’autres comptes, de sonder ou de perturber nos systèmes, ni d’extraire des données sans autorisation."] },
        { id: "enforcement", heading: "7. Application", body: ["Selon la gravité, nous pouvons adresser un avertissement, restreindre des fonctionnalités, retirer des sorties, retenir les revenus concernés ou fermer les comptes qui enfreignent la présente politique. Signalez tout problème à support@2ktunes.com."] },
      ],
    },
  },
};
