import type { Localized } from "@/lib/LanguageContext";
import type { PageCopy } from "../MarketingPage";

export const PROMOTION: Localized<PageCopy> = {
  EN: {
    meta: {
      title: "Promotion",
      description: "Editorial pitching, independent curators, creator campaigns and advertising — clearly explained, never guaranteed.",
    },
    hero: {
      eyebrow: "Promotion",
      title: "Reach listeners, honestly.",
      lede: "Getting on a store is the start. 2kTunes lays out four distinct ways to find an audience — two of them available today — and tells you plainly who decides, what you pay for and what no one can promise.",
      secondary: { label: "Creator campaigns", to: "/creators" },
      visual: "campaign",
    },
    sections: [
      {
        type: "compare",
        tone: "raised",
        eyebrow: "Four routes",
        title: "Know exactly what you're getting.",
        lede: "Promotion is often sold as one vague package. We keep the four routes separate so you can choose with clear expectations.",
        caption: "Comparison of promotion options",
        headers: ["Route", "What it is", "Who decides", "Guaranteed result?"],
        rows: [
          {
            name: "Editorial pitching",
            what: "A pitch for store editors to consider an upcoming release.",
            who: "Store editorial teams",
            guaranteed: "No",
          },
          {
            name: "Independent curators",
            what: "Not available yet. Your track would be offered to independent playlist curators and blogs for review.",
            who: "Each curator",
            guaranteed: "No — you pay for review",
          },
          {
            name: "Creator campaigns",
            what: "You order a package from a creator, who publishes content using your song, disclosed as promotion.",
            who: "You choose the creator and approve the post; the creator accepts or declines the order",
            guaranteed: "Posts published, not views",
          },
          {
            name: "Advertising",
            what: "Not available yet. Paid ads on platforms you choose, with your budget and target audience.",
            who: "You, within platform ad rules",
            guaranteed: "Ad delivery, not streams",
          },
        ],
        note: "Editorial pitching and creator campaigns are available today; independent curators and advertising are not available yet. We never buy streams, followers or playlist spots, and we remove any curator or creator who does. Artificial streaming can get your release removed from stores.",
      },
      {
        type: "features",
        tone: "dark",
        eyebrow: "In detail",
        title: "How each route works.",
        columns: 2,
        items: [
          {
            icon: "list",
            tag: "Included",
            title: "Editorial pitching",
            body: "For eligible stores, submit one upcoming song with genre, mood, language and story. We format the pitch the way editors ask for it. Editors are independent and most pitches are not selected — that's normal.",
          },
          {
            icon: "headphones",
            tag: "Not available yet",
            title: "Independent curator services",
            body: "This service isn't available yet. When it is: choose curators by genre and region. Each one listens and decides whether to add or write about your track, and leaves feedback either way. Your fee covers their time, not a placement.",
          },
          {
            icon: "video",
            tag: "Paid campaign",
            title: "Creator campaigns",
            body: "Browse reviewed creators and order a package at the price they set. 2kTunes holds your payment until you approve the post or the review window passes, and every post must be labelled as paid promotion in line with platform rules.",
          },
          {
            icon: "megaphone",
            tag: "Not available yet",
            title: "Advertising",
            body: "This service isn't available yet. When it is: promote a release with ads that lead to a smart link or store page. You control the budget, dates and audience; reporting shows spend and ad results.",
          },
        ],
      },
      {
        type: "split",
        tone: "light",
        eyebrow: "Release planning",
        title: "Promotion works best when it's planned.",
        lede: "Your dashboard lines up the release date, pitch deadline and campaign start so each step supports the next.",
        points: ["Pitch deadline reminders", "Pre-release campaign scheduling", "Results per route after release"],
        visual: "analytics",
      },
      {
        type: "faq",
        tone: "dark",
        eyebrow: "Promotion FAQ",
        title: "Straight answers",
        items: [
          { q: "Will pitching get me on a playlist?", a: "Not necessarily. Editors receive far more pitches than they can feature. A good pitch improves your chances; it doesn't decide the outcome." },
          { q: "Do creators have to say they were paid?", a: "Yes. Every campaign post must be disclosed as paid promotion according to the platform's rules and local advertising law." },
          { q: "What happens if a creator doesn't post?", a: "Your payment is held by 2kTunes and only released to the creator when you approve the post, or when the review window passes without a response. If you can't agree, 2kTunes staff resolve the dispute." },
        ],
        link: { label: "Read the Acceptable Use Policy", to: "/legal/acceptable-use" },
      },
    ],
    cta: { title: "Release first. Then let's find your listeners.", secondary: { label: "For creators", to: "/creators" } },
  },
  SW: {
    meta: {
      title: "Utangazaji",
      description: "Kuwasilisha kwa wahariri, wachaguzi huru, kampeni za watengeneza maudhui na matangazo — yameelezwa wazi, bila ahadi za uongo.",
    },
    hero: {
      eyebrow: "Utangazaji",
      title: "Fikia wasikilizaji, kwa uaminifu.",
      lede: "Kuingia dukani ni mwanzo tu. 2kTunes inaeleza njia nne tofauti za kupata hadhira — mbili kati yake zinapatikana sasa — na inakueleza wazi nani anaamua, unalipia nini na nini hakuna anayeweza kuahidi.",
      secondary: { label: "Kampeni za watengeneza maudhui", to: "/creators" },
      visual: "campaign",
    },
    sections: [
      {
        type: "compare",
        tone: "raised",
        eyebrow: "Njia nne",
        title: "Jua hasa unachopata.",
        lede: "Utangazaji mara nyingi huuzwa kama kifurushi kisicho wazi. Sisi tunatenganisha njia nne ili uchague ukiwa na matarajio sahihi.",
        caption: "Ulinganisho wa njia za utangazaji",
        headers: ["Njia", "Ni nini", "Nani anaamua", "Matokeo yamehakikishwa?"],
        rows: [
          { name: "Kuwasilisha kwa wahariri", what: "Ombi kwa wahariri wa maduka kuzingatia toleo linalokuja.", who: "Timu za wahariri wa maduka", guaranteed: "Hapana" },
          { name: "Wachaguzi huru", what: "Bado haipatikani. Wimbo wako utapelekwa kwa wachaguzi huru wa orodha na blogu kwa ukaguzi.", who: "Kila mchaguzi", guaranteed: "Hapana — unalipia ukaguzi" },
          { name: "Kampeni za watengeneza maudhui", what: "Unaagiza kifurushi kutoka kwa mtengeneza maudhui, naye anaweka maudhui yanayotumia wimbo wako, yakionyeshwa wazi kuwa tangazo.", who: "Wewe unamchagua na kuidhinisha chapisho; yeye anakubali au kukataa agizo", guaranteed: "Machapisho, si idadi ya watazamaji" },
          { name: "Matangazo", what: "Bado haipatikani. Matangazo ya kulipia kwenye majukwaa unayochagua, kwa bajeti na hadhira yako.", who: "Wewe, ndani ya sheria za jukwaa", guaranteed: "Matangazo kuonyeshwa, si usikilizaji" },
        ],
        note: "Kuwasilisha kwa wahariri na kampeni za watengeneza maudhui vinapatikana sasa; wachaguzi huru na matangazo bado hayapatikani. Hatununui usikilizaji, wafuasi wala nafasi kwenye orodha, na tunamwondoa mchaguzi au mtengeneza maudhui yeyote anayefanya hivyo. Usikilizaji wa kughushi unaweza kusababisha toleo lako kuondolewa madukani.",
      },
      {
        type: "features",
        tone: "dark",
        eyebrow: "Kwa undani",
        title: "Jinsi kila njia inavyofanya kazi.",
        columns: 2,
        items: [
          { icon: "list", tag: "Imejumuishwa", title: "Kuwasilisha kwa wahariri", body: "Kwa maduka yanayoruhusu, wasilisha wimbo mmoja unaokuja pamoja na aina, hisia, lugha na hadithi yake. Tunaandaa ombi jinsi wahariri wanavyotaka. Wahariri ni huru na maombi mengi hayachaguliwi — hilo ni kawaida." },
          { icon: "headphones", tag: "Bado haipatikani", title: "Huduma za wachaguzi huru", body: "Huduma hii bado haipatikani. Itakapopatikana: chagua wachaguzi kwa aina ya muziki na eneo. Kila mmoja anasikiliza na kuamua kama ataongeza au kuandika kuhusu wimbo wako, na anatoa maoni kwa vyovyote. Ada yako ni ya muda wao, si nafasi." },
          { icon: "video", tag: "Kampeni ya kulipia", title: "Kampeni za watengeneza maudhui", body: "Pitia watengeneza maudhui waliokaguliwa na uagize kifurushi kwa bei wanayoweka. 2kTunes inashikilia malipo yako hadi uidhinishe chapisho au muda wa ukaguzi upite, na kila chapisho lazima lionyeshwe kuwa ni tangazo la kulipia." },
          { icon: "megaphone", tag: "Bado haipatikani", title: "Matangazo", body: "Huduma hii bado haipatikani. Itakapopatikana: tangaza toleo kwa matangazo yanayoelekeza kwenye kiungo au ukurasa wa duka. Unadhibiti bajeti, tarehe na hadhira; ripoti zinaonyesha matumizi na matokeo." },
        ],
      },
      {
        type: "split",
        tone: "light",
        eyebrow: "Kupanga toleo",
        title: "Utangazaji hufanya kazi vizuri ukipangwa.",
        lede: "Dashibodi yako inapanga tarehe ya kutoa, mwisho wa kuwasilisha kwa wahariri na mwanzo wa kampeni ili kila hatua isaidie inayofuata.",
        points: ["Vikumbusho vya mwisho wa kuwasilisha", "Kupanga kampeni kabla ya kutoa", "Matokeo kwa kila njia baada ya kutoa"],
        visual: "analytics",
      },
      {
        type: "faq",
        tone: "dark",
        eyebrow: "Maswali ya utangazaji",
        title: "Majibu ya moja kwa moja",
        items: [
          { q: "Kuwasilisha kwa wahariri kutaniweka kwenye orodha?", a: "Si lazima. Wahariri hupokea maombi mengi kuliko wanavyoweza kuchagua. Ombi zuri linaongeza nafasi; haliamui matokeo." },
          { q: "Watengeneza maudhui lazima waseme wamelipwa?", a: "Ndiyo. Kila chapisho la kampeni lazima lionyeshwe kuwa tangazo la kulipia kulingana na sheria za jukwaa na sheria za matangazo." },
          { q: "Itakuwaje mtengeneza maudhui asipoweka chapisho?", a: "Malipo yako yanashikiliwa na 2kTunes na yanatolewa kwa mtengeneza maudhui tu ukiidhinisha chapisho, au muda wa ukaguzi ukipita bila jibu. Msipokubaliana, wafanyakazi wa 2kTunes wanatatua mgogoro." },
        ],
        link: { label: "Soma Sera ya Matumizi Yanayokubalika", to: "/legal/acceptable-use" },
      },
    ],
    cta: { title: "Toa kwanza. Kisha tutafute wasikilizaji wako.", secondary: { label: "Kwa watengeneza maudhui", to: "/creators" } },
  },
  FR: {
    meta: {
      title: "Promotion",
      description: "Pitch éditorial, curateurs indépendants, campagnes de créateurs de contenu et publicité — clairement expliqués, jamais garantis.",
    },
    hero: {
      eyebrow: "Promotion",
      title: "Touchez des auditeurs, honnêtement.",
      lede: "Être sur les plateformes n’est qu’un début. 2kTunes présente quatre façons distinctes de trouver un public — dont deux disponibles dès aujourd’hui — et vous dit clairement qui décide, ce que vous payez et ce que personne ne peut promettre.",
      secondary: { label: "Campagnes de créateurs", to: "/creators" },
      visual: "campaign",
    },
    sections: [
      {
        type: "compare",
        tone: "raised",
        eyebrow: "Quatre voies",
        title: "Sachez exactement ce que vous obtenez.",
        lede: "La promotion est souvent vendue comme une offre floue. Nous séparons les quatre voies pour que vous choisissiez avec des attentes claires.",
        caption: "Comparaison des options de promotion",
        headers: ["Voie", "En quoi ça consiste", "Qui décide", "Résultat garanti ?"],
        rows: [
          {
            name: "Pitch éditorial",
            what: "Une proposition soumise aux éditeurs des plateformes pour une sortie à venir.",
            who: "Les équipes éditoriales des plateformes",
            guaranteed: "Non",
          },
          {
            name: "Curateurs indépendants",
            what: "Pas encore disponible. Votre titre serait proposé à des curateurs de playlists et blogs indépendants pour écoute.",
            who: "Chaque curateur",
            guaranteed: "Non — vous payez l’écoute",
          },
          {
            name: "Campagnes de créateurs",
            what: "Vous commandez une offre à un créateur de contenu, qui publie du contenu avec votre titre, signalé comme promotion.",
            who: "Vous choisissez le créateur et validez la publication ; le créateur accepte ou refuse la commande",
            guaranteed: "Publications, pas de vues",
          },
          {
            name: "Publicité",
            what: "Pas encore disponible. Des publicités payantes sur les plateformes de votre choix, avec votre budget et votre public cible.",
            who: "Vous, dans le respect des règles publicitaires",
            guaranteed: "Diffusion des pubs, pas de streams",
          },
        ],
        note: "Le pitch éditorial et les campagnes de créateurs sont disponibles dès aujourd’hui ; les curateurs indépendants et la publicité ne le sont pas encore. Nous n’achetons jamais de streams, d’abonnés ou de places en playlist, et nous excluons tout curateur ou créateur qui le fait. Les streams artificiels peuvent entraîner le retrait de votre sortie des plateformes.",
      },
      {
        type: "features",
        tone: "dark",
        eyebrow: "En détail",
        title: "Comment fonctionne chaque voie.",
        columns: 2,
        items: [
          {
            icon: "list",
            tag: "Inclus",
            title: "Pitch éditorial",
            body: "Pour les plateformes éligibles, soumettez un titre à venir avec son genre, son ambiance, sa langue et son histoire. Nous mettons en forme le pitch comme les éditeurs le demandent. Les éditeurs sont indépendants et la plupart des pitchs ne sont pas retenus — c’est normal.",
          },
          {
            icon: "headphones",
            tag: "Pas encore disponible",
            title: "Curateurs indépendants",
            body: "Ce service n’est pas encore disponible. Une fois lancé : choisissez des curateurs par genre et par région. Chacun écoute, décide d’ajouter ou non votre titre ou d’écrire à son sujet, et vous laisse un retour dans tous les cas. Vous payez leur temps, pas un placement.",
          },
          {
            icon: "video",
            tag: "Campagne payante",
            title: "Campagnes de créateurs",
            body: "Parcourez des créateurs de contenu vérifiés et commandez une offre au prix qu’ils fixent. 2kTunes conserve votre paiement jusqu’à ce que vous validiez la publication ou que le délai de vérification expire, et chaque publication doit être signalée comme promotion payante conformément aux règles des plateformes.",
          },
          {
            icon: "megaphone",
            tag: "Pas encore disponible",
            title: "Publicité",
            body: "Ce service n’est pas encore disponible. Une fois lancé : promouvez une sortie avec des publicités menant vers un lien intelligent ou une page de plateforme. Vous gérez le budget, les dates et le public ; les rapports affichent les dépenses et les résultats.",
          },
        ],
      },
      {
        type: "split",
        tone: "light",
        eyebrow: "Planifier la sortie",
        title: "Une promotion planifiée marche mieux.",
        lede: "Votre tableau de bord aligne la date de sortie, la date limite de pitch et le début de campagne pour que chaque étape serve la suivante.",
        points: ["Rappels de date limite de pitch", "Campagnes programmées avant la sortie", "Résultats par voie après la sortie"],
        visual: "analytics",
      },
      {
        type: "faq",
        tone: "dark",
        eyebrow: "FAQ promotion",
        title: "Des réponses directes",
        items: [
          { q: "Le pitch me fera-t-il entrer dans une playlist ?", a: "Pas forcément. Les éditeurs reçoivent bien plus de pitchs qu’ils ne peuvent en retenir. Un bon pitch améliore vos chances ; il ne décide pas du résultat." },
          { q: "Les créateurs doivent-ils dire qu’ils ont été payés ?", a: "Oui. Chaque publication de campagne doit être signalée comme promotion payante, conformément aux règles de la plateforme et à la loi locale sur la publicité." },
          { q: "Que se passe-t-il si un créateur ne publie pas ?", a: "Votre paiement est conservé par 2kTunes et n’est versé au créateur que lorsque vous validez la publication, ou que le délai de vérification expire sans réponse. En cas de désaccord, l’équipe 2kTunes règle le litige." },
        ],
        link: { label: "Lire la Politique d’utilisation acceptable", to: "/legal/acceptable-use" },
      },
    ],
    cta: { title: "D’abord la sortie. Ensuite, vos auditeurs.", secondary: { label: "Pour les créateurs", to: "/creators" } },
  },
};
