/** Screen copy for the creators marketplace and orders. */

const EN = {
  /* Metrics provenance */
  metricsPartly: "Partly verified",
  metricsVerified: "Verified",
  metricsHint:
    "Self-reported numbers come from the creator and haven't been checked by 2kTunes. Verified numbers were checked by our team or taken from the platform.",
  verifiedOn: (date: string) => `Checked ${date}`,

  /* Creators browse */
  creatorsTitle: "Creators",
  creatorsIntro:
    "Find creators and influencers who can feature your music in their content. You agree the brief and price up front; results such as views or streams are never guaranteed.",
  forCampaign: (id: string) => `Ordering for campaign #${id}`,
  clearCampaign: "Stop ordering for this campaign",
  filtersTitle: "Filter creators",
  search: "Search",
  searchPlaceholder: "Name or keyword",
  platform: "Platform",
  anyPlatform: "Any platform",
  category: "Category",
  anyCategory: "Any category",
  country: "Country",
  countryHint: "Two-letter code, e.g. TZ",
  countryInvalid: "Use a two-letter country code, e.g. TZ or KE.",
  minFollowers: "Minimum followers",
  minFollowersInvalid: "Enter a whole number.",
  verifiedOnly: "Only creators with verified numbers",
  availableOnly: "Only creators taking orders",
  sort: "Sort by",
  sortNewest: "Newest",
  sortFollowers: "Most followers",
  sortPriceLow: "Lowest price",
  sortPriceHigh: "Highest price",
  apply: "Apply filters",
  results: (n: number) => (n === 1 ? "1 creator" : `${n} creators`),
  noCreatorsTitle: "No creators found",
  noCreatorsBody: "No approved creators match these filters yet. Try removing a filter or check back later.",
  noCreatorsAtAll: "There are no approved creators on 2kTunes yet. Check back soon.",
  followers: "Followers",
  totalFollowers: (n: string) => `${n} followers`,
  fromPrice: "From",
  noPackages: "No packages yet",
  available: "Taking orders",
  unavailable: "Not taking orders",
  viewProfile: (name: string) => `View ${name}'s profile`,

  /* Creator detail */
  backToCreators: "Creators",
  about: "About",
  noBio: "This creator hasn't written a bio yet.",
  languages: "Languages",
  categories: "Categories",
  turnaround: "Usual turnaround",
  days: (n: number) => (n === 1 ? "1 day" : `${n} days`),
  completedOrders: "Completed orders",
  location: "Location",
  socialTitle: "Social accounts",
  socialIntro: "Each number shows where it came from.",
  noSocial: "No social accounts listed.",
  handle: "Handle",
  avgViews: "Average views",
  engagement: "Engagement rate",
  audience: "Top audience countries",
  notShared: "Not shared",
  openAccount: (platform: string, handle: string) => `${handle} on ${platform} (opens in a new tab)`,
  packagesTitle: "Packages",
  packagesIntro: "Fixed-price offers. You'll describe what you want in the brief.",
  noPackagesBody: "This creator has no active packages right now.",
  deliverable: "What you get",
  orderPackage: "Order this package",
  portfolioTitle: "Past work",
  noPortfolio: "No examples shared yet.",
  views: (n: string) => `${n} views`,
  openExample: (title: string) => `${title} (opens in a new tab)`,
  example: "Example",
  howItWorksTitle: "How ordering works",
  howItWorks1: "Place the order inside one of your campaigns and pay from your 2kTunes wallet.",
  howItWorks2:
    "2kTunes holds your payment in an internal marketplace holding account. The creator is paid only after you accept the delivery.",
  howItWorks3: "If the creator declines or you cancel before they accept, the money goes back to your wallet.",
  howItWorks4: "Creators promise the content described, not results. Views, streams or followers are never guaranteed.",

  /* Order dialog */
  orderDialogTitle: (title: string) => `Order: ${title}`,
  orderDialogIntro: "Orders belong to a campaign so you can track everything for one release together.",
  campaignChoice: "Campaign",
  useExisting: "Add to an existing campaign",
  createNew: "Create a new campaign",
  chooseCampaign: "Choose a campaign",
  noOpenCampaigns: "You have no open campaigns yet — create one below.",
  campaignTitle: "Campaign title",
  campaignTitleRequired: "Give the campaign a title.",
  campaignType: "Campaign type",
  release: "Release",
  noRelease: "No specific release",
  brief: "Brief",
  briefHint: "What should the creator make? Include the song section, hashtags, dos and don'ts, and deadlines.",
  placeOrder: "Create order",
  orderCreated: "Order created",
  orderCreatedBody: "Review it and pay from your wallet to send it.",
  campaignRequired: "Choose a campaign.",
  payNext: "You'll pay on the next screen. Nothing is charged yet.",
  campaignKept: "The campaign was created. Fix the problem and try again — it will be reused.",

  /* Orders list */
  ordersTitle: "Orders",
  ordersIntro: "Everything you've ordered from creators and 2kTunes services, and work you've been hired for.",
  asBuyer: "As buyer",
  asCreator: "As creator",
  ordersTabs: "Order role",
  statusFilter: "Filter by status",
  allStatuses: "All",
  noOrdersTitle: "No orders yet",
  noOrdersBuyer: "Orders you place with creators or for promotion services will appear here.",
  noOrdersCreator: "Paid orders from artists will appear here.",
  noOrdersFiltered: "No orders with this status.",
  findCreators: "Find creators",
  colOrder: "Order",
  colWith: "With",
  colStatus: "Status",
  colPrice: "Price",
  colYourPayout: "Your payout",
  colCreated: "Created",
  ordersCaption: "Orders",
  serviceBy2k: "2kTunes service",

  /* Order detail */
  backToOrders: "Orders",
  orderRef: (ref: string) => `Reference ${ref}`,
  summary: "Summary",
  creator: "Creator",
  service: "Service",
  track: "Track",
  price: "Price",
  platformFee: "Platform fee",
  yourPayout: "Your payout",
  due: "Due",
  created: "Created",
  paid: "Paid",
  acceptedAt: "Accepted",
  submittedAt: "Submitted",
  completedAt: "Completed",
  revisions: "Revisions requested",
  campaign: "Campaign",
  viewCampaign: (id: number) => `Campaign #${id}`,
  briefTitle: "Brief",
  noBrief: "No brief was added.",
  submissionTitle: "Delivered work",
  submissionLink: "Open the delivered content (opens in a new tab)",
  submissionNotes: "Notes from the creator",
  disputesTitle: "Disputes",
  disputeOpened: (date: string) => `Opened ${date}`,
  disputeResolved: (date: string) => `Resolved ${date}`,
  resolution: "Resolution",
  messagesTitle: "Messages",
  noMessages: "No messages yet.",
  system: "2kTunes",
  you: "You",
  messageLabel: "Write a message",
  send: "Send",
  messageSent: "Message sent",
  messageRequired: "Write a message first.",
  actionsTitle: "Next steps",
  noActions: "There's nothing for you to do on this order right now.",
  holdingNote:
    "Your payment is held by 2kTunes until you accept the delivery. It is then released to the creator minus the platform fee. Results are not guaranteed.",
  serviceNote:
    "This service is run by the 2kTunes team. We'll mark it complete when it's done. Results are not guaranteed.",
  creatorNote: "You're paid your payout when the artist accepts your delivery.",

  pay: "Pay from wallet",
  payTitle: "Pay for this order?",
  payBody: (amount: string) => `${amount} will move from your wallet into 2kTunes' marketplace holding account.`,
  walletBalance: "Available in your wallet",
  walletLoading: "Checking your wallet…",
  walletNone: (currency: string) => `You have no ${currency} balance.`,
  insufficient: "Your wallet balance is lower than the order price, so this payment will fail.",
  topUpHint: "Go to wallet",
  paidToast: "Paid — the creator has been notified",
  paidServiceToast: "Paid — the 2kTunes team will start work",

  cancel: "Cancel order",
  cancelTitle: "Cancel this order?",
  cancelBodyUnpaid: "Nothing has been paid, so nothing is refunded.",
  cancelBodyPaid: "The creator hasn't accepted yet. Your payment goes back to your wallet.",
  cancelledToast: "Order cancelled",

  complete: "Accept delivery",
  completeTitle: "Accept this delivery?",
  completeBody: "The payment is released to the creator. You can't undo this.",
  completedToast: "Delivery accepted — the creator has been paid",

  revision: "Request a revision",
  revisionTitle: "Request a revision",
  revisionBody: "Explain what needs to change. A limited number of revisions is allowed per order.",
  revisionLabel: "What should change?",
  revisionToast: "Revision requested",

  dispute: "Open a dispute",
  disputeTitle: "Open a dispute",
  disputeBody:
    "Our team reviews disputes within 2 business days. The money stays held until the dispute is resolved.",
  disputeReason: "Reason",
  disputeDetails: "Details",
  disputeDetailsHint: "At least 20 characters. Say what happened and what you expected.",
  disputeDetailsShort: "Write at least 20 characters.",
  disputeReasonRequired: "Choose a reason.",
  disputeToast: "Dispute opened",

  accept: "Accept order",
  acceptTitle: "Accept this order?",
  acceptBody: "You commit to delivering the brief by the due date.",
  acceptedToast: "Order accepted",

  decline: "Decline",
  declineTitle: "Decline this order?",
  declineBody: "The artist's payment is refunded to their wallet.",
  declineReason: "Reason",
  declinedToast: "Order declined",

  submitWork: "Submit work",
  submitTitle: "Submit your work",
  submitBody: "Share the link to the published content. The artist will review it.",
  submitUrl: "Link to the content",
  submitUrlHint: "The full link, starting with https://",
  submitUrlInvalid: "Enter the full link, starting with http:// or https://",
  submitNotes: "Notes",
  submittedToast: "Work submitted",
};

const SW: typeof EN = {
  metricsPartly: "Imethibitishwa kwa sehemu",
  metricsVerified: "Imethibitishwa",
  metricsHint:
    "Takwimu zilizoripotiwa na mtengeneza maudhui mwenyewe hazijakaguliwa na 2kTunes. Takwimu zilizothibitishwa zimekaguliwa na timu yetu au zimetoka kwenye jukwaa husika.",
  verifiedOn: (date) => `Ilikaguliwa ${date}`,

  creatorsTitle: "Watengeneza maudhui",
  creatorsIntro:
    "Tafuta watengeneza maudhui na washawishi wanaoweza kutumia muziki wako kwenye maudhui yao. Mnakubaliana maelekezo na bei mapema; matokeo kama watazamaji au streams hayahakikishwi kamwe.",
  forCampaign: (id) => `Unaagiza kwa kampeni #${id}`,
  clearCampaign: "Acha kuagiza kwa kampeni hii",
  filtersTitle: "Chuja watengeneza maudhui",
  search: "Tafuta",
  searchPlaceholder: "Jina au neno",
  platform: "Jukwaa",
  anyPlatform: "Jukwaa lolote",
  category: "Kundi",
  anyCategory: "Kundi lolote",
  country: "Nchi",
  countryHint: "Msimbo wa herufi mbili, mf. TZ",
  countryInvalid: "Tumia msimbo wa nchi wa herufi mbili, mf. TZ au KE.",
  minFollowers: "Idadi ya chini ya wafuasi",
  minFollowersInvalid: "Weka namba kamili.",
  verifiedOnly: "Wenye takwimu zilizothibitishwa tu",
  availableOnly: "Wanaopokea oda tu",
  sort: "Panga kwa",
  sortNewest: "Wapya zaidi",
  sortFollowers: "Wafuasi wengi zaidi",
  sortPriceLow: "Bei ya chini kwanza",
  sortPriceHigh: "Bei ya juu kwanza",
  apply: "Tumia vichujio",
  results: (n) => (n === 1 ? "Mtengeneza maudhui 1" : `Watengeneza maudhui ${n}`),
  noCreatorsTitle: "Hakuna watengeneza maudhui",
  noCreatorsBody:
    "Bado hakuna watengeneza maudhui walioidhinishwa wanaolingana na vichujio hivi. Jaribu kuondoa kichujio au rudi baadaye.",
  noCreatorsAtAll: "Bado hakuna watengeneza maudhui walioidhinishwa kwenye 2kTunes. Rudi hivi karibuni.",
  followers: "Wafuasi",
  totalFollowers: (n) => `Wafuasi ${n}`,
  fromPrice: "Kuanzia",
  noPackages: "Bado hakuna vifurushi",
  available: "Anapokea oda",
  unavailable: "Hapokei oda kwa sasa",
  viewProfile: (name) => `Tazama wasifu wa ${name}`,

  backToCreators: "Watengeneza maudhui",
  about: "Kuhusu",
  noBio: "Mtengeneza maudhui huyu bado hajaandika maelezo yake.",
  languages: "Lugha",
  categories: "Makundi",
  turnaround: "Muda wa kawaida wa kukamilisha",
  days: (n) => (n === 1 ? "Siku 1" : `Siku ${n}`),
  completedOrders: "Oda zilizokamilika",
  location: "Mahali",
  socialTitle: "Akaunti za mitandao",
  socialIntro: "Kila takwimu inaonyesha ilikotoka.",
  noSocial: "Hakuna akaunti za mitandao zilizoorodheshwa.",
  handle: "Jina la akaunti",
  avgViews: "Wastani wa watazamaji",
  engagement: "Kiwango cha mwingiliano",
  audience: "Nchi kuu za hadhira",
  notShared: "Haijawekwa",
  openAccount: (platform, handle) => `${handle} kwenye ${platform} (inafunguka kichupo kipya)`,
  packagesTitle: "Vifurushi",
  packagesIntro: "Ofa za bei maalum. Utaeleza unachotaka kwenye maelekezo.",
  noPackagesBody: "Mtengeneza maudhui huyu hana vifurushi vinavyopatikana kwa sasa.",
  deliverable: "Utakachopata",
  orderPackage: "Agiza kifurushi hiki",
  portfolioTitle: "Kazi za awali",
  noPortfolio: "Bado hakuna mifano iliyowekwa.",
  views: (n) => `Watazamaji ${n}`,
  openExample: (title) => `${title} (inafunguka kichupo kipya)`,
  example: "Mfano",
  howItWorksTitle: "Jinsi kuagiza kunavyofanya kazi",
  howItWorks1: "Weka oda ndani ya mojawapo ya kampeni zako na ulipe kutoka pochi yako ya 2kTunes.",
  howItWorks2:
    "2kTunes inashikilia malipo yako kwenye akaunti ya ndani ya kushikilia fedha za soko. Mtengeneza maudhui analipwa tu baada ya wewe kukubali kazi aliyowasilisha.",
  howItWorks3: "Mtengeneza maudhui akikataa, au ukighairi kabla hajakubali, fedha zinarudi kwenye pochi yako.",
  howItWorks4:
    "Watengeneza maudhui wanaahidi maudhui yaliyoelezwa, si matokeo. Watazamaji, streams au wafuasi hawahakikishwi kamwe.",

  orderDialogTitle: (title) => `Oda: ${title}`,
  orderDialogIntro: "Oda zinakaa ndani ya kampeni ili ufuatilie kila kitu cha toleo moja pamoja.",
  campaignChoice: "Kampeni",
  useExisting: "Ongeza kwenye kampeni iliyopo",
  createNew: "Anzisha kampeni mpya",
  chooseCampaign: "Chagua kampeni",
  noOpenCampaigns: "Bado huna kampeni inayoendelea — anzisha moja hapa chini.",
  campaignTitle: "Jina la kampeni",
  campaignTitleRequired: "Ipe kampeni jina.",
  campaignType: "Aina ya kampeni",
  release: "Toleo",
  noRelease: "Hakuna toleo maalum",
  brief: "Maelekezo",
  briefHint:
    "Mtengeneza maudhui atengeneze nini? Taja sehemu ya wimbo, hashtag, mambo ya kufanya na kuepuka, na muda wa mwisho.",
  placeOrder: "Tengeneza oda",
  orderCreated: "Oda imetengenezwa",
  orderCreatedBody: "Ipitie kisha ulipe kutoka pochi yako ili iwasilishwe.",
  campaignRequired: "Chagua kampeni.",
  payNext: "Utalipa kwenye ukurasa unaofuata. Hakuna kinachotozwa bado.",
  campaignKept: "Kampeni imetengenezwa. Rekebisha tatizo kisha ujaribu tena — itatumika hiyo hiyo.",

  ordersTitle: "Oda",
  ordersIntro:
    "Kila ulichoagiza kutoka kwa watengeneza maudhui na huduma za 2kTunes, pamoja na kazi ulizoajiriwa kufanya.",
  asBuyer: "Kama mnunuzi",
  asCreator: "Kama mtengeneza maudhui",
  ordersTabs: "Nafasi yako kwenye oda",
  statusFilter: "Chuja kwa hali",
  allStatuses: "Zote",
  noOrdersTitle: "Bado hakuna oda",
  noOrdersBuyer: "Oda unazoweka kwa watengeneza maudhui au kwa huduma za utangazaji zitaonekana hapa.",
  noOrdersCreator: "Oda zilizolipiwa kutoka kwa wasanii zitaonekana hapa.",
  noOrdersFiltered: "Hakuna oda zenye hali hii.",
  findCreators: "Tafuta watengeneza maudhui",
  colOrder: "Oda",
  colWith: "Pamoja na",
  colStatus: "Hali",
  colPrice: "Bei",
  colYourPayout: "Malipo yako",
  colCreated: "Imetengenezwa",
  ordersCaption: "Oda",
  serviceBy2k: "Huduma ya 2kTunes",

  backToOrders: "Oda",
  orderRef: (ref) => `Kumbukumbu ${ref}`,
  summary: "Muhtasari",
  creator: "Mtengeneza maudhui",
  service: "Huduma",
  track: "Wimbo",
  price: "Bei",
  platformFee: "Ada ya jukwaa",
  yourPayout: "Malipo yako",
  due: "Mwisho",
  created: "Imetengenezwa",
  paid: "Imelipwa",
  acceptedAt: "Imekubaliwa",
  submittedAt: "Imewasilishwa",
  completedAt: "Imekamilika",
  revisions: "Marekebisho yaliyoombwa",
  campaign: "Kampeni",
  viewCampaign: (id) => `Kampeni #${id}`,
  briefTitle: "Maelekezo",
  noBrief: "Hakuna maelekezo yaliyoongezwa.",
  submissionTitle: "Kazi iliyowasilishwa",
  submissionLink: "Fungua maudhui yaliyowasilishwa (inafunguka kichupo kipya)",
  submissionNotes: "Maelezo kutoka kwa mtengeneza maudhui",
  disputesTitle: "Migogoro",
  disputeOpened: (date) => `Ulifunguliwa ${date}`,
  disputeResolved: (date) => `Ulitatuliwa ${date}`,
  resolution: "Uamuzi",
  messagesTitle: "Ujumbe",
  noMessages: "Bado hakuna ujumbe.",
  system: "2kTunes",
  you: "Wewe",
  messageLabel: "Andika ujumbe",
  send: "Tuma",
  messageSent: "Ujumbe umetumwa",
  messageRequired: "Andika ujumbe kwanza.",
  actionsTitle: "Hatua zinazofuata",
  noActions: "Hakuna unachohitaji kufanya kwenye oda hii kwa sasa.",
  holdingNote:
    "Malipo yako yanashikiliwa na 2kTunes hadi utakapokubali kazi iliyowasilishwa. Kisha yanatolewa kwa mtengeneza maudhui baada ya kukatwa ada ya jukwaa. Matokeo hayahakikishwi.",
  serviceNote:
    "Huduma hii inaendeshwa na timu ya 2kTunes. Tutaiweka kuwa imekamilika ikishafanyika. Matokeo hayahakikishwi.",
  creatorNote: "Unalipwa malipo yako msanii anapokubali kazi uliyowasilisha.",

  pay: "Lipa kutoka pochi",
  payTitle: "Ulipie oda hii?",
  payBody: (amount) => `${amount} zitahamishwa kutoka pochi yako kwenda akaunti ya kushikilia fedha za soko ya 2kTunes.`,
  walletBalance: "Salio linalopatikana kwenye pochi",
  walletLoading: "Tunaangalia pochi yako…",
  walletNone: (currency) => `Huna salio la ${currency}.`,
  insufficient: "Salio la pochi yako ni dogo kuliko bei ya oda, kwa hiyo malipo haya hayatafanikiwa.",
  topUpHint: "Nenda kwenye pochi",
  paidToast: "Imelipwa — mtengeneza maudhui amejulishwa",
  paidServiceToast: "Imelipwa — timu ya 2kTunes itaanza kazi",

  cancel: "Ghairi oda",
  cancelTitle: "Ughairi oda hii?",
  cancelBodyUnpaid: "Hakuna kilicholipwa, kwa hiyo hakuna kinachorejeshwa.",
  cancelBodyPaid: "Mtengeneza maudhui bado hajakubali. Malipo yako yanarudi kwenye pochi yako.",
  cancelledToast: "Oda imeghairiwa",

  complete: "Kubali kazi",
  completeTitle: "Ukubali kazi hii?",
  completeBody: "Malipo yatatolewa kwa mtengeneza maudhui. Huwezi kutengua hatua hii.",
  completedToast: "Kazi imekubaliwa — mtengeneza maudhui amelipwa",

  revision: "Omba marekebisho",
  revisionTitle: "Omba marekebisho",
  revisionBody: "Eleza kinachohitaji kubadilishwa. Idadi ya marekebisho kwa kila oda ina kikomo.",
  revisionLabel: "Nini kibadilishwe?",
  revisionToast: "Marekebisho yameombwa",

  dispute: "Fungua mgogoro",
  disputeTitle: "Fungua mgogoro",
  disputeBody:
    "Timu yetu hupitia migogoro ndani ya siku 2 za kazi. Fedha zinabaki zimeshikiliwa hadi mgogoro utatuliwe.",
  disputeReason: "Sababu",
  disputeDetails: "Maelezo",
  disputeDetailsHint: "Angalau herufi 20. Eleza kilichotokea na ulichotarajia.",
  disputeDetailsShort: "Andika angalau herufi 20.",
  disputeReasonRequired: "Chagua sababu.",
  disputeToast: "Mgogoro umefunguliwa",

  accept: "Kubali oda",
  acceptTitle: "Ukubali oda hii?",
  acceptBody: "Unajitolea kuwasilisha kazi kulingana na maelekezo kabla ya muda wa mwisho.",
  acceptedToast: "Oda imekubaliwa",

  decline: "Kataa",
  declineTitle: "Ukatae oda hii?",
  declineBody: "Malipo ya msanii yatarejeshwa kwenye pochi yake.",
  declineReason: "Sababu",
  declinedToast: "Oda imekataliwa",

  submitWork: "Wasilisha kazi",
  submitTitle: "Wasilisha kazi yako",
  submitBody: "Weka kiungo cha maudhui uliyochapisha. Msanii ataipitia.",
  submitUrl: "Kiungo cha maudhui",
  submitUrlHint: "Kiungo kamili, kinachoanza na https://",
  submitUrlInvalid: "Weka kiungo kamili, kinachoanza na http:// au https://",
  submitNotes: "Maelezo",
  submittedToast: "Kazi imewasilishwa",
};

export const COPY = { EN, SW };
