import type { OrderStatus } from "@/lib/api/types";

/**
 * Copy for the creator request flow (artist → 2kTunes → creator):
 * request form, order list/detail, payment, timeline and messages.
 * DOCS/API.md "Creator requests". No dashes in user-facing text.
 */

type StatusMap = Record<OrderStatus, string>;

const EN = {
  status: {
    requested: "Requested",
    under_review: "Under review",
    forwarded: "With the creator",
    awaiting_payment: "Accepted, awaiting payment",
    pending_payment: "Awaiting payment",
    in_progress: "In progress",
    submitted: "Delivered, being verified",
    disputed: "Disputed",
    completed: "Completed",
    rejected: "Not approved",
    declined: "Declined",
    expired: "Expired",
    cancelled: "Cancelled",
    refunded: "Refunded",
  } as StatusMap,
  /** One line under the status: what happens now (artist view). */
  stageBuyer: {
    requested: "2kTunes is reviewing your request.",
    under_review: "2kTunes is reviewing your request.",
    forwarded: "Sent to the creator. They have 3 days to accept or decline.",
    awaiting_payment: "The creator accepted. Pay within 7 days or the request expires.",
    pending_payment: "Waiting for your payment.",
    in_progress: "Paid. The creator is working on it.",
    submitted: "The creator posted. 2kTunes is checking the post.",
    disputed: "2kTunes is reviewing the dispute. The payment stays held.",
    completed: "Verified by 2kTunes. The creator has been paid.",
    rejected: "2kTunes did not approve this request. Nothing was charged.",
    declined: "The creator declined. Nothing was charged.",
    expired: "This request expired. Nothing was charged.",
    cancelled: "You cancelled this request. Nothing was charged.",
    refunded: "Refunded to your wallet.",
  } as StatusMap,
  /** Creator view. */
  stageCreator: {
    requested: "Under review by 2kTunes.",
    under_review: "Under review by 2kTunes.",
    forwarded: "New request. Listen, then accept or decline.",
    awaiting_payment: "You accepted. Waiting for the artist to pay.",
    pending_payment: "Waiting for payment.",
    in_progress: "Paid and held by 2kTunes. Post, then submit the link.",
    submitted: "Submitted. 2kTunes is verifying your post.",
    disputed: "2kTunes is reviewing the dispute.",
    completed: "Verified. Your share is in your wallet.",
    rejected: "Closed by 2kTunes.",
    declined: "You declined this request.",
    expired: "This request expired.",
    cancelled: "The artist cancelled this request.",
    refunded: "Refunded to the artist by 2kTunes.",
  } as StatusMap,
  actor: { artist: "Artist", creator: "Creator", staff: "2kTunes", system: "2kTunes", you: "You" } as Record<string, string>,

  /* Request form */
  newRequest: "New request",
  requestCreator: "Request this creator",
  requestTitle: (pkg: string) => `Request: ${pkg}`,
  requestIntro: "2kTunes reviews every request before it goes to the creator.",
  songSource: "Which song?",
  sourceCatalog: "My 2kTunes releases",
  sourceCatalogHint: "Pick a release and track",
  sourceExternal: "Released elsewhere",
  sourceExternalHint: "Paste a link to the song",
  release: "Release",
  chooseRelease: "Choose a release",
  releaseRequired: "Choose a release.",
  noReleases: "You have no releases on 2kTunes yet. Use a link instead.",
  track: "Track",
  firstTrack: "Lead track",
  tracksLoading: "Loading tracks…",
  songUrl: "Link to the song",
  songUrlHint: "Spotify, YouTube, Boomplay, Audiomack and more.",
  songUrlInvalid: "Paste the full link, starting with https://",
  detected: (p: string) => `Detected: ${p}`,
  songTitle: "Song title",
  songTitleRequired: "Add the song title.",
  songArtist: "Artist",
  songArtistRequired: "Add the artist name.",
  brief: "Brief",
  briefHint: "What should the creator make? The part of the song, the vibe, any hashtags.",
  contactNote: "Phone numbers, emails, links and @handles are removed automatically. All contact goes through 2kTunes.",
  postDate: "Preferred post date",
  postDateInvalid: "Pick today or a later date.",
  summaryTitle: "Price summary",
  packagePrice: "Package price",
  turnaround: (n: number) => (n === 1 ? "Posted within 1 day of payment" : `Posted within ${n} days of payment`),
  youPay: "You pay",
  payLater: "Nothing is charged now. You pay only after the creator accepts, within 7 days.",
  feeNote: (pct: string) =>
    `2kTunes holds your payment and releases it to the creator after checking the post. The creator receives the price minus the ${pct} platform fee.`,
  sendRequest: "Send request",
  requestSent: "Request sent",
  requestSentBody: "2kTunes will review it and forward it to the creator.",
  howTitle: "How requests work",
  how1: "Send a request. 2kTunes reviews it, then the creator has 3 days to accept.",
  how2: "Pay only after they accept: from your wallet, or by mobile money or bank.",
  how3: "2kTunes holds the payment and pays the creator only after checking the post.",
  how4: "Creators promise the content described, not results. Views and streams are never guaranteed.",
  noContact: "You never need the creator's contact details. Everything happens on 2kTunes.",
  pricesNote: "Prices are fixed. You see the full price before you request.",
  requestCta: "Request",
  socialNoHandles: "Numbers only. Handles and links stay private: all contact goes through 2kTunes.",
  watchExample: (t: string) => `Play ${t}`,
  openExample: (t: string) => `${t} (opens in a new tab)`,
  selfReportedViews: (n: string) => `${n} views, self-reported`,

  /* Order detail */
  backToOrders: "Orders",
  orderRef: (ref: string) => `Reference ${ref}`,
  summary: "Summary",
  creator: "Creator",
  artist: "Artist",
  service: "Service",
  pkg: "Package",
  song: "Song",
  listen: "Listen",
  openSong: "Open the song",
  price: "Price",
  platformFee: "Platform fee",
  yourPayout: "Your payout",
  preferredDate: "Preferred post date",
  created: "Requested",
  briefTitle: "Brief",
  noBrief: "No brief was added.",
  creatorNote: "Note from the creator",
  payBy: (d: string) => `Pay by ${d}`,
  respondBy: (d: string) => `Creator answers by ${d}`,
  respondByCreator: (d: string) => `Answer by ${d}`,
  dueBy: (d: string) => `Post due ${d}`,
  overdue: "Late. 2kTunes is following up and may refund the artist.",
  timelineTitle: "Timeline",
  nextTitle: "Next steps",
  noActions: "Nothing for you to do right now.",
  heldNote: "Your payment is held by 2kTunes and released to the creator only after we verify the post.",
  creatorHeldNote: "Paid orders are held by 2kTunes. Your share moves to your wallet after we verify your post.",
  serviceNote: "2kTunes delivers this service. Payment is held until the work is done.",

  /* Pay */
  daysLeft: (n: number) => (n === 1 ? "1 day left" : `${n} days left`),
  hoursLeft: (n: number) => (n === 1 ? "1 hour left" : `${n} hours left`),
  lessThanHour: "Less than an hour left",
  timeUp: "Time is up",
  accept: "Accept",
  acceptTitle: "Accept this request?",
  acceptBody: "The artist then has 7 days to pay. Start once the order shows In progress.",
  acceptNote: "Note to the artist",
  acceptNoteHint: "Optional, for example when you plan to post.",
  acceptedToast: "Request accepted",
  decline: "Decline",
  declineTitle: "Decline this request?",
  declineBody: "Nothing was charged. The artist is told you declined.",
  declineReason: "Reason",
  declinedToast: "Request declined",
  submitLinks: "Submit post links",
  submitTitle: "Submit your post",
  submitBody: "Add the link to each post. 2kTunes checks it, then pays your share into your wallet.",
  linkLabel: (n: number) => `Post link ${n}`,
  addLink: "Add another link",
  removeLink: (n: number) => `Remove post link ${n}`,
  linkInvalid: "Enter the full link, starting with https://",
  linksRequired: "Add at least one link.",
  submitNotes: "Notes for 2kTunes",
  submittedToast: "Post submitted for verification",
  whereToPay: "Where to pay",
  payNow: "Pay now",
  payTitle: "Pay for this request",
  payAmount: (amount: string) => `Amount due: ${amount}`,
  payWallet: "Wallet",
  payManual: "Mobile money or bank",
  walletBalance: "Available in your wallet",
  walletLoading: "Checking your wallet…",
  walletNone: (cur: string) => `You have no ${cur} balance.`,
  insufficient: "Your balance is too low for this payment.",
  topUp: "Go to wallet",
  payFromWallet: "Pay from wallet",
  manualMethod: "Payment method",
  manualMethodPick: "Choose a method",
  manualReference: "Transaction reference",
  manualReferenceHint: "The code on your M-Pesa, Airtel Money, Mixx or bank receipt.",
  manualSubmit: "Send reference",
  methodRequired: "Choose how you paid.",
  referenceRequired: "Enter the transaction reference.",
  manualSentToast: "Reference received",
  manualSentBody: "2kTunes Finance will confirm it within one business day.",
  manualWaiting: "Payment reference sent. Waiting for 2kTunes Finance to confirm it.",
  paidToast: "Paid. The creator can start now.",
  methods: { mpesa_tz: "M-Pesa", airtel_tz: "Airtel Money", mixx_tz: "Mixx by Yas", bank: "Bank transfer", wallet: "Wallet" } as Record<string, string>,

  /* Cancel */
  cancel: "Cancel request",
  cancelTitle: "Cancel this request?",
  cancelBody: "Nothing has been paid, so nothing is charged.",
  cancelledToast: "Request cancelled",

  /* Delivered */
  deliveredTitle: "Delivered posts",
  postLink: (n: number) => `Post ${n}`,
  opensNewTab: "(opens in a new tab)",
  deliveredNotes: "Notes from the creator",
  fixTitle: "2kTunes asked for a fix",

  /* Dispute */
  dispute: "Open a dispute",
  disputeTitle: "Open a dispute",
  disputeBody: "The payment stays held while 2kTunes reviews the dispute, usually within 2 business days.",
  disputeReason: "Reason",
  disputeReasonRequired: "Choose a reason.",
  disputeDetails: "What happened?",
  disputeDetailsHint: "At least 20 characters.",
  disputeDetailsShort: "Write at least 20 characters.",
  disputeToast: "Dispute opened",
  disputesTitle: "Disputes",
  disputeOpened: (d: string) => `Opened ${d}`,
  disputeResolved: (d: string) => `Resolved ${d}`,
  resolution: "Resolution",

  /* Messages */
  messagesTitle: "Messages",
  contactRemovedNote: "Messages are visible to 2kTunes staff. Contact details are removed automatically.",
  redacted: "Contact details removed",
  noMessages: "No messages yet.",
  messageLabel: "Write a message",
  send: "Send",
  messageSent: "Message sent",
  messageSentRedacted: "Sent. Some contact details were removed.",
  messageRequired: "Write a message first.",

  /* Orders list */
  ordersTitle: "Orders",
  ordersIntro: "Your creator requests and 2kTunes services, and work you have been hired for.",
  asBuyer: "My requests",
  asCreator: "As creator",
  ordersTabs: "Order role",
  statusFilter: "Filter by status",
  all: "All",
  noOrdersTitle: "No orders yet",
  noOrdersBuyer: "Request a creator to promote your song. You see every price before you ask.",
  noOrdersCreator: "Requests forwarded to you by 2kTunes appear here.",
  noOrdersFiltered: "No orders with this status.",
  findCreators: "Find creators",
  colOrder: "Order",
  colWith: "With",
  colStatus: "Status",
  colPrice: "Price",
  colYourPayout: "Your payout",
  colCreated: "Requested",
};

export type RequestCopy = typeof EN;

const SW: RequestCopy = {
  status: {
    requested: "Limeombwa",
    under_review: "Linakaguliwa",
    forwarded: "Kwa mtengeneza maudhui",
    awaiting_payment: "Limekubaliwa, linasubiri malipo",
    pending_payment: "Linasubiri malipo",
    in_progress: "Linaendelea",
    submitted: "Limewasilishwa, linathibitishwa",
    disputed: "Lina mgogoro",
    completed: "Limekamilika",
    rejected: "Halikuidhinishwa",
    declined: "Limekataliwa",
    expired: "Muda umeisha",
    cancelled: "Limeghairiwa",
    refunded: "Pesa imerudishwa",
  },
  stageBuyer: {
    requested: "2kTunes inakagua ombi lako.",
    under_review: "2kTunes inakagua ombi lako.",
    forwarded: "Limetumwa kwa mtengeneza maudhui. Ana siku 3 kukubali au kukataa.",
    awaiting_payment: "Mtengeneza maudhui amekubali. Lipa ndani ya siku 7 au ombi litaisha.",
    pending_payment: "Inasubiri malipo yako.",
    in_progress: "Umelipa. Mtengeneza maudhui anaanza kazi.",
    submitted: "Mtengeneza maudhui amechapisha. 2kTunes inakagua chapisho.",
    disputed: "2kTunes inakagua mgogoro. Malipo yanashikiliwa.",
    completed: "Limethibitishwa na 2kTunes. Mtengeneza maudhui amelipwa.",
    rejected: "2kTunes haikuidhinisha ombi hili. Hukutozwa chochote.",
    declined: "Mtengeneza maudhui amekataa. Hukutozwa chochote.",
    expired: "Ombi hili limeisha muda. Hukutozwa chochote.",
    cancelled: "Umeghairi ombi hili. Hukutozwa chochote.",
    refunded: "Pesa imerudishwa kwenye pochi yako.",
  },
  stageCreator: {
    requested: "Linakaguliwa na 2kTunes.",
    under_review: "Linakaguliwa na 2kTunes.",
    forwarded: "Ombi jipya. Sikiliza, kisha kubali au kataa.",
    awaiting_payment: "Umekubali. Inasubiri msanii alipe.",
    pending_payment: "Inasubiri malipo.",
    in_progress: "Limelipwa na linashikiliwa na 2kTunes. Chapisha, kisha wasilisha kiungo.",
    submitted: "Umewasilisha. 2kTunes inathibitisha chapisho lako.",
    disputed: "2kTunes inakagua mgogoro.",
    completed: "Limethibitishwa. Sehemu yako iko kwenye pochi.",
    rejected: "Limefungwa na 2kTunes.",
    declined: "Umekataa ombi hili.",
    expired: "Ombi hili limeisha muda.",
    cancelled: "Msanii ameghairi ombi hili.",
    refunded: "2kTunes imemrudishia msanii pesa.",
  },
  actor: { artist: "Msanii", creator: "Mtengeneza maudhui", staff: "2kTunes", system: "2kTunes", you: "Wewe" },

  newRequest: "Ombi jipya",
  requestCreator: "Mwombe mtengeneza maudhui huyu",
  requestTitle: (pkg) => `Ombi: ${pkg}`,
  requestIntro: "2kTunes inakagua kila ombi kabla halijamfikia mtengeneza maudhui.",
  songSource: "Wimbo gani?",
  sourceCatalog: "Matoleo yangu ya 2kTunes",
  sourceCatalogHint: "Chagua toleo na wimbo",
  sourceExternal: "Umetolewa kwingine",
  sourceExternalHint: "Bandika kiungo cha wimbo",
  release: "Toleo",
  chooseRelease: "Chagua toleo",
  releaseRequired: "Chagua toleo.",
  noReleases: "Bado huna matoleo kwenye 2kTunes. Tumia kiungo badala yake.",
  track: "Wimbo",
  firstTrack: "Wimbo mkuu",
  tracksLoading: "Inapakia nyimbo…",
  songUrl: "Kiungo cha wimbo",
  songUrlHint: "Spotify, YouTube, Boomplay, Audiomack na mengine.",
  songUrlInvalid: "Bandika kiungo kamili kinachoanza na https://",
  detected: (p) => `Imetambuliwa: ${p}`,
  songTitle: "Jina la wimbo",
  songTitleRequired: "Weka jina la wimbo.",
  songArtist: "Msanii",
  songArtistRequired: "Weka jina la msanii.",
  brief: "Maelekezo",
  briefHint: "Mtengeneza maudhui atengeneze nini? Sehemu ya wimbo, mtindo, hashtag.",
  contactNote: "Namba za simu, barua pepe, viungo na @majina huondolewa moja kwa moja. Mawasiliano yote hupitia 2kTunes.",
  postDate: "Tarehe unayopendelea ya kuchapisha",
  postDateInvalid: "Chagua leo au tarehe ijayo.",
  summaryTitle: "Muhtasari wa bei",
  packagePrice: "Bei ya kifurushi",
  turnaround: (n) => (n === 1 ? "Huchapishwa ndani ya siku 1 baada ya malipo" : `Huchapishwa ndani ya siku ${n} baada ya malipo`),
  youPay: "Utalipa",
  payLater: "Hutozwi sasa. Utalipa tu baada ya mtengeneza maudhui kukubali, ndani ya siku 7.",
  feeNote: (pct) =>
    `2kTunes inashikilia malipo yako na kumlipa mtengeneza maudhui baada ya kukagua chapisho. Mtengeneza maudhui anapokea bei ukiondoa ada ya jukwaa ya ${pct}.`,
  sendRequest: "Tuma ombi",
  requestSent: "Ombi limetumwa",
  requestSentBody: "2kTunes italikagua na kulituma kwa mtengeneza maudhui.",
  howTitle: "Jinsi maombi yanavyofanya kazi",
  how1: "Tuma ombi. 2kTunes inalikagua, kisha mtengeneza maudhui ana siku 3 kukubali.",
  how2: "Lipa tu baada ya kukubali: kutoka pochi, au kwa pesa ya simu au benki.",
  how3: "2kTunes inashikilia malipo na kumlipa mtengeneza maudhui baada ya kukagua chapisho.",
  how4: "Watengeneza maudhui wanaahidi maudhui yaliyoelezwa, si matokeo. Watazamaji na streams hazihakikishwi.",
  noContact: "Huhitaji mawasiliano ya mtengeneza maudhui. Kila kitu hufanyika kwenye 2kTunes.",
  pricesNote: "Bei ni maalum. Unaona bei kamili kabla ya kuomba.",
  requestCta: "Omba",
  socialNoHandles: "Takwimu tu. Majina ya akaunti na viungo ni siri: mawasiliano yote hupitia 2kTunes.",
  watchExample: (t) => `Cheza ${t}`,
  openExample: (t) => `${t} (inafunguka kichupo kipya)`,
  selfReportedViews: (n) => `Watazamaji ${n}, kwa kauli yake`,

  backToOrders: "Oda",
  orderRef: (ref) => `Kumbukumbu ${ref}`,
  summary: "Muhtasari",
  creator: "Mtengeneza maudhui",
  artist: "Msanii",
  service: "Huduma",
  pkg: "Kifurushi",
  song: "Wimbo",
  listen: "Sikiliza",
  openSong: "Fungua wimbo",
  price: "Bei",
  platformFee: "Ada ya jukwaa",
  yourPayout: "Malipo yako",
  preferredDate: "Tarehe inayopendekezwa",
  created: "Liliombwa",
  briefTitle: "Maelekezo",
  noBrief: "Hakuna maelekezo yaliyoongezwa.",
  creatorNote: "Ujumbe kutoka kwa mtengeneza maudhui",
  payBy: (d) => `Lipa kabla ya ${d}`,
  respondBy: (d) => `Atajibu kabla ya ${d}`,
  respondByCreator: (d) => `Jibu kabla ya ${d}`,
  dueBy: (d) => `Chapisho linatakiwa ${d}`,
  overdue: "Limechelewa. 2kTunes inafuatilia na inaweza kumrudishia msanii pesa.",
  timelineTitle: "Historia",
  nextTitle: "Hatua inayofuata",
  noActions: "Hakuna cha kufanya kwa sasa.",
  heldNote: "Malipo yako yanashikiliwa na 2kTunes na kutolewa kwa mtengeneza maudhui baada ya kuthibitisha chapisho.",
  creatorHeldNote: "Oda zilizolipwa zinashikiliwa na 2kTunes. Sehemu yako inaingia kwenye pochi baada ya kuthibitisha chapisho.",
  serviceNote: "2kTunes inatoa huduma hii. Malipo yanashikiliwa hadi kazi ikamilike.",

  daysLeft: (n) => (n === 1 ? "Imebaki siku 1" : `Zimebaki siku ${n}`),
  hoursLeft: (n) => (n === 1 ? "Imebaki saa 1" : `Zimebaki saa ${n}`),
  lessThanHour: "Imebaki chini ya saa moja",
  timeUp: "Muda umekwisha",
  accept: "Kubali",
  acceptTitle: "Ukubali ombi hili?",
  acceptBody: "Msanii atakuwa na siku 7 kulipa. Anza oda ikionyesha Linaendelea.",
  acceptNote: "Ujumbe kwa msanii",
  acceptNoteHint: "Si lazima, kwa mfano lini utachapisha.",
  acceptedToast: "Ombi limekubaliwa",
  decline: "Kataa",
  declineTitle: "Ukatae ombi hili?",
  declineBody: "Hakuna kilichotozwa. Msanii ataambiwa umekataa.",
  declineReason: "Sababu",
  declinedToast: "Ombi limekataliwa",
  submitLinks: "Wasilisha viungo vya chapisho",
  submitTitle: "Wasilisha chapisho lako",
  submitBody: "Weka kiungo cha kila chapisho. 2kTunes italikagua, kisha italipa sehemu yako kwenye pochi.",
  linkLabel: (n) => `Kiungo cha chapisho ${n}`,
  addLink: "Ongeza kiungo kingine",
  removeLink: (n) => `Ondoa kiungo cha chapisho ${n}`,
  linkInvalid: "Weka kiungo kamili kinachoanza na https://",
  linksRequired: "Weka angalau kiungo kimoja.",
  submitNotes: "Maelezo kwa 2kTunes",
  submittedToast: "Chapisho limewasilishwa kwa uthibitisho",
  whereToPay: "Mahali pa kulipa",
  payNow: "Lipa sasa",
  payTitle: "Lipia ombi hili",
  payAmount: (a) => `Kiasi cha kulipa: ${a}`,
  payWallet: "Pochi",
  payManual: "Pesa kwa simu au benki",
  walletBalance: "Kinachopatikana kwenye pochi",
  walletLoading: "Inakagua pochi yako…",
  walletNone: (cur) => `Huna salio la ${cur}.`,
  insufficient: "Salio lako ni dogo kwa malipo haya.",
  topUp: "Nenda kwenye pochi",
  payFromWallet: "Lipa kutoka pochi",
  manualMethod: "Njia ya malipo",
  manualMethodPick: "Chagua njia",
  manualReference: "Namba ya muamala",
  manualReferenceHint: "Namba kwenye risiti yako ya M-Pesa, Airtel Money, Mixx au benki.",
  manualSubmit: "Tuma namba ya muamala",
  methodRequired: "Chagua ulivyolipa.",
  referenceRequired: "Weka namba ya muamala.",
  manualSentToast: "Namba ya muamala imepokelewa",
  manualSentBody: "Idara ya Fedha ya 2kTunes itathibitisha ndani ya siku moja ya kazi.",
  manualWaiting: "Namba ya muamala imetumwa. Inasubiri uthibitisho wa Idara ya Fedha ya 2kTunes.",
  paidToast: "Umelipa. Mtengeneza maudhui anaweza kuanza sasa.",
  methods: { mpesa_tz: "M-Pesa", airtel_tz: "Airtel Money", mixx_tz: "Mixx by Yas", bank: "Uhamisho wa benki", wallet: "Pochi" },

  cancel: "Ghairi ombi",
  cancelTitle: "Ughairi ombi hili?",
  cancelBody: "Hakuna kilicholipwa, kwa hiyo hutozwi chochote.",
  cancelledToast: "Ombi limeghairiwa",

  deliveredTitle: "Machapisho yaliyowasilishwa",
  postLink: (n) => `Chapisho ${n}`,
  opensNewTab: "(inafunguka kichupo kipya)",
  deliveredNotes: "Maelezo kutoka kwa mtengeneza maudhui",
  fixTitle: "2kTunes imeomba marekebisho",

  dispute: "Fungua mgogoro",
  disputeTitle: "Fungua mgogoro",
  disputeBody: "Malipo yanabaki yameshikiliwa wakati 2kTunes inakagua mgogoro, kwa kawaida ndani ya siku 2 za kazi.",
  disputeReason: "Sababu",
  disputeReasonRequired: "Chagua sababu.",
  disputeDetails: "Nini kilitokea?",
  disputeDetailsHint: "Angalau herufi 20.",
  disputeDetailsShort: "Andika angalau herufi 20.",
  disputeToast: "Mgogoro umefunguliwa",
  disputesTitle: "Migogoro",
  disputeOpened: (d) => `Ulifunguliwa ${d}`,
  disputeResolved: (d) => `Ulitatuliwa ${d}`,
  resolution: "Uamuzi",

  messagesTitle: "Ujumbe",
  contactRemovedNote: "Ujumbe unaonekana na wafanyakazi wa 2kTunes. Taarifa za mawasiliano huondolewa moja kwa moja.",
  redacted: "Taarifa za mawasiliano zimeondolewa",
  noMessages: "Bado hakuna ujumbe.",
  messageLabel: "Andika ujumbe",
  send: "Tuma",
  messageSent: "Ujumbe umetumwa",
  messageSentRedacted: "Umetumwa. Baadhi ya taarifa za mawasiliano zimeondolewa.",
  messageRequired: "Andika ujumbe kwanza.",

  ordersTitle: "Oda",
  ordersIntro: "Maombi yako kwa watengeneza maudhui na huduma za 2kTunes, pamoja na kazi uliyoajiriwa.",
  asBuyer: "Maombi yangu",
  asCreator: "Kama mtengeneza maudhui",
  ordersTabs: "Nafasi kwenye oda",
  statusFilter: "Chuja kwa hali",
  all: "Zote",
  noOrdersTitle: "Bado hakuna oda",
  noOrdersBuyer: "Mwombe mtengeneza maudhui atangaze wimbo wako. Unaona kila bei kabla ya kuomba.",
  noOrdersCreator: "Maombi ambayo 2kTunes itakutumia yataonekana hapa.",
  noOrdersFiltered: "Hakuna oda zenye hali hii.",
  findCreators: "Tafuta watengeneza maudhui",
  colOrder: "Oda",
  colWith: "Na",
  colStatus: "Hali",
  colPrice: "Bei",
  colYourPayout: "Malipo yako",
  colCreated: "Liliombwa",
};

const FR: RequestCopy = {
  status: {
    requested: "Demandée",
    under_review: "En vérification",
    forwarded: "Chez le créateur",
    awaiting_payment: "Acceptée, paiement attendu",
    pending_payment: "Paiement attendu",
    in_progress: "En cours",
    submitted: "Livrée, en vérification",
    disputed: "Litige",
    completed: "Terminée",
    rejected: "Non approuvée",
    declined: "Refusée",
    expired: "Expirée",
    cancelled: "Annulée",
    refunded: "Remboursée",
  },
  stageBuyer: {
    requested: "2kTunes examine votre demande.",
    under_review: "2kTunes examine votre demande.",
    forwarded: "Envoyée au créateur. Il a 3 jours pour accepter ou refuser.",
    awaiting_payment: "Le créateur a accepté. Payez sous 7 jours, sinon la demande expire.",
    pending_payment: "En attente de votre paiement.",
    in_progress: "Payée. Le créateur y travaille.",
    submitted: "Le créateur a publié. 2kTunes vérifie la publication.",
    disputed: "2kTunes examine le litige. Le paiement reste bloqué.",
    completed: "Vérifiée par 2kTunes. Le créateur a été payé.",
    rejected: "2kTunes n’a pas approuvé cette demande. Rien n’a été débité.",
    declined: "Le créateur a refusé. Rien n’a été débité.",
    expired: "Cette demande a expiré. Rien n’a été débité.",
    cancelled: "Vous avez annulé cette demande. Rien n’a été débité.",
    refunded: "Remboursée sur votre portefeuille.",
  },
  stageCreator: {
    requested: "En vérification par 2kTunes.",
    under_review: "En vérification par 2kTunes.",
    forwarded: "Nouvelle demande. Écoutez, puis acceptez ou refusez.",
    awaiting_payment: "Vous avez accepté. En attente du paiement de l’artiste.",
    pending_payment: "En attente du paiement.",
    in_progress: "Payée et bloquée par 2kTunes. Publiez, puis envoyez le lien.",
    submitted: "Envoyée. 2kTunes vérifie votre publication.",
    disputed: "2kTunes examine le litige.",
    completed: "Vérifiée. Votre part est sur votre portefeuille.",
    rejected: "Clôturée par 2kTunes.",
    declined: "Vous avez refusé cette demande.",
    expired: "Cette demande a expiré.",
    cancelled: "L’artiste a annulé cette demande.",
    refunded: "Remboursée à l’artiste par 2kTunes.",
  },
  actor: { artist: "Artiste", creator: "Créateur", staff: "2kTunes", system: "2kTunes", you: "Vous" },

  newRequest: "Nouvelle demande",
  requestCreator: "Faire une demande",
  requestTitle: (pkg) => `Demande : ${pkg}`,
  requestIntro: "2kTunes vérifie chaque demande avant de l’envoyer au créateur.",
  songSource: "Quel titre ?",
  sourceCatalog: "Mes sorties 2kTunes",
  sourceCatalogHint: "Choisissez une sortie et un titre",
  sourceExternal: "Sorti ailleurs",
  sourceExternalHint: "Collez le lien du titre",
  release: "Sortie",
  chooseRelease: "Choisir une sortie",
  releaseRequired: "Choisissez une sortie.",
  noReleases: "Vous n’avez pas encore de sortie sur 2kTunes. Utilisez un lien.",
  track: "Titre",
  firstTrack: "Titre principal",
  tracksLoading: "Chargement des titres…",
  songUrl: "Lien du titre",
  songUrlHint: "Spotify, YouTube, Boomplay, Audiomack et d’autres.",
  songUrlInvalid: "Collez le lien complet, commençant par https://",
  detected: (p) => `Détecté : ${p}`,
  songTitle: "Nom du titre",
  songTitleRequired: "Indiquez le nom du titre.",
  songArtist: "Artiste",
  songArtistRequired: "Indiquez le nom de l’artiste.",
  brief: "Brief",
  briefHint: "Que doit créer le créateur ? Le passage du titre, l’ambiance, les hashtags.",
  contactNote:
    "Les numéros, e-mails, liens et @pseudos sont retirés automatiquement. Tous les échanges passent par 2kTunes.",
  postDate: "Date de publication souhaitée",
  postDateInvalid: "Choisissez aujourd’hui ou une date ultérieure.",
  summaryTitle: "Récapitulatif du prix",
  packagePrice: "Prix de l’offre",
  turnaround: (n) => (n === 1 ? "Publié sous 1 jour après paiement" : `Publié sous ${n} jours après paiement`),
  youPay: "Vous payez",
  payLater: "Rien n’est débité maintenant. Vous payez seulement après l’acceptation du créateur, sous 7 jours.",
  feeNote: (pct) =>
    `2kTunes conserve votre paiement et le verse au créateur après avoir vérifié la publication. Le créateur reçoit le prix moins les frais de plateforme de ${pct}.`,
  sendRequest: "Envoyer la demande",
  requestSent: "Demande envoyée",
  requestSentBody: "2kTunes va la vérifier puis la transmettre au créateur.",
  howTitle: "Comment fonctionnent les demandes",
  how1: "Envoyez une demande. 2kTunes la vérifie, puis le créateur a 3 jours pour accepter.",
  how2: "Payez seulement après son acceptation : avec votre portefeuille, ou par mobile money ou banque.",
  how3: "2kTunes conserve le paiement et paie le créateur seulement après avoir vérifié la publication.",
  how4: "Les créateurs s’engagent sur le contenu décrit, pas sur des résultats. Vues et streams ne sont jamais garantis.",
  noContact: "Vous n’avez jamais besoin des coordonnées du créateur. Tout se passe sur 2kTunes.",
  pricesNote: "Les prix sont fixes. Vous voyez le prix complet avant de demander.",
  requestCta: "Demander",
  socialNoHandles: "Chiffres uniquement. Pseudos et liens restent privés : tout passe par 2kTunes.",
  watchExample: (t) => `Lire ${t}`,
  openExample: (t) => `${t} (s’ouvre dans un nouvel onglet)`,
  selfReportedViews: (n) => `${n} vues, déclarées par le créateur`,

  backToOrders: "Commandes",
  orderRef: (ref) => `Référence ${ref}`,
  summary: "Résumé",
  creator: "Créateur",
  artist: "Artiste",
  service: "Service",
  pkg: "Offre",
  song: "Titre",
  listen: "Écouter",
  openSong: "Ouvrir le titre",
  price: "Prix",
  platformFee: "Frais de plateforme",
  yourPayout: "Votre part",
  preferredDate: "Date souhaitée",
  created: "Demandée le",
  briefTitle: "Brief",
  noBrief: "Aucun brief ajouté.",
  creatorNote: "Note du créateur",
  payBy: (d) => `À payer avant le ${d}`,
  respondBy: (d) => `Réponse du créateur avant le ${d}`,
  respondByCreator: (d) => `Répondez avant le ${d}`,
  dueBy: (d) => `Publication attendue le ${d}`,
  overdue: "En retard. 2kTunes fait le suivi et peut rembourser l’artiste.",
  timelineTitle: "Historique",
  nextTitle: "Prochaines étapes",
  noActions: "Rien à faire pour le moment.",
  heldNote: "Votre paiement est conservé par 2kTunes et versé au créateur seulement après vérification de la publication.",
  creatorHeldNote: "Les commandes payées sont conservées par 2kTunes. Votre part arrive sur votre portefeuille après vérification.",
  serviceNote: "2kTunes réalise ce service. Le paiement est conservé jusqu’à la fin du travail.",

  daysLeft: (n) => (n === 1 ? "1 jour restant" : `${n} jours restants`),
  hoursLeft: (n) => (n === 1 ? "1 heure restante" : `${n} heures restantes`),
  lessThanHour: "Moins d’une heure",
  timeUp: "Délai dépassé",
  accept: "Accepter",
  acceptTitle: "Accepter cette demande ?",
  acceptBody: "L’artiste a ensuite 7 jours pour payer. Commencez quand la commande passe En cours.",
  acceptNote: "Note à l’artiste",
  acceptNoteHint: "Facultatif, par exemple la date de publication prévue.",
  acceptedToast: "Demande acceptée",
  decline: "Refuser",
  declineTitle: "Refuser cette demande ?",
  declineBody: "Rien n’a été débité. L’artiste sera informé de votre refus.",
  declineReason: "Motif",
  declinedToast: "Demande refusée",
  submitLinks: "Envoyer les liens",
  submitTitle: "Envoyer votre publication",
  submitBody: "Ajoutez le lien de chaque publication. 2kTunes la vérifie, puis verse votre part sur votre portefeuille.",
  linkLabel: (n) => `Lien de publication ${n}`,
  addLink: "Ajouter un lien",
  removeLink: (n) => `Retirer le lien ${n}`,
  linkInvalid: "Saisissez le lien complet, commençant par https://",
  linksRequired: "Ajoutez au moins un lien.",
  submitNotes: "Notes pour 2kTunes",
  submittedToast: "Publication envoyée pour vérification",
  whereToPay: "Où payer",
  payNow: "Payer maintenant",
  payTitle: "Payer cette demande",
  payAmount: (a) => `Montant dû : ${a}`,
  payWallet: "Portefeuille",
  payManual: "Mobile money ou banque",
  walletBalance: "Disponible sur votre portefeuille",
  walletLoading: "Vérification du portefeuille…",
  walletNone: (cur) => `Vous n’avez pas de solde en ${cur}.`,
  insufficient: "Votre solde est insuffisant pour ce paiement.",
  topUp: "Aller au portefeuille",
  payFromWallet: "Payer avec le portefeuille",
  manualMethod: "Moyen de paiement",
  manualMethodPick: "Choisir un moyen",
  manualReference: "Référence de transaction",
  manualReferenceHint: "Le code de votre reçu M-Pesa, Airtel Money, Mixx ou bancaire.",
  manualSubmit: "Envoyer la référence",
  methodRequired: "Choisissez comment vous avez payé.",
  referenceRequired: "Saisissez la référence de transaction.",
  manualSentToast: "Référence reçue",
  manualSentBody: "Le service financier de 2kTunes la confirmera sous un jour ouvré.",
  manualWaiting: "Référence envoyée. En attente de confirmation par le service financier de 2kTunes.",
  paidToast: "Payée. Le créateur peut commencer.",
  methods: { mpesa_tz: "M-Pesa", airtel_tz: "Airtel Money", mixx_tz: "Mixx by Yas", bank: "Virement bancaire", wallet: "Portefeuille" },

  cancel: "Annuler la demande",
  cancelTitle: "Annuler cette demande ?",
  cancelBody: "Rien n’a été payé, donc rien n’est débité.",
  cancelledToast: "Demande annulée",

  deliveredTitle: "Publications livrées",
  postLink: (n) => `Publication ${n}`,
  opensNewTab: "(s’ouvre dans un nouvel onglet)",
  deliveredNotes: "Notes du créateur",
  fixTitle: "2kTunes a demandé une correction",

  dispute: "Ouvrir un litige",
  disputeTitle: "Ouvrir un litige",
  disputeBody: "Le paiement reste bloqué pendant que 2kTunes examine le litige, en général sous 2 jours ouvrés.",
  disputeReason: "Motif",
  disputeReasonRequired: "Choisissez un motif.",
  disputeDetails: "Que s’est-il passé ?",
  disputeDetailsHint: "Au moins 20 caractères.",
  disputeDetailsShort: "Écrivez au moins 20 caractères.",
  disputeToast: "Litige ouvert",
  disputesTitle: "Litiges",
  disputeOpened: (d) => `Ouvert le ${d}`,
  disputeResolved: (d) => `Résolu le ${d}`,
  resolution: "Décision",

  messagesTitle: "Messages",
  contactRemovedNote: "Les messages sont visibles par l’équipe 2kTunes. Les coordonnées sont retirées automatiquement.",
  redacted: "Coordonnées retirées",
  noMessages: "Aucun message pour l’instant.",
  messageLabel: "Écrire un message",
  send: "Envoyer",
  messageSent: "Message envoyé",
  messageSentRedacted: "Envoyé. Certaines coordonnées ont été retirées.",
  messageRequired: "Écrivez d’abord un message.",

  ordersTitle: "Commandes",
  ordersIntro: "Vos demandes aux créateurs et les services 2kTunes, ainsi que le travail pour lequel on vous a engagé.",
  asBuyer: "Mes demandes",
  asCreator: "En tant que créateur",
  ordersTabs: "Rôle",
  statusFilter: "Filtrer par statut",
  all: "Toutes",
  noOrdersTitle: "Aucune commande",
  noOrdersBuyer: "Demandez à un créateur de promouvoir votre titre. Vous voyez chaque prix avant de demander.",
  noOrdersCreator: "Les demandes que 2kTunes vous transmet apparaîtront ici.",
  noOrdersFiltered: "Aucune commande avec ce statut.",
  findCreators: "Trouver des créateurs",
  colOrder: "Commande",
  colWith: "Avec",
  colStatus: "Statut",
  colPrice: "Prix",
  colYourPayout: "Votre part",
  colCreated: "Demandée le",
};

export const REQ_COPY = { EN, SW, FR };
