/**
 * Referral copy: the /join/:code welcome, sign-up results, the "Invite
 * artists" dashboard page and the overview card. The API's own `text`
 * fields are English only, so sentences are built here from the numbers.
 * No dashes in user-facing text.
 */
const EN = {
  /* Join page */
  joinTitle: (name: string) => `${name} invited you to 2kTunes`,
  joinTitleGeneric: "You're invited to 2kTunes",
  joinSub: "Release your music to every major store, keep 100% of your rights and get paid by mobile money.",
  youGet: "What you get",
  friendPercent: (pct: string) => `${pct} off your first plan`,
  friendPriceYear: (price: string) => `Your first year for ${price}`,
  friendPricePlan: (plan: string, price: string) => `${plan} for ${price}`,
  friendGeneric: "A special price on your first plan",
  priceWas: (price: string) => `Usually ${price}`,
  joinChecking: "Checking your invite…",
  joinInvalid: "This invite link isn't active, but you can still join 2kTunes. Create your account below.",
  codeLabel: (code: string) => `Invite code ${code}`,
  haveAccount: "Already on 2kTunes?",
  logIn: "Log in",

  /* Sign-up result */
  appliedTitle: "Invite applied",
  appliedBody: "Your invited friend price shows on the Plan page.",
  notAppliedTitle: "We couldn't apply the invite",
  reasons: {
    invalid_code: "The invite code wasn't found. Your account is ready anyway.",
    program_disabled: "Invites are paused right now. Your account is ready anyway.",
    self_referral: "You can't use your own invite link.",
    not_a_new_account: "Invites are for new accounts only.",
    already_referred: "Your account already has an invite.",
    unavailable: "The invite couldn't be applied. Your account is ready anyway.",
  } as Record<string, string>,

  /* Dashboard page */
  pageTitle: "Invite artists",
  pageIntro: "Share your link. Your friends save on their first plan and you earn rewards.",
  yourLink: "Your invite link",
  copyLink: "Copy link",
  share: "Share",
  shareVia: "Share on",
  shareMessage: (gets: string) => `Join me on 2kTunes and release your music everywhere. ${gets}.`,
  shareMessageNoGift: "Join me on 2kTunes and release your music everywhere.",
  code: "Code",
  friendsGet: "Your friends get",
  youGetReward: "You get",
  rewardWallet: (amount: string) => `${amount} in your wallet`,
  rewardDays: (n: number) => (n === 1 ? "1 free day on your plan" : `${n} free days on your plan`),
  rewardJoin: (what: string) => `${what.charAt(0).toUpperCase()}${what.slice(1)} for each friend who joins and confirms their email.`,
  rewardPaid: (what: string) => `${what.charAt(0).toUpperCase()}${what.slice(1)} for each friend who joins and starts a paid plan.`,
  rewardNone: "Rewards are being set up.",
  holdNote: (n: number) => (n === 0 ? "Rewards are added as soon as a friend qualifies." : n === 1 ? "Rewards are added 1 day after a friend qualifies." : `Rewards are added ${n} days after a friend qualifies.`),
  capNote: (n: number) => `Up to ${n} rewards a month.`,
  walletNote: "Wallet rewards are real money you can withdraw.",
  statsTitle: "Your invites",
  joined: "Joined",
  qualified: "Qualified",
  rewarded: "Rewarded",
  earned: "Earned",
  freeDaysEarned: (n: number) => (n === 1 ? "1 free day" : `${n} free days`),
  pendingRewards: (n: number) => (n === 1 ? "1 reward on the way" : `${n} rewards on the way`),
  listTitle: "Friends who joined",
  listEmpty: "No one has joined with your link yet. Share it with artists you know.",
  listPrivacy: "For privacy you only see initials.",
  rewardDue: (d: string) => `Reward due ${d}`,
  rewardSkipped: "Monthly cap reached",
  joinedOn: (d: string) => `Joined ${d}`,
  disabledTitle: "Invites are coming soon",
  disabledBody: "We're getting the invite program ready. Check back soon to share your link and earn rewards.",
  terms: "Program terms",

  /* Overview card */
  cardTitle: "Invite artists, earn rewards",
  cardBody: (gets: string) => `Friends get ${gets.charAt(0).toLowerCase()}${gets.slice(1)}. You earn for each one who joins.`,
  cardBodyGeneric: "Share your link. You earn for each artist who joins.",
  cardCta: "Invite artists",
};

export type ReferralCopy = typeof EN;

const SW: ReferralCopy = {
  joinTitle: (name) => `${name} amekualika 2kTunes`,
  joinTitleGeneric: "Umealikwa 2kTunes",
  joinSub: "Peleka muziki wako kwenye maduka yote makubwa, baki na haki zako zote na ulipwe kwa pesa ya simu.",
  youGet: "Utakachopata",
  friendPercent: (pct) => `Punguzo la ${pct} kwenye kifurushi chako cha kwanza`,
  friendPriceYear: (price) => `Mwaka wako wa kwanza kwa ${price}`,
  friendPricePlan: (plan, price) => `${plan} kwa ${price}`,
  friendGeneric: "Bei maalum kwenye kifurushi chako cha kwanza",
  priceWas: (price) => `Kwa kawaida ${price}`,
  joinChecking: "Inakagua mwaliko wako…",
  joinInvalid: "Kiungo hiki cha mwaliko hakifanyi kazi, lakini bado unaweza kujiunga na 2kTunes. Fungua akaunti hapa chini.",
  codeLabel: (code) => `Msimbo wa mwaliko ${code}`,
  haveAccount: "Tayari uko 2kTunes?",
  logIn: "Ingia",

  appliedTitle: "Mwaliko umetumika",
  appliedBody: "Bei yako ya rafiki aliyealikwa inaonekana kwenye ukurasa wa Kifurushi.",
  notAppliedTitle: "Hatukuweza kutumia mwaliko",
  reasons: {
    invalid_code: "Msimbo wa mwaliko haukupatikana. Akaunti yako iko tayari hata hivyo.",
    program_disabled: "Mialiko imesimamishwa kwa sasa. Akaunti yako iko tayari hata hivyo.",
    self_referral: "Huwezi kutumia kiungo chako mwenyewe.",
    not_a_new_account: "Mialiko ni kwa akaunti mpya tu.",
    already_referred: "Akaunti yako tayari ina mwaliko.",
    unavailable: "Mwaliko haukuweza kutumika. Akaunti yako iko tayari hata hivyo.",
  },

  pageTitle: "Alika wasanii",
  pageIntro: "Shiriki kiungo chako. Marafiki zako wanaokoa kwenye kifurushi cha kwanza na wewe unapata zawadi.",
  yourLink: "Kiungo chako cha mwaliko",
  copyLink: "Nakili kiungo",
  share: "Shiriki",
  shareVia: "Shiriki kwenye",
  shareMessage: (gets) => `Jiunge nami 2kTunes upeleke muziki wako kila mahali. ${gets}.`,
  shareMessageNoGift: "Jiunge nami 2kTunes upeleke muziki wako kila mahali.",
  code: "Msimbo",
  friendsGet: "Marafiki zako wanapata",
  youGetReward: "Wewe unapata",
  rewardWallet: (amount) => `${amount} kwenye pochi yako`,
  rewardDays: (n) => (n === 1 ? "siku 1 ya bure kwenye kifurushi chako" : `siku ${n} za bure kwenye kifurushi chako`),
  rewardJoin: (what) => `${what.charAt(0).toUpperCase()}${what.slice(1)} kwa kila rafiki anayejiunga na kuthibitisha barua pepe.`,
  rewardPaid: (what) => `${what.charAt(0).toUpperCase()}${what.slice(1)} kwa kila rafiki anayejiunga na kuanza kifurushi cha kulipia.`,
  rewardNone: "Zawadi zinaandaliwa.",
  holdNote: (n) => (n === 0 ? "Zawadi zinaongezwa mara rafiki anapofuzu." : n === 1 ? "Zawadi zinaongezwa siku 1 baada ya rafiki kufuzu." : `Zawadi zinaongezwa siku ${n} baada ya rafiki kufuzu.`),
  capNote: (n) => `Hadi zawadi ${n} kwa mwezi.`,
  walletNote: "Zawadi za pochi ni pesa halisi unayoweza kutoa.",
  statsTitle: "Mialiko yako",
  joined: "Wamejiunga",
  qualified: "Wamefuzu",
  rewarded: "Zawadi zimetolewa",
  earned: "Umepata",
  freeDaysEarned: (n) => (n === 1 ? "Siku 1 ya bure" : `Siku ${n} za bure`),
  pendingRewards: (n) => (n === 1 ? "Zawadi 1 iko njiani" : `Zawadi ${n} ziko njiani`),
  listTitle: "Marafiki waliojiunga",
  listEmpty: "Bado hakuna aliyejiunga kupitia kiungo chako. Kishiriki na wasanii unaowajua.",
  listPrivacy: "Kwa faragha unaona herufi za kwanza tu.",
  rewardDue: (d) => `Zawadi itatolewa ${d}`,
  rewardSkipped: "Kikomo cha mwezi kimefikiwa",
  joinedOn: (d) => `Alijiunga ${d}`,
  disabledTitle: "Mialiko inakuja hivi karibuni",
  disabledBody: "Tunaandaa mpango wa mialiko. Rudi hivi karibuni ili kushiriki kiungo chako na kupata zawadi.",
  terms: "Masharti ya mpango",

  cardTitle: "Alika wasanii, upate zawadi",
  cardBody: (gets) => `Marafiki wanapata ${gets.charAt(0).toLowerCase()}${gets.slice(1)}. Unapata zawadi kwa kila anayejiunga.`,
  cardBodyGeneric: "Shiriki kiungo chako. Unapata zawadi kwa kila msanii anayejiunga.",
  cardCta: "Alika wasanii",
};

const FR: ReferralCopy = {
  joinTitle: (name) => `${name} vous invite sur 2kTunes`,
  joinTitleGeneric: "Vous êtes invité sur 2kTunes",
  joinSub: "Diffusez votre musique sur toutes les grandes plateformes, gardez 100 % de vos droits et soyez payé par mobile money.",
  youGet: "Ce que vous obtenez",
  friendPercent: (pct) => `${pct} de réduction sur votre première offre`,
  friendPriceYear: (price) => `Votre première année pour ${price}`,
  friendPricePlan: (plan, price) => `${plan} pour ${price}`,
  friendGeneric: "Un prix spécial sur votre première offre",
  priceWas: (price) => `Habituellement ${price}`,
  joinChecking: "Vérification de votre invitation…",
  joinInvalid: "Ce lien d’invitation n’est pas actif, mais vous pouvez quand même rejoindre 2kTunes. Créez votre compte ci-dessous.",
  codeLabel: (code) => `Code d’invitation ${code}`,
  haveAccount: "Déjà sur 2kTunes ?",
  logIn: "Se connecter",

  appliedTitle: "Invitation appliquée",
  appliedBody: "Votre prix ami invité s’affiche sur la page Offre.",
  notAppliedTitle: "Nous n’avons pas pu appliquer l’invitation",
  reasons: {
    invalid_code: "Le code d’invitation est introuvable. Votre compte est prêt malgré tout.",
    program_disabled: "Les invitations sont en pause. Votre compte est prêt malgré tout.",
    self_referral: "Vous ne pouvez pas utiliser votre propre lien.",
    not_a_new_account: "Les invitations sont réservées aux nouveaux comptes.",
    already_referred: "Votre compte a déjà une invitation.",
    unavailable: "L’invitation n’a pas pu être appliquée. Votre compte est prêt malgré tout.",
  },

  pageTitle: "Inviter des artistes",
  pageIntro: "Partagez votre lien. Vos amis économisent sur leur première offre et vous gagnez des récompenses.",
  yourLink: "Votre lien d’invitation",
  copyLink: "Copier le lien",
  share: "Partager",
  shareVia: "Partager sur",
  shareMessage: (gets) => `Rejoins-moi sur 2kTunes pour diffuser ta musique partout. ${gets}.`,
  shareMessageNoGift: "Rejoins-moi sur 2kTunes pour diffuser ta musique partout.",
  code: "Code",
  friendsGet: "Vos amis obtiennent",
  youGetReward: "Vous obtenez",
  rewardWallet: (amount) => `${amount} sur votre portefeuille`,
  rewardDays: (n) => (n === 1 ? "1 jour gratuit sur votre offre" : `${n} jours gratuits sur votre offre`),
  rewardJoin: (what) => `${what.charAt(0).toUpperCase()}${what.slice(1)} pour chaque ami qui s’inscrit et confirme son e-mail.`,
  rewardPaid: (what) => `${what.charAt(0).toUpperCase()}${what.slice(1)} pour chaque ami qui s’inscrit et prend une offre payante.`,
  rewardNone: "Les récompenses sont en préparation.",
  holdNote: (n) => (n === 0 ? "Les récompenses sont ajoutées dès qu’un ami est qualifié." : n === 1 ? "Les récompenses sont ajoutées 1 jour après la qualification d’un ami." : `Les récompenses sont ajoutées ${n} jours après la qualification d’un ami.`),
  capNote: (n) => `Jusqu’à ${n} récompenses par mois.`,
  walletNote: "Les récompenses portefeuille sont de l’argent réel que vous pouvez retirer.",
  statsTitle: "Vos invitations",
  joined: "Inscrits",
  qualified: "Qualifiés",
  rewarded: "Récompensés",
  earned: "Gagné",
  freeDaysEarned: (n) => (n === 1 ? "1 jour gratuit" : `${n} jours gratuits`),
  pendingRewards: (n) => (n === 1 ? "1 récompense en route" : `${n} récompenses en route`),
  listTitle: "Amis inscrits",
  listEmpty: "Personne ne s’est encore inscrit avec votre lien. Partagez-le avec des artistes que vous connaissez.",
  listPrivacy: "Par respect de la vie privée, vous ne voyez que les initiales.",
  rewardDue: (d) => `Récompense prévue le ${d}`,
  rewardSkipped: "Plafond mensuel atteint",
  joinedOn: (d) => `Inscrit le ${d}`,
  disabledTitle: "Les invitations arrivent bientôt",
  disabledBody: "Nous préparons le programme d’invitation. Revenez bientôt pour partager votre lien et gagner des récompenses.",
  terms: "Conditions du programme",

  cardTitle: "Invitez des artistes, gagnez des récompenses",
  cardBody: (gets) => `Vos amis obtiennent ${gets.charAt(0).toLowerCase()}${gets.slice(1)}. Vous gagnez pour chaque inscription.`,
  cardBodyGeneric: "Partagez votre lien. Vous gagnez pour chaque artiste qui s’inscrit.",
  cardCta: "Inviter des artistes",
};

export const REFERRAL_COPY = { EN, SW, FR };
