/** Copy for /dashboard/splits. */

const EN = {
  title: "Royalty splits",
  description: "Share a release's earnings with collaborators. Everyone is paid their share automatically.",
  newSheet: "New split sheet",
  howTitle: "How splits work",
  how1: "Your own share is accepted automatically.",
  how2: "Everyone else is invited by email and must accept.",
  how3: "The sheet becomes active once every collaborator accepts, and applies to statements processed from then on.",
  how4: "It never rewrites earnings that have already been posted.",

  inviteBannerTitle: "You've been invited to a royalty split",
  inviteBannerBody: "Accept to start receiving your share of this release's earnings, or decline if it isn't right.",
  accept: "Accept",
  decline: "Decline",
  inviteAccepted: "Split accepted",
  inviteDeclined: "Split declined",
  inviteInvalid: "This invitation is invalid or has already been answered.",
  dismiss: "Dismiss",

  invitationsTitle: "Invitations to you",
  invitationsEmpty: "No split invitations right now.",
  from: (name: string) => `From ${name}`,
  yourShare: "Your share",
  role: "Role",
  track: "Track",
  wholeRelease: "Whole release",
  effectiveFrom: "Effective from",
  sheetStatus: "Sheet",
  declineTitle: "Decline this split?",
  declineBody: "The owner will be told you declined. They can send you a new invitation later.",

  mineTitle: "Your split sheets",
  mineEmpty: "No split sheets yet",
  mineEmptyBody: "Create one to share a release's earnings with producers, writers or featured artists.",
  version: (n: number) => `Version ${n}`,
  activated: (date: string) => `Active since ${date}`,
  sharesCaption: (release: string) => `Shares for ${release}`,
  colName: "Name",
  colEmail: "Email",
  colRole: "Role",
  colShare: "Share",
  colStatus: "Status",
  untitled: (id: number) => `Release #${id}`,

  formTitle: "New split sheet",
  formDescription: "Shares must add up to exactly 100%. A new sheet replaces any open proposal for the same release or track.",
  release: "Release",
  releasePlaceholder: "Choose a release",
  releasesEmpty: "You don't have any releases yet. Create a release first.",
  trackLabel: "Applies to",
  trackHint: "Choose a track to split only that track's earnings.",
  effective: "Effective from",
  effectiveHint: "Leave empty to start today. Can't be in the past.",
  effectivePast: "Choose today or a later date.",
  sharesLegend: "Collaborators",
  shareName: "Name",
  shareEmail: "Email",
  shareRole: "Role",
  sharePercent: "Share (%)",
  addRow: "Add collaborator",
  removeRow: (n: number) => `Remove collaborator ${n}`,
  rowLabel: (n: number) => `Collaborator ${n}`,
  you: "You",
  total: "Total",
  remaining: (x: string) => `${x} left to assign`,
  over: (x: string) => `${x} over 100%`,
  exact: "Adds up to 100%",
  nameRequired: "Enter a name.",
  emailInvalid: "Enter a valid email.",
  emailDuplicate: "Each email can appear only once.",
  percentInvalid: "Enter a percentage between 0.01 and 100 (up to 2 decimals).",
  submit: "Send invitations",
  created: "Split sheet created",
  createdActive: "Split is active",
  cancel: "Cancel",
  loadingReleases: "Loading releases…",
  roles: {
    collaborator: "Collaborator",
    primary_artist: "Primary artist",
    featured_artist: "Featured artist",
    producer: "Producer",
    songwriter: "Songwriter",
    composer: "Composer",
    manager: "Manager",
    label: "Label",
  } as Record<string, string>,
};

const SW: typeof EN = {
  title: "Mgawanyo wa mirabaha",
  description: "Gawana mapato ya kazi na washirika wako. Kila mmoja analipwa sehemu yake moja kwa moja.",
  newSheet: "Mgawanyo mpya",
  howTitle: "Mgawanyo unavyofanya kazi",
  how1: "Sehemu yako mwenyewe inakubaliwa moja kwa moja.",
  how2: "Wengine wote wanaalikwa kwa barua pepe na lazima wakubali.",
  how3: "Mgawanyo unaanza kutumika pale kila mshirika anapokubali, na unahusu taarifa za mapato zitakazochakatwa kuanzia hapo.",
  how4: "Haubadilishi kamwe mapato ambayo tayari yameshawekwa.",

  inviteBannerTitle: "Umealikwa kwenye mgawanyo wa mirabaha",
  inviteBannerBody: "Kubali ili uanze kupokea sehemu yako ya mapato ya kazi hii, au kataa kama si sahihi.",
  accept: "Kubali",
  decline: "Kataa",
  inviteAccepted: "Umekubali mgawanyo",
  inviteDeclined: "Umekataa mgawanyo",
  inviteInvalid: "Mwaliko huu si halali au tayari umeshajibiwa.",
  dismiss: "Funga",

  invitationsTitle: "Mialiko kwako",
  invitationsEmpty: "Hakuna mialiko ya mgawanyo kwa sasa.",
  from: (name) => `Kutoka kwa ${name}`,
  yourShare: "Sehemu yako",
  role: "Nafasi",
  track: "Wimbo",
  wholeRelease: "Kazi nzima",
  effectiveFrom: "Inaanza kutumika",
  sheetStatus: "Mgawanyo",
  declineTitle: "Ukatae mgawanyo huu?",
  declineBody: "Mmiliki ataarifiwa kuwa umekataa. Anaweza kukutumia mwaliko mpya baadaye.",

  mineTitle: "Migawanyo yako",
  mineEmpty: "Bado huna mgawanyo wowote",
  mineEmptyBody: "Tengeneza mmoja ili kugawana mapato ya kazi na maprodyuza, watunzi au wasanii walioshirikishwa.",
  version: (n) => `Toleo ${n}`,
  activated: (date) => `Inatumika tangu ${date}`,
  sharesCaption: (release) => `Sehemu za ${release}`,
  colName: "Jina",
  colEmail: "Barua pepe",
  colRole: "Nafasi",
  colShare: "Sehemu",
  colStatus: "Hali",
  untitled: (id) => `Kazi #${id}`,

  formTitle: "Mgawanyo mpya",
  formDescription: "Sehemu zote lazima zijumlishe 100% kamili. Mgawanyo mpya unachukua nafasi ya pendekezo lolote lililo wazi kwa kazi au wimbo huo.",
  release: "Kazi",
  releasePlaceholder: "Chagua kazi",
  releasesEmpty: "Bado huna kazi yoyote. Tengeneza kazi kwanza.",
  trackLabel: "Unahusu",
  trackHint: "Chagua wimbo ili kugawa mapato ya wimbo huo pekee.",
  effective: "Inaanza kutumika",
  effectiveHint: "Acha wazi ili ianze leo. Haiwezi kuwa tarehe iliyopita.",
  effectivePast: "Chagua leo au tarehe ijayo.",
  sharesLegend: "Washirika",
  shareName: "Jina",
  shareEmail: "Barua pepe",
  shareRole: "Nafasi",
  sharePercent: "Sehemu (%)",
  addRow: "Ongeza mshirika",
  removeRow: (n) => `Ondoa mshirika namba ${n}`,
  rowLabel: (n) => `Mshirika namba ${n}`,
  you: "Wewe",
  total: "Jumla",
  remaining: (x) => `${x} bado haijagawiwa`,
  over: (x) => `${x} zaidi ya 100%`,
  exact: "Jumla ni 100%",
  nameRequired: "Weka jina.",
  emailInvalid: "Weka barua pepe sahihi.",
  emailDuplicate: "Kila barua pepe inaweza kuonekana mara moja tu.",
  percentInvalid: "Weka asilimia kati ya 0.01 na 100 (hadi desimali 2).",
  submit: "Tuma mialiko",
  created: "Mgawanyo umetengenezwa",
  createdActive: "Mgawanyo unatumika",
  cancel: "Ghairi",
  loadingReleases: "Inapakia kazi…",
  roles: {
    collaborator: "Mshirika",
    primary_artist: "Msanii mkuu",
    featured_artist: "Msanii aliyeshirikishwa",
    producer: "Prodyuza",
    songwriter: "Mtunzi wa mashairi",
    composer: "Mtunzi wa muziki",
    manager: "Meneja",
    label: "Lebo",
  },
};

const FR: typeof EN = {
  title: "Partages de revenus",
  description: "Partagez les revenus d'une sortie avec vos collaborateurs. Chacun reçoit automatiquement sa part.",
  newSheet: "Nouvelle fiche",
  howTitle: "Comment fonctionnent les partages",
  how1: "Votre propre part est acceptée automatiquement.",
  how2: "Les autres participants sont invités par e-mail et doivent accepter.",
  how3: "La fiche devient active dès que tous les collaborateurs ont accepté, et s'applique aux relevés traités à partir de ce moment.",
  how4: "Elle ne modifie jamais les revenus déjà comptabilisés.",

  inviteBannerTitle: "Vous êtes invité(e) à un partage de revenus",
  inviteBannerBody: "Acceptez pour commencer à recevoir votre part des revenus de cette sortie, ou refusez si elle ne vous convient pas.",
  accept: "Accepter",
  decline: "Refuser",
  inviteAccepted: "Partage accepté",
  inviteDeclined: "Partage refusé",
  inviteInvalid: "Cette invitation n'est pas valide ou a déjà reçu une réponse.",
  dismiss: "Fermer",

  invitationsTitle: "Invitations reçues",
  invitationsEmpty: "Aucune invitation de partage pour le moment.",
  from: (name: string) => `De ${name}`,
  yourShare: "Votre part",
  role: "Rôle",
  track: "Titre",
  wholeRelease: "Toute la sortie",
  effectiveFrom: "En vigueur à partir du",
  sheetStatus: "Fiche",
  declineTitle: "Refuser ce partage ?",
  declineBody: "Le propriétaire sera informé de votre refus. Il pourra vous envoyer une nouvelle invitation plus tard.",

  mineTitle: "Vos fiches de partage",
  mineEmpty: "Aucune fiche de partage",
  mineEmptyBody: "Créez-en une pour partager les revenus d'une sortie avec des producteurs, auteurs ou artistes invités.",
  version: (n: number) => `Version ${n}`,
  activated: (date: string) => `Active depuis le ${date}`,
  sharesCaption: (release: string) => `Parts pour ${release}`,
  colName: "Nom",
  colEmail: "E-mail",
  colRole: "Rôle",
  colShare: "Part",
  colStatus: "Statut",
  untitled: (id: number) => `Sortie n° ${id}`,

  formTitle: "Nouvelle fiche de partage",
  formDescription: "Le total des parts doit être exactement de 100 %. Une nouvelle fiche remplace toute proposition en cours pour la même sortie ou le même titre.",
  release: "Sortie",
  releasePlaceholder: "Choisissez une sortie",
  releasesEmpty: "Vous n'avez encore aucune sortie. Créez d'abord une sortie.",
  trackLabel: "S'applique à",
  trackHint: "Choisissez un titre pour ne partager que les revenus de ce titre.",
  effective: "En vigueur à partir du",
  effectiveHint: "Laissez vide pour commencer aujourd'hui. Ne peut pas être dans le passé.",
  effectivePast: "Choisissez aujourd'hui ou une date ultérieure.",
  sharesLegend: "Collaborateurs",
  shareName: "Nom",
  shareEmail: "E-mail",
  shareRole: "Rôle",
  sharePercent: "Part (%)",
  addRow: "Ajouter un collaborateur",
  removeRow: (n: number) => `Retirer le collaborateur ${n}`,
  rowLabel: (n: number) => `Collaborateur ${n}`,
  you: "Vous",
  total: "Total",
  remaining: (x: string) => `${x} restant à attribuer`,
  over: (x: string) => `${x} au-delà de 100 %`,
  exact: "Total : 100 %",
  nameRequired: "Saisissez un nom.",
  emailInvalid: "Saisissez une adresse e-mail valide.",
  emailDuplicate: "Chaque adresse e-mail ne peut apparaître qu'une fois.",
  percentInvalid: "Saisissez un pourcentage entre 0,01 et 100 (2 décimales max.).",
  submit: "Envoyer les invitations",
  created: "Fiche de partage créée",
  createdActive: "Le partage est actif",
  cancel: "Annuler",
  loadingReleases: "Chargement des sorties…",
  roles: {
    collaborator: "Collaborateur",
    primary_artist: "Artiste principal",
    featured_artist: "Artiste invité",
    producer: "Producteur",
    songwriter: "Auteur-compositeur",
    composer: "Compositeur",
    manager: "Manager",
    label: "Label",
  } as Record<string, string>,
};

export const COPY = { EN, SW, FR };
export const ROLE_KEYS = [
  "collaborator",
  "primary_artist",
  "featured_artist",
  "producer",
  "songwriter",
  "composer",
  "manager",
  "label",
] as const;
