/** Copy for /dashboard/splits. */

const EN = {
  title: "Royalty splits",
  description: "Share a release's earnings with collaborators. Everyone is paid their share automatically.",
  newSheet: "New split sheet",
  howTitle: "How splits work",
  how1: "Your own share is accepted automatically.",
  how2: "Everyone else is invited by email and must accept.",
  how3: "The sheet becomes active once every collaborator accepts, and applies to statements processed from then on.",
  how4: "It never rewrites earnings that have already been posted.",

  inviteBannerTitle: "You've been invited to a royalty split",
  inviteBannerBody: "Accept to start receiving your share of this release's earnings, or decline if it isn't right.",
  accept: "Accept",
  decline: "Decline",
  inviteAccepted: "Split accepted",
  inviteDeclined: "Split declined",
  inviteInvalid: "This invitation is invalid or has already been answered.",
  dismiss: "Dismiss",

  invitationsTitle: "Invitations to you",
  invitationsEmpty: "No split invitations right now.",
  from: (name: string) => `From ${name}`,
  yourShare: "Your share",
  role: "Role",
  track: "Track",
  wholeRelease: "Whole release",
  effectiveFrom: "Effective from",
  sheetStatus: "Sheet",
  declineTitle: "Decline this split?",
  declineBody: "The owner will be told you declined. They can send you a new invitation later.",

  mineTitle: "Your split sheets",
  mineEmpty: "No split sheets yet",
  mineEmptyBody: "Create one to share a release's earnings with producers, writers or featured artists.",
  version: (n: number) => `Version ${n}`,
  activated: (date: string) => `Active since ${date}`,
  sharesCaption: (release: string) => `Shares for ${release}`,
  colName: "Name",
  colEmail: "Email",
  colRole: "Role",
  colShare: "Share",
  colStatus: "Status",
  untitled: (id: number) => `Release #${id}`,

  formTitle: "New split sheet",
  formDescription: "Shares must add up to exactly 100%. A new sheet replaces any open proposal for the same release or track.",
  release: "Release",
  releasePlaceholder: "Choose a release",
  releasesEmpty: "You don't have any releases yet. Create a release first.",
  trackLabel: "Applies to",
  trackHint: "Choose a track to split only that track's earnings.",
  effective: "Effective from",
  effectiveHint: "Leave empty to start today. Can't be in the past.",
  effectivePast: "Choose today or a later date.",
  sharesLegend: "Collaborators",
  shareName: "Name",
  shareEmail: "Email",
  shareRole: "Role",
  sharePercent: "Share (%)",
  addRow: "Add collaborator",
  removeRow: (n: number) => `Remove collaborator ${n}`,
  rowLabel: (n: number) => `Collaborator ${n}`,
  you: "You",
  total: "Total",
  remaining: (x: string) => `${x} left to assign`,
  over: (x: string) => `${x} over 100%`,
  exact: "Adds up to 100%",
  nameRequired: "Enter a name.",
  emailInvalid: "Enter a valid email.",
  emailDuplicate: "Each email can appear only once.",
  percentInvalid: "Enter a percentage between 0.01 and 100 (up to 2 decimals).",
  submit: "Send invitations",
  created: "Split sheet created",
  createdActive: "Split is active",
  cancel: "Cancel",
  loadingReleases: "Loading releases…",
  roles: {
    collaborator: "Collaborator",
    primary_artist: "Primary artist",
    featured_artist: "Featured artist",
    producer: "Producer",
    songwriter: "Songwriter",
    composer: "Composer",
    manager: "Manager",
    label: "Label",
  } as Record<string, string>,
};

const SW: typeof EN = {
  title: "Mgawanyo wa mirabaha",
  description: "Gawana mapato ya kazi na washirika wako. Kila mmoja analipwa sehemu yake moja kwa moja.",
  newSheet: "Mgawanyo mpya",
  howTitle: "Mgawanyo unavyofanya kazi",
  how1: "Sehemu yako mwenyewe inakubaliwa moja kwa moja.",
  how2: "Wengine wote wanaalikwa kwa barua pepe na lazima wakubali.",
  how3: "Mgawanyo unaanza kutumika pale kila mshirika anapokubali, na unahusu taarifa za mapato zitakazochakatwa kuanzia hapo.",
  how4: "Haubadilishi kamwe mapato ambayo tayari yameshawekwa.",

  inviteBannerTitle: "Umealikwa kwenye mgawanyo wa mirabaha",
  inviteBannerBody: "Kubali ili uanze kupokea sehemu yako ya mapato ya kazi hii, au kataa kama si sahihi.",
  accept: "Kubali",
  decline: "Kataa",
  inviteAccepted: "Umekubali mgawanyo",
  inviteDeclined: "Umekataa mgawanyo",
  inviteInvalid: "Mwaliko huu si halali au tayari umeshajibiwa.",
  dismiss: "Funga",

  invitationsTitle: "Mialiko kwako",
  invitationsEmpty: "Hakuna mialiko ya mgawanyo kwa sasa.",
  from: (name) => `Kutoka kwa ${name}`,
  yourShare: "Sehemu yako",
  role: "Nafasi",
  track: "Wimbo",
  wholeRelease: "Kazi nzima",
  effectiveFrom: "Inaanza kutumika",
  sheetStatus: "Mgawanyo",
  declineTitle: "Ukatae mgawanyo huu?",
  declineBody: "Mmiliki ataarifiwa kuwa umekataa. Anaweza kukutumia mwaliko mpya baadaye.",

  mineTitle: "Migawanyo yako",
  mineEmpty: "Bado huna mgawanyo wowote",
  mineEmptyBody: "Tengeneza mmoja ili kugawana mapato ya kazi na maprodyuza, watunzi au wasanii walioshirikishwa.",
  version: (n) => `Toleo ${n}`,
  activated: (date) => `Inatumika tangu ${date}`,
  sharesCaption: (release) => `Sehemu za ${release}`,
  colName: "Jina",
  colEmail: "Barua pepe",
  colRole: "Nafasi",
  colShare: "Sehemu",
  colStatus: "Hali",
  untitled: (id) => `Kazi #${id}`,

  formTitle: "Mgawanyo mpya",
  formDescription: "Sehemu zote lazima zijumlishe 100% kamili. Mgawanyo mpya unachukua nafasi ya pendekezo lolote lililo wazi kwa kazi au wimbo huo.",
  release: "Kazi",
  releasePlaceholder: "Chagua kazi",
  releasesEmpty: "Bado huna kazi yoyote. Tengeneza kazi kwanza.",
  trackLabel: "Unahusu",
  trackHint: "Chagua wimbo ili kugawa mapato ya wimbo huo pekee.",
  effective: "Inaanza kutumika",
  effectiveHint: "Acha wazi ili ianze leo. Haiwezi kuwa tarehe iliyopita.",
  effectivePast: "Chagua leo au tarehe ijayo.",
  sharesLegend: "Washirika",
  shareName: "Jina",
  shareEmail: "Barua pepe",
  shareRole: "Nafasi",
  sharePercent: "Sehemu (%)",
  addRow: "Ongeza mshirika",
  removeRow: (n) => `Ondoa mshirika namba ${n}`,
  rowLabel: (n) => `Mshirika namba ${n}`,
  you: "Wewe",
  total: "Jumla",
  remaining: (x) => `${x} bado haijagawiwa`,
  over: (x) => `${x} zaidi ya 100%`,
  exact: "Jumla ni 100%",
  nameRequired: "Weka jina.",
  emailInvalid: "Weka barua pepe sahihi.",
  emailDuplicate: "Kila barua pepe inaweza kuonekana mara moja tu.",
  percentInvalid: "Weka asilimia kati ya 0.01 na 100 (hadi desimali 2).",
  submit: "Tuma mialiko",
  created: "Mgawanyo umetengenezwa",
  createdActive: "Mgawanyo unatumika",
  cancel: "Ghairi",
  loadingReleases: "Inapakia kazi…",
  roles: {
    collaborator: "Mshirika",
    primary_artist: "Msanii mkuu",
    featured_artist: "Msanii aliyeshirikishwa",
    producer: "Prodyuza",
    songwriter: "Mtunzi wa mashairi",
    composer: "Mtunzi wa muziki",
    manager: "Meneja",
    label: "Lebo",
  },
};

export const COPY = { EN, SW };
export const ROLE_KEYS = [
  "collaborator",
  "primary_artist",
  "featured_artist",
  "producer",
  "songwriter",
  "composer",
  "manager",
  "label",
] as const;
