/** Analytics screen copy. */

const EN = {
  title: "Analytics",
  intro: "Earnings and listening from posted store statements, plus activity on your smart links.",
  filtersLabel: "Analytics filters",
  range: "Period",
  ranges: { "7d": "7 days", "30d": "30 days", "90d": "90 days", "12m": "12 months", custom: "Custom" },
  from: "From",
  to: "To",
  pickDates: "Choose a start and end date to see this period.",
  rangeInvalid: "The start date must be on or before the end date.",
  release: "Release",
  allReleases: "All releases",
  showing: (from: string, to: string) => `Showing ${from} to ${to}`,

  emptyTitle: "No store data for this period yet",
  emptyBody:
    "Streams, downloads and earnings appear here when store statements are imported and posted by 2kTunes finance, usually 1 to 3 months after the plays happen.",

  totalsTitle: "Totals",
  revenue: (cur: string) => `Revenue (${cur})`,
  streams: "Streams",
  downloads: "Downloads",
  videoUses: "Video uses",
  videoUsesHint: "Video and user-generated content",

  monthlyTitle: "By month",
  monthlyDesc: "Revenue per month from posted statements.",
  chartCaption: (cur: string) => `Monthly revenue in ${cur}`,
  chartNote: "Exact values are in the table below.",
  tableCaption: (cur: string) => `Monthly revenue and streams in ${cur}`,
  colMonth: "Month",
  colRevenue: "Revenue",
  colStreams: "Streams",
  colUnits: "Units",

  topTitle: "Top performers",
  topReleases: "Releases",
  topTracks: "Tracks",
  topStores: "Stores",
  topTerritories: "Countries",
  byUsage: "Usage type",
  unitsCount: (n: string) => `${n} units`,
  unknown: "Unknown",
  usage: {
    stream: "Streams",
    streams: "Streams",
    download: "Downloads",
    video: "Video",
    ugc: "User videos (UGC)",
    other: "Other",
  } as Record<string, string>,

  linksTitle: "Smart links",
  linksDesc: "Visits and clicks on your release pages for this period.",
  views: "Page views",
  uniqueVisitors: "Unique visitors",
  clicks: "Store clicks",
  presaves: "Pre-saves",
  byStore: "Clicks by store",
  byCountry: "Views by country",
  byDevice: "Views by device",
  byReferrer: "Top referrers",
  devices: { mobile: "Mobile", desktop: "Desktop", tablet: "Tablet", bot: "Bot" } as Record<string, string>,

  campaignsTitle: "Promotion orders",
  activeOrders: "Active orders",
  completedOrders: "Completed orders",
};

const SW: typeof EN = {
  title: "Takwimu",
  intro: "Mapato na usikilizaji kutoka kwenye ripoti za maduka zilizothibitishwa, pamoja na shughuli kwenye viungo vyako mahiri.",
  filtersLabel: "Vichujio vya takwimu",
  range: "Kipindi",
  ranges: { "7d": "Siku 7", "30d": "Siku 30", "90d": "Siku 90", "12m": "Miezi 12", custom: "Chagua mwenyewe" },
  from: "Kuanzia",
  to: "Hadi",
  pickDates: "Chagua tarehe ya kuanzia na ya mwisho kuona kipindi hiki.",
  rangeInvalid: "Tarehe ya kuanzia lazima iwe kabla au sawa na tarehe ya mwisho.",
  release: "Toleo",
  allReleases: "Matoleo yote",
  showing: (from: string, to: string) => `Inaonyesha ${from} hadi ${to}`,

  emptyTitle: "Bado hakuna takwimu za maduka kwa kipindi hiki",
  emptyBody:
    "Usikilizaji, upakuaji na mapato huonekana hapa ripoti za maduka zikishaingizwa na kuthibitishwa na idara ya fedha ya 2kTunes, kwa kawaida miezi 1 hadi 3 baada ya nyimbo kusikilizwa.",

  totalsTitle: "Jumla",
  revenue: (cur: string) => `Mapato (${cur})`,
  streams: "Usikilizaji",
  downloads: "Upakuaji",
  videoUses: "Matumizi ya video",
  videoUsesHint: "Video na maudhui ya watumiaji",

  monthlyTitle: "Kwa mwezi",
  monthlyDesc: "Mapato kwa kila mwezi kutoka ripoti zilizothibitishwa.",
  chartCaption: (cur: string) => `Mapato ya kila mwezi kwa ${cur}`,
  chartNote: "Thamani kamili ziko kwenye jedwali hapa chini.",
  tableCaption: (cur: string) => `Mapato na usikilizaji wa kila mwezi kwa ${cur}`,
  colMonth: "Mwezi",
  colRevenue: "Mapato",
  colStreams: "Usikilizaji",
  colUnits: "Idadi",

  topTitle: "Vinavyofanya vizuri",
  topReleases: "Matoleo",
  topTracks: "Nyimbo",
  topStores: "Maduka",
  topTerritories: "Nchi",
  byUsage: "Aina ya matumizi",
  unitsCount: (n: string) => `mara ${n}`,
  unknown: "Haijulikani",
  usage: {
    stream: "Usikilizaji",
    streams: "Usikilizaji",
    download: "Upakuaji",
    video: "Video",
    ugc: "Video za watumiaji (UGC)",
    other: "Mengineyo",
  },

  linksTitle: "Viungo mahiri",
  linksDesc: "Walioitembelea na kubofya kurasa za matoleo yako katika kipindi hiki.",
  views: "Walioitazama",
  uniqueVisitors: "Wageni wa kipekee",
  clicks: "Mibofyo kwenda madukani",
  presaves: "Pre-save",
  byStore: "Mibofyo kwa duka",
  byCountry: "Walioitazama kwa nchi",
  byDevice: "Walioitazama kwa kifaa",
  byReferrer: "Walikotoka",
  devices: { mobile: "Simu", desktop: "Kompyuta", tablet: "Tableti", bot: "Roboti" },

  campaignsTitle: "Oda za matangazo",
  activeOrders: "Oda zinazoendelea",
  completedOrders: "Oda zilizokamilika",
};

const FR: typeof EN = {
  title: "Statistiques",
  intro: "Revenus et écoutes issus des relevés publiés des plateformes, ainsi que l'activité de vos liens intelligents.",
  filtersLabel: "Filtres des statistiques",
  range: "Période",
  ranges: { "7d": "7 jours", "30d": "30 jours", "90d": "90 jours", "12m": "12 mois", custom: "Personnalisée" },
  from: "Du",
  to: "Au",
  pickDates: "Choisissez une date de début et de fin pour afficher cette période.",
  rangeInvalid: "La date de début doit être antérieure ou égale à la date de fin.",
  release: "Sortie",
  allReleases: "Toutes les sorties",
  showing: (from: string, to: string) => `Du ${from} au ${to}`,

  emptyTitle: "Aucune donnée des plateformes sur cette période",
  emptyBody:
    "Les écoutes, téléchargements et revenus apparaissent ici une fois les relevés des plateformes importés et publiés par le service financier de 2kTunes, généralement 1 à 3 mois après les écoutes.",

  totalsTitle: "Totaux",
  revenue: (cur: string) => `Revenus (${cur})`,
  streams: "Écoutes",
  downloads: "Téléchargements",
  videoUses: "Utilisations vidéo",
  videoUsesHint: "Vidéos et contenus créés par les utilisateurs",

  monthlyTitle: "Par mois",
  monthlyDesc: "Revenus mensuels issus des relevés publiés.",
  chartCaption: (cur: string) => `Revenus mensuels en ${cur}`,
  chartNote: "Les valeurs exactes figurent dans le tableau ci-dessous.",
  tableCaption: (cur: string) => `Revenus et écoutes mensuels en ${cur}`,
  colMonth: "Mois",
  colRevenue: "Revenus",
  colStreams: "Écoutes",
  colUnits: "Unités",

  topTitle: "Meilleures performances",
  topReleases: "Sorties",
  topTracks: "Titres",
  topStores: "Plateformes",
  topTerritories: "Pays",
  byUsage: "Type d'utilisation",
  unitsCount: (n: string) => `${n} unités`,
  unknown: "Inconnu",
  usage: {
    stream: "Écoutes",
    streams: "Écoutes",
    download: "Téléchargements",
    video: "Vidéo",
    ugc: "Vidéos d'utilisateurs (UGC)",
    other: "Autre",
  },

  linksTitle: "Liens intelligents",
  linksDesc: "Visites et clics sur les pages de vos sorties pendant cette période.",
  views: "Pages vues",
  uniqueVisitors: "Visiteurs uniques",
  clicks: "Clics vers plateformes",
  presaves: "Pré-enregistrements",
  byStore: "Clics par plateforme",
  byCountry: "Vues par pays",
  byDevice: "Vues par appareil",
  byReferrer: "Principales sources",
  devices: { mobile: "Mobile", desktop: "Ordinateur", tablet: "Tablette", bot: "Robot" },

  campaignsTitle: "Commandes de promotion",
  activeOrders: "Commandes en cours",
  completedOrders: "Commandes terminées",
};

export const COPY = { EN, SW, FR };
export type AnalyticsCopy = typeof EN;
