/** Analytics screen copy. */

const EN = {
  title: "Analytics",
  intro: "Earnings and listening from posted store statements, plus activity on your smart links.",
  filtersLabel: "Analytics filters",
  range: "Period",
  ranges: { "7d": "7 days", "30d": "30 days", "90d": "90 days", "12m": "12 months", custom: "Custom" },
  from: "From",
  to: "To",
  pickDates: "Choose a start and end date to see this period.",
  rangeInvalid: "The start date must be on or before the end date.",
  release: "Release",
  allReleases: "All releases",
  showing: (from: string, to: string) => `Showing ${from} – ${to}`,

  emptyTitle: "No store data for this period yet",
  emptyBody:
    "Streams, downloads and earnings appear here when store statements are imported and posted by 2kTunes finance — usually 1–3 months after the plays happen.",

  totalsTitle: "Totals",
  revenue: (cur: string) => `Revenue (${cur})`,
  streams: "Streams",
  downloads: "Downloads",
  videoUses: "Video uses",
  videoUsesHint: "Video and user-generated content",

  monthlyTitle: "By month",
  monthlyDesc: "Revenue per month from posted statements.",
  chartCaption: (cur: string) => `Monthly revenue in ${cur}`,
  chartNote: "Exact values are in the table below.",
  tableCaption: (cur: string) => `Monthly revenue and streams in ${cur}`,
  colMonth: "Month",
  colRevenue: "Revenue",
  colStreams: "Streams",
  colUnits: "Units",

  topTitle: "Top performers",
  topReleases: "Releases",
  topTracks: "Tracks",
  topStores: "Stores",
  topTerritories: "Countries",
  byUsage: "Usage type",
  unitsCount: (n: string) => `${n} units`,
  unknown: "Unknown",
  usage: {
    stream: "Streams",
    streams: "Streams",
    download: "Downloads",
    video: "Video",
    ugc: "User videos (UGC)",
    other: "Other",
  } as Record<string, string>,

  linksTitle: "Smart links",
  linksDesc: "Visits and clicks on your release pages for this period.",
  views: "Page views",
  uniqueVisitors: "Unique visitors",
  clicks: "Store clicks",
  presaves: "Pre-saves",
  byStore: "Clicks by store",
  byCountry: "Views by country",
  byDevice: "Views by device",
  byReferrer: "Top referrers",
  devices: { mobile: "Mobile", desktop: "Desktop", tablet: "Tablet", bot: "Bot" } as Record<string, string>,

  campaignsTitle: "Promotion orders",
  activeOrders: "Active orders",
  completedOrders: "Completed orders",
};

const SW: typeof EN = {
  title: "Takwimu",
  intro: "Mapato na usikilizaji kutoka kwenye ripoti za maduka zilizothibitishwa, pamoja na shughuli kwenye viungo vyako mahiri.",
  filtersLabel: "Vichujio vya takwimu",
  range: "Kipindi",
  ranges: { "7d": "Siku 7", "30d": "Siku 30", "90d": "Siku 90", "12m": "Miezi 12", custom: "Chagua mwenyewe" },
  from: "Kuanzia",
  to: "Hadi",
  pickDates: "Chagua tarehe ya kuanzia na ya mwisho kuona kipindi hiki.",
  rangeInvalid: "Tarehe ya kuanzia lazima iwe kabla au sawa na tarehe ya mwisho.",
  release: "Toleo",
  allReleases: "Matoleo yote",
  showing: (from: string, to: string) => `Inaonyesha ${from} – ${to}`,

  emptyTitle: "Bado hakuna takwimu za maduka kwa kipindi hiki",
  emptyBody:
    "Usikilizaji, upakuaji na mapato huonekana hapa ripoti za maduka zikishaingizwa na kuthibitishwa na idara ya fedha ya 2kTunes — kwa kawaida miezi 1–3 baada ya nyimbo kusikilizwa.",

  totalsTitle: "Jumla",
  revenue: (cur: string) => `Mapato (${cur})`,
  streams: "Usikilizaji",
  downloads: "Upakuaji",
  videoUses: "Matumizi ya video",
  videoUsesHint: "Video na maudhui ya watumiaji",

  monthlyTitle: "Kwa mwezi",
  monthlyDesc: "Mapato kwa kila mwezi kutoka ripoti zilizothibitishwa.",
  chartCaption: (cur: string) => `Mapato ya kila mwezi kwa ${cur}`,
  chartNote: "Thamani kamili ziko kwenye jedwali hapa chini.",
  tableCaption: (cur: string) => `Mapato na usikilizaji wa kila mwezi kwa ${cur}`,
  colMonth: "Mwezi",
  colRevenue: "Mapato",
  colStreams: "Usikilizaji",
  colUnits: "Idadi",

  topTitle: "Vinavyofanya vizuri",
  topReleases: "Matoleo",
  topTracks: "Nyimbo",
  topStores: "Maduka",
  topTerritories: "Nchi",
  byUsage: "Aina ya matumizi",
  unitsCount: (n: string) => `mara ${n}`,
  unknown: "Haijulikani",
  usage: {
    stream: "Usikilizaji",
    streams: "Usikilizaji",
    download: "Upakuaji",
    video: "Video",
    ugc: "Video za watumiaji (UGC)",
    other: "Mengineyo",
  },

  linksTitle: "Viungo mahiri",
  linksDesc: "Walioitembelea na kubofya kurasa za matoleo yako katika kipindi hiki.",
  views: "Walioitazama",
  uniqueVisitors: "Wageni wa kipekee",
  clicks: "Mibofyo kwenda madukani",
  presaves: "Pre-save",
  byStore: "Mibofyo kwa duka",
  byCountry: "Walioitazama kwa nchi",
  byDevice: "Walioitazama kwa kifaa",
  byReferrer: "Walikotoka",
  devices: { mobile: "Simu", desktop: "Kompyuta", tablet: "Tableti", bot: "Roboti" },

  campaignsTitle: "Oda za matangazo",
  activeOrders: "Oda zinazoendelea",
  completedOrders: "Oda zilizokamilika",
};

export const COPY = { EN, SW };
export type AnalyticsCopy = typeof EN;
