/** Copy for the public smart-link page (/r/:slug). */

const EN = {
  loading: "Loading release…",
  coverAlt: (title: string, artist: string) => `Cover art for ${title} by ${artist}`,
  by: (artist: string) => `by ${artist}`,
  typeSingle: "Single",
  typeEP: "EP",
  typeAlbum: "Album",
  releasedOn: (date: string) => `Released ${date}`,
  outOn: (date: string) => `Out ${date}`,
  listenOn: "Listen on",
  listenAria: (store: string) => `Listen on ${store} (opens in a new tab)`,
  play: "Play",
  noLinks: "Store links will appear here as soon as they're live.",
  upcomingTitle: "Coming soon",
  upcomingBody: (date: string) => `This release arrives on ${date}.`,
  upcomingBodyNoDate: "This release is on its way.",
  pendingTitle: "Coming soon to your favourite stores",
  pendingBody:
    "This release is being delivered to music stores. Each store publishes on its own schedule — check back soon to listen.",
  notifyTitle: "Get notified when it's out",
  notifyBody: "Leave your email and we'll send you one message when it's available to stream.",
  email: "Email address",
  emailRequired: "Enter a valid email address.",
  consent: "I agree to receive an email about this release. My address won't be used for anything else.",
  consentRequired: "Tick the box so we can email you.",
  notify: "Notify me",
  notifySuccess: "You're on the list. We'll email you when it's out.",
  notifyUnavailable: "Notifications aren't available for this release any more.",
  followArtist: "Follow the artist",
  instagram: "Instagram",
  tiktok: "TikTok",
  youtube: "YouTube",
  followAria: (network: string) => `${network} (opens in a new tab)`,
  poweredBy: "Powered by",
  distributeCta: "Release your own music",
  notFoundTitle: "We couldn't find this release",
  notFoundBody: "The link may be mistyped, or the release is no longer available.",
  goHome: "Go to 2kTunes",
};

const SW: typeof EN = {
  loading: "Inapakia kazi…",
  coverAlt: (title, artist) => `Picha ya jalada ya ${title} ya ${artist}`,
  by: (artist) => `na ${artist}`,
  typeSingle: "Wimbo mmoja",
  typeEP: "EP",
  typeAlbum: "Albamu",
  releasedOn: (date) => `Imetoka ${date}`,
  outOn: (date) => `Inatoka ${date}`,
  listenOn: "Sikiliza kwenye",
  listenAria: (store) => `Sikiliza kwenye ${store} (inafunguka kwenye kichupo kipya)`,
  play: "Cheza",
  noLinks: "Viungo vya maduka vitaonekana hapa mara tu vitakapokuwa hewani.",
  upcomingTitle: "Inakuja hivi karibuni",
  upcomingBody: (date) => `Kazi hii itatoka tarehe ${date}.`,
  upcomingBodyNoDate: "Kazi hii iko njiani.",
  pendingTitle: "Inakuja hivi karibuni kwenye maduka unayopenda",
  pendingBody:
    "Kazi hii inapelekwa kwenye maduka ya muziki. Kila duka huchapisha kwa ratiba yake — rudi hivi karibuni kusikiliza.",
  notifyTitle: "Pata taarifa itakapotoka",
  notifyBody: "Acha barua pepe yako na tutakutumia ujumbe mmoja itakapopatikana kusikilizwa.",
  email: "Barua pepe",
  emailRequired: "Weka barua pepe sahihi.",
  consent: "Nakubali kupokea barua pepe kuhusu kazi hii. Anwani yangu haitatumika kwa jambo jingine.",
  consentRequired: "Weka alama kwenye kisanduku ili tukutumie barua pepe.",
  notify: "Nijulishe",
  notifySuccess: "Umeongezwa kwenye orodha. Tutakutumia barua pepe itakapotoka.",
  notifyUnavailable: "Taarifa hazipatikani tena kwa kazi hii.",
  followArtist: "Mfuatilie msanii",
  instagram: "Instagram",
  tiktok: "TikTok",
  youtube: "YouTube",
  followAria: (network) => `${network} (inafunguka kwenye kichupo kipya)`,
  poweredBy: "Inaendeshwa na",
  distributeCta: "Toa muziki wako mwenyewe",
  notFoundTitle: "Hatukuipata kazi hii",
  notFoundBody: "Huenda kiungo kimekosewa, au kazi hii haipatikani tena.",
  goHome: "Nenda 2kTunes",
};

export const COPY = { EN, SW };
