/** Copy for the public smart-link page (/r/:slug). */

const EN = {
  loading: "Loading release…",
  unsubscribed: "You're unsubscribed. We won't email you about this release again.",
  coverAlt: (title: string, artist: string) => `Cover art for ${title} by ${artist}`,
  by: (artist: string) => `by ${artist}`,
  typeSingle: "Single",
  typeEP: "EP",
  typeAlbum: "Album",
  releasedOn: (date: string) => `Released ${date}`,
  outOn: (date: string) => `Out ${date}`,
  listenOn: "Listen on",
  listenAria: (store: string) => `Listen on ${store} (opens in a new tab)`,
  play: "Play",
  noLinks: "Store links will appear here as soon as they're live.",
  upcomingTitle: "Coming soon",
  upcomingBody: (date: string) => `This release arrives on ${date}.`,
  upcomingBodyNoDate: "This release is on its way.",
  pendingTitle: "Coming soon to your favourite stores",
  pendingBody:
    "This release is being delivered to music stores. Each store publishes on its own schedule — check back soon to listen.",
  notifyTitle: "Get notified when it's out",
  notifyBody: "Leave your email and we'll send you one message when it's available to stream.",
  email: "Email address",
  emailRequired: "Enter a valid email address.",
  consent: "I agree to receive an email about this release. My address won't be used for anything else.",
  consentRequired: "Tick the box so we can email you.",
  notify: "Notify me",
  notifySuccess: "You're on the list. We'll email you when it's out.",
  notifyUnavailable: "Notifications aren't available for this release any more.",
  followArtist: "Follow the artist",
  instagram: "Instagram",
  tiktok: "TikTok",
  youtube: "YouTube",
  followAria: (network: string) => `${network} (opens in a new tab)`,
  poweredBy: "Powered by",
  distributeCta: "Release your own music",
  notFoundTitle: "We couldn't find this release",
  notFoundBody: "The link may be mistyped, or the release is no longer available.",
  goHome: "Go to 2kTunes",
};

const SW: typeof EN = {
  loading: "Inapakia kazi…",
  unsubscribed: "Umejiondoa. Hatutakutumia barua pepe tena kuhusu kazi hii.",
  coverAlt: (title, artist) => `Picha ya jalada ya ${title} ya ${artist}`,
  by: (artist) => `na ${artist}`,
  typeSingle: "Wimbo mmoja",
  typeEP: "EP",
  typeAlbum: "Albamu",
  releasedOn: (date) => `Imetoka ${date}`,
  outOn: (date) => `Inatoka ${date}`,
  listenOn: "Sikiliza kwenye",
  listenAria: (store) => `Sikiliza kwenye ${store} (inafunguka kwenye kichupo kipya)`,
  play: "Cheza",
  noLinks: "Viungo vya maduka vitaonekana hapa mara tu vitakapokuwa hewani.",
  upcomingTitle: "Inakuja hivi karibuni",
  upcomingBody: (date) => `Kazi hii itatoka tarehe ${date}.`,
  upcomingBodyNoDate: "Kazi hii iko njiani.",
  pendingTitle: "Inakuja hivi karibuni kwenye maduka unayopenda",
  pendingBody:
    "Kazi hii inapelekwa kwenye maduka ya muziki. Kila duka huchapisha kwa ratiba yake — rudi hivi karibuni kusikiliza.",
  notifyTitle: "Pata taarifa itakapotoka",
  notifyBody: "Acha barua pepe yako na tutakutumia ujumbe mmoja itakapopatikana kusikilizwa.",
  email: "Barua pepe",
  emailRequired: "Weka barua pepe sahihi.",
  consent: "Nakubali kupokea barua pepe kuhusu kazi hii. Anwani yangu haitatumika kwa jambo jingine.",
  consentRequired: "Weka alama kwenye kisanduku ili tukutumie barua pepe.",
  notify: "Nijulishe",
  notifySuccess: "Umeongezwa kwenye orodha. Tutakutumia barua pepe itakapotoka.",
  notifyUnavailable: "Taarifa hazipatikani tena kwa kazi hii.",
  followArtist: "Mfuatilie msanii",
  instagram: "Instagram",
  tiktok: "TikTok",
  youtube: "YouTube",
  followAria: (network) => `${network} (inafunguka kwenye kichupo kipya)`,
  poweredBy: "Inaendeshwa na",
  distributeCta: "Toa muziki wako mwenyewe",
  notFoundTitle: "Hatukuipata kazi hii",
  notFoundBody: "Huenda kiungo kimekosewa, au kazi hii haipatikani tena.",
  goHome: "Nenda 2kTunes",
};

const FR: typeof EN = {
  loading: "Chargement de la sortie…",
  unsubscribed: "Vous êtes désinscrit. Nous ne vous enverrons plus d'e-mail au sujet de cette sortie.",
  coverAlt: (title, artist) => `Pochette de ${title} par ${artist}`,
  by: (artist) => `par ${artist}`,
  typeSingle: "Single",
  typeEP: "EP",
  typeAlbum: "Album",
  releasedOn: (date) => `Sorti le ${date}`,
  outOn: (date) => `Sortie le ${date}`,
  listenOn: "Écouter sur",
  listenAria: (store) => `Écouter sur ${store} (s'ouvre dans un nouvel onglet)`,
  play: "Écouter",
  noLinks: "Les liens vers les plateformes apparaîtront ici dès qu'ils seront en ligne.",
  upcomingTitle: "Bientôt disponible",
  upcomingBody: (date) => `Cette sortie arrive le ${date}.`,
  upcomingBodyNoDate: "Cette sortie arrive bientôt.",
  pendingTitle: "Bientôt sur vos plateformes préférées",
  pendingBody:
    "Cette sortie est en cours de livraison aux plateformes musicales. Chaque plateforme publie selon son propre calendrier — revenez bientôt pour l'écouter.",
  notifyTitle: "Soyez prévenu de la sortie",
  notifyBody: "Laissez votre e-mail et nous vous enverrons un seul message dès qu'elle sera disponible en streaming.",
  email: "Adresse e-mail",
  emailRequired: "Saisissez une adresse e-mail valide.",
  consent: "J'accepte de recevoir un e-mail au sujet de cette sortie. Mon adresse ne servira à rien d'autre.",
  consentRequired: "Cochez la case pour que nous puissions vous écrire.",
  notify: "Me prévenir",
  notifySuccess: "C'est noté. Nous vous écrirons dès la sortie.",
  notifyUnavailable: "Les notifications ne sont plus disponibles pour cette sortie.",
  followArtist: "Suivre l'artiste",
  instagram: "Instagram",
  tiktok: "TikTok",
  youtube: "YouTube",
  followAria: (network) => `${network} (s'ouvre dans un nouvel onglet)`,
  poweredBy: "Propulsé par",
  distributeCta: "Sortez votre propre musique",
  notFoundTitle: "Sortie introuvable",
  notFoundBody: "Le lien contient peut-être une erreur, ou la sortie n'est plus disponible.",
  goHome: "Aller sur 2kTunes",
};

export const COPY = { EN, SW, FR };
