/** Copy for /dashboard/settings. */

const EN = {
  title: "Settings",
  description: "Your profile, sign-in details, communication preferences and account.",
  nav: "Settings sections",

  profileTitle: "Profile",
  profileDescription: "Used on statements, payouts and receipts. Keep it accurate.",
  displayName: "Display name",
  firstName: "First name",
  middleName: "Middle name",
  lastName: "Last name",
  businessName: "Business or label name",
  phone: "Phone number",
  phoneHint: "Include the country code, e.g. +255 712 345 678.",
  country: "Country",
  city: "City or town",
  address1: "Address line 1",
  address2: "Address line 2",
  postalCode: "Postal code",
  currency: "Preferred currency",
  currencyHint: "Used to show your earnings.",
  language: "Language",
  langEn: "English",
  langSw: "Kiswahili",
  langFr: "Français",
  saveProfile: "Save profile",
  profileSaved: "Profile saved",

  avatarTitle: "Profile photo",
  avatarDescription: "JPG, PNG or WebP, at least 100 × 100 px, up to 4 MB.",
  uploadAvatar: "Upload photo",
  changeAvatar: "Change photo",
  uploading: "Uploading…",
  avatarSaved: "Photo updated",
  avatarType: "Choose a JPG, PNG or WebP image.",
  avatarSize: "That image is larger than 4 MB.",
  avatarDims: "The image must be at least 100 × 100 pixels.",
  avatarUnreadable: "We couldn't read that image. Try a different file.",

  emailTitle: "Email address",
  emailDescription: "We'll send a confirmation link to the new address. Until you confirm it, some features stay limited.",
  currentEmail: "Current email",
  verified: "Verified",
  unverified: "Not verified",
  newEmail: "New email address",
  emailInvalid: "Enter a valid email address.",
  emailSame: "That's already your email address.",
  currentPassword: "Current password",
  passwordRequired: "Enter your current password.",
  changeEmail: "Change email",
  emailChanged: "Email updated",
  emailChangedBody: "Check your inbox to confirm the new address.",

  passwordTitle: "Password",
  passwordDescription: "Changing your password signs you out on your other devices.",
  newPassword: "New password",
  newPasswordHint: "At least 8 characters.",
  newPasswordShort: "Use at least 8 characters.",
  confirmPassword: "Confirm new password",
  passwordMismatch: "The passwords don't match.",
  passwordReused: "Choose a password you haven't used for this account.",
  changePassword: "Change password",
  passwordChanged: "Password changed",

  commsTitle: "Communication",
  commsDescription: "Overall switches for how we contact you.",
  allowEmail: "Email updates",
  allowEmailHint: "Receive emails about your account activity.",
  allowMobile: "Mobile alerts",
  allowMobileHint: "Receive alerts on your phone where available.",
  perCategory: "Choose which updates you get, per topic",
  saveComms: "Save preferences",
  commsSaved: "Preferences saved",

  sessionsTitle: "Sessions",
  sessionsDescription: "Signed in on a shared or lost device? Sign out everywhere, including here.",
  signOutAll: "Sign out of all devices",
  signOutAllTitle: "Sign out of all devices?",
  signOutAllBody: "Every device, including this one, will be signed out. You'll need your password to sign back in.",

  dangerTitle: "Delete account",
  dangerDescription:
    "Permanently deletes your profile and signs you out everywhere. If you have earnings history, your financial records are kept in anonymised form.",
  deleteAccount: "Delete my account",
  deleteTitle: "Delete your account?",
  deleteBody: "This can't be undone. Enter your password to confirm.",
  deleteReason: "Why are you leaving?",
  deleteReasonHint: "Optional, but it helps us improve.",
  deleteConfirm: "Delete account",
  deleted: "Your account has been deleted",
  balanceRemaining:
    "You still have money in your wallet or a withdrawal in progress. Withdraw your remaining balance (or contact support) before deleting your account.",
  goToWallet: "Go to wallet",
};

const SW: typeof EN = {
  title: "Mipangilio",
  description: "Wasifu wako, taarifa za kuingia, mapendeleo ya mawasiliano na akaunti.",
  nav: "Sehemu za mipangilio",

  profileTitle: "Wasifu",
  profileDescription: "Unatumika kwenye taarifa za mapato, malipo na risiti. Hakikisha ni sahihi.",
  displayName: "Jina la kuonyesha",
  firstName: "Jina la kwanza",
  middleName: "Jina la kati",
  lastName: "Jina la mwisho",
  businessName: "Jina la biashara au lebo",
  phone: "Namba ya simu",
  phoneHint: "Weka msimbo wa nchi, mfano +255 712 345 678.",
  country: "Nchi",
  city: "Jiji au mji",
  address1: "Anwani mstari wa 1",
  address2: "Anwani mstari wa 2",
  postalCode: "Msimbo wa posta",
  currency: "Sarafu unayopendelea",
  currencyHint: "Inatumika kuonyesha mapato yako.",
  language: "Lugha",
  langEn: "English",
  langSw: "Kiswahili",
  langFr: "Français",
  saveProfile: "Hifadhi wasifu",
  profileSaved: "Wasifu umehifadhiwa",

  avatarTitle: "Picha ya wasifu",
  avatarDescription: "JPG, PNG au WebP, angalau pikseli 100 × 100, hadi MB 4.",
  uploadAvatar: "Pakia picha",
  changeAvatar: "Badilisha picha",
  uploading: "Inapakia…",
  avatarSaved: "Picha imesasishwa",
  avatarType: "Chagua picha ya JPG, PNG au WebP.",
  avatarSize: "Picha hiyo ni kubwa kuliko MB 4.",
  avatarDims: "Picha lazima iwe angalau pikseli 100 × 100.",
  avatarUnreadable: "Hatukuweza kusoma picha hiyo. Jaribu faili nyingine.",

  emailTitle: "Barua pepe",
  emailDescription: "Tutatuma kiungo cha uthibitisho kwenye anwani mpya. Hadi utakapoithibitisha, baadhi ya huduma zitakuwa na mipaka.",
  currentEmail: "Barua pepe ya sasa",
  verified: "Imethibitishwa",
  unverified: "Haijathibitishwa",
  newEmail: "Barua pepe mpya",
  emailInvalid: "Weka barua pepe sahihi.",
  emailSame: "Hiyo tayari ni barua pepe yako.",
  currentPassword: "Nenosiri la sasa",
  passwordRequired: "Weka nenosiri lako la sasa.",
  changeEmail: "Badilisha barua pepe",
  emailChanged: "Barua pepe imesasishwa",
  emailChangedBody: "Angalia kikasha chako ili kuthibitisha anwani mpya.",

  passwordTitle: "Nenosiri",
  passwordDescription: "Kubadilisha nenosiri kunakutoa kwenye vifaa vyako vingine.",
  newPassword: "Nenosiri jipya",
  newPasswordHint: "Angalau herufi 8.",
  newPasswordShort: "Tumia angalau herufi 8.",
  confirmPassword: "Thibitisha nenosiri jipya",
  passwordMismatch: "Manenosiri hayafanani.",
  passwordReused: "Chagua nenosiri ambalo hujawahi kulitumia kwenye akaunti hii.",
  changePassword: "Badilisha nenosiri",
  passwordChanged: "Nenosiri limebadilishwa",

  commsTitle: "Mawasiliano",
  commsDescription: "Swichi kuu za jinsi tunavyowasiliana nawe.",
  allowEmail: "Habari kwa barua pepe",
  allowEmailHint: "Pokea barua pepe kuhusu shughuli za akaunti yako.",
  allowMobile: "Arifa za simu",
  allowMobileHint: "Pokea arifa kwenye simu yako pale inapowezekana.",
  perCategory: "Chagua habari unazopokea kwa kila mada",
  saveComms: "Hifadhi mapendeleo",
  commsSaved: "Mapendeleo yamehifadhiwa",

  sessionsTitle: "Vipindi vya kuingia",
  sessionsDescription: "Umeingia kwenye kifaa cha pamoja au kilichopotea? Toka kila mahali, pamoja na hapa.",
  signOutAll: "Toka kwenye vifaa vyote",
  signOutAllTitle: "Utoke kwenye vifaa vyote?",
  signOutAllBody: "Kila kifaa, pamoja na hiki, kitatolewa. Utahitaji nenosiri lako kuingia tena.",

  dangerTitle: "Futa akaunti",
  dangerDescription:
    "Inafuta wasifu wako kabisa na kukutoa kila mahali. Kama una historia ya mapato, kumbukumbu zako za fedha zinahifadhiwa bila kukutambulisha.",
  deleteAccount: "Futa akaunti yangu",
  deleteTitle: "Ufute akaunti yako?",
  deleteBody: "Hili haliwezi kutenduliwa. Weka nenosiri lako kuthibitisha.",
  deleteReason: "Kwa nini unaondoka?",
  deleteReasonHint: "Si lazima, ila inatusaidia kuboresha huduma.",
  deleteConfirm: "Futa akaunti",
  deleted: "Akaunti yako imefutwa",
  balanceRemaining:
    "Bado una fedha kwenye pochi yako au utoaji wa fedha unaoendelea. Toa salio lako lililobaki (au wasiliana na msaada) kabla ya kufuta akaunti yako.",
  goToWallet: "Nenda kwenye pochi",
};

const FR: typeof EN = {
  title: "Paramètres",
  description: "Votre profil, vos identifiants, vos préférences de communication et votre compte.",
  nav: "Sections des paramètres",

  profileTitle: "Profil",
  profileDescription: "Utilisé sur les relevés, versements et reçus. Veillez à ce qu’il soit exact.",
  displayName: "Nom affiché",
  firstName: "Prénom",
  middleName: "Deuxième prénom",
  lastName: "Nom",
  businessName: "Nom de l’entreprise ou du label",
  phone: "Numéro de téléphone",
  phoneHint: "Indiquez l’indicatif du pays, p. ex. +225 07 12 34 56 78.",
  country: "Pays",
  city: "Ville",
  address1: "Adresse (ligne 1)",
  address2: "Adresse (ligne 2)",
  postalCode: "Code postal",
  currency: "Devise préférée",
  currencyHint: "Sert à afficher vos revenus.",
  language: "Langue",
  langEn: "English",
  langSw: "Kiswahili",
  langFr: "Français",
  saveProfile: "Enregistrer le profil",
  profileSaved: "Profil enregistré",

  avatarTitle: "Photo de profil",
  avatarDescription: "JPG, PNG ou WebP, au moins 100 × 100 px, 4 Mo maximum.",
  uploadAvatar: "Importer une photo",
  changeAvatar: "Changer de photo",
  uploading: "Importation…",
  avatarSaved: "Photo mise à jour",
  avatarType: "Choisissez une image JPG, PNG ou WebP.",
  avatarSize: "Cette image dépasse 4 Mo.",
  avatarDims: "L’image doit faire au moins 100 × 100 pixels.",
  avatarUnreadable: "Impossible de lire cette image. Essayez un autre fichier.",

  emailTitle: "Adresse e-mail",
  emailDescription: "Nous enverrons un lien de confirmation à la nouvelle adresse. Tant qu’elle n’est pas confirmée, certaines fonctionnalités restent limitées.",
  currentEmail: "E-mail actuel",
  verified: "Vérifiée",
  unverified: "Non vérifiée",
  newEmail: "Nouvelle adresse e-mail",
  emailInvalid: "Saisissez une adresse e-mail valide.",
  emailSame: "C’est déjà votre adresse e-mail.",
  currentPassword: "Mot de passe actuel",
  passwordRequired: "Saisissez votre mot de passe actuel.",
  changeEmail: "Modifier l’e-mail",
  emailChanged: "E-mail mis à jour",
  emailChangedBody: "Consultez votre boîte de réception pour confirmer la nouvelle adresse.",

  passwordTitle: "Mot de passe",
  passwordDescription: "Changer votre mot de passe vous déconnecte de vos autres appareils.",
  newPassword: "Nouveau mot de passe",
  newPasswordHint: "Au moins 8 caractères.",
  newPasswordShort: "Utilisez au moins 8 caractères.",
  confirmPassword: "Confirmer le mot de passe",
  passwordMismatch: "Les mots de passe ne correspondent pas.",
  passwordReused: "Choisissez un mot de passe jamais utilisé pour ce compte.",
  changePassword: "Changer le mot de passe",
  passwordChanged: "Mot de passe modifié",

  commsTitle: "Communication",
  commsDescription: "Réglages généraux de la manière dont nous vous contactons.",
  allowEmail: "Actualités par e-mail",
  allowEmailHint: "Recevez des e-mails sur l’activité de votre compte.",
  allowMobile: "Alertes mobiles",
  allowMobileHint: "Recevez des alertes sur votre téléphone lorsque c’est possible.",
  perCategory: "Choisissez les notifications à recevoir par sujet",
  saveComms: "Enregistrer les préférences",
  commsSaved: "Préférences enregistrées",

  sessionsTitle: "Sessions",
  sessionsDescription: "Connecté sur un appareil partagé ou perdu ? Déconnectez-vous partout, y compris ici.",
  signOutAll: "Déconnecter tous les appareils",
  signOutAllTitle: "Déconnecter tous les appareils ?",
  signOutAllBody: "Tous les appareils, y compris celui-ci, seront déconnectés. Votre mot de passe sera nécessaire pour vous reconnecter.",

  dangerTitle: "Supprimer le compte",
  dangerDescription:
    "Supprime définitivement votre profil et vous déconnecte partout. Si vous avez un historique de revenus, vos données financières sont conservées sous forme anonymisée.",
  deleteAccount: "Supprimer mon compte",
  deleteTitle: "Supprimer votre compte ?",
  deleteBody: "Cette action est irréversible. Saisissez votre mot de passe pour confirmer.",
  deleteReason: "Pourquoi partez-vous ?",
  deleteReasonHint: "Facultatif, mais cela nous aide à nous améliorer.",
  deleteConfirm: "Supprimer le compte",
  deleted: "Votre compte a été supprimé",
  balanceRemaining:
    "Il reste de l’argent dans votre portefeuille ou un retrait est en cours. Retirez votre solde restant (ou contactez l’assistance) avant de supprimer votre compte.",
  goToWallet: "Aller au portefeuille",
};

export const COPY = { EN, SW, FR };
